/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Attachment.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

Attachment::Attachment(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

Attachment::Attachment() {
    this->initializeModel();
}

Attachment::~Attachment() {}

void Attachment::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_attachment_isSet = false;
    m_attachment_isValid = false;

    m_filename_isSet = false;
    m_filename_isValid = false;

    m_link_isSet = false;
    m_link_isValid = false;

    m_comment_isSet = false;
    m_comment_isValid = false;

    m_upload_date_isSet = false;
    m_upload_date_isValid = false;

    m_upload_user_isSet = false;
    m_upload_user_isValid = false;

    m_user_detail_isSet = false;
    m_user_detail_isValid = false;

    m_file_size_isSet = false;
    m_file_size_isValid = false;

    m_model_type_isSet = false;
    m_model_type_isValid = false;

    m_model_id_isSet = false;
    m_model_id_isValid = false;
}

void Attachment::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Attachment::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_attachment_isValid = ::InvenTree::fromJsonValue(m_attachment, json[QString("attachment")]);
    m_attachment_isSet = !json[QString("attachment")].isNull() && m_attachment_isValid;

    m_filename_isValid = ::InvenTree::fromJsonValue(m_filename, json[QString("filename")]);
    m_filename_isSet = !json[QString("filename")].isNull() && m_filename_isValid;

    m_link_isValid = ::InvenTree::fromJsonValue(m_link, json[QString("link")]);
    m_link_isSet = !json[QString("link")].isNull() && m_link_isValid;

    m_comment_isValid = ::InvenTree::fromJsonValue(m_comment, json[QString("comment")]);
    m_comment_isSet = !json[QString("comment")].isNull() && m_comment_isValid;

    m_upload_date_isValid = ::InvenTree::fromJsonValue(m_upload_date, json[QString("upload_date")]);
    m_upload_date_isSet = !json[QString("upload_date")].isNull() && m_upload_date_isValid;

    m_upload_user_isValid = ::InvenTree::fromJsonValue(m_upload_user, json[QString("upload_user")]);
    m_upload_user_isSet = !json[QString("upload_user")].isNull() && m_upload_user_isValid;

    m_user_detail_isValid = ::InvenTree::fromJsonValue(m_user_detail, json[QString("user_detail")]);
    m_user_detail_isSet = !json[QString("user_detail")].isNull() && m_user_detail_isValid;

    m_file_size_isValid = ::InvenTree::fromJsonValue(m_file_size, json[QString("file_size")]);
    m_file_size_isSet = !json[QString("file_size")].isNull() && m_file_size_isValid;

    m_model_type_isValid = ::InvenTree::fromJsonValue(m_model_type, json[QString("model_type")]);
    m_model_type_isSet = !json[QString("model_type")].isNull() && m_model_type_isValid;

    m_model_id_isValid = ::InvenTree::fromJsonValue(m_model_id, json[QString("model_id")]);
    m_model_id_isSet = !json[QString("model_id")].isNull() && m_model_id_isValid;
}

QString Attachment::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Attachment::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_attachment.isSet()) {
        obj.insert(QString("attachment"), ::InvenTree::toJsonValue(m_attachment));
    }
    if (m_filename_isSet) {
        obj.insert(QString("filename"), ::InvenTree::toJsonValue(m_filename));
    }
    if (m_link_isSet) {
        obj.insert(QString("link"), ::InvenTree::toJsonValue(m_link));
    }
    if (m_comment_isSet) {
        obj.insert(QString("comment"), ::InvenTree::toJsonValue(m_comment));
    }
    if (m_upload_date_isSet) {
        obj.insert(QString("upload_date"), ::InvenTree::toJsonValue(m_upload_date));
    }
    if (m_upload_user_isSet) {
        obj.insert(QString("upload_user"), ::InvenTree::toJsonValue(m_upload_user));
    }
    if (m_user_detail.isSet()) {
        obj.insert(QString("user_detail"), ::InvenTree::toJsonValue(m_user_detail));
    }
    if (m_file_size_isSet) {
        obj.insert(QString("file_size"), ::InvenTree::toJsonValue(m_file_size));
    }
    if (m_model_type.isSet()) {
        obj.insert(QString("model_type"), ::InvenTree::toJsonValue(m_model_type));
    }
    if (m_model_id_isSet) {
        obj.insert(QString("model_id"), ::InvenTree::toJsonValue(m_model_id));
    }
    return obj;
}

qint32 Attachment::getPk() const {
    return m_pk;
}
void Attachment::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool Attachment::is_pk_Set() const{
    return m_pk_isSet;
}

bool Attachment::is_pk_Valid() const{
    return m_pk_isValid;
}

HttpFileElement Attachment::getAttachment() const {
    return m_attachment;
}
void Attachment::setAttachment(const HttpFileElement &attachment) {
    m_attachment = attachment;
    m_attachment_isSet = true;
}

bool Attachment::is_attachment_Set() const{
    return m_attachment_isSet;
}

bool Attachment::is_attachment_Valid() const{
    return m_attachment_isValid;
}

QString Attachment::getFilename() const {
    return m_filename;
}
void Attachment::setFilename(const QString &filename) {
    m_filename = filename;
    m_filename_isSet = true;
}

bool Attachment::is_filename_Set() const{
    return m_filename_isSet;
}

bool Attachment::is_filename_Valid() const{
    return m_filename_isValid;
}

QString Attachment::getLink() const {
    return m_link;
}
void Attachment::setLink(const QString &link) {
    m_link = link;
    m_link_isSet = true;
}

bool Attachment::is_link_Set() const{
    return m_link_isSet;
}

bool Attachment::is_link_Valid() const{
    return m_link_isValid;
}

QString Attachment::getComment() const {
    return m_comment;
}
void Attachment::setComment(const QString &comment) {
    m_comment = comment;
    m_comment_isSet = true;
}

bool Attachment::is_comment_Set() const{
    return m_comment_isSet;
}

bool Attachment::is_comment_Valid() const{
    return m_comment_isValid;
}

QDate Attachment::getUploadDate() const {
    return m_upload_date;
}
void Attachment::setUploadDate(const QDate &upload_date) {
    m_upload_date = upload_date;
    m_upload_date_isSet = true;
}

bool Attachment::is_upload_date_Set() const{
    return m_upload_date_isSet;
}

bool Attachment::is_upload_date_Valid() const{
    return m_upload_date_isValid;
}

qint32 Attachment::getUploadUser() const {
    return m_upload_user;
}
void Attachment::setUploadUser(const qint32 &upload_user) {
    m_upload_user = upload_user;
    m_upload_user_isSet = true;
}

bool Attachment::is_upload_user_Set() const{
    return m_upload_user_isSet;
}

bool Attachment::is_upload_user_Valid() const{
    return m_upload_user_isValid;
}

User Attachment::getUserDetail() const {
    return m_user_detail;
}
void Attachment::setUserDetail(const User &user_detail) {
    m_user_detail = user_detail;
    m_user_detail_isSet = true;
}

bool Attachment::is_user_detail_Set() const{
    return m_user_detail_isSet;
}

bool Attachment::is_user_detail_Valid() const{
    return m_user_detail_isValid;
}

qint32 Attachment::getFileSize() const {
    return m_file_size;
}
void Attachment::setFileSize(const qint32 &file_size) {
    m_file_size = file_size;
    m_file_size_isSet = true;
}

bool Attachment::is_file_size_Set() const{
    return m_file_size_isSet;
}

bool Attachment::is_file_size_Valid() const{
    return m_file_size_isValid;
}

AttachmentModelTypeEnum Attachment::getModelType() const {
    return m_model_type;
}
void Attachment::setModelType(const AttachmentModelTypeEnum &model_type) {
    m_model_type = model_type;
    m_model_type_isSet = true;
}

bool Attachment::is_model_type_Set() const{
    return m_model_type_isSet;
}

bool Attachment::is_model_type_Valid() const{
    return m_model_type_isValid;
}

qint64 Attachment::getModelId() const {
    return m_model_id;
}
void Attachment::setModelId(const qint64 &model_id) {
    m_model_id = model_id;
    m_model_id_isSet = true;
}

bool Attachment::is_model_id_Set() const{
    return m_model_id_isSet;
}

bool Attachment::is_model_id_Valid() const{
    return m_model_id_isValid;
}

bool Attachment::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_attachment.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_filename_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_link_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_comment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_upload_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_upload_user_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_file_size_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_model_type.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_model_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Attachment::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pk_isValid && m_upload_date_isValid && m_user_detail_isValid && m_file_size_isValid && m_model_type_isValid && m_model_id_isValid && true;
}

} // namespace InvenTree
