/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Barcode.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

Barcode::Barcode(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

Barcode::Barcode() {
    this->initializeModel();
}

Barcode::~Barcode() {}

void Barcode::initializeModel() {

    m_barcode_isSet = false;
    m_barcode_isValid = false;
}

void Barcode::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Barcode::fromJsonObject(QJsonObject json) {

    m_barcode_isValid = ::InvenTree::fromJsonValue(m_barcode, json[QString("barcode")]);
    m_barcode_isSet = !json[QString("barcode")].isNull() && m_barcode_isValid;
}

QString Barcode::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Barcode::asJsonObject() const {
    QJsonObject obj;
    if (m_barcode_isSet) {
        obj.insert(QString("barcode"), ::InvenTree::toJsonValue(m_barcode));
    }
    return obj;
}

QMap<QString, QString> Barcode::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> Barcode::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_barcode_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("barcode"), namePrefix), m_barcode);
    }
    return vars;
}

QList<HttpFileElement> Barcode::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> Barcode::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_barcode_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("barcode"), namePrefix), m_barcode);
    }
    return files;
}

QString Barcode::getBarcode() const {
    return m_barcode;
}
void Barcode::setBarcode(const QString &barcode) {
    m_barcode = barcode;
    m_barcode_isSet = true;
}

bool Barcode::is_barcode_Set() const{
    return m_barcode_isSet;
}

bool Barcode::is_barcode_Valid() const{
    return m_barcode_isValid;
}

bool Barcode::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_barcode_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Barcode::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_barcode_isValid && true;
}

} // namespace InvenTree
