/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 160
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "BarcodeSOAllocate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

BarcodeSOAllocate::BarcodeSOAllocate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

BarcodeSOAllocate::BarcodeSOAllocate() {
    this->initializeModel();
}

BarcodeSOAllocate::~BarcodeSOAllocate() {}

void BarcodeSOAllocate::initializeModel() {

    m_barcode_isSet = false;
    m_barcode_isValid = false;

    m_sales_order_isSet = false;
    m_sales_order_isValid = false;

    m_line_isSet = false;
    m_line_isValid = false;

    m_shipment_isSet = false;
    m_shipment_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;
}

void BarcodeSOAllocate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void BarcodeSOAllocate::fromJsonObject(QJsonObject json) {

    m_barcode_isValid = ::InvenTree::fromJsonValue(m_barcode, json[QString("barcode")]);
    m_barcode_isSet = !json[QString("barcode")].isNull() && m_barcode_isValid;

    m_sales_order_isValid = ::InvenTree::fromJsonValue(m_sales_order, json[QString("sales_order")]);
    m_sales_order_isSet = !json[QString("sales_order")].isNull() && m_sales_order_isValid;

    m_line_isValid = ::InvenTree::fromJsonValue(m_line, json[QString("line")]);
    m_line_isSet = !json[QString("line")].isNull() && m_line_isValid;

    m_shipment_isValid = ::InvenTree::fromJsonValue(m_shipment, json[QString("shipment")]);
    m_shipment_isSet = !json[QString("shipment")].isNull() && m_shipment_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;
}

QString BarcodeSOAllocate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject BarcodeSOAllocate::asJsonObject() const {
    QJsonObject obj;
    if (m_barcode_isSet) {
        obj.insert(QString("barcode"), ::InvenTree::toJsonValue(m_barcode));
    }
    if (m_sales_order_isSet) {
        obj.insert(QString("sales_order"), ::InvenTree::toJsonValue(m_sales_order));
    }
    if (m_line_isSet) {
        obj.insert(QString("line"), ::InvenTree::toJsonValue(m_line));
    }
    if (m_shipment_isSet) {
        obj.insert(QString("shipment"), ::InvenTree::toJsonValue(m_shipment));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    return obj;
}

QString BarcodeSOAllocate::getBarcode() const {
    return m_barcode;
}
void BarcodeSOAllocate::setBarcode(const QString &barcode) {
    m_barcode = barcode;
    m_barcode_isSet = true;
}

bool BarcodeSOAllocate::is_barcode_Set() const{
    return m_barcode_isSet;
}

bool BarcodeSOAllocate::is_barcode_Valid() const{
    return m_barcode_isValid;
}

qint32 BarcodeSOAllocate::getSalesOrder() const {
    return m_sales_order;
}
void BarcodeSOAllocate::setSalesOrder(const qint32 &sales_order) {
    m_sales_order = sales_order;
    m_sales_order_isSet = true;
}

bool BarcodeSOAllocate::is_sales_order_Set() const{
    return m_sales_order_isSet;
}

bool BarcodeSOAllocate::is_sales_order_Valid() const{
    return m_sales_order_isValid;
}

qint32 BarcodeSOAllocate::getLine() const {
    return m_line;
}
void BarcodeSOAllocate::setLine(const qint32 &line) {
    m_line = line;
    m_line_isSet = true;
}

bool BarcodeSOAllocate::is_line_Set() const{
    return m_line_isSet;
}

bool BarcodeSOAllocate::is_line_Valid() const{
    return m_line_isValid;
}

qint32 BarcodeSOAllocate::getShipment() const {
    return m_shipment;
}
void BarcodeSOAllocate::setShipment(const qint32 &shipment) {
    m_shipment = shipment;
    m_shipment_isSet = true;
}

bool BarcodeSOAllocate::is_shipment_Set() const{
    return m_shipment_isSet;
}

bool BarcodeSOAllocate::is_shipment_Valid() const{
    return m_shipment_isValid;
}

qint32 BarcodeSOAllocate::getQuantity() const {
    return m_quantity;
}
void BarcodeSOAllocate::setQuantity(const qint32 &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool BarcodeSOAllocate::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool BarcodeSOAllocate::is_quantity_Valid() const{
    return m_quantity_isValid;
}

bool BarcodeSOAllocate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_barcode_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_sales_order_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_line_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_shipment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool BarcodeSOAllocate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_barcode_isValid && m_sales_order_isValid && true;
}

} // namespace InvenTree
