/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _BomApi_H
#define _BomApi_H

#include "Helpers.h"
#include "HttpRequest.h"
#include "ServerConfiguration.h"
#include "Oauth.h"

#include "BomImportExtract.h"
#include "BomImportSubmit.h"
#include "BomImportUpload.h"
#include "BomItem.h"
#include "BomItemSubstitute.h"
#include "BomItemValidation.h"
#include "PaginatedBomItemList.h"
#include "PaginatedBomItemSubstituteList.h"
#include "PatchedBomItem.h"
#include "PatchedBomItemSubstitute.h"
#include "PatchedBomItemValidation.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace InvenTree {

class BomApi : public QObject {
    Q_OBJECT

public:
    BomApi(const int timeOut = 0);
    ~BomApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables = QMap<QString, ServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  bom_item BomItem [required]
    */
    void bomCreate(const BomItem &bom_item);


    void bomDestroy();

    /**
    * @param[in]  id qint32 [required]
    */
    void bomDestroy2(const qint32 &id);

    /**
    * @param[in]  bom_import_extract BomImportExtract [required]
    */
    void bomImportExtractCreate(const BomImportExtract &bom_import_extract);

    /**
    * @param[in]  bom_import_submit BomImportSubmit [required]
    */
    void bomImportSubmitCreate(const BomImportSubmit &bom_import_submit);

    /**
    * @param[in]  bom_import_upload BomImportUpload [required]
    */
    void bomImportUploadCreate(const BomImportUpload &bom_import_upload);

    /**
    * @param[in]  allow_variants bool [optional]
    * @param[in]  available_stock bool [optional]
    * @param[in]  consumable bool [optional]
    * @param[in]  has_pricing bool [optional]
    * @param[in]  inherited bool [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  on_order bool [optional]
    * @param[in]  optional bool [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  part qint32 [optional]
    * @param[in]  part_active bool [optional]
    * @param[in]  part_trackable bool [optional]
    * @param[in]  search QString [optional]
    * @param[in]  sub_part_assembly bool [optional]
    * @param[in]  sub_part_trackable bool [optional]
    * @param[in]  uses qint32 [optional]
    * @param[in]  validated bool [optional]
    */
    void bomList(const ::InvenTree::OptionalParam<bool> &allow_variants = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &available_stock = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &consumable = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &has_pricing = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &inherited = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &on_order = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &optional = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &part = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &part_active = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &part_trackable = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &sub_part_assembly = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &sub_part_trackable = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &uses = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &validated = ::InvenTree::OptionalParam<bool>());

    /**
    * @param[in]  id qint32 [required]
    */
    void bomMetadataPartialUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void bomMetadataRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void bomMetadataUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_bom_item PatchedBomItem [optional]
    */
    void bomPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBomItem> &patched_bom_item = ::InvenTree::OptionalParam<PatchedBomItem>());

    /**
    * @param[in]  id qint32 [required]
    */
    void bomRetrieve(const qint32 &id);

    /**
    * @param[in]  bom_item_substitute BomItemSubstitute [required]
    */
    void bomSubstituteCreate(const BomItemSubstitute &bom_item_substitute);

    /**
    * @param[in]  id qint32 [required]
    */
    void bomSubstituteDestroy(const qint32 &id);

    /**
    * @param[in]  bom_item qint32 [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  part qint32 [optional]
    * @param[in]  search QString [optional]
    */
    void bomSubstituteList(const ::InvenTree::OptionalParam<qint32> &bom_item = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &part = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    void bomSubstituteMetadataPartialUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void bomSubstituteMetadataRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void bomSubstituteMetadataUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_bom_item_substitute PatchedBomItemSubstitute [optional]
    */
    void bomSubstitutePartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBomItemSubstitute> &patched_bom_item_substitute = ::InvenTree::OptionalParam<PatchedBomItemSubstitute>());

    /**
    * @param[in]  id qint32 [required]
    */
    void bomSubstituteRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  bom_item_substitute BomItemSubstitute [required]
    */
    void bomSubstituteUpdate(const qint32 &id, const BomItemSubstitute &bom_item_substitute);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  bom_item BomItem [required]
    */
    void bomUpdate(const qint32 &id, const BomItem &bom_item);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_bom_item_validation PatchedBomItemValidation [optional]
    */
    void bomValidatePartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBomItemValidation> &patched_bom_item_validation = ::InvenTree::OptionalParam<PatchedBomItemValidation>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  bom_item_validation BomItemValidation [optional]
    */
    void bomValidateUpdate(const qint32 &id, const ::InvenTree::OptionalParam<BomItemValidation> &bom_item_validation = ::InvenTree::OptionalParam<BomItemValidation>());


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<ServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    HttpRequestInput _latestInput;
    HttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void bomCreateCallback(HttpRequestWorker *worker);
    void bomDestroyCallback(HttpRequestWorker *worker);
    void bomDestroy2Callback(HttpRequestWorker *worker);
    void bomImportExtractCreateCallback(HttpRequestWorker *worker);
    void bomImportSubmitCreateCallback(HttpRequestWorker *worker);
    void bomImportUploadCreateCallback(HttpRequestWorker *worker);
    void bomListCallback(HttpRequestWorker *worker);
    void bomMetadataPartialUpdateCallback(HttpRequestWorker *worker);
    void bomMetadataRetrieveCallback(HttpRequestWorker *worker);
    void bomMetadataUpdateCallback(HttpRequestWorker *worker);
    void bomPartialUpdateCallback(HttpRequestWorker *worker);
    void bomRetrieveCallback(HttpRequestWorker *worker);
    void bomSubstituteCreateCallback(HttpRequestWorker *worker);
    void bomSubstituteDestroyCallback(HttpRequestWorker *worker);
    void bomSubstituteListCallback(HttpRequestWorker *worker);
    void bomSubstituteMetadataPartialUpdateCallback(HttpRequestWorker *worker);
    void bomSubstituteMetadataRetrieveCallback(HttpRequestWorker *worker);
    void bomSubstituteMetadataUpdateCallback(HttpRequestWorker *worker);
    void bomSubstitutePartialUpdateCallback(HttpRequestWorker *worker);
    void bomSubstituteRetrieveCallback(HttpRequestWorker *worker);
    void bomSubstituteUpdateCallback(HttpRequestWorker *worker);
    void bomUpdateCallback(HttpRequestWorker *worker);
    void bomValidatePartialUpdateCallback(HttpRequestWorker *worker);
    void bomValidateUpdateCallback(HttpRequestWorker *worker);

Q_SIGNALS:

    void bomCreateSignal(BomItem summary);
    void bomDestroySignal();
    void bomDestroy2Signal();
    void bomImportExtractCreateSignal(BomImportExtract summary);
    void bomImportSubmitCreateSignal(BomImportSubmit summary);
    void bomImportUploadCreateSignal(BomImportUpload summary);
    void bomListSignal(PaginatedBomItemList summary);
    void bomMetadataPartialUpdateSignal();
    void bomMetadataRetrieveSignal();
    void bomMetadataUpdateSignal();
    void bomPartialUpdateSignal(BomItem summary);
    void bomRetrieveSignal(BomItem summary);
    void bomSubstituteCreateSignal(BomItemSubstitute summary);
    void bomSubstituteDestroySignal();
    void bomSubstituteListSignal(PaginatedBomItemSubstituteList summary);
    void bomSubstituteMetadataPartialUpdateSignal();
    void bomSubstituteMetadataRetrieveSignal();
    void bomSubstituteMetadataUpdateSignal();
    void bomSubstitutePartialUpdateSignal(BomItemSubstitute summary);
    void bomSubstituteRetrieveSignal(BomItemSubstitute summary);
    void bomSubstituteUpdateSignal(BomItemSubstitute summary);
    void bomUpdateSignal(BomItem summary);
    void bomValidatePartialUpdateSignal(BomItemValidation summary);
    void bomValidateUpdateSignal(BomItemValidation summary);

    void bomCreateSignalFull(HttpRequestWorker *worker, BomItem summary);
    void bomDestroySignalFull(HttpRequestWorker *worker);
    void bomDestroy2SignalFull(HttpRequestWorker *worker);
    void bomImportExtractCreateSignalFull(HttpRequestWorker *worker, BomImportExtract summary);
    void bomImportSubmitCreateSignalFull(HttpRequestWorker *worker, BomImportSubmit summary);
    void bomImportUploadCreateSignalFull(HttpRequestWorker *worker, BomImportUpload summary);
    void bomListSignalFull(HttpRequestWorker *worker, PaginatedBomItemList summary);
    void bomMetadataPartialUpdateSignalFull(HttpRequestWorker *worker);
    void bomMetadataRetrieveSignalFull(HttpRequestWorker *worker);
    void bomMetadataUpdateSignalFull(HttpRequestWorker *worker);
    void bomPartialUpdateSignalFull(HttpRequestWorker *worker, BomItem summary);
    void bomRetrieveSignalFull(HttpRequestWorker *worker, BomItem summary);
    void bomSubstituteCreateSignalFull(HttpRequestWorker *worker, BomItemSubstitute summary);
    void bomSubstituteDestroySignalFull(HttpRequestWorker *worker);
    void bomSubstituteListSignalFull(HttpRequestWorker *worker, PaginatedBomItemSubstituteList summary);
    void bomSubstituteMetadataPartialUpdateSignalFull(HttpRequestWorker *worker);
    void bomSubstituteMetadataRetrieveSignalFull(HttpRequestWorker *worker);
    void bomSubstituteMetadataUpdateSignalFull(HttpRequestWorker *worker);
    void bomSubstitutePartialUpdateSignalFull(HttpRequestWorker *worker, BomItemSubstitute summary);
    void bomSubstituteRetrieveSignalFull(HttpRequestWorker *worker, BomItemSubstitute summary);
    void bomSubstituteUpdateSignalFull(HttpRequestWorker *worker, BomItemSubstitute summary);
    void bomUpdateSignalFull(HttpRequestWorker *worker, BomItem summary);
    void bomValidatePartialUpdateSignalFull(HttpRequestWorker *worker, BomItemValidation summary);
    void bomValidateUpdateSignalFull(HttpRequestWorker *worker, BomItemValidation summary);

    Q_DECL_DEPRECATED_X("Use bomCreateSignalError() instead")
    void bomCreateSignalE(BomItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomCreateSignalError(BomItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomDestroySignalError() instead")
    void bomDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomDestroy2SignalError() instead")
    void bomDestroy2SignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomDestroy2SignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportExtractCreateSignalError() instead")
    void bomImportExtractCreateSignalE(BomImportExtract summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportExtractCreateSignalError(BomImportExtract summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportSubmitCreateSignalError() instead")
    void bomImportSubmitCreateSignalE(BomImportSubmit summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportSubmitCreateSignalError(BomImportSubmit summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportUploadCreateSignalError() instead")
    void bomImportUploadCreateSignalE(BomImportUpload summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportUploadCreateSignalError(BomImportUpload summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomListSignalError() instead")
    void bomListSignalE(PaginatedBomItemList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomListSignalError(PaginatedBomItemList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataPartialUpdateSignalError() instead")
    void bomMetadataPartialUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataPartialUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataRetrieveSignalError() instead")
    void bomMetadataRetrieveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataRetrieveSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataUpdateSignalError() instead")
    void bomMetadataUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomPartialUpdateSignalError() instead")
    void bomPartialUpdateSignalE(BomItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomPartialUpdateSignalError(BomItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomRetrieveSignalError() instead")
    void bomRetrieveSignalE(BomItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomRetrieveSignalError(BomItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteCreateSignalError() instead")
    void bomSubstituteCreateSignalE(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteCreateSignalError(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteDestroySignalError() instead")
    void bomSubstituteDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteListSignalError() instead")
    void bomSubstituteListSignalE(PaginatedBomItemSubstituteList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteListSignalError(PaginatedBomItemSubstituteList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataPartialUpdateSignalError() instead")
    void bomSubstituteMetadataPartialUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataPartialUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataRetrieveSignalError() instead")
    void bomSubstituteMetadataRetrieveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataRetrieveSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataUpdateSignalError() instead")
    void bomSubstituteMetadataUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstitutePartialUpdateSignalError() instead")
    void bomSubstitutePartialUpdateSignalE(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstitutePartialUpdateSignalError(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteRetrieveSignalError() instead")
    void bomSubstituteRetrieveSignalE(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteRetrieveSignalError(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteUpdateSignalError() instead")
    void bomSubstituteUpdateSignalE(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteUpdateSignalError(BomItemSubstitute summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomUpdateSignalError() instead")
    void bomUpdateSignalE(BomItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomUpdateSignalError(BomItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomValidatePartialUpdateSignalError() instead")
    void bomValidatePartialUpdateSignalE(BomItemValidation summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomValidatePartialUpdateSignalError(BomItemValidation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomValidateUpdateSignalError() instead")
    void bomValidateUpdateSignalE(BomItemValidation summary, QNetworkReply::NetworkError error_type, QString error_str);
    void bomValidateUpdateSignalError(BomItemValidation summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use bomCreateSignalErrorFull() instead")
    void bomCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomDestroySignalErrorFull() instead")
    void bomDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomDestroy2SignalErrorFull() instead")
    void bomDestroy2SignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomDestroy2SignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportExtractCreateSignalErrorFull() instead")
    void bomImportExtractCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportExtractCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportSubmitCreateSignalErrorFull() instead")
    void bomImportSubmitCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportSubmitCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomImportUploadCreateSignalErrorFull() instead")
    void bomImportUploadCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomImportUploadCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomListSignalErrorFull() instead")
    void bomListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataPartialUpdateSignalErrorFull() instead")
    void bomMetadataPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataRetrieveSignalErrorFull() instead")
    void bomMetadataRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomMetadataUpdateSignalErrorFull() instead")
    void bomMetadataUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomMetadataUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomPartialUpdateSignalErrorFull() instead")
    void bomPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomRetrieveSignalErrorFull() instead")
    void bomRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteCreateSignalErrorFull() instead")
    void bomSubstituteCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteDestroySignalErrorFull() instead")
    void bomSubstituteDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteListSignalErrorFull() instead")
    void bomSubstituteListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataPartialUpdateSignalErrorFull() instead")
    void bomSubstituteMetadataPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataRetrieveSignalErrorFull() instead")
    void bomSubstituteMetadataRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteMetadataUpdateSignalErrorFull() instead")
    void bomSubstituteMetadataUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteMetadataUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstitutePartialUpdateSignalErrorFull() instead")
    void bomSubstitutePartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstitutePartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteRetrieveSignalErrorFull() instead")
    void bomSubstituteRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomSubstituteUpdateSignalErrorFull() instead")
    void bomSubstituteUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomSubstituteUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomUpdateSignalErrorFull() instead")
    void bomUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomValidatePartialUpdateSignalErrorFull() instead")
    void bomValidatePartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomValidatePartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use bomValidateUpdateSignalErrorFull() instead")
    void bomValidateUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void bomValidateUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace InvenTree
#endif
