/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 166
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _BuildApi_H
#define _BuildApi_H

#include "Helpers.h"
#include "HttpRequest.h"
#include "ServerConfiguration.h"
#include "Oauth.h"

#include "Build.h"
#include "BuildAllocation.h"
#include "BuildAttachment.h"
#include "BuildAutoAllocation.h"
#include "BuildCancel.h"
#include "BuildComplete.h"
#include "BuildItem.h"
#include "BuildLine.h"
#include "BuildOutputComplete.h"
#include "BuildOutputCreate.h"
#include "BuildOutputDelete.h"
#include "BuildOutputScrap.h"
#include "BuildUnallocation.h"
#include "PaginatedBuildAttachmentList.h"
#include "PaginatedBuildItemList.h"
#include "PaginatedBuildLineList.h"
#include "PaginatedBuildList.h"
#include "PatchedBuild.h"
#include "PatchedBuildAttachment.h"
#include "PatchedBuildItem.h"
#include "PatchedBuildLine.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace InvenTree {

class BuildApi : public QObject {
    Q_OBJECT

public:
    BuildApi(const int timeOut = 0);
    ~BuildApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables = QMap<QString, ServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_allocation BuildAllocation [required]
    */
    void buildAllocateCreate(const qint32 &id, const BuildAllocation &build_allocation);

    /**
    * @param[in]  build_attachment BuildAttachment [required]
    */
    void buildAttachmentCreate(const BuildAttachment &build_attachment);


    void buildAttachmentDestroy();

    /**
    * @param[in]  id qint32 [required]
    */
    void buildAttachmentDestroy2(const qint32 &id);

    /**
    * @param[in]  build qint32 [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  search QString [optional]
    */
    void buildAttachmentList(const ::InvenTree::OptionalParam<qint32> &build = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_build_attachment PatchedBuildAttachment [optional]
    */
    void buildAttachmentPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBuildAttachment> &patched_build_attachment = ::InvenTree::OptionalParam<PatchedBuildAttachment>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildAttachmentRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_attachment BuildAttachment [required]
    */
    void buildAttachmentUpdate(const qint32 &id, const BuildAttachment &build_attachment);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_auto_allocation BuildAutoAllocation [optional]
    */
    void buildAutoAllocateCreate(const qint32 &id, const ::InvenTree::OptionalParam<BuildAutoAllocation> &build_auto_allocation = ::InvenTree::OptionalParam<BuildAutoAllocation>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_cancel BuildCancel [optional]
    */
    void buildCancelCreate(const qint32 &id, const ::InvenTree::OptionalParam<BuildCancel> &build_cancel = ::InvenTree::OptionalParam<BuildCancel>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_output_complete BuildOutputComplete [required]
    */
    void buildCompleteCreate(const qint32 &id, const BuildOutputComplete &build_output_complete);

    /**
    * @param[in]  build Build [required]
    */
    void buildCreate(const Build &build);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_output_create BuildOutputCreate [required]
    */
    void buildCreateOutputCreate(const qint32 &id, const BuildOutputCreate &build_output_create);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_output_delete BuildOutputDelete [required]
    */
    void buildDeleteOutputsCreate(const qint32 &id, const BuildOutputDelete &build_output_delete);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildDestroy(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_complete BuildComplete [optional]
    */
    void buildFinishCreate(const qint32 &id, const ::InvenTree::OptionalParam<BuildComplete> &build_complete = ::InvenTree::OptionalParam<BuildComplete>());

    /**
    * @param[in]  build_item BuildItem [required]
    */
    void buildItemCreate(const BuildItem &build_item);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildItemDestroy(const qint32 &id);

    /**
    * @param[in]  build qint32 [optional]
    * @param[in]  build_line qint32 [optional]
    * @param[in]  install_into qint32 [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  part qint32 [optional]
    * @param[in]  stock_item qint32 [optional]
    * @param[in]  tracked bool [optional]
    */
    void buildItemList(const ::InvenTree::OptionalParam<qint32> &build = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &build_line = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &install_into = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &part = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &stock_item = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &tracked = ::InvenTree::OptionalParam<bool>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildItemMetadataPartialUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildItemMetadataRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildItemMetadataUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_build_item PatchedBuildItem [optional]
    */
    void buildItemPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBuildItem> &patched_build_item = ::InvenTree::OptionalParam<PatchedBuildItem>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildItemRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_item BuildItem [required]
    */
    void buildItemUpdate(const qint32 &id, const BuildItem &build_item);

    /**
    * @param[in]  build_line BuildLine [required]
    */
    void buildLineCreate(const BuildLine &build_line);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildLineDestroy(const qint32 &id);

    /**
    * @param[in]  allocated bool [optional]
    * @param[in]  available bool [optional]
    * @param[in]  bom_item qint32 [optional]
    * @param[in]  build qint32 [optional]
    * @param[in]  consumable bool [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  optional bool [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  search QString [optional]
    * @param[in]  tracked bool [optional]
    */
    void buildLineList(const ::InvenTree::OptionalParam<bool> &allocated = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &available = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &bom_item = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &build = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &consumable = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &optional = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &tracked = ::InvenTree::OptionalParam<bool>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_build_line PatchedBuildLine [optional]
    */
    void buildLinePartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBuildLine> &patched_build_line = ::InvenTree::OptionalParam<PatchedBuildLine>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildLineRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_line BuildLine [required]
    */
    void buildLineUpdate(const qint32 &id, const BuildLine &build_line);

    /**
    * @param[in]  active bool [optional]
    * @param[in]  assigned_to double [optional]
    * @param[in]  assigned_to_me bool [optional]
    * @param[in]  has_project_code bool [optional]
    * @param[in]  issued_by qint32 [optional]
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  overdue bool [optional]
    * @param[in]  parent qint32 [optional]
    * @param[in]  part qint32 [optional]
    * @param[in]  project_code qint32 [optional]
    * @param[in]  reference QString [optional]
    * @param[in]  sales_order qint32 [optional]
    * @param[in]  search QString [optional]
    * @param[in]  status qint32 [optional]
    */
    void buildList(const ::InvenTree::OptionalParam<bool> &active = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<double> &assigned_to = ::InvenTree::OptionalParam<double>(), const ::InvenTree::OptionalParam<bool> &assigned_to_me = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &has_project_code = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &issued_by = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &overdue = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<qint32> &parent = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &part = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &project_code = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &reference = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &sales_order = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &status = ::InvenTree::OptionalParam<qint32>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildMetadataPartialUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildMetadataRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    void buildMetadataUpdate(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_build PatchedBuild [optional]
    */
    void buildPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedBuild> &patched_build = ::InvenTree::OptionalParam<PatchedBuild>());

    /**
    * @param[in]  id qint32 [required]
    */
    void buildRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_output_scrap BuildOutputScrap [required]
    */
    void buildScrapOutputsCreate(const qint32 &id, const BuildOutputScrap &build_output_scrap);


    void buildStatusRetrieve();

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build_unallocation BuildUnallocation [optional]
    */
    void buildUnallocateCreate(const qint32 &id, const ::InvenTree::OptionalParam<BuildUnallocation> &build_unallocation = ::InvenTree::OptionalParam<BuildUnallocation>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  build Build [required]
    */
    void buildUpdate(const qint32 &id, const Build &build);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<ServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    HttpRequestInput _latestInput;
    HttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void buildAllocateCreateCallback(HttpRequestWorker *worker);
    void buildAttachmentCreateCallback(HttpRequestWorker *worker);
    void buildAttachmentDestroyCallback(HttpRequestWorker *worker);
    void buildAttachmentDestroy2Callback(HttpRequestWorker *worker);
    void buildAttachmentListCallback(HttpRequestWorker *worker);
    void buildAttachmentPartialUpdateCallback(HttpRequestWorker *worker);
    void buildAttachmentRetrieveCallback(HttpRequestWorker *worker);
    void buildAttachmentUpdateCallback(HttpRequestWorker *worker);
    void buildAutoAllocateCreateCallback(HttpRequestWorker *worker);
    void buildCancelCreateCallback(HttpRequestWorker *worker);
    void buildCompleteCreateCallback(HttpRequestWorker *worker);
    void buildCreateCallback(HttpRequestWorker *worker);
    void buildCreateOutputCreateCallback(HttpRequestWorker *worker);
    void buildDeleteOutputsCreateCallback(HttpRequestWorker *worker);
    void buildDestroyCallback(HttpRequestWorker *worker);
    void buildFinishCreateCallback(HttpRequestWorker *worker);
    void buildItemCreateCallback(HttpRequestWorker *worker);
    void buildItemDestroyCallback(HttpRequestWorker *worker);
    void buildItemListCallback(HttpRequestWorker *worker);
    void buildItemMetadataPartialUpdateCallback(HttpRequestWorker *worker);
    void buildItemMetadataRetrieveCallback(HttpRequestWorker *worker);
    void buildItemMetadataUpdateCallback(HttpRequestWorker *worker);
    void buildItemPartialUpdateCallback(HttpRequestWorker *worker);
    void buildItemRetrieveCallback(HttpRequestWorker *worker);
    void buildItemUpdateCallback(HttpRequestWorker *worker);
    void buildLineCreateCallback(HttpRequestWorker *worker);
    void buildLineDestroyCallback(HttpRequestWorker *worker);
    void buildLineListCallback(HttpRequestWorker *worker);
    void buildLinePartialUpdateCallback(HttpRequestWorker *worker);
    void buildLineRetrieveCallback(HttpRequestWorker *worker);
    void buildLineUpdateCallback(HttpRequestWorker *worker);
    void buildListCallback(HttpRequestWorker *worker);
    void buildMetadataPartialUpdateCallback(HttpRequestWorker *worker);
    void buildMetadataRetrieveCallback(HttpRequestWorker *worker);
    void buildMetadataUpdateCallback(HttpRequestWorker *worker);
    void buildPartialUpdateCallback(HttpRequestWorker *worker);
    void buildRetrieveCallback(HttpRequestWorker *worker);
    void buildScrapOutputsCreateCallback(HttpRequestWorker *worker);
    void buildStatusRetrieveCallback(HttpRequestWorker *worker);
    void buildUnallocateCreateCallback(HttpRequestWorker *worker);
    void buildUpdateCallback(HttpRequestWorker *worker);

Q_SIGNALS:

    void buildAllocateCreateSignal(BuildAllocation summary);
    void buildAttachmentCreateSignal(BuildAttachment summary);
    void buildAttachmentDestroySignal();
    void buildAttachmentDestroy2Signal();
    void buildAttachmentListSignal(PaginatedBuildAttachmentList summary);
    void buildAttachmentPartialUpdateSignal(BuildAttachment summary);
    void buildAttachmentRetrieveSignal(BuildAttachment summary);
    void buildAttachmentUpdateSignal(BuildAttachment summary);
    void buildAutoAllocateCreateSignal(BuildAutoAllocation summary);
    void buildCancelCreateSignal(BuildCancel summary);
    void buildCompleteCreateSignal(BuildOutputComplete summary);
    void buildCreateSignal(Build summary);
    void buildCreateOutputCreateSignal(BuildOutputCreate summary);
    void buildDeleteOutputsCreateSignal(BuildOutputDelete summary);
    void buildDestroySignal();
    void buildFinishCreateSignal(BuildComplete summary);
    void buildItemCreateSignal(BuildItem summary);
    void buildItemDestroySignal();
    void buildItemListSignal(PaginatedBuildItemList summary);
    void buildItemMetadataPartialUpdateSignal();
    void buildItemMetadataRetrieveSignal();
    void buildItemMetadataUpdateSignal();
    void buildItemPartialUpdateSignal(BuildItem summary);
    void buildItemRetrieveSignal(BuildItem summary);
    void buildItemUpdateSignal(BuildItem summary);
    void buildLineCreateSignal(BuildLine summary);
    void buildLineDestroySignal();
    void buildLineListSignal(PaginatedBuildLineList summary);
    void buildLinePartialUpdateSignal(BuildLine summary);
    void buildLineRetrieveSignal(BuildLine summary);
    void buildLineUpdateSignal(BuildLine summary);
    void buildListSignal(PaginatedBuildList summary);
    void buildMetadataPartialUpdateSignal();
    void buildMetadataRetrieveSignal();
    void buildMetadataUpdateSignal();
    void buildPartialUpdateSignal(Build summary);
    void buildRetrieveSignal(Build summary);
    void buildScrapOutputsCreateSignal(BuildOutputScrap summary);
    void buildStatusRetrieveSignal();
    void buildUnallocateCreateSignal(BuildUnallocation summary);
    void buildUpdateSignal(Build summary);

    void buildAllocateCreateSignalFull(HttpRequestWorker *worker, BuildAllocation summary);
    void buildAttachmentCreateSignalFull(HttpRequestWorker *worker, BuildAttachment summary);
    void buildAttachmentDestroySignalFull(HttpRequestWorker *worker);
    void buildAttachmentDestroy2SignalFull(HttpRequestWorker *worker);
    void buildAttachmentListSignalFull(HttpRequestWorker *worker, PaginatedBuildAttachmentList summary);
    void buildAttachmentPartialUpdateSignalFull(HttpRequestWorker *worker, BuildAttachment summary);
    void buildAttachmentRetrieveSignalFull(HttpRequestWorker *worker, BuildAttachment summary);
    void buildAttachmentUpdateSignalFull(HttpRequestWorker *worker, BuildAttachment summary);
    void buildAutoAllocateCreateSignalFull(HttpRequestWorker *worker, BuildAutoAllocation summary);
    void buildCancelCreateSignalFull(HttpRequestWorker *worker, BuildCancel summary);
    void buildCompleteCreateSignalFull(HttpRequestWorker *worker, BuildOutputComplete summary);
    void buildCreateSignalFull(HttpRequestWorker *worker, Build summary);
    void buildCreateOutputCreateSignalFull(HttpRequestWorker *worker, BuildOutputCreate summary);
    void buildDeleteOutputsCreateSignalFull(HttpRequestWorker *worker, BuildOutputDelete summary);
    void buildDestroySignalFull(HttpRequestWorker *worker);
    void buildFinishCreateSignalFull(HttpRequestWorker *worker, BuildComplete summary);
    void buildItemCreateSignalFull(HttpRequestWorker *worker, BuildItem summary);
    void buildItemDestroySignalFull(HttpRequestWorker *worker);
    void buildItemListSignalFull(HttpRequestWorker *worker, PaginatedBuildItemList summary);
    void buildItemMetadataPartialUpdateSignalFull(HttpRequestWorker *worker);
    void buildItemMetadataRetrieveSignalFull(HttpRequestWorker *worker);
    void buildItemMetadataUpdateSignalFull(HttpRequestWorker *worker);
    void buildItemPartialUpdateSignalFull(HttpRequestWorker *worker, BuildItem summary);
    void buildItemRetrieveSignalFull(HttpRequestWorker *worker, BuildItem summary);
    void buildItemUpdateSignalFull(HttpRequestWorker *worker, BuildItem summary);
    void buildLineCreateSignalFull(HttpRequestWorker *worker, BuildLine summary);
    void buildLineDestroySignalFull(HttpRequestWorker *worker);
    void buildLineListSignalFull(HttpRequestWorker *worker, PaginatedBuildLineList summary);
    void buildLinePartialUpdateSignalFull(HttpRequestWorker *worker, BuildLine summary);
    void buildLineRetrieveSignalFull(HttpRequestWorker *worker, BuildLine summary);
    void buildLineUpdateSignalFull(HttpRequestWorker *worker, BuildLine summary);
    void buildListSignalFull(HttpRequestWorker *worker, PaginatedBuildList summary);
    void buildMetadataPartialUpdateSignalFull(HttpRequestWorker *worker);
    void buildMetadataRetrieveSignalFull(HttpRequestWorker *worker);
    void buildMetadataUpdateSignalFull(HttpRequestWorker *worker);
    void buildPartialUpdateSignalFull(HttpRequestWorker *worker, Build summary);
    void buildRetrieveSignalFull(HttpRequestWorker *worker, Build summary);
    void buildScrapOutputsCreateSignalFull(HttpRequestWorker *worker, BuildOutputScrap summary);
    void buildStatusRetrieveSignalFull(HttpRequestWorker *worker);
    void buildUnallocateCreateSignalFull(HttpRequestWorker *worker, BuildUnallocation summary);
    void buildUpdateSignalFull(HttpRequestWorker *worker, Build summary);

    Q_DECL_DEPRECATED_X("Use buildAllocateCreateSignalError() instead")
    void buildAllocateCreateSignalE(BuildAllocation summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAllocateCreateSignalError(BuildAllocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentCreateSignalError() instead")
    void buildAttachmentCreateSignalE(BuildAttachment summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentCreateSignalError(BuildAttachment summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentDestroySignalError() instead")
    void buildAttachmentDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentDestroy2SignalError() instead")
    void buildAttachmentDestroy2SignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentDestroy2SignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentListSignalError() instead")
    void buildAttachmentListSignalE(PaginatedBuildAttachmentList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentListSignalError(PaginatedBuildAttachmentList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentPartialUpdateSignalError() instead")
    void buildAttachmentPartialUpdateSignalE(BuildAttachment summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentPartialUpdateSignalError(BuildAttachment summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentRetrieveSignalError() instead")
    void buildAttachmentRetrieveSignalE(BuildAttachment summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentRetrieveSignalError(BuildAttachment summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentUpdateSignalError() instead")
    void buildAttachmentUpdateSignalE(BuildAttachment summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentUpdateSignalError(BuildAttachment summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAutoAllocateCreateSignalError() instead")
    void buildAutoAllocateCreateSignalE(BuildAutoAllocation summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAutoAllocateCreateSignalError(BuildAutoAllocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCancelCreateSignalError() instead")
    void buildCancelCreateSignalE(BuildCancel summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCancelCreateSignalError(BuildCancel summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCompleteCreateSignalError() instead")
    void buildCompleteCreateSignalE(BuildOutputComplete summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCompleteCreateSignalError(BuildOutputComplete summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCreateSignalError() instead")
    void buildCreateSignalE(Build summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCreateSignalError(Build summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCreateOutputCreateSignalError() instead")
    void buildCreateOutputCreateSignalE(BuildOutputCreate summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCreateOutputCreateSignalError(BuildOutputCreate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildDeleteOutputsCreateSignalError() instead")
    void buildDeleteOutputsCreateSignalE(BuildOutputDelete summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildDeleteOutputsCreateSignalError(BuildOutputDelete summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildDestroySignalError() instead")
    void buildDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildFinishCreateSignalError() instead")
    void buildFinishCreateSignalE(BuildComplete summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildFinishCreateSignalError(BuildComplete summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemCreateSignalError() instead")
    void buildItemCreateSignalE(BuildItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemCreateSignalError(BuildItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemDestroySignalError() instead")
    void buildItemDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemListSignalError() instead")
    void buildItemListSignalE(PaginatedBuildItemList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemListSignalError(PaginatedBuildItemList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataPartialUpdateSignalError() instead")
    void buildItemMetadataPartialUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataPartialUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataRetrieveSignalError() instead")
    void buildItemMetadataRetrieveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataRetrieveSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataUpdateSignalError() instead")
    void buildItemMetadataUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemPartialUpdateSignalError() instead")
    void buildItemPartialUpdateSignalE(BuildItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemPartialUpdateSignalError(BuildItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemRetrieveSignalError() instead")
    void buildItemRetrieveSignalE(BuildItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemRetrieveSignalError(BuildItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemUpdateSignalError() instead")
    void buildItemUpdateSignalE(BuildItem summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemUpdateSignalError(BuildItem summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineCreateSignalError() instead")
    void buildLineCreateSignalE(BuildLine summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineCreateSignalError(BuildLine summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineDestroySignalError() instead")
    void buildLineDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineListSignalError() instead")
    void buildLineListSignalE(PaginatedBuildLineList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineListSignalError(PaginatedBuildLineList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLinePartialUpdateSignalError() instead")
    void buildLinePartialUpdateSignalE(BuildLine summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLinePartialUpdateSignalError(BuildLine summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineRetrieveSignalError() instead")
    void buildLineRetrieveSignalE(BuildLine summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineRetrieveSignalError(BuildLine summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineUpdateSignalError() instead")
    void buildLineUpdateSignalE(BuildLine summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineUpdateSignalError(BuildLine summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildListSignalError() instead")
    void buildListSignalE(PaginatedBuildList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildListSignalError(PaginatedBuildList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataPartialUpdateSignalError() instead")
    void buildMetadataPartialUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataPartialUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataRetrieveSignalError() instead")
    void buildMetadataRetrieveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataRetrieveSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataUpdateSignalError() instead")
    void buildMetadataUpdateSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataUpdateSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildPartialUpdateSignalError() instead")
    void buildPartialUpdateSignalE(Build summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildPartialUpdateSignalError(Build summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildRetrieveSignalError() instead")
    void buildRetrieveSignalE(Build summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildRetrieveSignalError(Build summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildScrapOutputsCreateSignalError() instead")
    void buildScrapOutputsCreateSignalE(BuildOutputScrap summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildScrapOutputsCreateSignalError(BuildOutputScrap summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildStatusRetrieveSignalError() instead")
    void buildStatusRetrieveSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void buildStatusRetrieveSignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildUnallocateCreateSignalError() instead")
    void buildUnallocateCreateSignalE(BuildUnallocation summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildUnallocateCreateSignalError(BuildUnallocation summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildUpdateSignalError() instead")
    void buildUpdateSignalE(Build summary, QNetworkReply::NetworkError error_type, QString error_str);
    void buildUpdateSignalError(Build summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use buildAllocateCreateSignalErrorFull() instead")
    void buildAllocateCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAllocateCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentCreateSignalErrorFull() instead")
    void buildAttachmentCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentDestroySignalErrorFull() instead")
    void buildAttachmentDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentDestroy2SignalErrorFull() instead")
    void buildAttachmentDestroy2SignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentDestroy2SignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentListSignalErrorFull() instead")
    void buildAttachmentListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentPartialUpdateSignalErrorFull() instead")
    void buildAttachmentPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentRetrieveSignalErrorFull() instead")
    void buildAttachmentRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAttachmentUpdateSignalErrorFull() instead")
    void buildAttachmentUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAttachmentUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildAutoAllocateCreateSignalErrorFull() instead")
    void buildAutoAllocateCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildAutoAllocateCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCancelCreateSignalErrorFull() instead")
    void buildCancelCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCancelCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCompleteCreateSignalErrorFull() instead")
    void buildCompleteCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCompleteCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCreateSignalErrorFull() instead")
    void buildCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildCreateOutputCreateSignalErrorFull() instead")
    void buildCreateOutputCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildCreateOutputCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildDeleteOutputsCreateSignalErrorFull() instead")
    void buildDeleteOutputsCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildDeleteOutputsCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildDestroySignalErrorFull() instead")
    void buildDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildFinishCreateSignalErrorFull() instead")
    void buildFinishCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildFinishCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemCreateSignalErrorFull() instead")
    void buildItemCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemDestroySignalErrorFull() instead")
    void buildItemDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemListSignalErrorFull() instead")
    void buildItemListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataPartialUpdateSignalErrorFull() instead")
    void buildItemMetadataPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataRetrieveSignalErrorFull() instead")
    void buildItemMetadataRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemMetadataUpdateSignalErrorFull() instead")
    void buildItemMetadataUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemMetadataUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemPartialUpdateSignalErrorFull() instead")
    void buildItemPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemRetrieveSignalErrorFull() instead")
    void buildItemRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildItemUpdateSignalErrorFull() instead")
    void buildItemUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildItemUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineCreateSignalErrorFull() instead")
    void buildLineCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineDestroySignalErrorFull() instead")
    void buildLineDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineListSignalErrorFull() instead")
    void buildLineListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLinePartialUpdateSignalErrorFull() instead")
    void buildLinePartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLinePartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineRetrieveSignalErrorFull() instead")
    void buildLineRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildLineUpdateSignalErrorFull() instead")
    void buildLineUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildLineUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildListSignalErrorFull() instead")
    void buildListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataPartialUpdateSignalErrorFull() instead")
    void buildMetadataPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataRetrieveSignalErrorFull() instead")
    void buildMetadataRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildMetadataUpdateSignalErrorFull() instead")
    void buildMetadataUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildMetadataUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildPartialUpdateSignalErrorFull() instead")
    void buildPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildRetrieveSignalErrorFull() instead")
    void buildRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildScrapOutputsCreateSignalErrorFull() instead")
    void buildScrapOutputsCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildScrapOutputsCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildStatusRetrieveSignalErrorFull() instead")
    void buildStatusRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildStatusRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildUnallocateCreateSignalErrorFull() instead")
    void buildUnallocateCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildUnallocateCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use buildUpdateSignalErrorFull() instead")
    void buildUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void buildUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace InvenTree
#endif
