/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "BuildAllocationItem.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

BuildAllocationItem::BuildAllocationItem(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

BuildAllocationItem::BuildAllocationItem() {
    this->initializeModel();
}

BuildAllocationItem::~BuildAllocationItem() {}

void BuildAllocationItem::initializeModel() {

    m_build_line_isSet = false;
    m_build_line_isValid = false;

    m_stock_item_isSet = false;
    m_stock_item_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;

    m_output_isSet = false;
    m_output_isValid = false;
}

void BuildAllocationItem::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void BuildAllocationItem::fromJsonObject(QJsonObject json) {

    m_build_line_isValid = ::InvenTree::fromJsonValue(m_build_line, json[QString("build_line")]);
    m_build_line_isSet = !json[QString("build_line")].isNull() && m_build_line_isValid;

    m_stock_item_isValid = ::InvenTree::fromJsonValue(m_stock_item, json[QString("stock_item")]);
    m_stock_item_isSet = !json[QString("stock_item")].isNull() && m_stock_item_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;

    m_output_isValid = ::InvenTree::fromJsonValue(m_output, json[QString("output")]);
    m_output_isSet = !json[QString("output")].isNull() && m_output_isValid;
}

QString BuildAllocationItem::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject BuildAllocationItem::asJsonObject() const {
    QJsonObject obj;
    if (m_build_line_isSet) {
        obj.insert(QString("build_line"), ::InvenTree::toJsonValue(m_build_line));
    }
    if (m_stock_item_isSet) {
        obj.insert(QString("stock_item"), ::InvenTree::toJsonValue(m_stock_item));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    if (m_output_isSet) {
        obj.insert(QString("output"), ::InvenTree::toJsonValue(m_output));
    }
    return obj;
}

QMap<QString, QString> BuildAllocationItem::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> BuildAllocationItem::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_build_line_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("build_line"), namePrefix), m_build_line);
    }
    if (m_stock_item_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("stock_item"), namePrefix), m_stock_item);
    }
    if (m_quantity_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("quantity"), namePrefix), m_quantity);
    }
    if (m_output_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("output"), namePrefix), m_output);
    }
    return vars;
}

QList<HttpFileElement> BuildAllocationItem::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> BuildAllocationItem::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_build_line_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("build_line"), namePrefix), m_build_line);
    }
    if (m_stock_item_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("stock_item"), namePrefix), m_stock_item);
    }
    if (m_quantity_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("quantity"), namePrefix), m_quantity);
    }
    if (m_output_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("output"), namePrefix), m_output);
    }
    return files;
}

qint32 BuildAllocationItem::getBuildLine() const {
    return m_build_line;
}
void BuildAllocationItem::setBuildLine(const qint32 &build_line) {
    m_build_line = build_line;
    m_build_line_isSet = true;
}

bool BuildAllocationItem::is_build_line_Set() const{
    return m_build_line_isSet;
}

bool BuildAllocationItem::is_build_line_Valid() const{
    return m_build_line_isValid;
}

qint32 BuildAllocationItem::getStockItem() const {
    return m_stock_item;
}
void BuildAllocationItem::setStockItem(const qint32 &stock_item) {
    m_stock_item = stock_item;
    m_stock_item_isSet = true;
}

bool BuildAllocationItem::is_stock_item_Set() const{
    return m_stock_item_isSet;
}

bool BuildAllocationItem::is_stock_item_Valid() const{
    return m_stock_item_isValid;
}

QString BuildAllocationItem::getQuantity() const {
    return m_quantity;
}
void BuildAllocationItem::setQuantity(const QString &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool BuildAllocationItem::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool BuildAllocationItem::is_quantity_Valid() const{
    return m_quantity_isValid;
}

qint32 BuildAllocationItem::getOutput() const {
    return m_output;
}
void BuildAllocationItem::setOutput(const qint32 &output) {
    m_output = output;
    m_output_isSet = true;
}

bool BuildAllocationItem::is_output_Set() const{
    return m_output_isSet;
}

bool BuildAllocationItem::is_output_Valid() const{
    return m_output_isValid;
}

bool BuildAllocationItem::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_build_line_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_stock_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_output_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool BuildAllocationItem::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_build_line_isValid && m_stock_item_isValid && m_quantity_isValid && true;
}

} // namespace InvenTree
