/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 158
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Build.h
 *
 * Serializes a Build object.
 */

#ifndef Build_H
#define Build_H

#include <QJsonObject>

#include "BuildStatusEnum.h"
#include "Owner.h"
#include "PartBrief.h"
#include "ProjectCode.h"
#include "User.h"
#include <QDate>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {
class PartBrief;
class ProjectCode;
class User;
class Owner;

class Build : public Object {
public:
    Build();
    Build(QString json);
    ~Build() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    QString getUrl() const;
    void setUrl(const QString &url);
    bool is_url_Set() const;
    bool is_url_Valid() const;

    QString getTitle() const;
    void setTitle(const QString &title);
    bool is_title_Set() const;
    bool is_title_Valid() const;

    QString getBarcodeHash() const;
    void setBarcodeHash(const QString &barcode_hash);
    bool is_barcode_hash_Set() const;
    bool is_barcode_hash_Valid() const;

    QString getBatch() const;
    void setBatch(const QString &batch);
    bool is_batch_Set() const;
    bool is_batch_Valid() const;

    QDate getCreationDate() const;
    void setCreationDate(const QDate &creation_date);
    bool is_creation_date_Set() const;
    bool is_creation_date_Valid() const;

    qint32 getCompleted() const;
    void setCompleted(const qint32 &completed);
    bool is_completed_Set() const;
    bool is_completed_Valid() const;

    QDate getCompletionDate() const;
    void setCompletionDate(const QDate &completion_date);
    bool is_completion_date_Set() const;
    bool is_completion_date_Valid() const;

    qint32 getDestination() const;
    void setDestination(const qint32 &destination);
    bool is_destination_Set() const;
    bool is_destination_Valid() const;

    qint32 getParent() const;
    void setParent(const qint32 &parent);
    bool is_parent_Set() const;
    bool is_parent_Valid() const;

    qint32 getPart() const;
    void setPart(const qint32 &part);
    bool is_part_Set() const;
    bool is_part_Valid() const;

    PartBrief getPartDetail() const;
    void setPartDetail(const PartBrief &part_detail);
    bool is_part_detail_Set() const;
    bool is_part_detail_Valid() const;

    qint32 getProjectCode() const;
    void setProjectCode(const qint32 &project_code);
    bool is_project_code_Set() const;
    bool is_project_code_Valid() const;

    ProjectCode getProjectCodeDetail() const;
    void setProjectCodeDetail(const ProjectCode &project_code_detail);
    bool is_project_code_detail_Set() const;
    bool is_project_code_detail_Valid() const;

    bool isOverdue() const;
    void setOverdue(const bool &overdue);
    bool is_overdue_Set() const;
    bool is_overdue_Valid() const;

    QString getReference() const;
    void setReference(const QString &reference);
    bool is_reference_Set() const;
    bool is_reference_Valid() const;

    qint32 getSalesOrder() const;
    void setSalesOrder(const qint32 &sales_order);
    bool is_sales_order_Set() const;
    bool is_sales_order_Valid() const;

    double getQuantity() const;
    void setQuantity(const double &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    BuildStatusEnum getStatus() const;
    void setStatus(const BuildStatusEnum &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getStatusText() const;
    void setStatusText(const QString &status_text);
    bool is_status_text_Set() const;
    bool is_status_text_Valid() const;

    QDate getTargetDate() const;
    void setTargetDate(const QDate &target_date);
    bool is_target_date_Set() const;
    bool is_target_date_Valid() const;

    qint32 getTakeFrom() const;
    void setTakeFrom(const qint32 &take_from);
    bool is_take_from_Set() const;
    bool is_take_from_Valid() const;

    QString getNotes() const;
    void setNotes(const QString &notes);
    bool is_notes_Set() const;
    bool is_notes_Valid() const;

    QString getLink() const;
    void setLink(const QString &link);
    bool is_link_Set() const;
    bool is_link_Valid() const;

    qint32 getIssuedBy() const;
    void setIssuedBy(const qint32 &issued_by);
    bool is_issued_by_Set() const;
    bool is_issued_by_Valid() const;

    User getIssuedByDetail() const;
    void setIssuedByDetail(const User &issued_by_detail);
    bool is_issued_by_detail_Set() const;
    bool is_issued_by_detail_Valid() const;

    qint32 getResponsible() const;
    void setResponsible(const qint32 &responsible);
    bool is_responsible_Set() const;
    bool is_responsible_Valid() const;

    Owner getResponsibleDetail() const;
    void setResponsibleDetail(const Owner &responsible_detail);
    bool is_responsible_detail_Set() const;
    bool is_responsible_detail_Valid() const;

    qint64 getPriority() const;
    void setPriority(const qint64 &priority);
    bool is_priority_Set() const;
    bool is_priority_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    QString m_url;
    bool m_url_isSet;
    bool m_url_isValid;

    QString m_title;
    bool m_title_isSet;
    bool m_title_isValid;

    QString m_barcode_hash;
    bool m_barcode_hash_isSet;
    bool m_barcode_hash_isValid;

    QString m_batch;
    bool m_batch_isSet;
    bool m_batch_isValid;

    QDate m_creation_date;
    bool m_creation_date_isSet;
    bool m_creation_date_isValid;

    qint32 m_completed;
    bool m_completed_isSet;
    bool m_completed_isValid;

    QDate m_completion_date;
    bool m_completion_date_isSet;
    bool m_completion_date_isValid;

    qint32 m_destination;
    bool m_destination_isSet;
    bool m_destination_isValid;

    qint32 m_parent;
    bool m_parent_isSet;
    bool m_parent_isValid;

    qint32 m_part;
    bool m_part_isSet;
    bool m_part_isValid;

    PartBrief m_part_detail;
    bool m_part_detail_isSet;
    bool m_part_detail_isValid;

    qint32 m_project_code;
    bool m_project_code_isSet;
    bool m_project_code_isValid;

    ProjectCode m_project_code_detail;
    bool m_project_code_detail_isSet;
    bool m_project_code_detail_isValid;

    bool m_overdue;
    bool m_overdue_isSet;
    bool m_overdue_isValid;

    QString m_reference;
    bool m_reference_isSet;
    bool m_reference_isValid;

    qint32 m_sales_order;
    bool m_sales_order_isSet;
    bool m_sales_order_isValid;

    double m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;

    BuildStatusEnum m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString m_status_text;
    bool m_status_text_isSet;
    bool m_status_text_isValid;

    QDate m_target_date;
    bool m_target_date_isSet;
    bool m_target_date_isValid;

    qint32 m_take_from;
    bool m_take_from_isSet;
    bool m_take_from_isValid;

    QString m_notes;
    bool m_notes_isSet;
    bool m_notes_isValid;

    QString m_link;
    bool m_link_isSet;
    bool m_link_isValid;

    qint32 m_issued_by;
    bool m_issued_by_isSet;
    bool m_issued_by_isValid;

    User m_issued_by_detail;
    bool m_issued_by_detail_isSet;
    bool m_issued_by_detail_isValid;

    qint32 m_responsible;
    bool m_responsible_isSet;
    bool m_responsible_isValid;

    Owner m_responsible_detail;
    bool m_responsible_detail_isSet;
    bool m_responsible_detail_isValid;

    qint64 m_priority;
    bool m_priority_isSet;
    bool m_priority_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::Build)

#endif // Build_H
