/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 160
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BuildOutputComplete.h
 *
 * DRF serializer for completing one or more build outputs.
 */

#ifndef BuildOutputComplete_H
#define BuildOutputComplete_H

#include <QJsonObject>

#include "BuildOutput.h"
#include "Status46bEnum.h"
#include <QList>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {
class BuildOutput;

class BuildOutputComplete : public Object {
public:
    BuildOutputComplete();
    BuildOutputComplete(QString json);
    ~BuildOutputComplete() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<BuildOutput> getOutputs() const;
    void setOutputs(const QList<BuildOutput> &outputs);
    bool is_outputs_Set() const;
    bool is_outputs_Valid() const;

    qint32 getLocation() const;
    void setLocation(const qint32 &location);
    bool is_location_Set() const;
    bool is_location_Valid() const;

    Status46bEnum getStatus() const;
    void setStatus(const Status46bEnum &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    bool isAcceptIncompleteAllocation() const;
    void setAcceptIncompleteAllocation(const bool &accept_incomplete_allocation);
    bool is_accept_incomplete_allocation_Set() const;
    bool is_accept_incomplete_allocation_Valid() const;

    QString getNotes() const;
    void setNotes(const QString &notes);
    bool is_notes_Set() const;
    bool is_notes_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<BuildOutput> m_outputs;
    bool m_outputs_isSet;
    bool m_outputs_isValid;

    qint32 m_location;
    bool m_location_isSet;
    bool m_location_isValid;

    Status46bEnum m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    bool m_accept_incomplete_allocation;
    bool m_accept_incomplete_allocation_isSet;
    bool m_accept_incomplete_allocation_isValid;

    QString m_notes;
    bool m_notes_isSet;
    bool m_notes_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::BuildOutputComplete)

#endif // BuildOutputComplete_H
