/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "BulkRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

BulkRequest::BulkRequest(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

BulkRequest::BulkRequest() {
    this->initializeModel();
}

BulkRequest::~BulkRequest() {}

void BulkRequest::initializeModel() {

    m_items_isSet = false;
    m_items_isValid = false;

    m_filters_isSet = false;
    m_filters_isValid = false;
}

void BulkRequest::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void BulkRequest::fromJsonObject(QJsonObject json) {

    m_items_isValid = ::InvenTree::fromJsonValue(m_items, json[QString("items")]);
    m_items_isSet = !json[QString("items")].isNull() && m_items_isValid;

    m_filters_isValid = ::InvenTree::fromJsonValue(m_filters, json[QString("filters")]);
    m_filters_isSet = !json[QString("filters")].isNull() && m_filters_isValid;
}

QString BulkRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject BulkRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_items.size() > 0) {
        obj.insert(QString("items"), ::InvenTree::toJsonValue(m_items));
    }
    if (m_filters.size() > 0) {
        obj.insert(QString("filters"), ::InvenTree::toJsonValue(m_filters));
    }
    return obj;
}

QMap<QString, QString> BulkRequest::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> BulkRequest::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_items.size() > 0) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("items"), namePrefix), m_items);
    }
    if (m_filters.size() > 0) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("filters"), namePrefix), m_filters);
    }
    return vars;
}

QList<HttpFileElement> BulkRequest::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> BulkRequest::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_items.size() > 0) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("items"), namePrefix), m_items);
    }
    if (m_filters.size() > 0) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("filters"), namePrefix), m_filters);
    }
    return files;
}

QList<qint32> BulkRequest::getItems() const {
    return m_items;
}
void BulkRequest::setItems(const QList<qint32> &items) {
    m_items = items;
    m_items_isSet = true;
}

bool BulkRequest::is_items_Set() const{
    return m_items_isSet;
}

bool BulkRequest::is_items_Valid() const{
    return m_items_isValid;
}

QMap<QString, QJsonValue> BulkRequest::getFilters() const {
    return m_filters;
}
void BulkRequest::setFilters(const QMap<QString, QJsonValue> &filters) {
    m_filters = filters;
    m_filters_isSet = true;
}

bool BulkRequest::is_filters_Set() const{
    return m_filters_isSet;
}

bool BulkRequest::is_filters_Valid() const{
    return m_filters_isValid;
}

bool BulkRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_items.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_filters.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool BulkRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
