QT += network

HEADERS += \
# Models
    $${PWD}/APISearchView.h \
    $${PWD}/AcceptOverallocatedEnum.h \
    $${PWD}/ActionPlugin.h \
    $${PWD}/ActionPluginError.h \
    $${PWD}/Address.h \
    $${PWD}/AddressBrief.h \
    $${PWD}/AllUnitListResponse.h \
    $${PWD}/ApiToken.h \
    $${PWD}/Attachment.h \
    $${PWD}/AttachmentModelTypeEnum.h \
    $${PWD}/Barcode.h \
    $${PWD}/BarcodeAssign.h \
    $${PWD}/BarcodeGenerate.h \
    $${PWD}/BarcodePOAllocate.h \
    $${PWD}/BarcodePOReceive.h \
    $${PWD}/BarcodeSOAllocate.h \
    $${PWD}/BarcodeScanResult.h \
    $${PWD}/BarcodeUnassign.h \
    $${PWD}/BlankEnum.h \
    $${PWD}/BomItem.h \
    $${PWD}/BomItemSubstitute.h \
    $${PWD}/BomItemValidation.h \
    $${PWD}/BriefUserProfile.h \
    $${PWD}/Build.h \
    $${PWD}/BuildAllocation.h \
    $${PWD}/BuildAllocationItem.h \
    $${PWD}/BuildAutoAllocation.h \
    $${PWD}/BuildCancel.h \
    $${PWD}/BuildComplete.h \
    $${PWD}/BuildConsume.h \
    $${PWD}/BuildConsumeAllocation.h \
    $${PWD}/BuildConsumeLineItem.h \
    $${PWD}/BuildItem.h \
    $${PWD}/BuildLine.h \
    $${PWD}/BuildOutput.h \
    $${PWD}/BuildOutputComplete.h \
    $${PWD}/BuildOutputCreate.h \
    $${PWD}/BuildOutputDelete.h \
    $${PWD}/BuildOutputQuantity.h \
    $${PWD}/BuildOutputScrap.h \
    $${PWD}/BuildStatusEnum.h \
    $${PWD}/BuildUnallocation.h \
    $${PWD}/BulkRequest.h \
    $${PWD}/Category.h \
    $${PWD}/CategoryParameterTemplate.h \
    $${PWD}/CategoryTree.h \
    $${PWD}/ColorEnum.h \
    $${PWD}/Company.h \
    $${PWD}/CompanyBrief.h \
    $${PWD}/Config.h \
    $${PWD}/ConfigTypeEnum.h \
    $${PWD}/Contact.h \
    $${PWD}/ContentType.h \
    $${PWD}/ConvertStockItem.h \
    $${PWD}/CurrencyExchange.h \
    $${PWD}/CustomState.h \
    $${PWD}/CustomUnit.h \
    $${PWD}/Customize.h \
    $${PWD}/DataImportAcceptRow.h \
    $${PWD}/DataImportColumnMap.h \
    $${PWD}/DataImportRow.h \
    $${PWD}/DataImportSession.h \
    $${PWD}/DataImportSessionModelTypeEnum.h \
    $${PWD}/DataImportSessionStatusEnum.h \
    $${PWD}/DataImporterModel.h \
    $${PWD}/DataOutput.h \
    $${PWD}/DefaultLocation.h \
    $${PWD}/DirectionEnum.h \
    $${PWD}/DuplicateOrder.h \
    $${PWD}/DuplicatePart.h \
    $${PWD}/EmailMessage.h \
    $${PWD}/EmailMessageStatusEnum.h \
    $${PWD}/ErrorMessage.h \
    $${PWD}/ExtendedUser.h \
    $${PWD}/FailedTask.h \
    $${PWD}/Flag.h \
    $${PWD}/GenerateBatchCode.h \
    $${PWD}/GenerateSerialNumber.h \
    $${PWD}/GenericStateClass.h \
    $${PWD}/GenericStateValue.h \
    $${PWD}/GetAuthToken.h \
    $${PWD}/GetSimpleLogin.h \
    $${PWD}/GlobalSettings.h \
    $${PWD}/Group.h \
    $${PWD}/HealthCheckStatus.h \
    $${PWD}/HealthCheckStatusStatusEnum.h \
    $${PWD}/Icon.h \
    $${PWD}/IconPackage.h \
    $${PWD}/ImportParameter.h \
    $${PWD}/ImportRequest.h \
    $${PWD}/ImportResult.h \
    $${PWD}/InfoApi.h \
    $${PWD}/InitialStock.h \
    $${PWD}/InitialSupplier.h \
    $${PWD}/InstallStockItem.h \
    $${PWD}/LabelPrint.h \
    $${PWD}/LabelTemplate.h \
    $${PWD}/LicenseView.h \
    $${PWD}/Link.h \
    $${PWD}/LocatePlugin.h \
    $${PWD}/Location.h \
    $${PWD}/LocationBrief.h \
    $${PWD}/LocationTree.h \
    $${PWD}/MachineConfig.h \
    $${PWD}/MachineConfigCreate.h \
    $${PWD}/MachineDriver.h \
    $${PWD}/MachineProperty.h \
    $${PWD}/MachinePropertyTypeEnum.h \
    $${PWD}/MachineRegistryError.h \
    $${PWD}/MachineRegistryStatus.h \
    $${PWD}/MachineRestart.h \
    $${PWD}/MachineSetting.h \
    $${PWD}/MachineType.h \
    $${PWD}/ManufacturerPart.h \
    $${PWD}/MeUser.h \
    $${PWD}/ModelType4f8Enum.h \
    $${PWD}/NameEnum.h \
    $${PWD}/NewsFeedEntry.h \
    $${PWD}/NotesImage.h \
    $${PWD}/NotificationMessage.h \
    $${PWD}/NullEnum.h \
    $${PWD}/OutcomeEnum.h \
    $${PWD}/Owner.h \
    $${PWD}/PageSizeEnum.h \
    $${PWD}/PaginatedAddressList.h \
    $${PWD}/PaginatedApiTokenList.h \
    $${PWD}/PaginatedAttachmentList.h \
    $${PWD}/PaginatedBarcodeScanResultList.h \
    $${PWD}/PaginatedBomItemList.h \
    $${PWD}/PaginatedBomItemSubstituteList.h \
    $${PWD}/PaginatedBuildItemList.h \
    $${PWD}/PaginatedBuildLineList.h \
    $${PWD}/PaginatedBuildList.h \
    $${PWD}/PaginatedCategoryList.h \
    $${PWD}/PaginatedCategoryParameterTemplateList.h \
    $${PWD}/PaginatedCategoryTreeList.h \
    $${PWD}/PaginatedCompanyList.h \
    $${PWD}/PaginatedContactList.h \
    $${PWD}/PaginatedContentTypeList.h \
    $${PWD}/PaginatedCustomStateList.h \
    $${PWD}/PaginatedCustomUnitList.h \
    $${PWD}/PaginatedDataImportColumnMapList.h \
    $${PWD}/PaginatedDataImportRowList.h \
    $${PWD}/PaginatedDataImportSessionList.h \
    $${PWD}/PaginatedDataOutputList.h \
    $${PWD}/PaginatedEmailMessageList.h \
    $${PWD}/PaginatedErrorMessageList.h \
    $${PWD}/PaginatedFailedTaskList.h \
    $${PWD}/PaginatedGlobalSettingsList.h \
    $${PWD}/PaginatedGroupList.h \
    $${PWD}/PaginatedIconPackageList.h \
    $${PWD}/PaginatedLabelTemplateList.h \
    $${PWD}/PaginatedLocationList.h \
    $${PWD}/PaginatedLocationTreeList.h \
    $${PWD}/PaginatedMachineConfigList.h \
    $${PWD}/PaginatedManufacturerPartList.h \
    $${PWD}/PaginatedNewsFeedEntryList.h \
    $${PWD}/PaginatedNotesImageList.h \
    $${PWD}/PaginatedNotificationMessageList.h \
    $${PWD}/PaginatedOwnerList.h \
    $${PWD}/PaginatedParameterList.h \
    $${PWD}/PaginatedParameterTemplateList.h \
    $${PWD}/PaginatedPartInternalPriceList.h \
    $${PWD}/PaginatedPartList.h \
    $${PWD}/PaginatedPartRelationList.h \
    $${PWD}/PaginatedPartSalePriceList.h \
    $${PWD}/PaginatedPartStocktakeList.h \
    $${PWD}/PaginatedPartTestTemplateList.h \
    $${PWD}/PaginatedPartThumbList.h \
    $${PWD}/PaginatedPendingTaskList.h \
    $${PWD}/PaginatedPluginConfigList.h \
    $${PWD}/PaginatedPluginSettingList.h \
    $${PWD}/PaginatedProjectCodeList.h \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.h \
    $${PWD}/PaginatedPurchaseOrderLineItemList.h \
    $${PWD}/PaginatedPurchaseOrderList.h \
    $${PWD}/PaginatedReportAssetList.h \
    $${PWD}/PaginatedReportSnippetList.h \
    $${PWD}/PaginatedReportTemplateList.h \
    $${PWD}/PaginatedReturnOrderExtraLineList.h \
    $${PWD}/PaginatedReturnOrderLineItemList.h \
    $${PWD}/PaginatedReturnOrderList.h \
    $${PWD}/PaginatedRuleSetList.h \
    $${PWD}/PaginatedSalesOrderAllocationList.h \
    $${PWD}/PaginatedSalesOrderExtraLineList.h \
    $${PWD}/PaginatedSalesOrderLineItemList.h \
    $${PWD}/PaginatedSalesOrderList.h \
    $${PWD}/PaginatedSalesOrderShipmentList.h \
    $${PWD}/PaginatedScheduledTaskList.h \
    $${PWD}/PaginatedSelectionEntryList.h \
    $${PWD}/PaginatedSelectionListList.h \
    $${PWD}/PaginatedStockItemList.h \
    $${PWD}/PaginatedStockItemTestResultList.h \
    $${PWD}/PaginatedStockLocationTypeList.h \
    $${PWD}/PaginatedStockTrackingList.h \
    $${PWD}/PaginatedSupplierPartList.h \
    $${PWD}/PaginatedSupplierPriceBreakList.h \
    $${PWD}/PaginatedUserCreateList.h \
    $${PWD}/PaginatedUserSettingsList.h \
    $${PWD}/Parameter.h \
    $${PWD}/ParameterTemplate.h \
    $${PWD}/Part.h \
    $${PWD}/PartBomValidate.h \
    $${PWD}/PartBrief.h \
    $${PWD}/PartCopyBOM.h \
    $${PWD}/PartInternalPrice.h \
    $${PWD}/PartPricing.h \
    $${PWD}/PartRelation.h \
    $${PWD}/PartRequirements.h \
    $${PWD}/PartSalePrice.h \
    $${PWD}/PartSerialNumber.h \
    $${PWD}/PartStocktake.h \
    $${PWD}/PartTestTemplate.h \
    $${PWD}/PartThumb.h \
    $${PWD}/PartThumbSerializerUpdate.h \
    $${PWD}/PatchedAddress.h \
    $${PWD}/PatchedAttachment.h \
    $${PWD}/PatchedBomItem.h \
    $${PWD}/PatchedBomItemSubstitute.h \
    $${PWD}/PatchedBomItemValidation.h \
    $${PWD}/PatchedBuild.h \
    $${PWD}/PatchedBuildItem.h \
    $${PWD}/PatchedBuildLine.h \
    $${PWD}/PatchedCategory.h \
    $${PWD}/PatchedCategoryParameterTemplate.h \
    $${PWD}/PatchedCompany.h \
    $${PWD}/PatchedContact.h \
    $${PWD}/PatchedCustomState.h \
    $${PWD}/PatchedCustomUnit.h \
    $${PWD}/PatchedDataImportColumnMap.h \
    $${PWD}/PatchedDataImportRow.h \
    $${PWD}/PatchedDataImportSession.h \
    $${PWD}/PatchedErrorMessage.h \
    $${PWD}/PatchedExtendedUser.h \
    $${PWD}/PatchedGlobalSettings.h \
    $${PWD}/PatchedGroup.h \
    $${PWD}/PatchedLabelTemplate.h \
    $${PWD}/PatchedLocation.h \
    $${PWD}/PatchedMachineConfig.h \
    $${PWD}/PatchedMachineSetting.h \
    $${PWD}/PatchedManufacturerPart.h \
    $${PWD}/PatchedMeUser.h \
    $${PWD}/PatchedNewsFeedEntry.h \
    $${PWD}/PatchedNotificationMessage.h \
    $${PWD}/PatchedParameter.h \
    $${PWD}/PatchedParameterTemplate.h \
    $${PWD}/PatchedPart.h \
    $${PWD}/PatchedPartBomValidate.h \
    $${PWD}/PatchedPartInternalPrice.h \
    $${PWD}/PatchedPartPricing.h \
    $${PWD}/PatchedPartRelation.h \
    $${PWD}/PatchedPartSalePrice.h \
    $${PWD}/PatchedPartStocktake.h \
    $${PWD}/PatchedPartTestTemplate.h \
    $${PWD}/PatchedPartThumbSerializerUpdate.h \
    $${PWD}/PatchedPluginActivate.h \
    $${PWD}/PatchedPluginSetting.h \
    $${PWD}/PatchedPluginUninstall.h \
    $${PWD}/PatchedPluginUserSetting.h \
    $${PWD}/PatchedProjectCode.h \
    $${PWD}/PatchedPurchaseOrder.h \
    $${PWD}/PatchedPurchaseOrderExtraLine.h \
    $${PWD}/PatchedPurchaseOrderLineItem.h \
    $${PWD}/PatchedReportAsset.h \
    $${PWD}/PatchedReportSnippet.h \
    $${PWD}/PatchedReportTemplate.h \
    $${PWD}/PatchedReturnOrder.h \
    $${PWD}/PatchedReturnOrderExtraLine.h \
    $${PWD}/PatchedReturnOrderLineItem.h \
    $${PWD}/PatchedRuleSet.h \
    $${PWD}/PatchedSalesOrder.h \
    $${PWD}/PatchedSalesOrderAllocation.h \
    $${PWD}/PatchedSalesOrderExtraLine.h \
    $${PWD}/PatchedSalesOrderLineItem.h \
    $${PWD}/PatchedSalesOrderShipment.h \
    $${PWD}/PatchedSelectionEntry.h \
    $${PWD}/PatchedSelectionList.h \
    $${PWD}/PatchedStockItem.h \
    $${PWD}/PatchedStockItemTestResult.h \
    $${PWD}/PatchedStockLocationType.h \
    $${PWD}/PatchedSupplierPart.h \
    $${PWD}/PatchedSupplierPriceBreak.h \
    $${PWD}/PatchedUserProfile.h \
    $${PWD}/PatchedUserSetPassword.h \
    $${PWD}/PatchedUserSettings.h \
    $${PWD}/PendingTask.h \
    $${PWD}/PluginActivate.h \
    $${PWD}/PluginAdminDetail.h \
    $${PWD}/PluginConfig.h \
    $${PWD}/PluginConfigInstall.h \
    $${PWD}/PluginRegistryError.h \
    $${PWD}/PluginRegistryStatus.h \
    $${PWD}/PluginReload.h \
    $${PWD}/PluginSetting.h \
    $${PWD}/PluginUIFeature.h \
    $${PWD}/PluginUninstall.h \
    $${PWD}/PluginUserSetting.h \
    $${PWD}/PriorityEnum.h \
    $${PWD}/ProjectCode.h \
    $${PWD}/PurchaseOrder.h \
    $${PWD}/PurchaseOrderComplete.h \
    $${PWD}/PurchaseOrderExtraLine.h \
    $${PWD}/PurchaseOrderLineItem.h \
    $${PWD}/PurchaseOrderLineItemReceive.h \
    $${PWD}/PurchaseOrderReceive.h \
    $${PWD}/ReferenceStatusEnum.h \
    $${PWD}/ReportAsset.h \
    $${PWD}/ReportPrint.h \
    $${PWD}/ReportSnippet.h \
    $${PWD}/ReportTemplate.h \
    $${PWD}/ReturnOrder.h \
    $${PWD}/ReturnOrderExtraLine.h \
    $${PWD}/ReturnOrderLineItem.h \
    $${PWD}/ReturnOrderLineItemReceive.h \
    $${PWD}/ReturnOrderReceive.h \
    $${PWD}/Role.h \
    $${PWD}/RuleSet.h \
    $${PWD}/SalesOrder.h \
    $${PWD}/SalesOrderAllocation.h \
    $${PWD}/SalesOrderComplete.h \
    $${PWD}/SalesOrderExtraLine.h \
    $${PWD}/SalesOrderLineItem.h \
    $${PWD}/SalesOrderSerialAllocation.h \
    $${PWD}/SalesOrderShipment.h \
    $${PWD}/SalesOrderShipmentAllocation.h \
    $${PWD}/SalesOrderShipmentAllocationItem.h \
    $${PWD}/SalesOrderShipmentComplete.h \
    $${PWD}/ScheduleTypeEnum.h \
    $${PWD}/ScheduledTask.h \
    $${PWD}/SearchResult.h \
    $${PWD}/SelectionEntry.h \
    $${PWD}/SelectionList.h \
    $${PWD}/SerializeStockItem.h \
    $${PWD}/Settings.h \
    $${PWD}/StockAdd.h \
    $${PWD}/StockAdjustmentItem.h \
    $${PWD}/StockAssignment.h \
    $${PWD}/StockAssignmentItem.h \
    $${PWD}/StockChangeStatus.h \
    $${PWD}/StockCount.h \
    $${PWD}/StockItem.h \
    $${PWD}/StockItemSerialNumbers.h \
    $${PWD}/StockItemStatusEnum.h \
    $${PWD}/StockItemTestResult.h \
    $${PWD}/StockLocationType.h \
    $${PWD}/StockMerge.h \
    $${PWD}/StockMergeItem.h \
    $${PWD}/StockRemove.h \
    $${PWD}/StockReturn.h \
    $${PWD}/StockTracking.h \
    $${PWD}/StockTransfer.h \
    $${PWD}/SupplierList.h \
    $${PWD}/SupplierPart.h \
    $${PWD}/SupplierPriceBreak.h \
    $${PWD}/SupplierPriceBreakBrief.h \
    $${PWD}/TaskOverview.h \
    $${PWD}/TemplateModelTypeEnum.h \
    $${PWD}/TestEmail.h \
    $${PWD}/UninstallStockItem.h \
    $${PWD}/Unit.h \
    $${PWD}/User.h \
    $${PWD}/UserCreate.h \
    $${PWD}/UserProfile.h \
    $${PWD}/UserSetPassword.h \
    $${PWD}/UserSettings.h \
    $${PWD}/UserTypeEnum.h \
    $${PWD}/Version.h \
    $${PWD}/VersionInformation.h \
    $${PWD}/VersionView.h \
# APIs
    $${PWD}/ActionApi.h \
    $${PWD}/AdminApi.h \
    $${PWD}/AttachmentApi.h \
    $${PWD}/BackgroundTaskApi.h \
    $${PWD}/BarcodeApi.h \
    $${PWD}/BomApi.h \
    $${PWD}/BuildApi.h \
    $${PWD}/CompanyApi.h \
    $${PWD}/ContenttypeApi.h \
    $${PWD}/CurrencyApi.h \
    $${PWD}/DataOutputApi.h \
    $${PWD}/DefaultApi.h \
    $${PWD}/EmailApi.h \
    $${PWD}/ErrorReportApi.h \
    $${PWD}/FlagsApi.h \
    $${PWD}/GenerateApi.h \
    $${PWD}/GenericApi.h \
    $${PWD}/IconsApi.h \
    $${PWD}/ImporterApi.h \
    $${PWD}/LabelApi.h \
    $${PWD}/LicenseApi.h \
    $${PWD}/LocateApi.h \
    $${PWD}/MachineApi.h \
    $${PWD}/MetadataApi.h \
    $${PWD}/NewsApi.h \
    $${PWD}/NotesImageUploadApi.h \
    $${PWD}/NotificationsApi.h \
    $${PWD}/OrderApi.h \
    $${PWD}/ParameterApi.h \
    $${PWD}/PartApi.h \
    $${PWD}/PluginsApi.h \
    $${PWD}/ProjectCodeApi.h \
    $${PWD}/ReportApi.h \
    $${PWD}/SearchApi.h \
    $${PWD}/SelectionApi.h \
    $${PWD}/SettingsApi.h \
    $${PWD}/StockApi.h \
    $${PWD}/SupplierApi.h \
    $${PWD}/SystemApi.h \
    $${PWD}/UnitsApi.h \
    $${PWD}/UserApi.h \
    $${PWD}/VersionApi.h \
    $${PWD}/VersionTextApi.h \
    $${PWD}/WebhookApi.h \
# Others
    $${PWD}/Helpers.h \
    $${PWD}/HttpRequest.h \
    $${PWD}/Object.h \
    $${PWD}/Enum.h \
    $${PWD}/HttpFileElement.h \
    $${PWD}/ServerConfiguration.h \
    $${PWD}/ServerVariable.h \
    $${PWD}/Oauth.h

SOURCES += \
# Models
    $${PWD}/APISearchView.cpp \
    $${PWD}/AcceptOverallocatedEnum.cpp \
    $${PWD}/ActionPlugin.cpp \
    $${PWD}/ActionPluginError.cpp \
    $${PWD}/Address.cpp \
    $${PWD}/AddressBrief.cpp \
    $${PWD}/AllUnitListResponse.cpp \
    $${PWD}/ApiToken.cpp \
    $${PWD}/Attachment.cpp \
    $${PWD}/AttachmentModelTypeEnum.cpp \
    $${PWD}/Barcode.cpp \
    $${PWD}/BarcodeAssign.cpp \
    $${PWD}/BarcodeGenerate.cpp \
    $${PWD}/BarcodePOAllocate.cpp \
    $${PWD}/BarcodePOReceive.cpp \
    $${PWD}/BarcodeSOAllocate.cpp \
    $${PWD}/BarcodeScanResult.cpp \
    $${PWD}/BarcodeUnassign.cpp \
    $${PWD}/BlankEnum.cpp \
    $${PWD}/BomItem.cpp \
    $${PWD}/BomItemSubstitute.cpp \
    $${PWD}/BomItemValidation.cpp \
    $${PWD}/BriefUserProfile.cpp \
    $${PWD}/Build.cpp \
    $${PWD}/BuildAllocation.cpp \
    $${PWD}/BuildAllocationItem.cpp \
    $${PWD}/BuildAutoAllocation.cpp \
    $${PWD}/BuildCancel.cpp \
    $${PWD}/BuildComplete.cpp \
    $${PWD}/BuildConsume.cpp \
    $${PWD}/BuildConsumeAllocation.cpp \
    $${PWD}/BuildConsumeLineItem.cpp \
    $${PWD}/BuildItem.cpp \
    $${PWD}/BuildLine.cpp \
    $${PWD}/BuildOutput.cpp \
    $${PWD}/BuildOutputComplete.cpp \
    $${PWD}/BuildOutputCreate.cpp \
    $${PWD}/BuildOutputDelete.cpp \
    $${PWD}/BuildOutputQuantity.cpp \
    $${PWD}/BuildOutputScrap.cpp \
    $${PWD}/BuildStatusEnum.cpp \
    $${PWD}/BuildUnallocation.cpp \
    $${PWD}/BulkRequest.cpp \
    $${PWD}/Category.cpp \
    $${PWD}/CategoryParameterTemplate.cpp \
    $${PWD}/CategoryTree.cpp \
    $${PWD}/ColorEnum.cpp \
    $${PWD}/Company.cpp \
    $${PWD}/CompanyBrief.cpp \
    $${PWD}/Config.cpp \
    $${PWD}/ConfigTypeEnum.cpp \
    $${PWD}/Contact.cpp \
    $${PWD}/ContentType.cpp \
    $${PWD}/ConvertStockItem.cpp \
    $${PWD}/CurrencyExchange.cpp \
    $${PWD}/CustomState.cpp \
    $${PWD}/CustomUnit.cpp \
    $${PWD}/Customize.cpp \
    $${PWD}/DataImportAcceptRow.cpp \
    $${PWD}/DataImportColumnMap.cpp \
    $${PWD}/DataImportRow.cpp \
    $${PWD}/DataImportSession.cpp \
    $${PWD}/DataImportSessionModelTypeEnum.cpp \
    $${PWD}/DataImportSessionStatusEnum.cpp \
    $${PWD}/DataImporterModel.cpp \
    $${PWD}/DataOutput.cpp \
    $${PWD}/DefaultLocation.cpp \
    $${PWD}/DirectionEnum.cpp \
    $${PWD}/DuplicateOrder.cpp \
    $${PWD}/DuplicatePart.cpp \
    $${PWD}/EmailMessage.cpp \
    $${PWD}/EmailMessageStatusEnum.cpp \
    $${PWD}/ErrorMessage.cpp \
    $${PWD}/ExtendedUser.cpp \
    $${PWD}/FailedTask.cpp \
    $${PWD}/Flag.cpp \
    $${PWD}/GenerateBatchCode.cpp \
    $${PWD}/GenerateSerialNumber.cpp \
    $${PWD}/GenericStateClass.cpp \
    $${PWD}/GenericStateValue.cpp \
    $${PWD}/GetAuthToken.cpp \
    $${PWD}/GetSimpleLogin.cpp \
    $${PWD}/GlobalSettings.cpp \
    $${PWD}/Group.cpp \
    $${PWD}/HealthCheckStatus.cpp \
    $${PWD}/HealthCheckStatusStatusEnum.cpp \
    $${PWD}/Icon.cpp \
    $${PWD}/IconPackage.cpp \
    $${PWD}/ImportParameter.cpp \
    $${PWD}/ImportRequest.cpp \
    $${PWD}/ImportResult.cpp \
    $${PWD}/InfoApi.cpp \
    $${PWD}/InitialStock.cpp \
    $${PWD}/InitialSupplier.cpp \
    $${PWD}/InstallStockItem.cpp \
    $${PWD}/LabelPrint.cpp \
    $${PWD}/LabelTemplate.cpp \
    $${PWD}/LicenseView.cpp \
    $${PWD}/Link.cpp \
    $${PWD}/LocatePlugin.cpp \
    $${PWD}/Location.cpp \
    $${PWD}/LocationBrief.cpp \
    $${PWD}/LocationTree.cpp \
    $${PWD}/MachineConfig.cpp \
    $${PWD}/MachineConfigCreate.cpp \
    $${PWD}/MachineDriver.cpp \
    $${PWD}/MachineProperty.cpp \
    $${PWD}/MachinePropertyTypeEnum.cpp \
    $${PWD}/MachineRegistryError.cpp \
    $${PWD}/MachineRegistryStatus.cpp \
    $${PWD}/MachineRestart.cpp \
    $${PWD}/MachineSetting.cpp \
    $${PWD}/MachineType.cpp \
    $${PWD}/ManufacturerPart.cpp \
    $${PWD}/MeUser.cpp \
    $${PWD}/ModelType4f8Enum.cpp \
    $${PWD}/NameEnum.cpp \
    $${PWD}/NewsFeedEntry.cpp \
    $${PWD}/NotesImage.cpp \
    $${PWD}/NotificationMessage.cpp \
    $${PWD}/NullEnum.cpp \
    $${PWD}/OutcomeEnum.cpp \
    $${PWD}/Owner.cpp \
    $${PWD}/PageSizeEnum.cpp \
    $${PWD}/PaginatedAddressList.cpp \
    $${PWD}/PaginatedApiTokenList.cpp \
    $${PWD}/PaginatedAttachmentList.cpp \
    $${PWD}/PaginatedBarcodeScanResultList.cpp \
    $${PWD}/PaginatedBomItemList.cpp \
    $${PWD}/PaginatedBomItemSubstituteList.cpp \
    $${PWD}/PaginatedBuildItemList.cpp \
    $${PWD}/PaginatedBuildLineList.cpp \
    $${PWD}/PaginatedBuildList.cpp \
    $${PWD}/PaginatedCategoryList.cpp \
    $${PWD}/PaginatedCategoryParameterTemplateList.cpp \
    $${PWD}/PaginatedCategoryTreeList.cpp \
    $${PWD}/PaginatedCompanyList.cpp \
    $${PWD}/PaginatedContactList.cpp \
    $${PWD}/PaginatedContentTypeList.cpp \
    $${PWD}/PaginatedCustomStateList.cpp \
    $${PWD}/PaginatedCustomUnitList.cpp \
    $${PWD}/PaginatedDataImportColumnMapList.cpp \
    $${PWD}/PaginatedDataImportRowList.cpp \
    $${PWD}/PaginatedDataImportSessionList.cpp \
    $${PWD}/PaginatedDataOutputList.cpp \
    $${PWD}/PaginatedEmailMessageList.cpp \
    $${PWD}/PaginatedErrorMessageList.cpp \
    $${PWD}/PaginatedFailedTaskList.cpp \
    $${PWD}/PaginatedGlobalSettingsList.cpp \
    $${PWD}/PaginatedGroupList.cpp \
    $${PWD}/PaginatedIconPackageList.cpp \
    $${PWD}/PaginatedLabelTemplateList.cpp \
    $${PWD}/PaginatedLocationList.cpp \
    $${PWD}/PaginatedLocationTreeList.cpp \
    $${PWD}/PaginatedMachineConfigList.cpp \
    $${PWD}/PaginatedManufacturerPartList.cpp \
    $${PWD}/PaginatedNewsFeedEntryList.cpp \
    $${PWD}/PaginatedNotesImageList.cpp \
    $${PWD}/PaginatedNotificationMessageList.cpp \
    $${PWD}/PaginatedOwnerList.cpp \
    $${PWD}/PaginatedParameterList.cpp \
    $${PWD}/PaginatedParameterTemplateList.cpp \
    $${PWD}/PaginatedPartInternalPriceList.cpp \
    $${PWD}/PaginatedPartList.cpp \
    $${PWD}/PaginatedPartRelationList.cpp \
    $${PWD}/PaginatedPartSalePriceList.cpp \
    $${PWD}/PaginatedPartStocktakeList.cpp \
    $${PWD}/PaginatedPartTestTemplateList.cpp \
    $${PWD}/PaginatedPartThumbList.cpp \
    $${PWD}/PaginatedPendingTaskList.cpp \
    $${PWD}/PaginatedPluginConfigList.cpp \
    $${PWD}/PaginatedPluginSettingList.cpp \
    $${PWD}/PaginatedProjectCodeList.cpp \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.cpp \
    $${PWD}/PaginatedPurchaseOrderLineItemList.cpp \
    $${PWD}/PaginatedPurchaseOrderList.cpp \
    $${PWD}/PaginatedReportAssetList.cpp \
    $${PWD}/PaginatedReportSnippetList.cpp \
    $${PWD}/PaginatedReportTemplateList.cpp \
    $${PWD}/PaginatedReturnOrderExtraLineList.cpp \
    $${PWD}/PaginatedReturnOrderLineItemList.cpp \
    $${PWD}/PaginatedReturnOrderList.cpp \
    $${PWD}/PaginatedRuleSetList.cpp \
    $${PWD}/PaginatedSalesOrderAllocationList.cpp \
    $${PWD}/PaginatedSalesOrderExtraLineList.cpp \
    $${PWD}/PaginatedSalesOrderLineItemList.cpp \
    $${PWD}/PaginatedSalesOrderList.cpp \
    $${PWD}/PaginatedSalesOrderShipmentList.cpp \
    $${PWD}/PaginatedScheduledTaskList.cpp \
    $${PWD}/PaginatedSelectionEntryList.cpp \
    $${PWD}/PaginatedSelectionListList.cpp \
    $${PWD}/PaginatedStockItemList.cpp \
    $${PWD}/PaginatedStockItemTestResultList.cpp \
    $${PWD}/PaginatedStockLocationTypeList.cpp \
    $${PWD}/PaginatedStockTrackingList.cpp \
    $${PWD}/PaginatedSupplierPartList.cpp \
    $${PWD}/PaginatedSupplierPriceBreakList.cpp \
    $${PWD}/PaginatedUserCreateList.cpp \
    $${PWD}/PaginatedUserSettingsList.cpp \
    $${PWD}/Parameter.cpp \
    $${PWD}/ParameterTemplate.cpp \
    $${PWD}/Part.cpp \
    $${PWD}/PartBomValidate.cpp \
    $${PWD}/PartBrief.cpp \
    $${PWD}/PartCopyBOM.cpp \
    $${PWD}/PartInternalPrice.cpp \
    $${PWD}/PartPricing.cpp \
    $${PWD}/PartRelation.cpp \
    $${PWD}/PartRequirements.cpp \
    $${PWD}/PartSalePrice.cpp \
    $${PWD}/PartSerialNumber.cpp \
    $${PWD}/PartStocktake.cpp \
    $${PWD}/PartTestTemplate.cpp \
    $${PWD}/PartThumb.cpp \
    $${PWD}/PartThumbSerializerUpdate.cpp \
    $${PWD}/PatchedAddress.cpp \
    $${PWD}/PatchedAttachment.cpp \
    $${PWD}/PatchedBomItem.cpp \
    $${PWD}/PatchedBomItemSubstitute.cpp \
    $${PWD}/PatchedBomItemValidation.cpp \
    $${PWD}/PatchedBuild.cpp \
    $${PWD}/PatchedBuildItem.cpp \
    $${PWD}/PatchedBuildLine.cpp \
    $${PWD}/PatchedCategory.cpp \
    $${PWD}/PatchedCategoryParameterTemplate.cpp \
    $${PWD}/PatchedCompany.cpp \
    $${PWD}/PatchedContact.cpp \
    $${PWD}/PatchedCustomState.cpp \
    $${PWD}/PatchedCustomUnit.cpp \
    $${PWD}/PatchedDataImportColumnMap.cpp \
    $${PWD}/PatchedDataImportRow.cpp \
    $${PWD}/PatchedDataImportSession.cpp \
    $${PWD}/PatchedErrorMessage.cpp \
    $${PWD}/PatchedExtendedUser.cpp \
    $${PWD}/PatchedGlobalSettings.cpp \
    $${PWD}/PatchedGroup.cpp \
    $${PWD}/PatchedLabelTemplate.cpp \
    $${PWD}/PatchedLocation.cpp \
    $${PWD}/PatchedMachineConfig.cpp \
    $${PWD}/PatchedMachineSetting.cpp \
    $${PWD}/PatchedManufacturerPart.cpp \
    $${PWD}/PatchedMeUser.cpp \
    $${PWD}/PatchedNewsFeedEntry.cpp \
    $${PWD}/PatchedNotificationMessage.cpp \
    $${PWD}/PatchedParameter.cpp \
    $${PWD}/PatchedParameterTemplate.cpp \
    $${PWD}/PatchedPart.cpp \
    $${PWD}/PatchedPartBomValidate.cpp \
    $${PWD}/PatchedPartInternalPrice.cpp \
    $${PWD}/PatchedPartPricing.cpp \
    $${PWD}/PatchedPartRelation.cpp \
    $${PWD}/PatchedPartSalePrice.cpp \
    $${PWD}/PatchedPartStocktake.cpp \
    $${PWD}/PatchedPartTestTemplate.cpp \
    $${PWD}/PatchedPartThumbSerializerUpdate.cpp \
    $${PWD}/PatchedPluginActivate.cpp \
    $${PWD}/PatchedPluginSetting.cpp \
    $${PWD}/PatchedPluginUninstall.cpp \
    $${PWD}/PatchedPluginUserSetting.cpp \
    $${PWD}/PatchedProjectCode.cpp \
    $${PWD}/PatchedPurchaseOrder.cpp \
    $${PWD}/PatchedPurchaseOrderExtraLine.cpp \
    $${PWD}/PatchedPurchaseOrderLineItem.cpp \
    $${PWD}/PatchedReportAsset.cpp \
    $${PWD}/PatchedReportSnippet.cpp \
    $${PWD}/PatchedReportTemplate.cpp \
    $${PWD}/PatchedReturnOrder.cpp \
    $${PWD}/PatchedReturnOrderExtraLine.cpp \
    $${PWD}/PatchedReturnOrderLineItem.cpp \
    $${PWD}/PatchedRuleSet.cpp \
    $${PWD}/PatchedSalesOrder.cpp \
    $${PWD}/PatchedSalesOrderAllocation.cpp \
    $${PWD}/PatchedSalesOrderExtraLine.cpp \
    $${PWD}/PatchedSalesOrderLineItem.cpp \
    $${PWD}/PatchedSalesOrderShipment.cpp \
    $${PWD}/PatchedSelectionEntry.cpp \
    $${PWD}/PatchedSelectionList.cpp \
    $${PWD}/PatchedStockItem.cpp \
    $${PWD}/PatchedStockItemTestResult.cpp \
    $${PWD}/PatchedStockLocationType.cpp \
    $${PWD}/PatchedSupplierPart.cpp \
    $${PWD}/PatchedSupplierPriceBreak.cpp \
    $${PWD}/PatchedUserProfile.cpp \
    $${PWD}/PatchedUserSetPassword.cpp \
    $${PWD}/PatchedUserSettings.cpp \
    $${PWD}/PendingTask.cpp \
    $${PWD}/PluginActivate.cpp \
    $${PWD}/PluginAdminDetail.cpp \
    $${PWD}/PluginConfig.cpp \
    $${PWD}/PluginConfigInstall.cpp \
    $${PWD}/PluginRegistryError.cpp \
    $${PWD}/PluginRegistryStatus.cpp \
    $${PWD}/PluginReload.cpp \
    $${PWD}/PluginSetting.cpp \
    $${PWD}/PluginUIFeature.cpp \
    $${PWD}/PluginUninstall.cpp \
    $${PWD}/PluginUserSetting.cpp \
    $${PWD}/PriorityEnum.cpp \
    $${PWD}/ProjectCode.cpp \
    $${PWD}/PurchaseOrder.cpp \
    $${PWD}/PurchaseOrderComplete.cpp \
    $${PWD}/PurchaseOrderExtraLine.cpp \
    $${PWD}/PurchaseOrderLineItem.cpp \
    $${PWD}/PurchaseOrderLineItemReceive.cpp \
    $${PWD}/PurchaseOrderReceive.cpp \
    $${PWD}/ReferenceStatusEnum.cpp \
    $${PWD}/ReportAsset.cpp \
    $${PWD}/ReportPrint.cpp \
    $${PWD}/ReportSnippet.cpp \
    $${PWD}/ReportTemplate.cpp \
    $${PWD}/ReturnOrder.cpp \
    $${PWD}/ReturnOrderExtraLine.cpp \
    $${PWD}/ReturnOrderLineItem.cpp \
    $${PWD}/ReturnOrderLineItemReceive.cpp \
    $${PWD}/ReturnOrderReceive.cpp \
    $${PWD}/Role.cpp \
    $${PWD}/RuleSet.cpp \
    $${PWD}/SalesOrder.cpp \
    $${PWD}/SalesOrderAllocation.cpp \
    $${PWD}/SalesOrderComplete.cpp \
    $${PWD}/SalesOrderExtraLine.cpp \
    $${PWD}/SalesOrderLineItem.cpp \
    $${PWD}/SalesOrderSerialAllocation.cpp \
    $${PWD}/SalesOrderShipment.cpp \
    $${PWD}/SalesOrderShipmentAllocation.cpp \
    $${PWD}/SalesOrderShipmentAllocationItem.cpp \
    $${PWD}/SalesOrderShipmentComplete.cpp \
    $${PWD}/ScheduleTypeEnum.cpp \
    $${PWD}/ScheduledTask.cpp \
    $${PWD}/SearchResult.cpp \
    $${PWD}/SelectionEntry.cpp \
    $${PWD}/SelectionList.cpp \
    $${PWD}/SerializeStockItem.cpp \
    $${PWD}/Settings.cpp \
    $${PWD}/StockAdd.cpp \
    $${PWD}/StockAdjustmentItem.cpp \
    $${PWD}/StockAssignment.cpp \
    $${PWD}/StockAssignmentItem.cpp \
    $${PWD}/StockChangeStatus.cpp \
    $${PWD}/StockCount.cpp \
    $${PWD}/StockItem.cpp \
    $${PWD}/StockItemSerialNumbers.cpp \
    $${PWD}/StockItemStatusEnum.cpp \
    $${PWD}/StockItemTestResult.cpp \
    $${PWD}/StockLocationType.cpp \
    $${PWD}/StockMerge.cpp \
    $${PWD}/StockMergeItem.cpp \
    $${PWD}/StockRemove.cpp \
    $${PWD}/StockReturn.cpp \
    $${PWD}/StockTracking.cpp \
    $${PWD}/StockTransfer.cpp \
    $${PWD}/SupplierList.cpp \
    $${PWD}/SupplierPart.cpp \
    $${PWD}/SupplierPriceBreak.cpp \
    $${PWD}/SupplierPriceBreakBrief.cpp \
    $${PWD}/TaskOverview.cpp \
    $${PWD}/TemplateModelTypeEnum.cpp \
    $${PWD}/TestEmail.cpp \
    $${PWD}/UninstallStockItem.cpp \
    $${PWD}/Unit.cpp \
    $${PWD}/User.cpp \
    $${PWD}/UserCreate.cpp \
    $${PWD}/UserProfile.cpp \
    $${PWD}/UserSetPassword.cpp \
    $${PWD}/UserSettings.cpp \
    $${PWD}/UserTypeEnum.cpp \
    $${PWD}/Version.cpp \
    $${PWD}/VersionInformation.cpp \
    $${PWD}/VersionView.cpp \
# APIs
    $${PWD}/ActionApi.cpp \
    $${PWD}/AdminApi.cpp \
    $${PWD}/AttachmentApi.cpp \
    $${PWD}/BackgroundTaskApi.cpp \
    $${PWD}/BarcodeApi.cpp \
    $${PWD}/BomApi.cpp \
    $${PWD}/BuildApi.cpp \
    $${PWD}/CompanyApi.cpp \
    $${PWD}/ContenttypeApi.cpp \
    $${PWD}/CurrencyApi.cpp \
    $${PWD}/DataOutputApi.cpp \
    $${PWD}/DefaultApi.cpp \
    $${PWD}/EmailApi.cpp \
    $${PWD}/ErrorReportApi.cpp \
    $${PWD}/FlagsApi.cpp \
    $${PWD}/GenerateApi.cpp \
    $${PWD}/GenericApi.cpp \
    $${PWD}/IconsApi.cpp \
    $${PWD}/ImporterApi.cpp \
    $${PWD}/LabelApi.cpp \
    $${PWD}/LicenseApi.cpp \
    $${PWD}/LocateApi.cpp \
    $${PWD}/MachineApi.cpp \
    $${PWD}/MetadataApi.cpp \
    $${PWD}/NewsApi.cpp \
    $${PWD}/NotesImageUploadApi.cpp \
    $${PWD}/NotificationsApi.cpp \
    $${PWD}/OrderApi.cpp \
    $${PWD}/ParameterApi.cpp \
    $${PWD}/PartApi.cpp \
    $${PWD}/PluginsApi.cpp \
    $${PWD}/ProjectCodeApi.cpp \
    $${PWD}/ReportApi.cpp \
    $${PWD}/SearchApi.cpp \
    $${PWD}/SelectionApi.cpp \
    $${PWD}/SettingsApi.cpp \
    $${PWD}/StockApi.cpp \
    $${PWD}/SupplierApi.cpp \
    $${PWD}/SystemApi.cpp \
    $${PWD}/UnitsApi.cpp \
    $${PWD}/UserApi.cpp \
    $${PWD}/VersionApi.cpp \
    $${PWD}/VersionTextApi.cpp \
    $${PWD}/WebhookApi.cpp \
# Others
    $${PWD}/Helpers.cpp \
    $${PWD}/HttpRequest.cpp \
    $${PWD}/HttpFileElement.cpp \
    $${PWD}/Oauth.cpp
