QT += network

HEADERS += \
# Models
    $${PWD}/APISearchView.h \
    $${PWD}/AcceptOverallocatedEnum.h \
    $${PWD}/ActionPlugin.h \
    $${PWD}/Address.h \
    $${PWD}/AddressBrief.h \
    $${PWD}/Attachment.h \
    $${PWD}/AttachmentModelTypeEnum.h \
    $${PWD}/BOMValidate.h \
    $${PWD}/Barcode.h \
    $${PWD}/BarcodeAssign.h \
    $${PWD}/BarcodePOAllocate.h \
    $${PWD}/BarcodePOReceive.h \
    $${PWD}/BarcodeSOAllocate.h \
    $${PWD}/BarcodeUnassign.h \
    $${PWD}/BlankEnum.h \
    $${PWD}/BomImportExtract.h \
    $${PWD}/BomImportSubmit.h \
    $${PWD}/BomImportUpload.h \
    $${PWD}/BomItem.h \
    $${PWD}/BomItemSubstitute.h \
    $${PWD}/BomItemValidation.h \
    $${PWD}/Build.h \
    $${PWD}/BuildAllocation.h \
    $${PWD}/BuildAllocationItem.h \
    $${PWD}/BuildAutoAllocation.h \
    $${PWD}/BuildCancel.h \
    $${PWD}/BuildComplete.h \
    $${PWD}/BuildItem.h \
    $${PWD}/BuildLine.h \
    $${PWD}/BuildOutput.h \
    $${PWD}/BuildOutputComplete.h \
    $${PWD}/BuildOutputCreate.h \
    $${PWD}/BuildOutputDelete.h \
    $${PWD}/BuildOutputQuantity.h \
    $${PWD}/BuildOutputScrap.h \
    $${PWD}/BuildStatusEnum.h \
    $${PWD}/BuildUnallocation.h \
    $${PWD}/Category.h \
    $${PWD}/CategoryParameterTemplate.h \
    $${PWD}/CategoryTree.h \
    $${PWD}/Company.h \
    $${PWD}/CompanyBrief.h \
    $${PWD}/ConfigTypeEnum.h \
    $${PWD}/Contact.h \
    $${PWD}/ContentType.h \
    $${PWD}/ConvertStockItem.h \
    $${PWD}/CurrencyExchange.h \
    $${PWD}/CustomUnit.h \
    $${PWD}/DataImportAcceptRow.h \
    $${PWD}/DataImportColumnMap.h \
    $${PWD}/DataImportRow.h \
    $${PWD}/DataImportSession.h \
    $${PWD}/DataImportSessionModelTypeEnum.h \
    $${PWD}/DataImportSessionStatusEnum.h \
    $${PWD}/EmailAddress.h \
    $${PWD}/ErrorMessage.h \
    $${PWD}/ExendedUser.h \
    $${PWD}/FailedTask.h \
    $${PWD}/GenerateBatchCode.h \
    $${PWD}/GenerateSerialNumber.h \
    $${PWD}/GetSimpleLogin.h \
    $${PWD}/GlobalSettings.h \
    $${PWD}/Group.h \
    $${PWD}/InstallStockItem.h \
    $${PWD}/LabelOutput.h \
    $${PWD}/LabelPrint.h \
    $${PWD}/LabelTemplate.h \
    $${PWD}/LicenseView.h \
    $${PWD}/Link.h \
    $${PWD}/LocatePlugin.h \
    $${PWD}/Location.h \
    $${PWD}/LocationBrief.h \
    $${PWD}/LocationTree.h \
    $${PWD}/Login.h \
    $${PWD}/MachineConfig.h \
    $${PWD}/MachineConfigCreate.h \
    $${PWD}/MachineDriver.h \
    $${PWD}/MachineRegistryError.h \
    $${PWD}/MachineRegistryStatus.h \
    $${PWD}/MachineRestart.h \
    $${PWD}/MachineSetting.h \
    $${PWD}/MachineType.h \
    $${PWD}/ManufacturerPart.h \
    $${PWD}/ManufacturerPartParameter.h \
    $${PWD}/ModelType972Enum.h \
    $${PWD}/NewsFeedEntry.h \
    $${PWD}/NotesImage.h \
    $${PWD}/NotificationMessage.h \
    $${PWD}/NotificationUserSetting.h \
    $${PWD}/NullEnum.h \
    $${PWD}/OutcomeEnum.h \
    $${PWD}/Owner.h \
    $${PWD}/PageSizeEnum.h \
    $${PWD}/PaginatedAddressList.h \
    $${PWD}/PaginatedAttachmentList.h \
    $${PWD}/PaginatedBomItemList.h \
    $${PWD}/PaginatedBomItemSubstituteList.h \
    $${PWD}/PaginatedBuildItemList.h \
    $${PWD}/PaginatedBuildLineList.h \
    $${PWD}/PaginatedBuildList.h \
    $${PWD}/PaginatedCategoryList.h \
    $${PWD}/PaginatedCategoryParameterTemplateList.h \
    $${PWD}/PaginatedCategoryTreeList.h \
    $${PWD}/PaginatedCompanyList.h \
    $${PWD}/PaginatedContactList.h \
    $${PWD}/PaginatedContentTypeList.h \
    $${PWD}/PaginatedCustomUnitList.h \
    $${PWD}/PaginatedDataImportColumnMapList.h \
    $${PWD}/PaginatedDataImportRowList.h \
    $${PWD}/PaginatedDataImportSessionList.h \
    $${PWD}/PaginatedEmailAddressList.h \
    $${PWD}/PaginatedErrorMessageList.h \
    $${PWD}/PaginatedFailedTaskList.h \
    $${PWD}/PaginatedGlobalSettingsList.h \
    $${PWD}/PaginatedGroupList.h \
    $${PWD}/PaginatedLabelOutputList.h \
    $${PWD}/PaginatedLabelTemplateList.h \
    $${PWD}/PaginatedLocationList.h \
    $${PWD}/PaginatedLocationTreeList.h \
    $${PWD}/PaginatedMachineConfigList.h \
    $${PWD}/PaginatedManufacturerPartList.h \
    $${PWD}/PaginatedManufacturerPartParameterList.h \
    $${PWD}/PaginatedNewsFeedEntryList.h \
    $${PWD}/PaginatedNotesImageList.h \
    $${PWD}/PaginatedNotificationMessageList.h \
    $${PWD}/PaginatedNotificationUserSettingList.h \
    $${PWD}/PaginatedOwnerList.h \
    $${PWD}/PaginatedPartInternalPriceList.h \
    $${PWD}/PaginatedPartList.h \
    $${PWD}/PaginatedPartParameterList.h \
    $${PWD}/PaginatedPartParameterTemplateList.h \
    $${PWD}/PaginatedPartRelationList.h \
    $${PWD}/PaginatedPartSalePriceList.h \
    $${PWD}/PaginatedPartStocktakeList.h \
    $${PWD}/PaginatedPartStocktakeReportList.h \
    $${PWD}/PaginatedPartTestTemplateList.h \
    $${PWD}/PaginatedPartThumbList.h \
    $${PWD}/PaginatedPendingTaskList.h \
    $${PWD}/PaginatedPluginConfigList.h \
    $${PWD}/PaginatedPluginSettingList.h \
    $${PWD}/PaginatedProjectCodeList.h \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.h \
    $${PWD}/PaginatedPurchaseOrderLineItemList.h \
    $${PWD}/PaginatedPurchaseOrderList.h \
    $${PWD}/PaginatedReportAssetList.h \
    $${PWD}/PaginatedReportOutputList.h \
    $${PWD}/PaginatedReportSnippetList.h \
    $${PWD}/PaginatedReportTemplateList.h \
    $${PWD}/PaginatedReturnOrderExtraLineList.h \
    $${PWD}/PaginatedReturnOrderLineItemList.h \
    $${PWD}/PaginatedReturnOrderList.h \
    $${PWD}/PaginatedSalesOrderAllocationList.h \
    $${PWD}/PaginatedSalesOrderExtraLineList.h \
    $${PWD}/PaginatedSalesOrderLineItemList.h \
    $${PWD}/PaginatedSalesOrderList.h \
    $${PWD}/PaginatedSalesOrderShipmentList.h \
    $${PWD}/PaginatedScheduledTaskList.h \
    $${PWD}/PaginatedSocialAccountList.h \
    $${PWD}/PaginatedSocialProviderListResponseList.h \
    $${PWD}/PaginatedStockItemList.h \
    $${PWD}/PaginatedStockItemTestResultList.h \
    $${PWD}/PaginatedStockLocationTypeList.h \
    $${PWD}/PaginatedStockTrackingList.h \
    $${PWD}/PaginatedSupplierPartList.h \
    $${PWD}/PaginatedSupplierPriceBreakList.h \
    $${PWD}/PaginatedUserCreateList.h \
    $${PWD}/PaginatedUserSettingsList.h \
    $${PWD}/PaginatedVersionInformationList.h \
    $${PWD}/Part.h \
    $${PWD}/PartBrief.h \
    $${PWD}/PartCopyBOM.h \
    $${PWD}/PartInternalPrice.h \
    $${PWD}/PartParameter.h \
    $${PWD}/PartParameterTemplate.h \
    $${PWD}/PartPricing.h \
    $${PWD}/PartRelation.h \
    $${PWD}/PartSalePrice.h \
    $${PWD}/PartSetCategory.h \
    $${PWD}/PartStocktake.h \
    $${PWD}/PartStocktakeReport.h \
    $${PWD}/PartStocktakeReportGenerate.h \
    $${PWD}/PartTestTemplate.h \
    $${PWD}/PartThumb.h \
    $${PWD}/PartThumbSerializerUpdate.h \
    $${PWD}/PasswordChange.h \
    $${PWD}/PasswordReset.h \
    $${PWD}/PasswordResetConfirm.h \
    $${PWD}/PatchedAddress.h \
    $${PWD}/PatchedAttachment.h \
    $${PWD}/PatchedBOMValidate.h \
    $${PWD}/PatchedBomItem.h \
    $${PWD}/PatchedBomItemSubstitute.h \
    $${PWD}/PatchedBomItemValidation.h \
    $${PWD}/PatchedBuild.h \
    $${PWD}/PatchedBuildItem.h \
    $${PWD}/PatchedBuildLine.h \
    $${PWD}/PatchedCategory.h \
    $${PWD}/PatchedCategoryParameterTemplate.h \
    $${PWD}/PatchedCompany.h \
    $${PWD}/PatchedContact.h \
    $${PWD}/PatchedCustomUnit.h \
    $${PWD}/PatchedDataImportColumnMap.h \
    $${PWD}/PatchedDataImportRow.h \
    $${PWD}/PatchedDataImportSession.h \
    $${PWD}/PatchedErrorMessage.h \
    $${PWD}/PatchedExendedUser.h \
    $${PWD}/PatchedGlobalSettings.h \
    $${PWD}/PatchedGroup.h \
    $${PWD}/PatchedLabelTemplate.h \
    $${PWD}/PatchedLocation.h \
    $${PWD}/PatchedMachineConfig.h \
    $${PWD}/PatchedMachineSetting.h \
    $${PWD}/PatchedManufacturerPart.h \
    $${PWD}/PatchedManufacturerPartParameter.h \
    $${PWD}/PatchedNewsFeedEntry.h \
    $${PWD}/PatchedNotificationMessage.h \
    $${PWD}/PatchedNotificationUserSetting.h \
    $${PWD}/PatchedPart.h \
    $${PWD}/PatchedPartInternalPrice.h \
    $${PWD}/PatchedPartParameter.h \
    $${PWD}/PatchedPartParameterTemplate.h \
    $${PWD}/PatchedPartPricing.h \
    $${PWD}/PatchedPartRelation.h \
    $${PWD}/PatchedPartSalePrice.h \
    $${PWD}/PatchedPartStocktake.h \
    $${PWD}/PatchedPartTestTemplate.h \
    $${PWD}/PatchedPartThumbSerializerUpdate.h \
    $${PWD}/PatchedPluginActivate.h \
    $${PWD}/PatchedPluginConfig.h \
    $${PWD}/PatchedPluginSetting.h \
    $${PWD}/PatchedPluginUninstall.h \
    $${PWD}/PatchedProjectCode.h \
    $${PWD}/PatchedPurchaseOrder.h \
    $${PWD}/PatchedPurchaseOrderExtraLine.h \
    $${PWD}/PatchedPurchaseOrderLineItem.h \
    $${PWD}/PatchedPurchaseOrder_order_currency.h \
    $${PWD}/PatchedReportAsset.h \
    $${PWD}/PatchedReportSnippet.h \
    $${PWD}/PatchedReportTemplate.h \
    $${PWD}/PatchedReturnOrder.h \
    $${PWD}/PatchedReturnOrderExtraLine.h \
    $${PWD}/PatchedReturnOrderLineItem.h \
    $${PWD}/PatchedSalesOrder.h \
    $${PWD}/PatchedSalesOrderAllocation.h \
    $${PWD}/PatchedSalesOrderExtraLine.h \
    $${PWD}/PatchedSalesOrderLineItem.h \
    $${PWD}/PatchedSalesOrderShipment.h \
    $${PWD}/PatchedStockItem.h \
    $${PWD}/PatchedStockItemTestResult.h \
    $${PWD}/PatchedStockLocationType.h \
    $${PWD}/PatchedSupplierPart.h \
    $${PWD}/PatchedSupplierPriceBreak.h \
    $${PWD}/PatchedUserDetails.h \
    $${PWD}/PatchedUserSettings.h \
    $${PWD}/PendingTask.h \
    $${PWD}/PluginActivate.h \
    $${PWD}/PluginConfig.h \
    $${PWD}/PluginConfigInstall.h \
    $${PWD}/PluginRegistryError.h \
    $${PWD}/PluginRegistryStatus.h \
    $${PWD}/PluginReload.h \
    $${PWD}/PluginSetting.h \
    $${PWD}/PluginUninstall.h \
    $${PWD}/Preferred.h \
    $${PWD}/PreferredMethodEnum.h \
    $${PWD}/ProjectCode.h \
    $${PWD}/PurchaseOrder.h \
    $${PWD}/PurchaseOrderComplete.h \
    $${PWD}/PurchaseOrderExtraLine.h \
    $${PWD}/PurchaseOrderLineItem.h \
    $${PWD}/PurchaseOrderLineItemReceive.h \
    $${PWD}/PurchaseOrderReceive.h \
    $${PWD}/Register.h \
    $${PWD}/ReportAsset.h \
    $${PWD}/ReportOutput.h \
    $${PWD}/ReportPrint.h \
    $${PWD}/ReportSnippet.h \
    $${PWD}/ReportTemplate.h \
    $${PWD}/ResendEmailVerification.h \
    $${PWD}/RestAuthDetail.h \
    $${PWD}/ReturnOrder.h \
    $${PWD}/ReturnOrderExtraLine.h \
    $${PWD}/ReturnOrderLineItem.h \
    $${PWD}/ReturnOrderLineItemReceive.h \
    $${PWD}/ReturnOrderReceive.h \
    $${PWD}/ReturnStockItem.h \
    $${PWD}/Role.h \
    $${PWD}/SalePriceCurrencyEnum.h \
    $${PWD}/SalesOrder.h \
    $${PWD}/SalesOrderAllocation.h \
    $${PWD}/SalesOrderComplete.h \
    $${PWD}/SalesOrderExtraLine.h \
    $${PWD}/SalesOrderLineItem.h \
    $${PWD}/SalesOrderSerialAllocation.h \
    $${PWD}/SalesOrderShipment.h \
    $${PWD}/SalesOrderShipmentAllocation.h \
    $${PWD}/SalesOrderShipmentAllocationItem.h \
    $${PWD}/SalesOrderShipmentComplete.h \
    $${PWD}/ScheduleTypeEnum.h \
    $${PWD}/ScheduledTask.h \
    $${PWD}/SerializeStockItem.h \
    $${PWD}/SocialAccount.h \
    $${PWD}/SocialConnect.h \
    $${PWD}/SocialProvider.h \
    $${PWD}/SocialProviderListResponse.h \
    $${PWD}/Status2a7Enum.h \
    $${PWD}/StockAdd.h \
    $${PWD}/StockAdjustmentItem.h \
    $${PWD}/StockAdjustmentItem_status.h \
    $${PWD}/StockAssignment.h \
    $${PWD}/StockAssignmentItem.h \
    $${PWD}/StockChangeStatus.h \
    $${PWD}/StockCount.h \
    $${PWD}/StockItem.h \
    $${PWD}/StockItemSerializerBrief.h \
    $${PWD}/StockItemTestResult.h \
    $${PWD}/StockLocationType.h \
    $${PWD}/StockMerge.h \
    $${PWD}/StockMergeItem.h \
    $${PWD}/StockRemove.h \
    $${PWD}/StockTracking.h \
    $${PWD}/StockTransfer.h \
    $${PWD}/SupplierPart.h \
    $${PWD}/SupplierPriceBreak.h \
    $${PWD}/Token.h \
    $${PWD}/UninstallStockItem.h \
    $${PWD}/User.h \
    $${PWD}/UserCreate.h \
    $${PWD}/UserDetails.h \
    $${PWD}/UserSettings.h \
    $${PWD}/VerifyEmail.h \
    $${PWD}/Version.h \
    $${PWD}/VersionInformation.h \
    $${PWD}/VersionView.h \
# APIs
    $${PWD}/ActionApi.h \
    $${PWD}/AdminApi.h \
    $${PWD}/AttachmentApi.h \
    $${PWD}/AuthApi.h \
    $${PWD}/BackgroundTaskApi.h \
    $${PWD}/BarcodeApi.h \
    $${PWD}/BomApi.h \
    $${PWD}/BuildApi.h \
    $${PWD}/CompanyApi.h \
    $${PWD}/ContenttypeApi.h \
    $${PWD}/CurrencyApi.h \
    $${PWD}/EmailApi.h \
    $${PWD}/ErrorReportApi.h \
    $${PWD}/FlagsApi.h \
    $${PWD}/GenerateApi.h \
    $${PWD}/GenericApi.h \
    $${PWD}/ImporterApi.h \
    $${PWD}/LabelApi.h \
    $${PWD}/LicenseApi.h \
    $${PWD}/LocateApi.h \
    $${PWD}/MachineApi.h \
    $${PWD}/NewsApi.h \
    $${PWD}/NotesImageUploadApi.h \
    $${PWD}/NotificationsApi.h \
    $${PWD}/OrderApi.h \
    $${PWD}/PartApi.h \
    $${PWD}/PluginsApi.h \
    $${PWD}/ProjectCodeApi.h \
    $${PWD}/ReportApi.h \
    $${PWD}/SearchApi.h \
    $${PWD}/SettingsApi.h \
    $${PWD}/StockApi.h \
    $${PWD}/UnitsApi.h \
    $${PWD}/UserApi.h \
    $${PWD}/VersionApi.h \
    $${PWD}/VersionTextApi.h \
    $${PWD}/WebApi.h \
    $${PWD}/WebhookApi.h \
# Others
    $${PWD}/Helpers.h \
    $${PWD}/HttpRequest.h \
    $${PWD}/Object.h \
    $${PWD}/Enum.h \
    $${PWD}/HttpFileElement.h \
    $${PWD}/ServerConfiguration.h \
    $${PWD}/ServerVariable.h \
    $${PWD}/Oauth.h

SOURCES += \
# Models
    $${PWD}/APISearchView.cpp \
    $${PWD}/AcceptOverallocatedEnum.cpp \
    $${PWD}/ActionPlugin.cpp \
    $${PWD}/Address.cpp \
    $${PWD}/AddressBrief.cpp \
    $${PWD}/Attachment.cpp \
    $${PWD}/AttachmentModelTypeEnum.cpp \
    $${PWD}/BOMValidate.cpp \
    $${PWD}/Barcode.cpp \
    $${PWD}/BarcodeAssign.cpp \
    $${PWD}/BarcodePOAllocate.cpp \
    $${PWD}/BarcodePOReceive.cpp \
    $${PWD}/BarcodeSOAllocate.cpp \
    $${PWD}/BarcodeUnassign.cpp \
    $${PWD}/BlankEnum.cpp \
    $${PWD}/BomImportExtract.cpp \
    $${PWD}/BomImportSubmit.cpp \
    $${PWD}/BomImportUpload.cpp \
    $${PWD}/BomItem.cpp \
    $${PWD}/BomItemSubstitute.cpp \
    $${PWD}/BomItemValidation.cpp \
    $${PWD}/Build.cpp \
    $${PWD}/BuildAllocation.cpp \
    $${PWD}/BuildAllocationItem.cpp \
    $${PWD}/BuildAutoAllocation.cpp \
    $${PWD}/BuildCancel.cpp \
    $${PWD}/BuildComplete.cpp \
    $${PWD}/BuildItem.cpp \
    $${PWD}/BuildLine.cpp \
    $${PWD}/BuildOutput.cpp \
    $${PWD}/BuildOutputComplete.cpp \
    $${PWD}/BuildOutputCreate.cpp \
    $${PWD}/BuildOutputDelete.cpp \
    $${PWD}/BuildOutputQuantity.cpp \
    $${PWD}/BuildOutputScrap.cpp \
    $${PWD}/BuildStatusEnum.cpp \
    $${PWD}/BuildUnallocation.cpp \
    $${PWD}/Category.cpp \
    $${PWD}/CategoryParameterTemplate.cpp \
    $${PWD}/CategoryTree.cpp \
    $${PWD}/Company.cpp \
    $${PWD}/CompanyBrief.cpp \
    $${PWD}/ConfigTypeEnum.cpp \
    $${PWD}/Contact.cpp \
    $${PWD}/ContentType.cpp \
    $${PWD}/ConvertStockItem.cpp \
    $${PWD}/CurrencyExchange.cpp \
    $${PWD}/CustomUnit.cpp \
    $${PWD}/DataImportAcceptRow.cpp \
    $${PWD}/DataImportColumnMap.cpp \
    $${PWD}/DataImportRow.cpp \
    $${PWD}/DataImportSession.cpp \
    $${PWD}/DataImportSessionModelTypeEnum.cpp \
    $${PWD}/DataImportSessionStatusEnum.cpp \
    $${PWD}/EmailAddress.cpp \
    $${PWD}/ErrorMessage.cpp \
    $${PWD}/ExendedUser.cpp \
    $${PWD}/FailedTask.cpp \
    $${PWD}/GenerateBatchCode.cpp \
    $${PWD}/GenerateSerialNumber.cpp \
    $${PWD}/GetSimpleLogin.cpp \
    $${PWD}/GlobalSettings.cpp \
    $${PWD}/Group.cpp \
    $${PWD}/InstallStockItem.cpp \
    $${PWD}/LabelOutput.cpp \
    $${PWD}/LabelPrint.cpp \
    $${PWD}/LabelTemplate.cpp \
    $${PWD}/LicenseView.cpp \
    $${PWD}/Link.cpp \
    $${PWD}/LocatePlugin.cpp \
    $${PWD}/Location.cpp \
    $${PWD}/LocationBrief.cpp \
    $${PWD}/LocationTree.cpp \
    $${PWD}/Login.cpp \
    $${PWD}/MachineConfig.cpp \
    $${PWD}/MachineConfigCreate.cpp \
    $${PWD}/MachineDriver.cpp \
    $${PWD}/MachineRegistryError.cpp \
    $${PWD}/MachineRegistryStatus.cpp \
    $${PWD}/MachineRestart.cpp \
    $${PWD}/MachineSetting.cpp \
    $${PWD}/MachineType.cpp \
    $${PWD}/ManufacturerPart.cpp \
    $${PWD}/ManufacturerPartParameter.cpp \
    $${PWD}/ModelType972Enum.cpp \
    $${PWD}/NewsFeedEntry.cpp \
    $${PWD}/NotesImage.cpp \
    $${PWD}/NotificationMessage.cpp \
    $${PWD}/NotificationUserSetting.cpp \
    $${PWD}/NullEnum.cpp \
    $${PWD}/OutcomeEnum.cpp \
    $${PWD}/Owner.cpp \
    $${PWD}/PageSizeEnum.cpp \
    $${PWD}/PaginatedAddressList.cpp \
    $${PWD}/PaginatedAttachmentList.cpp \
    $${PWD}/PaginatedBomItemList.cpp \
    $${PWD}/PaginatedBomItemSubstituteList.cpp \
    $${PWD}/PaginatedBuildItemList.cpp \
    $${PWD}/PaginatedBuildLineList.cpp \
    $${PWD}/PaginatedBuildList.cpp \
    $${PWD}/PaginatedCategoryList.cpp \
    $${PWD}/PaginatedCategoryParameterTemplateList.cpp \
    $${PWD}/PaginatedCategoryTreeList.cpp \
    $${PWD}/PaginatedCompanyList.cpp \
    $${PWD}/PaginatedContactList.cpp \
    $${PWD}/PaginatedContentTypeList.cpp \
    $${PWD}/PaginatedCustomUnitList.cpp \
    $${PWD}/PaginatedDataImportColumnMapList.cpp \
    $${PWD}/PaginatedDataImportRowList.cpp \
    $${PWD}/PaginatedDataImportSessionList.cpp \
    $${PWD}/PaginatedEmailAddressList.cpp \
    $${PWD}/PaginatedErrorMessageList.cpp \
    $${PWD}/PaginatedFailedTaskList.cpp \
    $${PWD}/PaginatedGlobalSettingsList.cpp \
    $${PWD}/PaginatedGroupList.cpp \
    $${PWD}/PaginatedLabelOutputList.cpp \
    $${PWD}/PaginatedLabelTemplateList.cpp \
    $${PWD}/PaginatedLocationList.cpp \
    $${PWD}/PaginatedLocationTreeList.cpp \
    $${PWD}/PaginatedMachineConfigList.cpp \
    $${PWD}/PaginatedManufacturerPartList.cpp \
    $${PWD}/PaginatedManufacturerPartParameterList.cpp \
    $${PWD}/PaginatedNewsFeedEntryList.cpp \
    $${PWD}/PaginatedNotesImageList.cpp \
    $${PWD}/PaginatedNotificationMessageList.cpp \
    $${PWD}/PaginatedNotificationUserSettingList.cpp \
    $${PWD}/PaginatedOwnerList.cpp \
    $${PWD}/PaginatedPartInternalPriceList.cpp \
    $${PWD}/PaginatedPartList.cpp \
    $${PWD}/PaginatedPartParameterList.cpp \
    $${PWD}/PaginatedPartParameterTemplateList.cpp \
    $${PWD}/PaginatedPartRelationList.cpp \
    $${PWD}/PaginatedPartSalePriceList.cpp \
    $${PWD}/PaginatedPartStocktakeList.cpp \
    $${PWD}/PaginatedPartStocktakeReportList.cpp \
    $${PWD}/PaginatedPartTestTemplateList.cpp \
    $${PWD}/PaginatedPartThumbList.cpp \
    $${PWD}/PaginatedPendingTaskList.cpp \
    $${PWD}/PaginatedPluginConfigList.cpp \
    $${PWD}/PaginatedPluginSettingList.cpp \
    $${PWD}/PaginatedProjectCodeList.cpp \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.cpp \
    $${PWD}/PaginatedPurchaseOrderLineItemList.cpp \
    $${PWD}/PaginatedPurchaseOrderList.cpp \
    $${PWD}/PaginatedReportAssetList.cpp \
    $${PWD}/PaginatedReportOutputList.cpp \
    $${PWD}/PaginatedReportSnippetList.cpp \
    $${PWD}/PaginatedReportTemplateList.cpp \
    $${PWD}/PaginatedReturnOrderExtraLineList.cpp \
    $${PWD}/PaginatedReturnOrderLineItemList.cpp \
    $${PWD}/PaginatedReturnOrderList.cpp \
    $${PWD}/PaginatedSalesOrderAllocationList.cpp \
    $${PWD}/PaginatedSalesOrderExtraLineList.cpp \
    $${PWD}/PaginatedSalesOrderLineItemList.cpp \
    $${PWD}/PaginatedSalesOrderList.cpp \
    $${PWD}/PaginatedSalesOrderShipmentList.cpp \
    $${PWD}/PaginatedScheduledTaskList.cpp \
    $${PWD}/PaginatedSocialAccountList.cpp \
    $${PWD}/PaginatedSocialProviderListResponseList.cpp \
    $${PWD}/PaginatedStockItemList.cpp \
    $${PWD}/PaginatedStockItemTestResultList.cpp \
    $${PWD}/PaginatedStockLocationTypeList.cpp \
    $${PWD}/PaginatedStockTrackingList.cpp \
    $${PWD}/PaginatedSupplierPartList.cpp \
    $${PWD}/PaginatedSupplierPriceBreakList.cpp \
    $${PWD}/PaginatedUserCreateList.cpp \
    $${PWD}/PaginatedUserSettingsList.cpp \
    $${PWD}/PaginatedVersionInformationList.cpp \
    $${PWD}/Part.cpp \
    $${PWD}/PartBrief.cpp \
    $${PWD}/PartCopyBOM.cpp \
    $${PWD}/PartInternalPrice.cpp \
    $${PWD}/PartParameter.cpp \
    $${PWD}/PartParameterTemplate.cpp \
    $${PWD}/PartPricing.cpp \
    $${PWD}/PartRelation.cpp \
    $${PWD}/PartSalePrice.cpp \
    $${PWD}/PartSetCategory.cpp \
    $${PWD}/PartStocktake.cpp \
    $${PWD}/PartStocktakeReport.cpp \
    $${PWD}/PartStocktakeReportGenerate.cpp \
    $${PWD}/PartTestTemplate.cpp \
    $${PWD}/PartThumb.cpp \
    $${PWD}/PartThumbSerializerUpdate.cpp \
    $${PWD}/PasswordChange.cpp \
    $${PWD}/PasswordReset.cpp \
    $${PWD}/PasswordResetConfirm.cpp \
    $${PWD}/PatchedAddress.cpp \
    $${PWD}/PatchedAttachment.cpp \
    $${PWD}/PatchedBOMValidate.cpp \
    $${PWD}/PatchedBomItem.cpp \
    $${PWD}/PatchedBomItemSubstitute.cpp \
    $${PWD}/PatchedBomItemValidation.cpp \
    $${PWD}/PatchedBuild.cpp \
    $${PWD}/PatchedBuildItem.cpp \
    $${PWD}/PatchedBuildLine.cpp \
    $${PWD}/PatchedCategory.cpp \
    $${PWD}/PatchedCategoryParameterTemplate.cpp \
    $${PWD}/PatchedCompany.cpp \
    $${PWD}/PatchedContact.cpp \
    $${PWD}/PatchedCustomUnit.cpp \
    $${PWD}/PatchedDataImportColumnMap.cpp \
    $${PWD}/PatchedDataImportRow.cpp \
    $${PWD}/PatchedDataImportSession.cpp \
    $${PWD}/PatchedErrorMessage.cpp \
    $${PWD}/PatchedExendedUser.cpp \
    $${PWD}/PatchedGlobalSettings.cpp \
    $${PWD}/PatchedGroup.cpp \
    $${PWD}/PatchedLabelTemplate.cpp \
    $${PWD}/PatchedLocation.cpp \
    $${PWD}/PatchedMachineConfig.cpp \
    $${PWD}/PatchedMachineSetting.cpp \
    $${PWD}/PatchedManufacturerPart.cpp \
    $${PWD}/PatchedManufacturerPartParameter.cpp \
    $${PWD}/PatchedNewsFeedEntry.cpp \
    $${PWD}/PatchedNotificationMessage.cpp \
    $${PWD}/PatchedNotificationUserSetting.cpp \
    $${PWD}/PatchedPart.cpp \
    $${PWD}/PatchedPartInternalPrice.cpp \
    $${PWD}/PatchedPartParameter.cpp \
    $${PWD}/PatchedPartParameterTemplate.cpp \
    $${PWD}/PatchedPartPricing.cpp \
    $${PWD}/PatchedPartRelation.cpp \
    $${PWD}/PatchedPartSalePrice.cpp \
    $${PWD}/PatchedPartStocktake.cpp \
    $${PWD}/PatchedPartTestTemplate.cpp \
    $${PWD}/PatchedPartThumbSerializerUpdate.cpp \
    $${PWD}/PatchedPluginActivate.cpp \
    $${PWD}/PatchedPluginConfig.cpp \
    $${PWD}/PatchedPluginSetting.cpp \
    $${PWD}/PatchedPluginUninstall.cpp \
    $${PWD}/PatchedProjectCode.cpp \
    $${PWD}/PatchedPurchaseOrder.cpp \
    $${PWD}/PatchedPurchaseOrderExtraLine.cpp \
    $${PWD}/PatchedPurchaseOrderLineItem.cpp \
    $${PWD}/PatchedPurchaseOrder_order_currency.cpp \
    $${PWD}/PatchedReportAsset.cpp \
    $${PWD}/PatchedReportSnippet.cpp \
    $${PWD}/PatchedReportTemplate.cpp \
    $${PWD}/PatchedReturnOrder.cpp \
    $${PWD}/PatchedReturnOrderExtraLine.cpp \
    $${PWD}/PatchedReturnOrderLineItem.cpp \
    $${PWD}/PatchedSalesOrder.cpp \
    $${PWD}/PatchedSalesOrderAllocation.cpp \
    $${PWD}/PatchedSalesOrderExtraLine.cpp \
    $${PWD}/PatchedSalesOrderLineItem.cpp \
    $${PWD}/PatchedSalesOrderShipment.cpp \
    $${PWD}/PatchedStockItem.cpp \
    $${PWD}/PatchedStockItemTestResult.cpp \
    $${PWD}/PatchedStockLocationType.cpp \
    $${PWD}/PatchedSupplierPart.cpp \
    $${PWD}/PatchedSupplierPriceBreak.cpp \
    $${PWD}/PatchedUserDetails.cpp \
    $${PWD}/PatchedUserSettings.cpp \
    $${PWD}/PendingTask.cpp \
    $${PWD}/PluginActivate.cpp \
    $${PWD}/PluginConfig.cpp \
    $${PWD}/PluginConfigInstall.cpp \
    $${PWD}/PluginRegistryError.cpp \
    $${PWD}/PluginRegistryStatus.cpp \
    $${PWD}/PluginReload.cpp \
    $${PWD}/PluginSetting.cpp \
    $${PWD}/PluginUninstall.cpp \
    $${PWD}/Preferred.cpp \
    $${PWD}/PreferredMethodEnum.cpp \
    $${PWD}/ProjectCode.cpp \
    $${PWD}/PurchaseOrder.cpp \
    $${PWD}/PurchaseOrderComplete.cpp \
    $${PWD}/PurchaseOrderExtraLine.cpp \
    $${PWD}/PurchaseOrderLineItem.cpp \
    $${PWD}/PurchaseOrderLineItemReceive.cpp \
    $${PWD}/PurchaseOrderReceive.cpp \
    $${PWD}/Register.cpp \
    $${PWD}/ReportAsset.cpp \
    $${PWD}/ReportOutput.cpp \
    $${PWD}/ReportPrint.cpp \
    $${PWD}/ReportSnippet.cpp \
    $${PWD}/ReportTemplate.cpp \
    $${PWD}/ResendEmailVerification.cpp \
    $${PWD}/RestAuthDetail.cpp \
    $${PWD}/ReturnOrder.cpp \
    $${PWD}/ReturnOrderExtraLine.cpp \
    $${PWD}/ReturnOrderLineItem.cpp \
    $${PWD}/ReturnOrderLineItemReceive.cpp \
    $${PWD}/ReturnOrderReceive.cpp \
    $${PWD}/ReturnStockItem.cpp \
    $${PWD}/Role.cpp \
    $${PWD}/SalePriceCurrencyEnum.cpp \
    $${PWD}/SalesOrder.cpp \
    $${PWD}/SalesOrderAllocation.cpp \
    $${PWD}/SalesOrderComplete.cpp \
    $${PWD}/SalesOrderExtraLine.cpp \
    $${PWD}/SalesOrderLineItem.cpp \
    $${PWD}/SalesOrderSerialAllocation.cpp \
    $${PWD}/SalesOrderShipment.cpp \
    $${PWD}/SalesOrderShipmentAllocation.cpp \
    $${PWD}/SalesOrderShipmentAllocationItem.cpp \
    $${PWD}/SalesOrderShipmentComplete.cpp \
    $${PWD}/ScheduleTypeEnum.cpp \
    $${PWD}/ScheduledTask.cpp \
    $${PWD}/SerializeStockItem.cpp \
    $${PWD}/SocialAccount.cpp \
    $${PWD}/SocialConnect.cpp \
    $${PWD}/SocialProvider.cpp \
    $${PWD}/SocialProviderListResponse.cpp \
    $${PWD}/Status2a7Enum.cpp \
    $${PWD}/StockAdd.cpp \
    $${PWD}/StockAdjustmentItem.cpp \
    $${PWD}/StockAdjustmentItem_status.cpp \
    $${PWD}/StockAssignment.cpp \
    $${PWD}/StockAssignmentItem.cpp \
    $${PWD}/StockChangeStatus.cpp \
    $${PWD}/StockCount.cpp \
    $${PWD}/StockItem.cpp \
    $${PWD}/StockItemSerializerBrief.cpp \
    $${PWD}/StockItemTestResult.cpp \
    $${PWD}/StockLocationType.cpp \
    $${PWD}/StockMerge.cpp \
    $${PWD}/StockMergeItem.cpp \
    $${PWD}/StockRemove.cpp \
    $${PWD}/StockTracking.cpp \
    $${PWD}/StockTransfer.cpp \
    $${PWD}/SupplierPart.cpp \
    $${PWD}/SupplierPriceBreak.cpp \
    $${PWD}/Token.cpp \
    $${PWD}/UninstallStockItem.cpp \
    $${PWD}/User.cpp \
    $${PWD}/UserCreate.cpp \
    $${PWD}/UserDetails.cpp \
    $${PWD}/UserSettings.cpp \
    $${PWD}/VerifyEmail.cpp \
    $${PWD}/Version.cpp \
    $${PWD}/VersionInformation.cpp \
    $${PWD}/VersionView.cpp \
# APIs
    $${PWD}/ActionApi.cpp \
    $${PWD}/AdminApi.cpp \
    $${PWD}/AttachmentApi.cpp \
    $${PWD}/AuthApi.cpp \
    $${PWD}/BackgroundTaskApi.cpp \
    $${PWD}/BarcodeApi.cpp \
    $${PWD}/BomApi.cpp \
    $${PWD}/BuildApi.cpp \
    $${PWD}/CompanyApi.cpp \
    $${PWD}/ContenttypeApi.cpp \
    $${PWD}/CurrencyApi.cpp \
    $${PWD}/EmailApi.cpp \
    $${PWD}/ErrorReportApi.cpp \
    $${PWD}/FlagsApi.cpp \
    $${PWD}/GenerateApi.cpp \
    $${PWD}/GenericApi.cpp \
    $${PWD}/ImporterApi.cpp \
    $${PWD}/LabelApi.cpp \
    $${PWD}/LicenseApi.cpp \
    $${PWD}/LocateApi.cpp \
    $${PWD}/MachineApi.cpp \
    $${PWD}/NewsApi.cpp \
    $${PWD}/NotesImageUploadApi.cpp \
    $${PWD}/NotificationsApi.cpp \
    $${PWD}/OrderApi.cpp \
    $${PWD}/PartApi.cpp \
    $${PWD}/PluginsApi.cpp \
    $${PWD}/ProjectCodeApi.cpp \
    $${PWD}/ReportApi.cpp \
    $${PWD}/SearchApi.cpp \
    $${PWD}/SettingsApi.cpp \
    $${PWD}/StockApi.cpp \
    $${PWD}/UnitsApi.cpp \
    $${PWD}/UserApi.cpp \
    $${PWD}/VersionApi.cpp \
    $${PWD}/VersionTextApi.cpp \
    $${PWD}/WebApi.cpp \
    $${PWD}/WebhookApi.cpp \
# Others
    $${PWD}/Helpers.cpp \
    $${PWD}/HttpRequest.cpp \
    $${PWD}/HttpFileElement.cpp \
    $${PWD}/Oauth.cpp
