QT += network

HEADERS += \
# Models
    $${PWD}/AcceptOverallocatedEnum.h \
    $${PWD}/Address.h \
    $${PWD}/AddressBrief.h \
    $${PWD}/BOMReport.h \
    $${PWD}/BOMValidate.h \
    $${PWD}/Barcode.h \
    $${PWD}/BarcodeAssign.h \
    $${PWD}/BarcodePOAllocate.h \
    $${PWD}/BarcodePOReceive.h \
    $${PWD}/BarcodeUnassign.h \
    $${PWD}/BlankEnum.h \
    $${PWD}/BomImportExtract.h \
    $${PWD}/BomImportSubmit.h \
    $${PWD}/BomImportUpload.h \
    $${PWD}/BomItem.h \
    $${PWD}/BomItemSubstitute.h \
    $${PWD}/BomItemValidation.h \
    $${PWD}/Build.h \
    $${PWD}/BuildAllocation.h \
    $${PWD}/BuildAllocationItem.h \
    $${PWD}/BuildAttachment.h \
    $${PWD}/BuildAutoAllocation.h \
    $${PWD}/BuildCancel.h \
    $${PWD}/BuildComplete.h \
    $${PWD}/BuildItem.h \
    $${PWD}/BuildLine.h \
    $${PWD}/BuildLineLabel.h \
    $${PWD}/BuildOutput.h \
    $${PWD}/BuildOutputComplete.h \
    $${PWD}/BuildOutputCreate.h \
    $${PWD}/BuildOutputDelete.h \
    $${PWD}/BuildOutputQuantity.h \
    $${PWD}/BuildOutputScrap.h \
    $${PWD}/BuildReport.h \
    $${PWD}/BuildStatusEnum.h \
    $${PWD}/BuildUnallocation.h \
    $${PWD}/Category.h \
    $${PWD}/CategoryParameterTemplate.h \
    $${PWD}/CategoryTree.h \
    $${PWD}/Company.h \
    $${PWD}/CompanyAttachment.h \
    $${PWD}/CompanyBrief.h \
    $${PWD}/Contact.h \
    $${PWD}/ConvertStockItem.h \
    $${PWD}/CustomUnit.h \
    $${PWD}/EmailAddress.h \
    $${PWD}/ExendedUser.h \
    $${PWD}/GetSimpleLogin.h \
    $${PWD}/GlobalSettings.h \
    $${PWD}/Group.h \
    $${PWD}/InstallStockItem.h \
    $${PWD}/Location.h \
    $${PWD}/LocationBrief.h \
    $${PWD}/LocationTree.h \
    $${PWD}/Login.h \
    $${PWD}/ManufacturerPart.h \
    $${PWD}/ManufacturerPartAttachment.h \
    $${PWD}/ManufacturerPartParameter.h \
    $${PWD}/NewsFeedEntry.h \
    $${PWD}/NotesImage.h \
    $${PWD}/NotificationMessage.h \
    $${PWD}/NotificationUserSetting.h \
    $${PWD}/NullEnum.h \
    $${PWD}/OutcomeEnum.h \
    $${PWD}/Owner.h \
    $${PWD}/PaginatedAddressList.h \
    $${PWD}/PaginatedBOMReportList.h \
    $${PWD}/PaginatedBomItemList.h \
    $${PWD}/PaginatedBomItemSubstituteList.h \
    $${PWD}/PaginatedBuildAttachmentList.h \
    $${PWD}/PaginatedBuildItemList.h \
    $${PWD}/PaginatedBuildLineLabelList.h \
    $${PWD}/PaginatedBuildLineList.h \
    $${PWD}/PaginatedBuildList.h \
    $${PWD}/PaginatedBuildReportList.h \
    $${PWD}/PaginatedCategoryList.h \
    $${PWD}/PaginatedCategoryParameterTemplateList.h \
    $${PWD}/PaginatedCategoryTreeList.h \
    $${PWD}/PaginatedCompanyAttachmentList.h \
    $${PWD}/PaginatedCompanyList.h \
    $${PWD}/PaginatedContactList.h \
    $${PWD}/PaginatedCustomUnitList.h \
    $${PWD}/PaginatedEmailAddressList.h \
    $${PWD}/PaginatedGlobalSettingsList.h \
    $${PWD}/PaginatedGroupList.h \
    $${PWD}/PaginatedLocationList.h \
    $${PWD}/PaginatedLocationTreeList.h \
    $${PWD}/PaginatedManufacturerPartAttachmentList.h \
    $${PWD}/PaginatedManufacturerPartList.h \
    $${PWD}/PaginatedManufacturerPartParameterList.h \
    $${PWD}/PaginatedNewsFeedEntryList.h \
    $${PWD}/PaginatedNotesImageList.h \
    $${PWD}/PaginatedNotificationMessageList.h \
    $${PWD}/PaginatedNotificationUserSettingList.h \
    $${PWD}/PaginatedOwnerList.h \
    $${PWD}/PaginatedPartAttachmentList.h \
    $${PWD}/PaginatedPartInternalPriceList.h \
    $${PWD}/PaginatedPartLabelList.h \
    $${PWD}/PaginatedPartList.h \
    $${PWD}/PaginatedPartParameterList.h \
    $${PWD}/PaginatedPartParameterTemplateList.h \
    $${PWD}/PaginatedPartRelationList.h \
    $${PWD}/PaginatedPartSalePriceList.h \
    $${PWD}/PaginatedPartStocktakeList.h \
    $${PWD}/PaginatedPartStocktakeReportList.h \
    $${PWD}/PaginatedPartTestTemplateList.h \
    $${PWD}/PaginatedPartThumbList.h \
    $${PWD}/PaginatedPluginConfigList.h \
    $${PWD}/PaginatedPluginSettingList.h \
    $${PWD}/PaginatedProjectCodeList.h \
    $${PWD}/PaginatedPurchaseOrderAttachmentList.h \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.h \
    $${PWD}/PaginatedPurchaseOrderLineItemList.h \
    $${PWD}/PaginatedPurchaseOrderList.h \
    $${PWD}/PaginatedPurchaseOrderReportList.h \
    $${PWD}/PaginatedReturnOrderAttachmentList.h \
    $${PWD}/PaginatedReturnOrderExtraLineList.h \
    $${PWD}/PaginatedReturnOrderLineItemList.h \
    $${PWD}/PaginatedReturnOrderList.h \
    $${PWD}/PaginatedReturnOrderReportList.h \
    $${PWD}/PaginatedSalesOrderAllocationList.h \
    $${PWD}/PaginatedSalesOrderAttachmentList.h \
    $${PWD}/PaginatedSalesOrderExtraLineList.h \
    $${PWD}/PaginatedSalesOrderLineItemList.h \
    $${PWD}/PaginatedSalesOrderList.h \
    $${PWD}/PaginatedSalesOrderReportList.h \
    $${PWD}/PaginatedSalesOrderShipmentList.h \
    $${PWD}/PaginatedSocialAccountList.h \
    $${PWD}/PaginatedStockItemAttachmentList.h \
    $${PWD}/PaginatedStockItemLabelList.h \
    $${PWD}/PaginatedStockItemList.h \
    $${PWD}/PaginatedStockItemTestResultList.h \
    $${PWD}/PaginatedStockLocationLabelList.h \
    $${PWD}/PaginatedStockLocationReportList.h \
    $${PWD}/PaginatedStockLocationTypeList.h \
    $${PWD}/PaginatedStockTrackingList.h \
    $${PWD}/PaginatedSupplierPartList.h \
    $${PWD}/PaginatedSupplierPriceBreakList.h \
    $${PWD}/PaginatedTestReportList.h \
    $${PWD}/PaginatedUserCreateList.h \
    $${PWD}/PaginatedUserSettingsList.h \
    $${PWD}/Part.h \
    $${PWD}/PartAttachment.h \
    $${PWD}/PartBrief.h \
    $${PWD}/PartCopyBOM.h \
    $${PWD}/PartInternalPrice.h \
    $${PWD}/PartLabel.h \
    $${PWD}/PartParameter.h \
    $${PWD}/PartParameterTemplate.h \
    $${PWD}/PartPricing.h \
    $${PWD}/PartRelation.h \
    $${PWD}/PartSalePrice.h \
    $${PWD}/PartSetCategory.h \
    $${PWD}/PartStocktake.h \
    $${PWD}/PartStocktakeReport.h \
    $${PWD}/PartStocktakeReportGenerate.h \
    $${PWD}/PartTestTemplate.h \
    $${PWD}/PartThumb.h \
    $${PWD}/PartThumbSerializerUpdate.h \
    $${PWD}/PasswordChange.h \
    $${PWD}/PasswordReset.h \
    $${PWD}/PasswordResetConfirm.h \
    $${PWD}/PatchedAddress.h \
    $${PWD}/PatchedBOMReport.h \
    $${PWD}/PatchedBOMValidate.h \
    $${PWD}/PatchedBomItem.h \
    $${PWD}/PatchedBomItemSubstitute.h \
    $${PWD}/PatchedBomItemValidation.h \
    $${PWD}/PatchedBuild.h \
    $${PWD}/PatchedBuildAttachment.h \
    $${PWD}/PatchedBuildItem.h \
    $${PWD}/PatchedBuildLine.h \
    $${PWD}/PatchedBuildLineLabel.h \
    $${PWD}/PatchedBuildReport.h \
    $${PWD}/PatchedCategory.h \
    $${PWD}/PatchedCategoryParameterTemplate.h \
    $${PWD}/PatchedCompany.h \
    $${PWD}/PatchedCompanyAttachment.h \
    $${PWD}/PatchedContact.h \
    $${PWD}/PatchedCustomUnit.h \
    $${PWD}/PatchedExendedUser.h \
    $${PWD}/PatchedGlobalSettings.h \
    $${PWD}/PatchedGroup.h \
    $${PWD}/PatchedLocation.h \
    $${PWD}/PatchedManufacturerPart.h \
    $${PWD}/PatchedManufacturerPartAttachment.h \
    $${PWD}/PatchedManufacturerPartParameter.h \
    $${PWD}/PatchedNewsFeedEntry.h \
    $${PWD}/PatchedNotificationMessage.h \
    $${PWD}/PatchedNotificationUserSetting.h \
    $${PWD}/PatchedPart.h \
    $${PWD}/PatchedPartAttachment.h \
    $${PWD}/PatchedPartInternalPrice.h \
    $${PWD}/PatchedPartLabel.h \
    $${PWD}/PatchedPartParameter.h \
    $${PWD}/PatchedPartParameterTemplate.h \
    $${PWD}/PatchedPartPricing.h \
    $${PWD}/PatchedPartRelation.h \
    $${PWD}/PatchedPartSalePrice.h \
    $${PWD}/PatchedPartStocktake.h \
    $${PWD}/PatchedPartTestTemplate.h \
    $${PWD}/PatchedPartThumbSerializerUpdate.h \
    $${PWD}/PatchedPluginActivate.h \
    $${PWD}/PatchedPluginConfig.h \
    $${PWD}/PatchedPluginSetting.h \
    $${PWD}/PatchedProjectCode.h \
    $${PWD}/PatchedPurchaseOrder.h \
    $${PWD}/PatchedPurchaseOrderAttachment.h \
    $${PWD}/PatchedPurchaseOrderExtraLine.h \
    $${PWD}/PatchedPurchaseOrderLineItem.h \
    $${PWD}/PatchedPurchaseOrderReport.h \
    $${PWD}/PatchedReturnOrder.h \
    $${PWD}/PatchedReturnOrderAttachment.h \
    $${PWD}/PatchedReturnOrderExtraLine.h \
    $${PWD}/PatchedReturnOrderLineItem.h \
    $${PWD}/PatchedReturnOrderReport.h \
    $${PWD}/PatchedSalesOrder.h \
    $${PWD}/PatchedSalesOrderAllocation.h \
    $${PWD}/PatchedSalesOrderAttachment.h \
    $${PWD}/PatchedSalesOrderExtraLine.h \
    $${PWD}/PatchedSalesOrderLineItem.h \
    $${PWD}/PatchedSalesOrderReport.h \
    $${PWD}/PatchedSalesOrderShipment.h \
    $${PWD}/PatchedStockItem.h \
    $${PWD}/PatchedStockItemAttachment.h \
    $${PWD}/PatchedStockItemLabel.h \
    $${PWD}/PatchedStockItemTestResult.h \
    $${PWD}/PatchedStockLocationLabel.h \
    $${PWD}/PatchedStockLocationReport.h \
    $${PWD}/PatchedStockLocationType.h \
    $${PWD}/PatchedSupplierPart.h \
    $${PWD}/PatchedSupplierPriceBreak.h \
    $${PWD}/PatchedTestReport.h \
    $${PWD}/PatchedUserDetails.h \
    $${PWD}/PatchedUserSettings.h \
    $${PWD}/PluginActivate.h \
    $${PWD}/PluginConfig.h \
    $${PWD}/PluginConfigInstall.h \
    $${PWD}/PluginRegistryError.h \
    $${PWD}/PluginRegistryStatus.h \
    $${PWD}/PluginSetting.h \
    $${PWD}/ProjectCode.h \
    $${PWD}/PurchaseOrder.h \
    $${PWD}/PurchaseOrderAttachment.h \
    $${PWD}/PurchaseOrderComplete.h \
    $${PWD}/PurchaseOrderExtraLine.h \
    $${PWD}/PurchaseOrderLineItem.h \
    $${PWD}/PurchaseOrderLineItemReceive.h \
    $${PWD}/PurchaseOrderReceive.h \
    $${PWD}/PurchaseOrderReport.h \
    $${PWD}/Register.h \
    $${PWD}/Rendel_s_p_nzneme.h \
    $${PWD}/ResendEmailVerification.h \
    $${PWD}/RestAuthDetail.h \
    $${PWD}/ReturnOrder.h \
    $${PWD}/ReturnOrderAttachment.h \
    $${PWD}/ReturnOrderExtraLine.h \
    $${PWD}/ReturnOrderLineItem.h \
    $${PWD}/ReturnOrderLineItemReceive.h \
    $${PWD}/ReturnOrderReceive.h \
    $${PWD}/ReturnOrderReport.h \
    $${PWD}/ReturnStockItem.h \
    $${PWD}/SalePriceCurrencyEnum.h \
    $${PWD}/SalesOrder.h \
    $${PWD}/SalesOrderAllocation.h \
    $${PWD}/SalesOrderAttachment.h \
    $${PWD}/SalesOrderComplete.h \
    $${PWD}/SalesOrderExtraLine.h \
    $${PWD}/SalesOrderLineItem.h \
    $${PWD}/SalesOrderReport.h \
    $${PWD}/SalesOrderSerialAllocation.h \
    $${PWD}/SalesOrderShipment.h \
    $${PWD}/SalesOrderShipmentAllocation.h \
    $${PWD}/SalesOrderShipmentAllocationItem.h \
    $${PWD}/SalesOrderShipmentComplete.h \
    $${PWD}/SerializeStockItem.h \
    $${PWD}/SocialAccount.h \
    $${PWD}/SocialConnect.h \
    $${PWD}/Status46bEnum.h \
    $${PWD}/StockAdd.h \
    $${PWD}/StockAdjustmentItem.h \
    $${PWD}/StockAssignment.h \
    $${PWD}/StockAssignmentItem.h \
    $${PWD}/StockChangeStatus.h \
    $${PWD}/StockCount.h \
    $${PWD}/StockItem.h \
    $${PWD}/StockItemAttachment.h \
    $${PWD}/StockItemLabel.h \
    $${PWD}/StockItemTestResult.h \
    $${PWD}/StockLocationLabel.h \
    $${PWD}/StockLocationReport.h \
    $${PWD}/StockLocationType.h \
    $${PWD}/StockMerge.h \
    $${PWD}/StockMergeItem.h \
    $${PWD}/StockRemove.h \
    $${PWD}/StockTracking.h \
    $${PWD}/StockTransfer.h \
    $${PWD}/SupplierPart.h \
    $${PWD}/SupplierPriceBreak.h \
    $${PWD}/TestReport.h \
    $${PWD}/Token.h \
    $${PWD}/UninstallStockItem.h \
    $${PWD}/User.h \
    $${PWD}/UserCreate.h \
    $${PWD}/UserDetails.h \
    $${PWD}/UserSettings.h \
    $${PWD}/VerifyEmail.h \
    $${PWD}/_llapot.h \
# APIs
    $${PWD}/ActionApi.h \
    $${PWD}/AdminApi.h \
    $${PWD}/AuthApi.h \
    $${PWD}/BarcodeApi.h \
    $${PWD}/BomApi.h \
    $${PWD}/BuildApi.h \
    $${PWD}/CompanyApi.h \
    $${PWD}/CurrencyApi.h \
    $${PWD}/EmailApi.h \
    $${PWD}/FlagsApi.h \
    $${PWD}/GenericApi.h \
    $${PWD}/LabelApi.h \
    $${PWD}/LocateApi.h \
    $${PWD}/NewsApi.h \
    $${PWD}/NotesImageUploadApi.h \
    $${PWD}/NotificationsApi.h \
    $${PWD}/OrderApi.h \
    $${PWD}/PartApi.h \
    $${PWD}/PluginsApi.h \
    $${PWD}/ProjectCodeApi.h \
    $${PWD}/ReportApi.h \
    $${PWD}/SearchApi.h \
    $${PWD}/SettingsApi.h \
    $${PWD}/StockApi.h \
    $${PWD}/UnitsApi.h \
    $${PWD}/UserApi.h \
    $${PWD}/VersionApi.h \
    $${PWD}/VersionTextApi.h \
    $${PWD}/WebhookApi.h \
# Others
    $${PWD}/Helpers.h \
    $${PWD}/HttpRequest.h \
    $${PWD}/Object.h \
    $${PWD}/Enum.h \
    $${PWD}/HttpFileElement.h \
    $${PWD}/ServerConfiguration.h \
    $${PWD}/ServerVariable.h \
    $${PWD}/Oauth.h

SOURCES += \
# Models
    $${PWD}/AcceptOverallocatedEnum.cpp \
    $${PWD}/Address.cpp \
    $${PWD}/AddressBrief.cpp \
    $${PWD}/BOMReport.cpp \
    $${PWD}/BOMValidate.cpp \
    $${PWD}/Barcode.cpp \
    $${PWD}/BarcodeAssign.cpp \
    $${PWD}/BarcodePOAllocate.cpp \
    $${PWD}/BarcodePOReceive.cpp \
    $${PWD}/BarcodeUnassign.cpp \
    $${PWD}/BlankEnum.cpp \
    $${PWD}/BomImportExtract.cpp \
    $${PWD}/BomImportSubmit.cpp \
    $${PWD}/BomImportUpload.cpp \
    $${PWD}/BomItem.cpp \
    $${PWD}/BomItemSubstitute.cpp \
    $${PWD}/BomItemValidation.cpp \
    $${PWD}/Build.cpp \
    $${PWD}/BuildAllocation.cpp \
    $${PWD}/BuildAllocationItem.cpp \
    $${PWD}/BuildAttachment.cpp \
    $${PWD}/BuildAutoAllocation.cpp \
    $${PWD}/BuildCancel.cpp \
    $${PWD}/BuildComplete.cpp \
    $${PWD}/BuildItem.cpp \
    $${PWD}/BuildLine.cpp \
    $${PWD}/BuildLineLabel.cpp \
    $${PWD}/BuildOutput.cpp \
    $${PWD}/BuildOutputComplete.cpp \
    $${PWD}/BuildOutputCreate.cpp \
    $${PWD}/BuildOutputDelete.cpp \
    $${PWD}/BuildOutputQuantity.cpp \
    $${PWD}/BuildOutputScrap.cpp \
    $${PWD}/BuildReport.cpp \
    $${PWD}/BuildStatusEnum.cpp \
    $${PWD}/BuildUnallocation.cpp \
    $${PWD}/Category.cpp \
    $${PWD}/CategoryParameterTemplate.cpp \
    $${PWD}/CategoryTree.cpp \
    $${PWD}/Company.cpp \
    $${PWD}/CompanyAttachment.cpp \
    $${PWD}/CompanyBrief.cpp \
    $${PWD}/Contact.cpp \
    $${PWD}/ConvertStockItem.cpp \
    $${PWD}/CustomUnit.cpp \
    $${PWD}/EmailAddress.cpp \
    $${PWD}/ExendedUser.cpp \
    $${PWD}/GetSimpleLogin.cpp \
    $${PWD}/GlobalSettings.cpp \
    $${PWD}/Group.cpp \
    $${PWD}/InstallStockItem.cpp \
    $${PWD}/Location.cpp \
    $${PWD}/LocationBrief.cpp \
    $${PWD}/LocationTree.cpp \
    $${PWD}/Login.cpp \
    $${PWD}/ManufacturerPart.cpp \
    $${PWD}/ManufacturerPartAttachment.cpp \
    $${PWD}/ManufacturerPartParameter.cpp \
    $${PWD}/NewsFeedEntry.cpp \
    $${PWD}/NotesImage.cpp \
    $${PWD}/NotificationMessage.cpp \
    $${PWD}/NotificationUserSetting.cpp \
    $${PWD}/NullEnum.cpp \
    $${PWD}/OutcomeEnum.cpp \
    $${PWD}/Owner.cpp \
    $${PWD}/PaginatedAddressList.cpp \
    $${PWD}/PaginatedBOMReportList.cpp \
    $${PWD}/PaginatedBomItemList.cpp \
    $${PWD}/PaginatedBomItemSubstituteList.cpp \
    $${PWD}/PaginatedBuildAttachmentList.cpp \
    $${PWD}/PaginatedBuildItemList.cpp \
    $${PWD}/PaginatedBuildLineLabelList.cpp \
    $${PWD}/PaginatedBuildLineList.cpp \
    $${PWD}/PaginatedBuildList.cpp \
    $${PWD}/PaginatedBuildReportList.cpp \
    $${PWD}/PaginatedCategoryList.cpp \
    $${PWD}/PaginatedCategoryParameterTemplateList.cpp \
    $${PWD}/PaginatedCategoryTreeList.cpp \
    $${PWD}/PaginatedCompanyAttachmentList.cpp \
    $${PWD}/PaginatedCompanyList.cpp \
    $${PWD}/PaginatedContactList.cpp \
    $${PWD}/PaginatedCustomUnitList.cpp \
    $${PWD}/PaginatedEmailAddressList.cpp \
    $${PWD}/PaginatedGlobalSettingsList.cpp \
    $${PWD}/PaginatedGroupList.cpp \
    $${PWD}/PaginatedLocationList.cpp \
    $${PWD}/PaginatedLocationTreeList.cpp \
    $${PWD}/PaginatedManufacturerPartAttachmentList.cpp \
    $${PWD}/PaginatedManufacturerPartList.cpp \
    $${PWD}/PaginatedManufacturerPartParameterList.cpp \
    $${PWD}/PaginatedNewsFeedEntryList.cpp \
    $${PWD}/PaginatedNotesImageList.cpp \
    $${PWD}/PaginatedNotificationMessageList.cpp \
    $${PWD}/PaginatedNotificationUserSettingList.cpp \
    $${PWD}/PaginatedOwnerList.cpp \
    $${PWD}/PaginatedPartAttachmentList.cpp \
    $${PWD}/PaginatedPartInternalPriceList.cpp \
    $${PWD}/PaginatedPartLabelList.cpp \
    $${PWD}/PaginatedPartList.cpp \
    $${PWD}/PaginatedPartParameterList.cpp \
    $${PWD}/PaginatedPartParameterTemplateList.cpp \
    $${PWD}/PaginatedPartRelationList.cpp \
    $${PWD}/PaginatedPartSalePriceList.cpp \
    $${PWD}/PaginatedPartStocktakeList.cpp \
    $${PWD}/PaginatedPartStocktakeReportList.cpp \
    $${PWD}/PaginatedPartTestTemplateList.cpp \
    $${PWD}/PaginatedPartThumbList.cpp \
    $${PWD}/PaginatedPluginConfigList.cpp \
    $${PWD}/PaginatedPluginSettingList.cpp \
    $${PWD}/PaginatedProjectCodeList.cpp \
    $${PWD}/PaginatedPurchaseOrderAttachmentList.cpp \
    $${PWD}/PaginatedPurchaseOrderExtraLineList.cpp \
    $${PWD}/PaginatedPurchaseOrderLineItemList.cpp \
    $${PWD}/PaginatedPurchaseOrderList.cpp \
    $${PWD}/PaginatedPurchaseOrderReportList.cpp \
    $${PWD}/PaginatedReturnOrderAttachmentList.cpp \
    $${PWD}/PaginatedReturnOrderExtraLineList.cpp \
    $${PWD}/PaginatedReturnOrderLineItemList.cpp \
    $${PWD}/PaginatedReturnOrderList.cpp \
    $${PWD}/PaginatedReturnOrderReportList.cpp \
    $${PWD}/PaginatedSalesOrderAllocationList.cpp \
    $${PWD}/PaginatedSalesOrderAttachmentList.cpp \
    $${PWD}/PaginatedSalesOrderExtraLineList.cpp \
    $${PWD}/PaginatedSalesOrderLineItemList.cpp \
    $${PWD}/PaginatedSalesOrderList.cpp \
    $${PWD}/PaginatedSalesOrderReportList.cpp \
    $${PWD}/PaginatedSalesOrderShipmentList.cpp \
    $${PWD}/PaginatedSocialAccountList.cpp \
    $${PWD}/PaginatedStockItemAttachmentList.cpp \
    $${PWD}/PaginatedStockItemLabelList.cpp \
    $${PWD}/PaginatedStockItemList.cpp \
    $${PWD}/PaginatedStockItemTestResultList.cpp \
    $${PWD}/PaginatedStockLocationLabelList.cpp \
    $${PWD}/PaginatedStockLocationReportList.cpp \
    $${PWD}/PaginatedStockLocationTypeList.cpp \
    $${PWD}/PaginatedStockTrackingList.cpp \
    $${PWD}/PaginatedSupplierPartList.cpp \
    $${PWD}/PaginatedSupplierPriceBreakList.cpp \
    $${PWD}/PaginatedTestReportList.cpp \
    $${PWD}/PaginatedUserCreateList.cpp \
    $${PWD}/PaginatedUserSettingsList.cpp \
    $${PWD}/Part.cpp \
    $${PWD}/PartAttachment.cpp \
    $${PWD}/PartBrief.cpp \
    $${PWD}/PartCopyBOM.cpp \
    $${PWD}/PartInternalPrice.cpp \
    $${PWD}/PartLabel.cpp \
    $${PWD}/PartParameter.cpp \
    $${PWD}/PartParameterTemplate.cpp \
    $${PWD}/PartPricing.cpp \
    $${PWD}/PartRelation.cpp \
    $${PWD}/PartSalePrice.cpp \
    $${PWD}/PartSetCategory.cpp \
    $${PWD}/PartStocktake.cpp \
    $${PWD}/PartStocktakeReport.cpp \
    $${PWD}/PartStocktakeReportGenerate.cpp \
    $${PWD}/PartTestTemplate.cpp \
    $${PWD}/PartThumb.cpp \
    $${PWD}/PartThumbSerializerUpdate.cpp \
    $${PWD}/PasswordChange.cpp \
    $${PWD}/PasswordReset.cpp \
    $${PWD}/PasswordResetConfirm.cpp \
    $${PWD}/PatchedAddress.cpp \
    $${PWD}/PatchedBOMReport.cpp \
    $${PWD}/PatchedBOMValidate.cpp \
    $${PWD}/PatchedBomItem.cpp \
    $${PWD}/PatchedBomItemSubstitute.cpp \
    $${PWD}/PatchedBomItemValidation.cpp \
    $${PWD}/PatchedBuild.cpp \
    $${PWD}/PatchedBuildAttachment.cpp \
    $${PWD}/PatchedBuildItem.cpp \
    $${PWD}/PatchedBuildLine.cpp \
    $${PWD}/PatchedBuildLineLabel.cpp \
    $${PWD}/PatchedBuildReport.cpp \
    $${PWD}/PatchedCategory.cpp \
    $${PWD}/PatchedCategoryParameterTemplate.cpp \
    $${PWD}/PatchedCompany.cpp \
    $${PWD}/PatchedCompanyAttachment.cpp \
    $${PWD}/PatchedContact.cpp \
    $${PWD}/PatchedCustomUnit.cpp \
    $${PWD}/PatchedExendedUser.cpp \
    $${PWD}/PatchedGlobalSettings.cpp \
    $${PWD}/PatchedGroup.cpp \
    $${PWD}/PatchedLocation.cpp \
    $${PWD}/PatchedManufacturerPart.cpp \
    $${PWD}/PatchedManufacturerPartAttachment.cpp \
    $${PWD}/PatchedManufacturerPartParameter.cpp \
    $${PWD}/PatchedNewsFeedEntry.cpp \
    $${PWD}/PatchedNotificationMessage.cpp \
    $${PWD}/PatchedNotificationUserSetting.cpp \
    $${PWD}/PatchedPart.cpp \
    $${PWD}/PatchedPartAttachment.cpp \
    $${PWD}/PatchedPartInternalPrice.cpp \
    $${PWD}/PatchedPartLabel.cpp \
    $${PWD}/PatchedPartParameter.cpp \
    $${PWD}/PatchedPartParameterTemplate.cpp \
    $${PWD}/PatchedPartPricing.cpp \
    $${PWD}/PatchedPartRelation.cpp \
    $${PWD}/PatchedPartSalePrice.cpp \
    $${PWD}/PatchedPartStocktake.cpp \
    $${PWD}/PatchedPartTestTemplate.cpp \
    $${PWD}/PatchedPartThumbSerializerUpdate.cpp \
    $${PWD}/PatchedPluginActivate.cpp \
    $${PWD}/PatchedPluginConfig.cpp \
    $${PWD}/PatchedPluginSetting.cpp \
    $${PWD}/PatchedProjectCode.cpp \
    $${PWD}/PatchedPurchaseOrder.cpp \
    $${PWD}/PatchedPurchaseOrderAttachment.cpp \
    $${PWD}/PatchedPurchaseOrderExtraLine.cpp \
    $${PWD}/PatchedPurchaseOrderLineItem.cpp \
    $${PWD}/PatchedPurchaseOrderReport.cpp \
    $${PWD}/PatchedReturnOrder.cpp \
    $${PWD}/PatchedReturnOrderAttachment.cpp \
    $${PWD}/PatchedReturnOrderExtraLine.cpp \
    $${PWD}/PatchedReturnOrderLineItem.cpp \
    $${PWD}/PatchedReturnOrderReport.cpp \
    $${PWD}/PatchedSalesOrder.cpp \
    $${PWD}/PatchedSalesOrderAllocation.cpp \
    $${PWD}/PatchedSalesOrderAttachment.cpp \
    $${PWD}/PatchedSalesOrderExtraLine.cpp \
    $${PWD}/PatchedSalesOrderLineItem.cpp \
    $${PWD}/PatchedSalesOrderReport.cpp \
    $${PWD}/PatchedSalesOrderShipment.cpp \
    $${PWD}/PatchedStockItem.cpp \
    $${PWD}/PatchedStockItemAttachment.cpp \
    $${PWD}/PatchedStockItemLabel.cpp \
    $${PWD}/PatchedStockItemTestResult.cpp \
    $${PWD}/PatchedStockLocationLabel.cpp \
    $${PWD}/PatchedStockLocationReport.cpp \
    $${PWD}/PatchedStockLocationType.cpp \
    $${PWD}/PatchedSupplierPart.cpp \
    $${PWD}/PatchedSupplierPriceBreak.cpp \
    $${PWD}/PatchedTestReport.cpp \
    $${PWD}/PatchedUserDetails.cpp \
    $${PWD}/PatchedUserSettings.cpp \
    $${PWD}/PluginActivate.cpp \
    $${PWD}/PluginConfig.cpp \
    $${PWD}/PluginConfigInstall.cpp \
    $${PWD}/PluginRegistryError.cpp \
    $${PWD}/PluginRegistryStatus.cpp \
    $${PWD}/PluginSetting.cpp \
    $${PWD}/ProjectCode.cpp \
    $${PWD}/PurchaseOrder.cpp \
    $${PWD}/PurchaseOrderAttachment.cpp \
    $${PWD}/PurchaseOrderComplete.cpp \
    $${PWD}/PurchaseOrderExtraLine.cpp \
    $${PWD}/PurchaseOrderLineItem.cpp \
    $${PWD}/PurchaseOrderLineItemReceive.cpp \
    $${PWD}/PurchaseOrderReceive.cpp \
    $${PWD}/PurchaseOrderReport.cpp \
    $${PWD}/Register.cpp \
    $${PWD}/Rendel_s_p_nzneme.cpp \
    $${PWD}/ResendEmailVerification.cpp \
    $${PWD}/RestAuthDetail.cpp \
    $${PWD}/ReturnOrder.cpp \
    $${PWD}/ReturnOrderAttachment.cpp \
    $${PWD}/ReturnOrderExtraLine.cpp \
    $${PWD}/ReturnOrderLineItem.cpp \
    $${PWD}/ReturnOrderLineItemReceive.cpp \
    $${PWD}/ReturnOrderReceive.cpp \
    $${PWD}/ReturnOrderReport.cpp \
    $${PWD}/ReturnStockItem.cpp \
    $${PWD}/SalePriceCurrencyEnum.cpp \
    $${PWD}/SalesOrder.cpp \
    $${PWD}/SalesOrderAllocation.cpp \
    $${PWD}/SalesOrderAttachment.cpp \
    $${PWD}/SalesOrderComplete.cpp \
    $${PWD}/SalesOrderExtraLine.cpp \
    $${PWD}/SalesOrderLineItem.cpp \
    $${PWD}/SalesOrderReport.cpp \
    $${PWD}/SalesOrderSerialAllocation.cpp \
    $${PWD}/SalesOrderShipment.cpp \
    $${PWD}/SalesOrderShipmentAllocation.cpp \
    $${PWD}/SalesOrderShipmentAllocationItem.cpp \
    $${PWD}/SalesOrderShipmentComplete.cpp \
    $${PWD}/SerializeStockItem.cpp \
    $${PWD}/SocialAccount.cpp \
    $${PWD}/SocialConnect.cpp \
    $${PWD}/Status46bEnum.cpp \
    $${PWD}/StockAdd.cpp \
    $${PWD}/StockAdjustmentItem.cpp \
    $${PWD}/StockAssignment.cpp \
    $${PWD}/StockAssignmentItem.cpp \
    $${PWD}/StockChangeStatus.cpp \
    $${PWD}/StockCount.cpp \
    $${PWD}/StockItem.cpp \
    $${PWD}/StockItemAttachment.cpp \
    $${PWD}/StockItemLabel.cpp \
    $${PWD}/StockItemTestResult.cpp \
    $${PWD}/StockLocationLabel.cpp \
    $${PWD}/StockLocationReport.cpp \
    $${PWD}/StockLocationType.cpp \
    $${PWD}/StockMerge.cpp \
    $${PWD}/StockMergeItem.cpp \
    $${PWD}/StockRemove.cpp \
    $${PWD}/StockTracking.cpp \
    $${PWD}/StockTransfer.cpp \
    $${PWD}/SupplierPart.cpp \
    $${PWD}/SupplierPriceBreak.cpp \
    $${PWD}/TestReport.cpp \
    $${PWD}/Token.cpp \
    $${PWD}/UninstallStockItem.cpp \
    $${PWD}/User.cpp \
    $${PWD}/UserCreate.cpp \
    $${PWD}/UserDetails.cpp \
    $${PWD}/UserSettings.cpp \
    $${PWD}/VerifyEmail.cpp \
    $${PWD}/_llapot.cpp \
# APIs
    $${PWD}/ActionApi.cpp \
    $${PWD}/AdminApi.cpp \
    $${PWD}/AuthApi.cpp \
    $${PWD}/BarcodeApi.cpp \
    $${PWD}/BomApi.cpp \
    $${PWD}/BuildApi.cpp \
    $${PWD}/CompanyApi.cpp \
    $${PWD}/CurrencyApi.cpp \
    $${PWD}/EmailApi.cpp \
    $${PWD}/FlagsApi.cpp \
    $${PWD}/GenericApi.cpp \
    $${PWD}/LabelApi.cpp \
    $${PWD}/LocateApi.cpp \
    $${PWD}/NewsApi.cpp \
    $${PWD}/NotesImageUploadApi.cpp \
    $${PWD}/NotificationsApi.cpp \
    $${PWD}/OrderApi.cpp \
    $${PWD}/PartApi.cpp \
    $${PWD}/PluginsApi.cpp \
    $${PWD}/ProjectCodeApi.cpp \
    $${PWD}/ReportApi.cpp \
    $${PWD}/SearchApi.cpp \
    $${PWD}/SettingsApi.cpp \
    $${PWD}/StockApi.cpp \
    $${PWD}/UnitsApi.cpp \
    $${PWD}/UserApi.cpp \
    $${PWD}/VersionApi.cpp \
    $${PWD}/VersionTextApi.cpp \
    $${PWD}/WebhookApi.cpp \
# Others
    $${PWD}/Helpers.cpp \
    $${PWD}/HttpRequest.cpp \
    $${PWD}/HttpFileElement.cpp \
    $${PWD}/Oauth.cpp
