cmake_minimum_required(VERSION 3.5)

project(QtOpenAPIClient)

set(CMAKE_AUTOMOC ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Network Gui)

include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

add_library(${PROJECT_NAME}
  APISearchView.h
  AcceptOverallocatedEnum.h
  ActionPlugin.h
  ActionPluginError.h
  Address.h
  AddressBrief.h
  AllUnitListResponse.h
  ApiToken.h
  Attachment.h
  AttachmentModelTypeEnum.h
  Barcode.h
  BarcodeAssign.h
  BarcodeGenerate.h
  BarcodePOAllocate.h
  BarcodePOReceive.h
  BarcodeSOAllocate.h
  BarcodeScanResult.h
  BarcodeUnassign.h
  BlankEnum.h
  BomItem.h
  BomItemSubstitute.h
  BomItemValidation.h
  BriefUserProfile.h
  Build.h
  BuildAllocation.h
  BuildAllocationItem.h
  BuildAutoAllocation.h
  BuildCancel.h
  BuildComplete.h
  BuildConsume.h
  BuildConsumeAllocation.h
  BuildConsumeLineItem.h
  BuildItem.h
  BuildLine.h
  BuildOutput.h
  BuildOutputComplete.h
  BuildOutputCreate.h
  BuildOutputDelete.h
  BuildOutputQuantity.h
  BuildOutputScrap.h
  BuildStatusEnum.h
  BuildUnallocation.h
  BulkRequest.h
  Category.h
  CategoryParameterTemplate.h
  CategoryTree.h
  ColorEnum.h
  Company.h
  CompanyBrief.h
  Config.h
  ConfigTypeEnum.h
  Contact.h
  ContentType.h
  ConvertStockItem.h
  CurrencyExchange.h
  CustomState.h
  CustomUnit.h
  Customize.h
  DataImportAcceptRow.h
  DataImportColumnMap.h
  DataImportRow.h
  DataImportSession.h
  DataImportSessionModelTypeEnum.h
  DataImportSessionStatusEnum.h
  DataImporterModel.h
  DataOutput.h
  DefaultLocation.h
  DirectionEnum.h
  DuplicateOrder.h
  DuplicatePart.h
  EmailMessage.h
  EmailMessageStatusEnum.h
  ErrorMessage.h
  ExtendedUser.h
  FailedTask.h
  Flag.h
  GenerateBatchCode.h
  GenerateSerialNumber.h
  GenericStateClass.h
  GenericStateValue.h
  GetAuthToken.h
  GetSimpleLogin.h
  GlobalSettings.h
  Group.h
  HealthCheckStatus.h
  HealthCheckStatusStatusEnum.h
  Icon.h
  IconPackage.h
  ImportParameter.h
  ImportRequest.h
  ImportResult.h
  InfoApi.h
  InitialStock.h
  InitialSupplier.h
  InstallStockItem.h
  LabelPrint.h
  LabelTemplate.h
  LicenseView.h
  Link.h
  LocatePlugin.h
  Location.h
  LocationBrief.h
  LocationTree.h
  MachineConfig.h
  MachineConfigCreate.h
  MachineDriver.h
  MachineProperty.h
  MachinePropertyTypeEnum.h
  MachineRegistryError.h
  MachineRegistryStatus.h
  MachineRestart.h
  MachineSetting.h
  MachineType.h
  ManufacturerPart.h
  MeUser.h
  ModelType4f8Enum.h
  NameEnum.h
  NewsFeedEntry.h
  NotesImage.h
  NotificationMessage.h
  NullEnum.h
  OutcomeEnum.h
  Owner.h
  PageSizeEnum.h
  PaginatedAddressList.h
  PaginatedApiTokenList.h
  PaginatedAttachmentList.h
  PaginatedBarcodeScanResultList.h
  PaginatedBomItemList.h
  PaginatedBomItemSubstituteList.h
  PaginatedBuildItemList.h
  PaginatedBuildLineList.h
  PaginatedBuildList.h
  PaginatedCategoryList.h
  PaginatedCategoryParameterTemplateList.h
  PaginatedCategoryTreeList.h
  PaginatedCompanyList.h
  PaginatedContactList.h
  PaginatedContentTypeList.h
  PaginatedCustomStateList.h
  PaginatedCustomUnitList.h
  PaginatedDataImportColumnMapList.h
  PaginatedDataImportRowList.h
  PaginatedDataImportSessionList.h
  PaginatedDataOutputList.h
  PaginatedEmailMessageList.h
  PaginatedErrorMessageList.h
  PaginatedFailedTaskList.h
  PaginatedGlobalSettingsList.h
  PaginatedGroupList.h
  PaginatedIconPackageList.h
  PaginatedLabelTemplateList.h
  PaginatedLocationList.h
  PaginatedLocationTreeList.h
  PaginatedMachineConfigList.h
  PaginatedManufacturerPartList.h
  PaginatedNewsFeedEntryList.h
  PaginatedNotesImageList.h
  PaginatedNotificationMessageList.h
  PaginatedOwnerList.h
  PaginatedParameterList.h
  PaginatedParameterTemplateList.h
  PaginatedPartInternalPriceList.h
  PaginatedPartList.h
  PaginatedPartRelationList.h
  PaginatedPartSalePriceList.h
  PaginatedPartStocktakeList.h
  PaginatedPartTestTemplateList.h
  PaginatedPartThumbList.h
  PaginatedPendingTaskList.h
  PaginatedPluginConfigList.h
  PaginatedPluginSettingList.h
  PaginatedProjectCodeList.h
  PaginatedPurchaseOrderExtraLineList.h
  PaginatedPurchaseOrderLineItemList.h
  PaginatedPurchaseOrderList.h
  PaginatedReportAssetList.h
  PaginatedReportSnippetList.h
  PaginatedReportTemplateList.h
  PaginatedReturnOrderExtraLineList.h
  PaginatedReturnOrderLineItemList.h
  PaginatedReturnOrderList.h
  PaginatedRuleSetList.h
  PaginatedSalesOrderAllocationList.h
  PaginatedSalesOrderExtraLineList.h
  PaginatedSalesOrderLineItemList.h
  PaginatedSalesOrderList.h
  PaginatedSalesOrderShipmentList.h
  PaginatedScheduledTaskList.h
  PaginatedSelectionEntryList.h
  PaginatedSelectionListList.h
  PaginatedStockItemList.h
  PaginatedStockItemTestResultList.h
  PaginatedStockLocationTypeList.h
  PaginatedStockTrackingList.h
  PaginatedSupplierPartList.h
  PaginatedSupplierPriceBreakList.h
  PaginatedUserCreateList.h
  PaginatedUserSettingsList.h
  Parameter.h
  ParameterTemplate.h
  Part.h
  PartBomValidate.h
  PartBrief.h
  PartCopyBOM.h
  PartInternalPrice.h
  PartPricing.h
  PartRelation.h
  PartRequirements.h
  PartSalePrice.h
  PartSerialNumber.h
  PartStocktake.h
  PartTestTemplate.h
  PartThumb.h
  PartThumbSerializerUpdate.h
  PatchedAddress.h
  PatchedAttachment.h
  PatchedBomItem.h
  PatchedBomItemSubstitute.h
  PatchedBomItemValidation.h
  PatchedBuild.h
  PatchedBuildItem.h
  PatchedBuildLine.h
  PatchedCategory.h
  PatchedCategoryParameterTemplate.h
  PatchedCompany.h
  PatchedContact.h
  PatchedCustomState.h
  PatchedCustomUnit.h
  PatchedDataImportColumnMap.h
  PatchedDataImportRow.h
  PatchedDataImportSession.h
  PatchedErrorMessage.h
  PatchedExtendedUser.h
  PatchedGlobalSettings.h
  PatchedGroup.h
  PatchedLabelTemplate.h
  PatchedLocation.h
  PatchedMachineConfig.h
  PatchedMachineSetting.h
  PatchedManufacturerPart.h
  PatchedMeUser.h
  PatchedNewsFeedEntry.h
  PatchedNotificationMessage.h
  PatchedParameter.h
  PatchedParameterTemplate.h
  PatchedPart.h
  PatchedPartBomValidate.h
  PatchedPartInternalPrice.h
  PatchedPartPricing.h
  PatchedPartRelation.h
  PatchedPartSalePrice.h
  PatchedPartStocktake.h
  PatchedPartTestTemplate.h
  PatchedPartThumbSerializerUpdate.h
  PatchedPluginActivate.h
  PatchedPluginSetting.h
  PatchedPluginUninstall.h
  PatchedPluginUserSetting.h
  PatchedProjectCode.h
  PatchedPurchaseOrder.h
  PatchedPurchaseOrderExtraLine.h
  PatchedPurchaseOrderLineItem.h
  PatchedReportAsset.h
  PatchedReportSnippet.h
  PatchedReportTemplate.h
  PatchedReturnOrder.h
  PatchedReturnOrderExtraLine.h
  PatchedReturnOrderLineItem.h
  PatchedRuleSet.h
  PatchedSalesOrder.h
  PatchedSalesOrderAllocation.h
  PatchedSalesOrderExtraLine.h
  PatchedSalesOrderLineItem.h
  PatchedSalesOrderShipment.h
  PatchedSelectionEntry.h
  PatchedSelectionList.h
  PatchedStockItem.h
  PatchedStockItemTestResult.h
  PatchedStockLocationType.h
  PatchedSupplierPart.h
  PatchedSupplierPriceBreak.h
  PatchedUserProfile.h
  PatchedUserSetPassword.h
  PatchedUserSettings.h
  PendingTask.h
  PluginActivate.h
  PluginAdminDetail.h
  PluginConfig.h
  PluginConfigInstall.h
  PluginRegistryError.h
  PluginRegistryStatus.h
  PluginReload.h
  PluginSetting.h
  PluginUIFeature.h
  PluginUninstall.h
  PluginUserSetting.h
  PriorityEnum.h
  ProjectCode.h
  PurchaseOrder.h
  PurchaseOrderComplete.h
  PurchaseOrderExtraLine.h
  PurchaseOrderLineItem.h
  PurchaseOrderLineItemReceive.h
  PurchaseOrderReceive.h
  ReferenceStatusEnum.h
  ReportAsset.h
  ReportPrint.h
  ReportSnippet.h
  ReportTemplate.h
  ReturnOrder.h
  ReturnOrderExtraLine.h
  ReturnOrderLineItem.h
  ReturnOrderLineItemReceive.h
  ReturnOrderReceive.h
  Role.h
  RuleSet.h
  SalesOrder.h
  SalesOrderAllocation.h
  SalesOrderComplete.h
  SalesOrderExtraLine.h
  SalesOrderLineItem.h
  SalesOrderSerialAllocation.h
  SalesOrderShipment.h
  SalesOrderShipmentAllocation.h
  SalesOrderShipmentAllocationItem.h
  SalesOrderShipmentComplete.h
  ScheduleTypeEnum.h
  ScheduledTask.h
  SearchResult.h
  SelectionEntry.h
  SelectionList.h
  SerializeStockItem.h
  Settings.h
  StockAdd.h
  StockAdjustmentItem.h
  StockAssignment.h
  StockAssignmentItem.h
  StockChangeStatus.h
  StockCount.h
  StockItem.h
  StockItemSerialNumbers.h
  StockItemStatusEnum.h
  StockItemTestResult.h
  StockLocationType.h
  StockMerge.h
  StockMergeItem.h
  StockRemove.h
  StockReturn.h
  StockTracking.h
  StockTransfer.h
  SupplierList.h
  SupplierPart.h
  SupplierPriceBreak.h
  SupplierPriceBreakBrief.h
  TaskOverview.h
  TemplateModelTypeEnum.h
  TestEmail.h
  UninstallStockItem.h
  Unit.h
  User.h
  UserCreate.h
  UserProfile.h
  UserSetPassword.h
  UserSettings.h
  UserTypeEnum.h
  Version.h
  VersionInformation.h
  VersionView.h
  ActionApi.h
  AdminApi.h
  AttachmentApi.h
  BackgroundTaskApi.h
  BarcodeApi.h
  BomApi.h
  BuildApi.h
  CompanyApi.h
  ContenttypeApi.h
  CurrencyApi.h
  DataOutputApi.h
  DefaultApi.h
  EmailApi.h
  ErrorReportApi.h
  FlagsApi.h
  GenerateApi.h
  GenericApi.h
  IconsApi.h
  ImporterApi.h
  LabelApi.h
  LicenseApi.h
  LocateApi.h
  MachineApi.h
  MetadataApi.h
  NewsApi.h
  NotesImageUploadApi.h
  NotificationsApi.h
  OrderApi.h
  ParameterApi.h
  PartApi.h
  PluginsApi.h
  ProjectCodeApi.h
  ReportApi.h
  SearchApi.h
  SelectionApi.h
  SettingsApi.h
  StockApi.h
  SupplierApi.h
  SystemApi.h
  UnitsApi.h
  UserApi.h
  VersionApi.h
  VersionTextApi.h
  WebhookApi.h
  Helpers.h
  HttpRequest.h
  Object.h
  Enum.h
  HttpFileElement.h
  ServerConfiguration.h
  ServerVariable.h
  Oauth.h
  APISearchView.cpp
  AcceptOverallocatedEnum.cpp
  ActionPlugin.cpp
  ActionPluginError.cpp
  Address.cpp
  AddressBrief.cpp
  AllUnitListResponse.cpp
  ApiToken.cpp
  Attachment.cpp
  AttachmentModelTypeEnum.cpp
  Barcode.cpp
  BarcodeAssign.cpp
  BarcodeGenerate.cpp
  BarcodePOAllocate.cpp
  BarcodePOReceive.cpp
  BarcodeSOAllocate.cpp
  BarcodeScanResult.cpp
  BarcodeUnassign.cpp
  BlankEnum.cpp
  BomItem.cpp
  BomItemSubstitute.cpp
  BomItemValidation.cpp
  BriefUserProfile.cpp
  Build.cpp
  BuildAllocation.cpp
  BuildAllocationItem.cpp
  BuildAutoAllocation.cpp
  BuildCancel.cpp
  BuildComplete.cpp
  BuildConsume.cpp
  BuildConsumeAllocation.cpp
  BuildConsumeLineItem.cpp
  BuildItem.cpp
  BuildLine.cpp
  BuildOutput.cpp
  BuildOutputComplete.cpp
  BuildOutputCreate.cpp
  BuildOutputDelete.cpp
  BuildOutputQuantity.cpp
  BuildOutputScrap.cpp
  BuildStatusEnum.cpp
  BuildUnallocation.cpp
  BulkRequest.cpp
  Category.cpp
  CategoryParameterTemplate.cpp
  CategoryTree.cpp
  ColorEnum.cpp
  Company.cpp
  CompanyBrief.cpp
  Config.cpp
  ConfigTypeEnum.cpp
  Contact.cpp
  ContentType.cpp
  ConvertStockItem.cpp
  CurrencyExchange.cpp
  CustomState.cpp
  CustomUnit.cpp
  Customize.cpp
  DataImportAcceptRow.cpp
  DataImportColumnMap.cpp
  DataImportRow.cpp
  DataImportSession.cpp
  DataImportSessionModelTypeEnum.cpp
  DataImportSessionStatusEnum.cpp
  DataImporterModel.cpp
  DataOutput.cpp
  DefaultLocation.cpp
  DirectionEnum.cpp
  DuplicateOrder.cpp
  DuplicatePart.cpp
  EmailMessage.cpp
  EmailMessageStatusEnum.cpp
  ErrorMessage.cpp
  ExtendedUser.cpp
  FailedTask.cpp
  Flag.cpp
  GenerateBatchCode.cpp
  GenerateSerialNumber.cpp
  GenericStateClass.cpp
  GenericStateValue.cpp
  GetAuthToken.cpp
  GetSimpleLogin.cpp
  GlobalSettings.cpp
  Group.cpp
  HealthCheckStatus.cpp
  HealthCheckStatusStatusEnum.cpp
  Icon.cpp
  IconPackage.cpp
  ImportParameter.cpp
  ImportRequest.cpp
  ImportResult.cpp
  InfoApi.cpp
  InitialStock.cpp
  InitialSupplier.cpp
  InstallStockItem.cpp
  LabelPrint.cpp
  LabelTemplate.cpp
  LicenseView.cpp
  Link.cpp
  LocatePlugin.cpp
  Location.cpp
  LocationBrief.cpp
  LocationTree.cpp
  MachineConfig.cpp
  MachineConfigCreate.cpp
  MachineDriver.cpp
  MachineProperty.cpp
  MachinePropertyTypeEnum.cpp
  MachineRegistryError.cpp
  MachineRegistryStatus.cpp
  MachineRestart.cpp
  MachineSetting.cpp
  MachineType.cpp
  ManufacturerPart.cpp
  MeUser.cpp
  ModelType4f8Enum.cpp
  NameEnum.cpp
  NewsFeedEntry.cpp
  NotesImage.cpp
  NotificationMessage.cpp
  NullEnum.cpp
  OutcomeEnum.cpp
  Owner.cpp
  PageSizeEnum.cpp
  PaginatedAddressList.cpp
  PaginatedApiTokenList.cpp
  PaginatedAttachmentList.cpp
  PaginatedBarcodeScanResultList.cpp
  PaginatedBomItemList.cpp
  PaginatedBomItemSubstituteList.cpp
  PaginatedBuildItemList.cpp
  PaginatedBuildLineList.cpp
  PaginatedBuildList.cpp
  PaginatedCategoryList.cpp
  PaginatedCategoryParameterTemplateList.cpp
  PaginatedCategoryTreeList.cpp
  PaginatedCompanyList.cpp
  PaginatedContactList.cpp
  PaginatedContentTypeList.cpp
  PaginatedCustomStateList.cpp
  PaginatedCustomUnitList.cpp
  PaginatedDataImportColumnMapList.cpp
  PaginatedDataImportRowList.cpp
  PaginatedDataImportSessionList.cpp
  PaginatedDataOutputList.cpp
  PaginatedEmailMessageList.cpp
  PaginatedErrorMessageList.cpp
  PaginatedFailedTaskList.cpp
  PaginatedGlobalSettingsList.cpp
  PaginatedGroupList.cpp
  PaginatedIconPackageList.cpp
  PaginatedLabelTemplateList.cpp
  PaginatedLocationList.cpp
  PaginatedLocationTreeList.cpp
  PaginatedMachineConfigList.cpp
  PaginatedManufacturerPartList.cpp
  PaginatedNewsFeedEntryList.cpp
  PaginatedNotesImageList.cpp
  PaginatedNotificationMessageList.cpp
  PaginatedOwnerList.cpp
  PaginatedParameterList.cpp
  PaginatedParameterTemplateList.cpp
  PaginatedPartInternalPriceList.cpp
  PaginatedPartList.cpp
  PaginatedPartRelationList.cpp
  PaginatedPartSalePriceList.cpp
  PaginatedPartStocktakeList.cpp
  PaginatedPartTestTemplateList.cpp
  PaginatedPartThumbList.cpp
  PaginatedPendingTaskList.cpp
  PaginatedPluginConfigList.cpp
  PaginatedPluginSettingList.cpp
  PaginatedProjectCodeList.cpp
  PaginatedPurchaseOrderExtraLineList.cpp
  PaginatedPurchaseOrderLineItemList.cpp
  PaginatedPurchaseOrderList.cpp
  PaginatedReportAssetList.cpp
  PaginatedReportSnippetList.cpp
  PaginatedReportTemplateList.cpp
  PaginatedReturnOrderExtraLineList.cpp
  PaginatedReturnOrderLineItemList.cpp
  PaginatedReturnOrderList.cpp
  PaginatedRuleSetList.cpp
  PaginatedSalesOrderAllocationList.cpp
  PaginatedSalesOrderExtraLineList.cpp
  PaginatedSalesOrderLineItemList.cpp
  PaginatedSalesOrderList.cpp
  PaginatedSalesOrderShipmentList.cpp
  PaginatedScheduledTaskList.cpp
  PaginatedSelectionEntryList.cpp
  PaginatedSelectionListList.cpp
  PaginatedStockItemList.cpp
  PaginatedStockItemTestResultList.cpp
  PaginatedStockLocationTypeList.cpp
  PaginatedStockTrackingList.cpp
  PaginatedSupplierPartList.cpp
  PaginatedSupplierPriceBreakList.cpp
  PaginatedUserCreateList.cpp
  PaginatedUserSettingsList.cpp
  Parameter.cpp
  ParameterTemplate.cpp
  Part.cpp
  PartBomValidate.cpp
  PartBrief.cpp
  PartCopyBOM.cpp
  PartInternalPrice.cpp
  PartPricing.cpp
  PartRelation.cpp
  PartRequirements.cpp
  PartSalePrice.cpp
  PartSerialNumber.cpp
  PartStocktake.cpp
  PartTestTemplate.cpp
  PartThumb.cpp
  PartThumbSerializerUpdate.cpp
  PatchedAddress.cpp
  PatchedAttachment.cpp
  PatchedBomItem.cpp
  PatchedBomItemSubstitute.cpp
  PatchedBomItemValidation.cpp
  PatchedBuild.cpp
  PatchedBuildItem.cpp
  PatchedBuildLine.cpp
  PatchedCategory.cpp
  PatchedCategoryParameterTemplate.cpp
  PatchedCompany.cpp
  PatchedContact.cpp
  PatchedCustomState.cpp
  PatchedCustomUnit.cpp
  PatchedDataImportColumnMap.cpp
  PatchedDataImportRow.cpp
  PatchedDataImportSession.cpp
  PatchedErrorMessage.cpp
  PatchedExtendedUser.cpp
  PatchedGlobalSettings.cpp
  PatchedGroup.cpp
  PatchedLabelTemplate.cpp
  PatchedLocation.cpp
  PatchedMachineConfig.cpp
  PatchedMachineSetting.cpp
  PatchedManufacturerPart.cpp
  PatchedMeUser.cpp
  PatchedNewsFeedEntry.cpp
  PatchedNotificationMessage.cpp
  PatchedParameter.cpp
  PatchedParameterTemplate.cpp
  PatchedPart.cpp
  PatchedPartBomValidate.cpp
  PatchedPartInternalPrice.cpp
  PatchedPartPricing.cpp
  PatchedPartRelation.cpp
  PatchedPartSalePrice.cpp
  PatchedPartStocktake.cpp
  PatchedPartTestTemplate.cpp
  PatchedPartThumbSerializerUpdate.cpp
  PatchedPluginActivate.cpp
  PatchedPluginSetting.cpp
  PatchedPluginUninstall.cpp
  PatchedPluginUserSetting.cpp
  PatchedProjectCode.cpp
  PatchedPurchaseOrder.cpp
  PatchedPurchaseOrderExtraLine.cpp
  PatchedPurchaseOrderLineItem.cpp
  PatchedReportAsset.cpp
  PatchedReportSnippet.cpp
  PatchedReportTemplate.cpp
  PatchedReturnOrder.cpp
  PatchedReturnOrderExtraLine.cpp
  PatchedReturnOrderLineItem.cpp
  PatchedRuleSet.cpp
  PatchedSalesOrder.cpp
  PatchedSalesOrderAllocation.cpp
  PatchedSalesOrderExtraLine.cpp
  PatchedSalesOrderLineItem.cpp
  PatchedSalesOrderShipment.cpp
  PatchedSelectionEntry.cpp
  PatchedSelectionList.cpp
  PatchedStockItem.cpp
  PatchedStockItemTestResult.cpp
  PatchedStockLocationType.cpp
  PatchedSupplierPart.cpp
  PatchedSupplierPriceBreak.cpp
  PatchedUserProfile.cpp
  PatchedUserSetPassword.cpp
  PatchedUserSettings.cpp
  PendingTask.cpp
  PluginActivate.cpp
  PluginAdminDetail.cpp
  PluginConfig.cpp
  PluginConfigInstall.cpp
  PluginRegistryError.cpp
  PluginRegistryStatus.cpp
  PluginReload.cpp
  PluginSetting.cpp
  PluginUIFeature.cpp
  PluginUninstall.cpp
  PluginUserSetting.cpp
  PriorityEnum.cpp
  ProjectCode.cpp
  PurchaseOrder.cpp
  PurchaseOrderComplete.cpp
  PurchaseOrderExtraLine.cpp
  PurchaseOrderLineItem.cpp
  PurchaseOrderLineItemReceive.cpp
  PurchaseOrderReceive.cpp
  ReferenceStatusEnum.cpp
  ReportAsset.cpp
  ReportPrint.cpp
  ReportSnippet.cpp
  ReportTemplate.cpp
  ReturnOrder.cpp
  ReturnOrderExtraLine.cpp
  ReturnOrderLineItem.cpp
  ReturnOrderLineItemReceive.cpp
  ReturnOrderReceive.cpp
  Role.cpp
  RuleSet.cpp
  SalesOrder.cpp
  SalesOrderAllocation.cpp
  SalesOrderComplete.cpp
  SalesOrderExtraLine.cpp
  SalesOrderLineItem.cpp
  SalesOrderSerialAllocation.cpp
  SalesOrderShipment.cpp
  SalesOrderShipmentAllocation.cpp
  SalesOrderShipmentAllocationItem.cpp
  SalesOrderShipmentComplete.cpp
  ScheduleTypeEnum.cpp
  ScheduledTask.cpp
  SearchResult.cpp
  SelectionEntry.cpp
  SelectionList.cpp
  SerializeStockItem.cpp
  Settings.cpp
  StockAdd.cpp
  StockAdjustmentItem.cpp
  StockAssignment.cpp
  StockAssignmentItem.cpp
  StockChangeStatus.cpp
  StockCount.cpp
  StockItem.cpp
  StockItemSerialNumbers.cpp
  StockItemStatusEnum.cpp
  StockItemTestResult.cpp
  StockLocationType.cpp
  StockMerge.cpp
  StockMergeItem.cpp
  StockRemove.cpp
  StockReturn.cpp
  StockTracking.cpp
  StockTransfer.cpp
  SupplierList.cpp
  SupplierPart.cpp
  SupplierPriceBreak.cpp
  SupplierPriceBreakBrief.cpp
  TaskOverview.cpp
  TemplateModelTypeEnum.cpp
  TestEmail.cpp
  UninstallStockItem.cpp
  Unit.cpp
  User.cpp
  UserCreate.cpp
  UserProfile.cpp
  UserSetPassword.cpp
  UserSettings.cpp
  UserTypeEnum.cpp
  Version.cpp
  VersionInformation.cpp
  VersionView.cpp
  ActionApi.cpp
  AdminApi.cpp
  AttachmentApi.cpp
  BackgroundTaskApi.cpp
  BarcodeApi.cpp
  BomApi.cpp
  BuildApi.cpp
  CompanyApi.cpp
  ContenttypeApi.cpp
  CurrencyApi.cpp
  DataOutputApi.cpp
  DefaultApi.cpp
  EmailApi.cpp
  ErrorReportApi.cpp
  FlagsApi.cpp
  GenerateApi.cpp
  GenericApi.cpp
  IconsApi.cpp
  ImporterApi.cpp
  LabelApi.cpp
  LicenseApi.cpp
  LocateApi.cpp
  MachineApi.cpp
  MetadataApi.cpp
  NewsApi.cpp
  NotesImageUploadApi.cpp
  NotificationsApi.cpp
  OrderApi.cpp
  ParameterApi.cpp
  PartApi.cpp
  PluginsApi.cpp
  ProjectCodeApi.cpp
  ReportApi.cpp
  SearchApi.cpp
  SelectionApi.cpp
  SettingsApi.cpp
  StockApi.cpp
  SupplierApi.cpp
  SystemApi.cpp
  UnitsApi.cpp
  UserApi.cpp
  VersionApi.cpp
  VersionTextApi.cpp
  WebhookApi.cpp
  Helpers.cpp
  HttpRequest.cpp
  HttpFileElement.cpp
  Oauth.cpp
  )

target_include_directories(${PROJECT_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        Qt${QT_VERSION_MAJOR}::Core
        Qt${QT_VERSION_MAJOR}::Network
        Qt${QT_VERSION_MAJOR}::Gui

)

configure_package_config_file(${CMAKE_CURRENT_SOURCE_DIR}/Config.cmake.in
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(
    TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}"
)

install(
    FILES ${HEADER_FILES}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)

install(
    EXPORT ${PROJECT_NAME}Targets
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)
