cmake_minimum_required(VERSION 3.5)

project(QtOpenAPIClient)

set(CMAKE_AUTOMOC ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Network Gui)

include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

add_library(${PROJECT_NAME}
  APISearchView.h
  AcceptOverallocatedEnum.h
  ActionPlugin.h
  Address.h
  AddressBrief.h
  BOMReport.h
  BOMValidate.h
  Barcode.h
  BarcodeAssign.h
  BarcodePOAllocate.h
  BarcodePOReceive.h
  BarcodeSOAllocate.h
  BarcodeUnassign.h
  BlankEnum.h
  BomImportExtract.h
  BomImportSubmit.h
  BomImportUpload.h
  BomItem.h
  BomItemSubstitute.h
  BomItemValidation.h
  Build.h
  BuildAllocation.h
  BuildAllocationItem.h
  BuildAttachment.h
  BuildAutoAllocation.h
  BuildCancel.h
  BuildComplete.h
  BuildItem.h
  BuildLine.h
  BuildLineLabel.h
  BuildOutput.h
  BuildOutputComplete.h
  BuildOutputCreate.h
  BuildOutputDelete.h
  BuildOutputQuantity.h
  BuildOutputScrap.h
  BuildReport.h
  BuildStatusEnum.h
  BuildUnallocation.h
  Category.h
  CategoryParameterTemplate.h
  CategoryTree.h
  Company.h
  CompanyAttachment.h
  CompanyBrief.h
  ConfigTypeEnum.h
  Contact.h
  ConvertStockItem.h
  CustomUnit.h
  EmailAddress.h
  ErrorMessage.h
  ExendedUser.h
  FailedTask.h
  GetSimpleLogin.h
  GlobalSettings.h
  Group.h
  InstallStockItem.h
  Link.h
  LocatePlugin.h
  Location.h
  LocationBrief.h
  LocationTree.h
  Login.h
  MachineConfig.h
  MachineConfigCreate.h
  MachineDriver.h
  MachineRegistryError.h
  MachineRegistryStatus.h
  MachineRestart.h
  MachineSetting.h
  MachineType.h
  ManufacturerPart.h
  ManufacturerPartAttachment.h
  ManufacturerPartParameter.h
  NewsFeedEntry.h
  NotesImage.h
  NotificationMessage.h
  NotificationUserSetting.h
  NullEnum.h
  OutcomeEnum.h
  Owner.h
  PaginatedAddressList.h
  PaginatedBOMReportList.h
  PaginatedBomItemList.h
  PaginatedBomItemSubstituteList.h
  PaginatedBuildAttachmentList.h
  PaginatedBuildItemList.h
  PaginatedBuildLineLabelList.h
  PaginatedBuildLineList.h
  PaginatedBuildList.h
  PaginatedBuildReportList.h
  PaginatedCategoryList.h
  PaginatedCategoryParameterTemplateList.h
  PaginatedCategoryTreeList.h
  PaginatedCompanyAttachmentList.h
  PaginatedCompanyList.h
  PaginatedContactList.h
  PaginatedCustomUnitList.h
  PaginatedEmailAddressList.h
  PaginatedErrorMessageList.h
  PaginatedFailedTaskList.h
  PaginatedGlobalSettingsList.h
  PaginatedGroupList.h
  PaginatedLocationList.h
  PaginatedLocationTreeList.h
  PaginatedMachineConfigList.h
  PaginatedManufacturerPartAttachmentList.h
  PaginatedManufacturerPartList.h
  PaginatedManufacturerPartParameterList.h
  PaginatedNewsFeedEntryList.h
  PaginatedNotesImageList.h
  PaginatedNotificationMessageList.h
  PaginatedNotificationUserSettingList.h
  PaginatedOwnerList.h
  PaginatedPartAttachmentList.h
  PaginatedPartInternalPriceList.h
  PaginatedPartLabelList.h
  PaginatedPartList.h
  PaginatedPartParameterList.h
  PaginatedPartParameterTemplateList.h
  PaginatedPartRelationList.h
  PaginatedPartSalePriceList.h
  PaginatedPartStocktakeList.h
  PaginatedPartStocktakeReportList.h
  PaginatedPartTestTemplateList.h
  PaginatedPartThumbList.h
  PaginatedPendingTaskList.h
  PaginatedPluginConfigList.h
  PaginatedPluginSettingList.h
  PaginatedProjectCodeList.h
  PaginatedPurchaseOrderAttachmentList.h
  PaginatedPurchaseOrderExtraLineList.h
  PaginatedPurchaseOrderLineItemList.h
  PaginatedPurchaseOrderList.h
  PaginatedPurchaseOrderReportList.h
  PaginatedReportAssetList.h
  PaginatedReportSnippetList.h
  PaginatedReturnOrderAttachmentList.h
  PaginatedReturnOrderExtraLineList.h
  PaginatedReturnOrderLineItemList.h
  PaginatedReturnOrderList.h
  PaginatedReturnOrderReportList.h
  PaginatedSalesOrderAllocationList.h
  PaginatedSalesOrderAttachmentList.h
  PaginatedSalesOrderExtraLineList.h
  PaginatedSalesOrderLineItemList.h
  PaginatedSalesOrderList.h
  PaginatedSalesOrderReportList.h
  PaginatedSalesOrderShipmentList.h
  PaginatedScheduledTaskList.h
  PaginatedSocialAccountList.h
  PaginatedSocialProviderListResponseList.h
  PaginatedStockItemAttachmentList.h
  PaginatedStockItemLabelList.h
  PaginatedStockItemList.h
  PaginatedStockLocationLabelList.h
  PaginatedStockLocationReportList.h
  PaginatedStockLocationTypeList.h
  PaginatedStockTrackingList.h
  PaginatedSupplierPartList.h
  PaginatedSupplierPriceBreakList.h
  PaginatedTemplateList.h
  PaginatedTestReportList.h
  PaginatedUserCreateList.h
  PaginatedUserSettingsList.h
  PaginatedVersionInformationList.h
  Part.h
  PartAttachment.h
  PartBrief.h
  PartCopyBOM.h
  PartInternalPrice.h
  PartLabel.h
  PartParameter.h
  PartParameterTemplate.h
  PartPricing.h
  PartRelation.h
  PartSalePrice.h
  PartSetCategory.h
  PartStocktake.h
  PartStocktakeReport.h
  PartStocktakeReportGenerate.h
  PartTestTemplate.h
  PartThumb.h
  PartThumbSerializerUpdate.h
  PasswordChange.h
  PasswordReset.h
  PasswordResetConfirm.h
  PatchedAddress.h
  PatchedBOMReport.h
  PatchedBOMValidate.h
  PatchedBomItem.h
  PatchedBomItemSubstitute.h
  PatchedBomItemValidation.h
  PatchedBuild.h
  PatchedBuildAttachment.h
  PatchedBuildItem.h
  PatchedBuildLine.h
  PatchedBuildLineLabel.h
  PatchedBuildReport.h
  PatchedCategory.h
  PatchedCategoryParameterTemplate.h
  PatchedCompany.h
  PatchedCompanyAttachment.h
  PatchedContact.h
  PatchedCustomUnit.h
  PatchedErrorMessage.h
  PatchedExendedUser.h
  PatchedGlobalSettings.h
  PatchedGroup.h
  PatchedLocation.h
  PatchedMachineConfig.h
  PatchedMachineSetting.h
  PatchedManufacturerPart.h
  PatchedManufacturerPartAttachment.h
  PatchedManufacturerPartParameter.h
  PatchedNewsFeedEntry.h
  PatchedNotificationMessage.h
  PatchedNotificationUserSetting.h
  PatchedPart.h
  PatchedPartAttachment.h
  PatchedPartInternalPrice.h
  PatchedPartLabel.h
  PatchedPartParameter.h
  PatchedPartParameterTemplate.h
  PatchedPartPricing.h
  PatchedPartRelation.h
  PatchedPartSalePrice.h
  PatchedPartStocktake.h
  PatchedPartTestTemplate.h
  PatchedPartThumbSerializerUpdate.h
  PatchedPluginActivate.h
  PatchedPluginConfig.h
  PatchedPluginSetting.h
  PatchedPluginUninstall.h
  PatchedProjectCode.h
  PatchedPurchaseOrder.h
  PatchedPurchaseOrderAttachment.h
  PatchedPurchaseOrderExtraLine.h
  PatchedPurchaseOrderLineItem.h
  PatchedPurchaseOrderReport.h
  PatchedPurchaseOrder_order_currency.h
  PatchedReportAsset.h
  PatchedReportSnippet.h
  PatchedReturnOrder.h
  PatchedReturnOrderAttachment.h
  PatchedReturnOrderExtraLine.h
  PatchedReturnOrderLineItem.h
  PatchedReturnOrderReport.h
  PatchedSalesOrder.h
  PatchedSalesOrderAllocation.h
  PatchedSalesOrderAttachment.h
  PatchedSalesOrderExtraLine.h
  PatchedSalesOrderLineItem.h
  PatchedSalesOrderReport.h
  PatchedSalesOrderShipment.h
  PatchedStockItem.h
  PatchedStockItemAttachment.h
  PatchedStockItemLabel.h
  PatchedStockItemTestResult.h
  PatchedStockLocationLabel.h
  PatchedStockLocationReport.h
  PatchedStockLocationType.h
  PatchedSupplierPart.h
  PatchedSupplierPriceBreak.h
  PatchedTemplate.h
  PatchedTestReport.h
  PatchedUserDetails.h
  PatchedUserSettings.h
  PendingTask.h
  PluginActivate.h
  PluginConfig.h
  PluginConfigInstall.h
  PluginRegistryError.h
  PluginRegistryStatus.h
  PluginReload.h
  PluginSetting.h
  PluginUninstall.h
  Preferred.h
  PreferredMethodEnum.h
  ProjectCode.h
  PurchaseOrder.h
  PurchaseOrderAttachment.h
  PurchaseOrderComplete.h
  PurchaseOrderExtraLine.h
  PurchaseOrderLineItem.h
  PurchaseOrderLineItemReceive.h
  PurchaseOrderReceive.h
  PurchaseOrderReport.h
  Register.h
  ReportAsset.h
  ReportSnippet.h
  ResendEmailVerification.h
  RestAuthDetail.h
  ReturnOrder.h
  ReturnOrderAttachment.h
  ReturnOrderExtraLine.h
  ReturnOrderLineItem.h
  ReturnOrderLineItemReceive.h
  ReturnOrderReceive.h
  ReturnOrderReport.h
  ReturnStockItem.h
  SalePriceCurrencyEnum.h
  SalesOrder.h
  SalesOrderAllocation.h
  SalesOrderAttachment.h
  SalesOrderComplete.h
  SalesOrderExtraLine.h
  SalesOrderLineItem.h
  SalesOrderReport.h
  SalesOrderSerialAllocation.h
  SalesOrderShipment.h
  SalesOrderShipmentAllocation.h
  SalesOrderShipmentAllocationItem.h
  SalesOrderShipmentComplete.h
  ScheduleTypeEnum.h
  ScheduledTask.h
  SerializeStockItem.h
  SocialAccount.h
  SocialConnect.h
  SocialProvider.h
  SocialProviderListResponse.h
  Status2a7Enum.h
  StockAdd.h
  StockAdjustmentItem.h
  StockAdjustmentItem_status.h
  StockAssignment.h
  StockAssignmentItem.h
  StockChangeStatus.h
  StockCount.h
  StockItem.h
  StockItemAttachment.h
  StockItemLabel.h
  StockItemSerializerBrief.h
  StockItemTestResult.h
  StockLocationLabel.h
  StockLocationReport.h
  StockLocationType.h
  StockMerge.h
  StockMergeItem.h
  StockRemove.h
  StockTracking.h
  StockTransfer.h
  SupplierPart.h
  SupplierPriceBreak.h
  Template.h
  TestReport.h
  Token.h
  UninstallStockItem.h
  User.h
  UserCreate.h
  UserDetails.h
  UserSettings.h
  VerifyEmail.h
  Version.h
  VersionInformation.h
  VersionView.h
  ActionApi.h
  AdminApi.h
  AuthApi.h
  BackgroundTaskApi.h
  BarcodeApi.h
  BomApi.h
  BuildApi.h
  CompanyApi.h
  CurrencyApi.h
  EmailApi.h
  ErrorReportApi.h
  FlagsApi.h
  GenericApi.h
  LabelApi.h
  LocateApi.h
  MachineApi.h
  NewsApi.h
  NotesImageUploadApi.h
  NotificationsApi.h
  OrderApi.h
  PartApi.h
  PluginApi.h
  PluginsApi.h
  ProjectCodeApi.h
  ReportApi.h
  SearchApi.h
  SettingsApi.h
  StockApi.h
  UnitsApi.h
  UserApi.h
  VersionApi.h
  VersionTextApi.h
  WebApi.h
  WebhookApi.h
  Helpers.h
  HttpRequest.h
  Object.h
  Enum.h
  HttpFileElement.h
  ServerConfiguration.h
  ServerVariable.h
  Oauth.h
  APISearchView.cpp
  AcceptOverallocatedEnum.cpp
  ActionPlugin.cpp
  Address.cpp
  AddressBrief.cpp
  BOMReport.cpp
  BOMValidate.cpp
  Barcode.cpp
  BarcodeAssign.cpp
  BarcodePOAllocate.cpp
  BarcodePOReceive.cpp
  BarcodeSOAllocate.cpp
  BarcodeUnassign.cpp
  BlankEnum.cpp
  BomImportExtract.cpp
  BomImportSubmit.cpp
  BomImportUpload.cpp
  BomItem.cpp
  BomItemSubstitute.cpp
  BomItemValidation.cpp
  Build.cpp
  BuildAllocation.cpp
  BuildAllocationItem.cpp
  BuildAttachment.cpp
  BuildAutoAllocation.cpp
  BuildCancel.cpp
  BuildComplete.cpp
  BuildItem.cpp
  BuildLine.cpp
  BuildLineLabel.cpp
  BuildOutput.cpp
  BuildOutputComplete.cpp
  BuildOutputCreate.cpp
  BuildOutputDelete.cpp
  BuildOutputQuantity.cpp
  BuildOutputScrap.cpp
  BuildReport.cpp
  BuildStatusEnum.cpp
  BuildUnallocation.cpp
  Category.cpp
  CategoryParameterTemplate.cpp
  CategoryTree.cpp
  Company.cpp
  CompanyAttachment.cpp
  CompanyBrief.cpp
  ConfigTypeEnum.cpp
  Contact.cpp
  ConvertStockItem.cpp
  CustomUnit.cpp
  EmailAddress.cpp
  ErrorMessage.cpp
  ExendedUser.cpp
  FailedTask.cpp
  GetSimpleLogin.cpp
  GlobalSettings.cpp
  Group.cpp
  InstallStockItem.cpp
  Link.cpp
  LocatePlugin.cpp
  Location.cpp
  LocationBrief.cpp
  LocationTree.cpp
  Login.cpp
  MachineConfig.cpp
  MachineConfigCreate.cpp
  MachineDriver.cpp
  MachineRegistryError.cpp
  MachineRegistryStatus.cpp
  MachineRestart.cpp
  MachineSetting.cpp
  MachineType.cpp
  ManufacturerPart.cpp
  ManufacturerPartAttachment.cpp
  ManufacturerPartParameter.cpp
  NewsFeedEntry.cpp
  NotesImage.cpp
  NotificationMessage.cpp
  NotificationUserSetting.cpp
  NullEnum.cpp
  OutcomeEnum.cpp
  Owner.cpp
  PaginatedAddressList.cpp
  PaginatedBOMReportList.cpp
  PaginatedBomItemList.cpp
  PaginatedBomItemSubstituteList.cpp
  PaginatedBuildAttachmentList.cpp
  PaginatedBuildItemList.cpp
  PaginatedBuildLineLabelList.cpp
  PaginatedBuildLineList.cpp
  PaginatedBuildList.cpp
  PaginatedBuildReportList.cpp
  PaginatedCategoryList.cpp
  PaginatedCategoryParameterTemplateList.cpp
  PaginatedCategoryTreeList.cpp
  PaginatedCompanyAttachmentList.cpp
  PaginatedCompanyList.cpp
  PaginatedContactList.cpp
  PaginatedCustomUnitList.cpp
  PaginatedEmailAddressList.cpp
  PaginatedErrorMessageList.cpp
  PaginatedFailedTaskList.cpp
  PaginatedGlobalSettingsList.cpp
  PaginatedGroupList.cpp
  PaginatedLocationList.cpp
  PaginatedLocationTreeList.cpp
  PaginatedMachineConfigList.cpp
  PaginatedManufacturerPartAttachmentList.cpp
  PaginatedManufacturerPartList.cpp
  PaginatedManufacturerPartParameterList.cpp
  PaginatedNewsFeedEntryList.cpp
  PaginatedNotesImageList.cpp
  PaginatedNotificationMessageList.cpp
  PaginatedNotificationUserSettingList.cpp
  PaginatedOwnerList.cpp
  PaginatedPartAttachmentList.cpp
  PaginatedPartInternalPriceList.cpp
  PaginatedPartLabelList.cpp
  PaginatedPartList.cpp
  PaginatedPartParameterList.cpp
  PaginatedPartParameterTemplateList.cpp
  PaginatedPartRelationList.cpp
  PaginatedPartSalePriceList.cpp
  PaginatedPartStocktakeList.cpp
  PaginatedPartStocktakeReportList.cpp
  PaginatedPartTestTemplateList.cpp
  PaginatedPartThumbList.cpp
  PaginatedPendingTaskList.cpp
  PaginatedPluginConfigList.cpp
  PaginatedPluginSettingList.cpp
  PaginatedProjectCodeList.cpp
  PaginatedPurchaseOrderAttachmentList.cpp
  PaginatedPurchaseOrderExtraLineList.cpp
  PaginatedPurchaseOrderLineItemList.cpp
  PaginatedPurchaseOrderList.cpp
  PaginatedPurchaseOrderReportList.cpp
  PaginatedReportAssetList.cpp
  PaginatedReportSnippetList.cpp
  PaginatedReturnOrderAttachmentList.cpp
  PaginatedReturnOrderExtraLineList.cpp
  PaginatedReturnOrderLineItemList.cpp
  PaginatedReturnOrderList.cpp
  PaginatedReturnOrderReportList.cpp
  PaginatedSalesOrderAllocationList.cpp
  PaginatedSalesOrderAttachmentList.cpp
  PaginatedSalesOrderExtraLineList.cpp
  PaginatedSalesOrderLineItemList.cpp
  PaginatedSalesOrderList.cpp
  PaginatedSalesOrderReportList.cpp
  PaginatedSalesOrderShipmentList.cpp
  PaginatedScheduledTaskList.cpp
  PaginatedSocialAccountList.cpp
  PaginatedSocialProviderListResponseList.cpp
  PaginatedStockItemAttachmentList.cpp
  PaginatedStockItemLabelList.cpp
  PaginatedStockItemList.cpp
  PaginatedStockLocationLabelList.cpp
  PaginatedStockLocationReportList.cpp
  PaginatedStockLocationTypeList.cpp
  PaginatedStockTrackingList.cpp
  PaginatedSupplierPartList.cpp
  PaginatedSupplierPriceBreakList.cpp
  PaginatedTemplateList.cpp
  PaginatedTestReportList.cpp
  PaginatedUserCreateList.cpp
  PaginatedUserSettingsList.cpp
  PaginatedVersionInformationList.cpp
  Part.cpp
  PartAttachment.cpp
  PartBrief.cpp
  PartCopyBOM.cpp
  PartInternalPrice.cpp
  PartLabel.cpp
  PartParameter.cpp
  PartParameterTemplate.cpp
  PartPricing.cpp
  PartRelation.cpp
  PartSalePrice.cpp
  PartSetCategory.cpp
  PartStocktake.cpp
  PartStocktakeReport.cpp
  PartStocktakeReportGenerate.cpp
  PartTestTemplate.cpp
  PartThumb.cpp
  PartThumbSerializerUpdate.cpp
  PasswordChange.cpp
  PasswordReset.cpp
  PasswordResetConfirm.cpp
  PatchedAddress.cpp
  PatchedBOMReport.cpp
  PatchedBOMValidate.cpp
  PatchedBomItem.cpp
  PatchedBomItemSubstitute.cpp
  PatchedBomItemValidation.cpp
  PatchedBuild.cpp
  PatchedBuildAttachment.cpp
  PatchedBuildItem.cpp
  PatchedBuildLine.cpp
  PatchedBuildLineLabel.cpp
  PatchedBuildReport.cpp
  PatchedCategory.cpp
  PatchedCategoryParameterTemplate.cpp
  PatchedCompany.cpp
  PatchedCompanyAttachment.cpp
  PatchedContact.cpp
  PatchedCustomUnit.cpp
  PatchedErrorMessage.cpp
  PatchedExendedUser.cpp
  PatchedGlobalSettings.cpp
  PatchedGroup.cpp
  PatchedLocation.cpp
  PatchedMachineConfig.cpp
  PatchedMachineSetting.cpp
  PatchedManufacturerPart.cpp
  PatchedManufacturerPartAttachment.cpp
  PatchedManufacturerPartParameter.cpp
  PatchedNewsFeedEntry.cpp
  PatchedNotificationMessage.cpp
  PatchedNotificationUserSetting.cpp
  PatchedPart.cpp
  PatchedPartAttachment.cpp
  PatchedPartInternalPrice.cpp
  PatchedPartLabel.cpp
  PatchedPartParameter.cpp
  PatchedPartParameterTemplate.cpp
  PatchedPartPricing.cpp
  PatchedPartRelation.cpp
  PatchedPartSalePrice.cpp
  PatchedPartStocktake.cpp
  PatchedPartTestTemplate.cpp
  PatchedPartThumbSerializerUpdate.cpp
  PatchedPluginActivate.cpp
  PatchedPluginConfig.cpp
  PatchedPluginSetting.cpp
  PatchedPluginUninstall.cpp
  PatchedProjectCode.cpp
  PatchedPurchaseOrder.cpp
  PatchedPurchaseOrderAttachment.cpp
  PatchedPurchaseOrderExtraLine.cpp
  PatchedPurchaseOrderLineItem.cpp
  PatchedPurchaseOrderReport.cpp
  PatchedPurchaseOrder_order_currency.cpp
  PatchedReportAsset.cpp
  PatchedReportSnippet.cpp
  PatchedReturnOrder.cpp
  PatchedReturnOrderAttachment.cpp
  PatchedReturnOrderExtraLine.cpp
  PatchedReturnOrderLineItem.cpp
  PatchedReturnOrderReport.cpp
  PatchedSalesOrder.cpp
  PatchedSalesOrderAllocation.cpp
  PatchedSalesOrderAttachment.cpp
  PatchedSalesOrderExtraLine.cpp
  PatchedSalesOrderLineItem.cpp
  PatchedSalesOrderReport.cpp
  PatchedSalesOrderShipment.cpp
  PatchedStockItem.cpp
  PatchedStockItemAttachment.cpp
  PatchedStockItemLabel.cpp
  PatchedStockItemTestResult.cpp
  PatchedStockLocationLabel.cpp
  PatchedStockLocationReport.cpp
  PatchedStockLocationType.cpp
  PatchedSupplierPart.cpp
  PatchedSupplierPriceBreak.cpp
  PatchedTemplate.cpp
  PatchedTestReport.cpp
  PatchedUserDetails.cpp
  PatchedUserSettings.cpp
  PendingTask.cpp
  PluginActivate.cpp
  PluginConfig.cpp
  PluginConfigInstall.cpp
  PluginRegistryError.cpp
  PluginRegistryStatus.cpp
  PluginReload.cpp
  PluginSetting.cpp
  PluginUninstall.cpp
  Preferred.cpp
  PreferredMethodEnum.cpp
  ProjectCode.cpp
  PurchaseOrder.cpp
  PurchaseOrderAttachment.cpp
  PurchaseOrderComplete.cpp
  PurchaseOrderExtraLine.cpp
  PurchaseOrderLineItem.cpp
  PurchaseOrderLineItemReceive.cpp
  PurchaseOrderReceive.cpp
  PurchaseOrderReport.cpp
  Register.cpp
  ReportAsset.cpp
  ReportSnippet.cpp
  ResendEmailVerification.cpp
  RestAuthDetail.cpp
  ReturnOrder.cpp
  ReturnOrderAttachment.cpp
  ReturnOrderExtraLine.cpp
  ReturnOrderLineItem.cpp
  ReturnOrderLineItemReceive.cpp
  ReturnOrderReceive.cpp
  ReturnOrderReport.cpp
  ReturnStockItem.cpp
  SalePriceCurrencyEnum.cpp
  SalesOrder.cpp
  SalesOrderAllocation.cpp
  SalesOrderAttachment.cpp
  SalesOrderComplete.cpp
  SalesOrderExtraLine.cpp
  SalesOrderLineItem.cpp
  SalesOrderReport.cpp
  SalesOrderSerialAllocation.cpp
  SalesOrderShipment.cpp
  SalesOrderShipmentAllocation.cpp
  SalesOrderShipmentAllocationItem.cpp
  SalesOrderShipmentComplete.cpp
  ScheduleTypeEnum.cpp
  ScheduledTask.cpp
  SerializeStockItem.cpp
  SocialAccount.cpp
  SocialConnect.cpp
  SocialProvider.cpp
  SocialProviderListResponse.cpp
  Status2a7Enum.cpp
  StockAdd.cpp
  StockAdjustmentItem.cpp
  StockAdjustmentItem_status.cpp
  StockAssignment.cpp
  StockAssignmentItem.cpp
  StockChangeStatus.cpp
  StockCount.cpp
  StockItem.cpp
  StockItemAttachment.cpp
  StockItemLabel.cpp
  StockItemSerializerBrief.cpp
  StockItemTestResult.cpp
  StockLocationLabel.cpp
  StockLocationReport.cpp
  StockLocationType.cpp
  StockMerge.cpp
  StockMergeItem.cpp
  StockRemove.cpp
  StockTracking.cpp
  StockTransfer.cpp
  SupplierPart.cpp
  SupplierPriceBreak.cpp
  Template.cpp
  TestReport.cpp
  Token.cpp
  UninstallStockItem.cpp
  User.cpp
  UserCreate.cpp
  UserDetails.cpp
  UserSettings.cpp
  VerifyEmail.cpp
  Version.cpp
  VersionInformation.cpp
  VersionView.cpp
  ActionApi.cpp
  AdminApi.cpp
  AuthApi.cpp
  BackgroundTaskApi.cpp
  BarcodeApi.cpp
  BomApi.cpp
  BuildApi.cpp
  CompanyApi.cpp
  CurrencyApi.cpp
  EmailApi.cpp
  ErrorReportApi.cpp
  FlagsApi.cpp
  GenericApi.cpp
  LabelApi.cpp
  LocateApi.cpp
  MachineApi.cpp
  NewsApi.cpp
  NotesImageUploadApi.cpp
  NotificationsApi.cpp
  OrderApi.cpp
  PartApi.cpp
  PluginApi.cpp
  PluginsApi.cpp
  ProjectCodeApi.cpp
  ReportApi.cpp
  SearchApi.cpp
  SettingsApi.cpp
  StockApi.cpp
  UnitsApi.cpp
  UserApi.cpp
  VersionApi.cpp
  VersionTextApi.cpp
  WebApi.cpp
  WebhookApi.cpp
  Helpers.cpp
  HttpRequest.cpp
  HttpFileElement.cpp
  Oauth.cpp
  )

target_include_directories(${PROJECT_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        Qt${QT_VERSION_MAJOR}::Core
        Qt${QT_VERSION_MAJOR}::Network
        Qt${QT_VERSION_MAJOR}::Gui

)

configure_package_config_file(${CMAKE_CURRENT_SOURCE_DIR}/Config.cmake.in
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(
    TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}"
)

install(
    FILES ${HEADER_FILES}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)

install(
    EXPORT ${PROJECT_NAME}Targets
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)
