cmake_minimum_required(VERSION 3.5)

project(QtOpenAPIClient)

set(CMAKE_AUTOMOC ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Network Gui)

include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

add_library(${PROJECT_NAME}
  APISearchView.h
  AcceptOverallocatedEnum.h
  ActionPlugin.h
  Address.h
  AddressBrief.h
  Attachment.h
  AttachmentModelTypeEnum.h
  BOMValidate.h
  Barcode.h
  BarcodeAssign.h
  BarcodePOAllocate.h
  BarcodePOReceive.h
  BarcodeSOAllocate.h
  BarcodeUnassign.h
  BlankEnum.h
  BomImportExtract.h
  BomImportSubmit.h
  BomImportUpload.h
  BomItem.h
  BomItemSubstitute.h
  BomItemValidation.h
  Build.h
  BuildAllocation.h
  BuildAllocationItem.h
  BuildAutoAllocation.h
  BuildCancel.h
  BuildComplete.h
  BuildItem.h
  BuildLine.h
  BuildOutput.h
  BuildOutputComplete.h
  BuildOutputCreate.h
  BuildOutputDelete.h
  BuildOutputQuantity.h
  BuildOutputScrap.h
  BuildStatusEnum.h
  BuildUnallocation.h
  Category.h
  CategoryParameterTemplate.h
  CategoryTree.h
  Company.h
  CompanyBrief.h
  ConfigTypeEnum.h
  Contact.h
  ContentType.h
  ConvertStockItem.h
  CurrencyExchange.h
  CustomUnit.h
  DataImportAcceptRow.h
  DataImportColumnMap.h
  DataImportRow.h
  DataImportSession.h
  DataImportSessionModelTypeEnum.h
  DataImportSessionStatusEnum.h
  EmailAddress.h
  ErrorMessage.h
  ExendedUser.h
  FailedTask.h
  GenerateBatchCode.h
  GenerateSerialNumber.h
  GetSimpleLogin.h
  GlobalSettings.h
  Group.h
  InstallStockItem.h
  LabelOutput.h
  LabelPrint.h
  LabelTemplate.h
  LicenseView.h
  Link.h
  LocatePlugin.h
  Location.h
  LocationBrief.h
  LocationTree.h
  Login.h
  MachineConfig.h
  MachineConfigCreate.h
  MachineDriver.h
  MachineRegistryError.h
  MachineRegistryStatus.h
  MachineRestart.h
  MachineSetting.h
  MachineType.h
  ManufacturerPart.h
  ManufacturerPartParameter.h
  ModelType972Enum.h
  NewsFeedEntry.h
  NotesImage.h
  NotificationMessage.h
  NotificationUserSetting.h
  NullEnum.h
  OutcomeEnum.h
  Owner.h
  PageSizeEnum.h
  PaginatedAddressList.h
  PaginatedAttachmentList.h
  PaginatedBomItemList.h
  PaginatedBomItemSubstituteList.h
  PaginatedBuildItemList.h
  PaginatedBuildLineList.h
  PaginatedBuildList.h
  PaginatedCategoryList.h
  PaginatedCategoryParameterTemplateList.h
  PaginatedCategoryTreeList.h
  PaginatedCompanyList.h
  PaginatedContactList.h
  PaginatedContentTypeList.h
  PaginatedCustomUnitList.h
  PaginatedDataImportColumnMapList.h
  PaginatedDataImportRowList.h
  PaginatedDataImportSessionList.h
  PaginatedEmailAddressList.h
  PaginatedErrorMessageList.h
  PaginatedFailedTaskList.h
  PaginatedGlobalSettingsList.h
  PaginatedGroupList.h
  PaginatedLabelOutputList.h
  PaginatedLabelTemplateList.h
  PaginatedLocationList.h
  PaginatedLocationTreeList.h
  PaginatedMachineConfigList.h
  PaginatedManufacturerPartList.h
  PaginatedManufacturerPartParameterList.h
  PaginatedNewsFeedEntryList.h
  PaginatedNotesImageList.h
  PaginatedNotificationMessageList.h
  PaginatedNotificationUserSettingList.h
  PaginatedOwnerList.h
  PaginatedPartInternalPriceList.h
  PaginatedPartList.h
  PaginatedPartParameterList.h
  PaginatedPartParameterTemplateList.h
  PaginatedPartRelationList.h
  PaginatedPartSalePriceList.h
  PaginatedPartStocktakeList.h
  PaginatedPartStocktakeReportList.h
  PaginatedPartTestTemplateList.h
  PaginatedPartThumbList.h
  PaginatedPendingTaskList.h
  PaginatedPluginConfigList.h
  PaginatedPluginSettingList.h
  PaginatedProjectCodeList.h
  PaginatedPurchaseOrderExtraLineList.h
  PaginatedPurchaseOrderLineItemList.h
  PaginatedPurchaseOrderList.h
  PaginatedReportAssetList.h
  PaginatedReportOutputList.h
  PaginatedReportSnippetList.h
  PaginatedReportTemplateList.h
  PaginatedReturnOrderExtraLineList.h
  PaginatedReturnOrderLineItemList.h
  PaginatedReturnOrderList.h
  PaginatedSalesOrderAllocationList.h
  PaginatedSalesOrderExtraLineList.h
  PaginatedSalesOrderLineItemList.h
  PaginatedSalesOrderList.h
  PaginatedSalesOrderShipmentList.h
  PaginatedScheduledTaskList.h
  PaginatedSocialAccountList.h
  PaginatedSocialProviderListResponseList.h
  PaginatedStockItemList.h
  PaginatedStockItemTestResultList.h
  PaginatedStockLocationTypeList.h
  PaginatedStockTrackingList.h
  PaginatedSupplierPartList.h
  PaginatedSupplierPriceBreakList.h
  PaginatedUserCreateList.h
  PaginatedUserSettingsList.h
  PaginatedVersionInformationList.h
  Part.h
  PartBrief.h
  PartCopyBOM.h
  PartInternalPrice.h
  PartParameter.h
  PartParameterTemplate.h
  PartPricing.h
  PartRelation.h
  PartSalePrice.h
  PartSetCategory.h
  PartStocktake.h
  PartStocktakeReport.h
  PartStocktakeReportGenerate.h
  PartTestTemplate.h
  PartThumb.h
  PartThumbSerializerUpdate.h
  PasswordChange.h
  PasswordReset.h
  PasswordResetConfirm.h
  PatchedAddress.h
  PatchedAttachment.h
  PatchedBOMValidate.h
  PatchedBomItem.h
  PatchedBomItemSubstitute.h
  PatchedBomItemValidation.h
  PatchedBuild.h
  PatchedBuildItem.h
  PatchedBuildLine.h
  PatchedCategory.h
  PatchedCategoryParameterTemplate.h
  PatchedCompany.h
  PatchedContact.h
  PatchedCustomUnit.h
  PatchedDataImportColumnMap.h
  PatchedDataImportRow.h
  PatchedDataImportSession.h
  PatchedErrorMessage.h
  PatchedExendedUser.h
  PatchedGlobalSettings.h
  PatchedGroup.h
  PatchedLabelTemplate.h
  PatchedLocation.h
  PatchedMachineConfig.h
  PatchedMachineSetting.h
  PatchedManufacturerPart.h
  PatchedManufacturerPartParameter.h
  PatchedNewsFeedEntry.h
  PatchedNotificationMessage.h
  PatchedNotificationUserSetting.h
  PatchedPart.h
  PatchedPartInternalPrice.h
  PatchedPartParameter.h
  PatchedPartParameterTemplate.h
  PatchedPartPricing.h
  PatchedPartRelation.h
  PatchedPartSalePrice.h
  PatchedPartStocktake.h
  PatchedPartTestTemplate.h
  PatchedPartThumbSerializerUpdate.h
  PatchedPluginActivate.h
  PatchedPluginConfig.h
  PatchedPluginSetting.h
  PatchedPluginUninstall.h
  PatchedProjectCode.h
  PatchedPurchaseOrder.h
  PatchedPurchaseOrderExtraLine.h
  PatchedPurchaseOrderLineItem.h
  PatchedReportAsset.h
  PatchedReportSnippet.h
  PatchedReportTemplate.h
  PatchedReturnOrder.h
  PatchedReturnOrderExtraLine.h
  PatchedReturnOrderLineItem.h
  PatchedSalesOrder.h
  PatchedSalesOrderAllocation.h
  PatchedSalesOrderExtraLine.h
  PatchedSalesOrderLineItem.h
  PatchedSalesOrderShipment.h
  PatchedStockItem.h
  PatchedStockItemTestResult.h
  PatchedStockLocationType.h
  PatchedSupplierPart.h
  PatchedSupplierPriceBreak.h
  PatchedUserDetails.h
  PatchedUserSettings.h
  PendingTask.h
  PluginActivate.h
  PluginConfig.h
  PluginConfigInstall.h
  PluginRegistryError.h
  PluginRegistryStatus.h
  PluginReload.h
  PluginSetting.h
  PluginUninstall.h
  Preferred.h
  PreferredMethodEnum.h
  ProjectCode.h
  PurchaseOrder.h
  PurchaseOrderComplete.h
  PurchaseOrderExtraLine.h
  PurchaseOrderLineItem.h
  PurchaseOrderLineItemReceive.h
  PurchaseOrderReceive.h
  Register.h
  ReportAsset.h
  ReportOutput.h
  ReportPrint.h
  ReportSnippet.h
  ReportTemplate.h
  ResendEmailVerification.h
  RestAuthDetail.h
  ReturnOrder.h
  ReturnOrderExtraLine.h
  ReturnOrderLineItem.h
  ReturnOrderLineItemReceive.h
  ReturnOrderReceive.h
  ReturnStockItem.h
  Role.h
  SalePriceCurrencyEnum.h
  SalesOrder.h
  SalesOrderAllocation.h
  SalesOrderComplete.h
  SalesOrderExtraLine.h
  SalesOrderLineItem.h
  SalesOrderSerialAllocation.h
  SalesOrderShipment.h
  SalesOrderShipmentAllocation.h
  SalesOrderShipmentAllocationItem.h
  SalesOrderShipmentComplete.h
  ScheduleTypeEnum.h
  ScheduledTask.h
  SerializeStockItem.h
  SocialAccount.h
  SocialConnect.h
  SocialProvider.h
  SocialProviderListResponse.h
  Status2a7Enum.h
  StockAdd.h
  StockAdjustmentItem.h
  StockAdjustmentItem_status.h
  StockAssignment.h
  StockAssignmentItem.h
  StockChangeStatus.h
  StockCount.h
  StockItem.h
  StockItemSerializerBrief.h
  StockItemTestResult.h
  StockLocationType.h
  StockMerge.h
  StockMergeItem.h
  StockRemove.h
  StockTracking.h
  StockTransfer.h
  SupplierPart.h
  SupplierPriceBreak.h
  Token.h
  UninstallStockItem.h
  User.h
  UserCreate.h
  UserDetails.h
  UserSettings.h
  VerifyEmail.h
  Version.h
  VersionInformation.h
  VersionView.h
  ActionApi.h
  AdminApi.h
  AttachmentApi.h
  AuthApi.h
  BackgroundTaskApi.h
  BarcodeApi.h
  BomApi.h
  BuildApi.h
  CompanyApi.h
  ContenttypeApi.h
  CurrencyApi.h
  EmailApi.h
  ErrorReportApi.h
  FlagsApi.h
  GenerateApi.h
  GenericApi.h
  ImporterApi.h
  LabelApi.h
  LicenseApi.h
  LocateApi.h
  MachineApi.h
  NewsApi.h
  NotesImageUploadApi.h
  NotificationsApi.h
  OrderApi.h
  PartApi.h
  PluginsApi.h
  ProjectCodeApi.h
  ReportApi.h
  SearchApi.h
  SettingsApi.h
  StockApi.h
  UnitsApi.h
  UserApi.h
  VersionApi.h
  VersionTextApi.h
  WebApi.h
  WebhookApi.h
  Helpers.h
  HttpRequest.h
  Object.h
  Enum.h
  HttpFileElement.h
  ServerConfiguration.h
  ServerVariable.h
  Oauth.h
  APISearchView.cpp
  AcceptOverallocatedEnum.cpp
  ActionPlugin.cpp
  Address.cpp
  AddressBrief.cpp
  Attachment.cpp
  AttachmentModelTypeEnum.cpp
  BOMValidate.cpp
  Barcode.cpp
  BarcodeAssign.cpp
  BarcodePOAllocate.cpp
  BarcodePOReceive.cpp
  BarcodeSOAllocate.cpp
  BarcodeUnassign.cpp
  BlankEnum.cpp
  BomImportExtract.cpp
  BomImportSubmit.cpp
  BomImportUpload.cpp
  BomItem.cpp
  BomItemSubstitute.cpp
  BomItemValidation.cpp
  Build.cpp
  BuildAllocation.cpp
  BuildAllocationItem.cpp
  BuildAutoAllocation.cpp
  BuildCancel.cpp
  BuildComplete.cpp
  BuildItem.cpp
  BuildLine.cpp
  BuildOutput.cpp
  BuildOutputComplete.cpp
  BuildOutputCreate.cpp
  BuildOutputDelete.cpp
  BuildOutputQuantity.cpp
  BuildOutputScrap.cpp
  BuildStatusEnum.cpp
  BuildUnallocation.cpp
  Category.cpp
  CategoryParameterTemplate.cpp
  CategoryTree.cpp
  Company.cpp
  CompanyBrief.cpp
  ConfigTypeEnum.cpp
  Contact.cpp
  ContentType.cpp
  ConvertStockItem.cpp
  CurrencyExchange.cpp
  CustomUnit.cpp
  DataImportAcceptRow.cpp
  DataImportColumnMap.cpp
  DataImportRow.cpp
  DataImportSession.cpp
  DataImportSessionModelTypeEnum.cpp
  DataImportSessionStatusEnum.cpp
  EmailAddress.cpp
  ErrorMessage.cpp
  ExendedUser.cpp
  FailedTask.cpp
  GenerateBatchCode.cpp
  GenerateSerialNumber.cpp
  GetSimpleLogin.cpp
  GlobalSettings.cpp
  Group.cpp
  InstallStockItem.cpp
  LabelOutput.cpp
  LabelPrint.cpp
  LabelTemplate.cpp
  LicenseView.cpp
  Link.cpp
  LocatePlugin.cpp
  Location.cpp
  LocationBrief.cpp
  LocationTree.cpp
  Login.cpp
  MachineConfig.cpp
  MachineConfigCreate.cpp
  MachineDriver.cpp
  MachineRegistryError.cpp
  MachineRegistryStatus.cpp
  MachineRestart.cpp
  MachineSetting.cpp
  MachineType.cpp
  ManufacturerPart.cpp
  ManufacturerPartParameter.cpp
  ModelType972Enum.cpp
  NewsFeedEntry.cpp
  NotesImage.cpp
  NotificationMessage.cpp
  NotificationUserSetting.cpp
  NullEnum.cpp
  OutcomeEnum.cpp
  Owner.cpp
  PageSizeEnum.cpp
  PaginatedAddressList.cpp
  PaginatedAttachmentList.cpp
  PaginatedBomItemList.cpp
  PaginatedBomItemSubstituteList.cpp
  PaginatedBuildItemList.cpp
  PaginatedBuildLineList.cpp
  PaginatedBuildList.cpp
  PaginatedCategoryList.cpp
  PaginatedCategoryParameterTemplateList.cpp
  PaginatedCategoryTreeList.cpp
  PaginatedCompanyList.cpp
  PaginatedContactList.cpp
  PaginatedContentTypeList.cpp
  PaginatedCustomUnitList.cpp
  PaginatedDataImportColumnMapList.cpp
  PaginatedDataImportRowList.cpp
  PaginatedDataImportSessionList.cpp
  PaginatedEmailAddressList.cpp
  PaginatedErrorMessageList.cpp
  PaginatedFailedTaskList.cpp
  PaginatedGlobalSettingsList.cpp
  PaginatedGroupList.cpp
  PaginatedLabelOutputList.cpp
  PaginatedLabelTemplateList.cpp
  PaginatedLocationList.cpp
  PaginatedLocationTreeList.cpp
  PaginatedMachineConfigList.cpp
  PaginatedManufacturerPartList.cpp
  PaginatedManufacturerPartParameterList.cpp
  PaginatedNewsFeedEntryList.cpp
  PaginatedNotesImageList.cpp
  PaginatedNotificationMessageList.cpp
  PaginatedNotificationUserSettingList.cpp
  PaginatedOwnerList.cpp
  PaginatedPartInternalPriceList.cpp
  PaginatedPartList.cpp
  PaginatedPartParameterList.cpp
  PaginatedPartParameterTemplateList.cpp
  PaginatedPartRelationList.cpp
  PaginatedPartSalePriceList.cpp
  PaginatedPartStocktakeList.cpp
  PaginatedPartStocktakeReportList.cpp
  PaginatedPartTestTemplateList.cpp
  PaginatedPartThumbList.cpp
  PaginatedPendingTaskList.cpp
  PaginatedPluginConfigList.cpp
  PaginatedPluginSettingList.cpp
  PaginatedProjectCodeList.cpp
  PaginatedPurchaseOrderExtraLineList.cpp
  PaginatedPurchaseOrderLineItemList.cpp
  PaginatedPurchaseOrderList.cpp
  PaginatedReportAssetList.cpp
  PaginatedReportOutputList.cpp
  PaginatedReportSnippetList.cpp
  PaginatedReportTemplateList.cpp
  PaginatedReturnOrderExtraLineList.cpp
  PaginatedReturnOrderLineItemList.cpp
  PaginatedReturnOrderList.cpp
  PaginatedSalesOrderAllocationList.cpp
  PaginatedSalesOrderExtraLineList.cpp
  PaginatedSalesOrderLineItemList.cpp
  PaginatedSalesOrderList.cpp
  PaginatedSalesOrderShipmentList.cpp
  PaginatedScheduledTaskList.cpp
  PaginatedSocialAccountList.cpp
  PaginatedSocialProviderListResponseList.cpp
  PaginatedStockItemList.cpp
  PaginatedStockItemTestResultList.cpp
  PaginatedStockLocationTypeList.cpp
  PaginatedStockTrackingList.cpp
  PaginatedSupplierPartList.cpp
  PaginatedSupplierPriceBreakList.cpp
  PaginatedUserCreateList.cpp
  PaginatedUserSettingsList.cpp
  PaginatedVersionInformationList.cpp
  Part.cpp
  PartBrief.cpp
  PartCopyBOM.cpp
  PartInternalPrice.cpp
  PartParameter.cpp
  PartParameterTemplate.cpp
  PartPricing.cpp
  PartRelation.cpp
  PartSalePrice.cpp
  PartSetCategory.cpp
  PartStocktake.cpp
  PartStocktakeReport.cpp
  PartStocktakeReportGenerate.cpp
  PartTestTemplate.cpp
  PartThumb.cpp
  PartThumbSerializerUpdate.cpp
  PasswordChange.cpp
  PasswordReset.cpp
  PasswordResetConfirm.cpp
  PatchedAddress.cpp
  PatchedAttachment.cpp
  PatchedBOMValidate.cpp
  PatchedBomItem.cpp
  PatchedBomItemSubstitute.cpp
  PatchedBomItemValidation.cpp
  PatchedBuild.cpp
  PatchedBuildItem.cpp
  PatchedBuildLine.cpp
  PatchedCategory.cpp
  PatchedCategoryParameterTemplate.cpp
  PatchedCompany.cpp
  PatchedContact.cpp
  PatchedCustomUnit.cpp
  PatchedDataImportColumnMap.cpp
  PatchedDataImportRow.cpp
  PatchedDataImportSession.cpp
  PatchedErrorMessage.cpp
  PatchedExendedUser.cpp
  PatchedGlobalSettings.cpp
  PatchedGroup.cpp
  PatchedLabelTemplate.cpp
  PatchedLocation.cpp
  PatchedMachineConfig.cpp
  PatchedMachineSetting.cpp
  PatchedManufacturerPart.cpp
  PatchedManufacturerPartParameter.cpp
  PatchedNewsFeedEntry.cpp
  PatchedNotificationMessage.cpp
  PatchedNotificationUserSetting.cpp
  PatchedPart.cpp
  PatchedPartInternalPrice.cpp
  PatchedPartParameter.cpp
  PatchedPartParameterTemplate.cpp
  PatchedPartPricing.cpp
  PatchedPartRelation.cpp
  PatchedPartSalePrice.cpp
  PatchedPartStocktake.cpp
  PatchedPartTestTemplate.cpp
  PatchedPartThumbSerializerUpdate.cpp
  PatchedPluginActivate.cpp
  PatchedPluginConfig.cpp
  PatchedPluginSetting.cpp
  PatchedPluginUninstall.cpp
  PatchedProjectCode.cpp
  PatchedPurchaseOrder.cpp
  PatchedPurchaseOrderExtraLine.cpp
  PatchedPurchaseOrderLineItem.cpp
  PatchedReportAsset.cpp
  PatchedReportSnippet.cpp
  PatchedReportTemplate.cpp
  PatchedReturnOrder.cpp
  PatchedReturnOrderExtraLine.cpp
  PatchedReturnOrderLineItem.cpp
  PatchedSalesOrder.cpp
  PatchedSalesOrderAllocation.cpp
  PatchedSalesOrderExtraLine.cpp
  PatchedSalesOrderLineItem.cpp
  PatchedSalesOrderShipment.cpp
  PatchedStockItem.cpp
  PatchedStockItemTestResult.cpp
  PatchedStockLocationType.cpp
  PatchedSupplierPart.cpp
  PatchedSupplierPriceBreak.cpp
  PatchedUserDetails.cpp
  PatchedUserSettings.cpp
  PendingTask.cpp
  PluginActivate.cpp
  PluginConfig.cpp
  PluginConfigInstall.cpp
  PluginRegistryError.cpp
  PluginRegistryStatus.cpp
  PluginReload.cpp
  PluginSetting.cpp
  PluginUninstall.cpp
  Preferred.cpp
  PreferredMethodEnum.cpp
  ProjectCode.cpp
  PurchaseOrder.cpp
  PurchaseOrderComplete.cpp
  PurchaseOrderExtraLine.cpp
  PurchaseOrderLineItem.cpp
  PurchaseOrderLineItemReceive.cpp
  PurchaseOrderReceive.cpp
  Register.cpp
  ReportAsset.cpp
  ReportOutput.cpp
  ReportPrint.cpp
  ReportSnippet.cpp
  ReportTemplate.cpp
  ResendEmailVerification.cpp
  RestAuthDetail.cpp
  ReturnOrder.cpp
  ReturnOrderExtraLine.cpp
  ReturnOrderLineItem.cpp
  ReturnOrderLineItemReceive.cpp
  ReturnOrderReceive.cpp
  ReturnStockItem.cpp
  Role.cpp
  SalePriceCurrencyEnum.cpp
  SalesOrder.cpp
  SalesOrderAllocation.cpp
  SalesOrderComplete.cpp
  SalesOrderExtraLine.cpp
  SalesOrderLineItem.cpp
  SalesOrderSerialAllocation.cpp
  SalesOrderShipment.cpp
  SalesOrderShipmentAllocation.cpp
  SalesOrderShipmentAllocationItem.cpp
  SalesOrderShipmentComplete.cpp
  ScheduleTypeEnum.cpp
  ScheduledTask.cpp
  SerializeStockItem.cpp
  SocialAccount.cpp
  SocialConnect.cpp
  SocialProvider.cpp
  SocialProviderListResponse.cpp
  Status2a7Enum.cpp
  StockAdd.cpp
  StockAdjustmentItem.cpp
  StockAdjustmentItem_status.cpp
  StockAssignment.cpp
  StockAssignmentItem.cpp
  StockChangeStatus.cpp
  StockCount.cpp
  StockItem.cpp
  StockItemSerializerBrief.cpp
  StockItemTestResult.cpp
  StockLocationType.cpp
  StockMerge.cpp
  StockMergeItem.cpp
  StockRemove.cpp
  StockTracking.cpp
  StockTransfer.cpp
  SupplierPart.cpp
  SupplierPriceBreak.cpp
  Token.cpp
  UninstallStockItem.cpp
  User.cpp
  UserCreate.cpp
  UserDetails.cpp
  UserSettings.cpp
  VerifyEmail.cpp
  Version.cpp
  VersionInformation.cpp
  VersionView.cpp
  ActionApi.cpp
  AdminApi.cpp
  AttachmentApi.cpp
  AuthApi.cpp
  BackgroundTaskApi.cpp
  BarcodeApi.cpp
  BomApi.cpp
  BuildApi.cpp
  CompanyApi.cpp
  ContenttypeApi.cpp
  CurrencyApi.cpp
  EmailApi.cpp
  ErrorReportApi.cpp
  FlagsApi.cpp
  GenerateApi.cpp
  GenericApi.cpp
  ImporterApi.cpp
  LabelApi.cpp
  LicenseApi.cpp
  LocateApi.cpp
  MachineApi.cpp
  NewsApi.cpp
  NotesImageUploadApi.cpp
  NotificationsApi.cpp
  OrderApi.cpp
  PartApi.cpp
  PluginsApi.cpp
  ProjectCodeApi.cpp
  ReportApi.cpp
  SearchApi.cpp
  SettingsApi.cpp
  StockApi.cpp
  UnitsApi.cpp
  UserApi.cpp
  VersionApi.cpp
  VersionTextApi.cpp
  WebApi.cpp
  WebhookApi.cpp
  Helpers.cpp
  HttpRequest.cpp
  HttpFileElement.cpp
  Oauth.cpp
  )

target_include_directories(${PROJECT_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        Qt${QT_VERSION_MAJOR}::Core
        Qt${QT_VERSION_MAJOR}::Network
        Qt${QT_VERSION_MAJOR}::Gui

)

configure_package_config_file(${CMAKE_CURRENT_SOURCE_DIR}/Config.cmake.in
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(
    TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}Targets
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}"
)

install(
    FILES ${HEADER_FILES}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}
)

install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)

install(
    EXPORT ${PROJECT_NAME}Targets
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
)
