/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 160
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CompanyAttachment.h
 *
 * Serializer for the CompanyAttachment class
 */

#ifndef CompanyAttachment_H
#define CompanyAttachment_H

#include <QJsonObject>

#include "User.h"
#include <QDate>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {
class User;

class CompanyAttachment : public Object {
public:
    CompanyAttachment();
    CompanyAttachment(QString json);
    ~CompanyAttachment() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    QString getAttachment() const;
    void setAttachment(const QString &attachment);
    bool is_attachment_Set() const;
    bool is_attachment_Valid() const;

    QString getFilename() const;
    void setFilename(const QString &filename);
    bool is_filename_Set() const;
    bool is_filename_Valid() const;

    QString getLink() const;
    void setLink(const QString &link);
    bool is_link_Set() const;
    bool is_link_Valid() const;

    QString getComment() const;
    void setComment(const QString &comment);
    bool is_comment_Set() const;
    bool is_comment_Valid() const;

    QDate getUploadDate() const;
    void setUploadDate(const QDate &upload_date);
    bool is_upload_date_Set() const;
    bool is_upload_date_Valid() const;

    qint32 getUser() const;
    void setUser(const qint32 &user);
    bool is_user_Set() const;
    bool is_user_Valid() const;

    User getUserDetail() const;
    void setUserDetail(const User &user_detail);
    bool is_user_detail_Set() const;
    bool is_user_detail_Valid() const;

    qint32 getCompany() const;
    void setCompany(const qint32 &company);
    bool is_company_Set() const;
    bool is_company_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    QString m_attachment;
    bool m_attachment_isSet;
    bool m_attachment_isValid;

    QString m_filename;
    bool m_filename_isSet;
    bool m_filename_isValid;

    QString m_link;
    bool m_link_isSet;
    bool m_link_isValid;

    QString m_comment;
    bool m_comment_isSet;
    bool m_comment_isValid;

    QDate m_upload_date;
    bool m_upload_date_isSet;
    bool m_upload_date_isValid;

    qint32 m_user;
    bool m_user_isSet;
    bool m_user_isValid;

    User m_user_detail;
    bool m_user_detail_isSet;
    bool m_user_detail_isValid;

    qint32 m_company;
    bool m_company_isSet;
    bool m_company_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::CompanyAttachment)

#endif // CompanyAttachment_H
