/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Config.h
 *
 * Serializer for the InvenTree configuration.  This is a read-only serializer.
 */

#ifndef Config_H
#define Config_H

#include <QJsonObject>

#include <QDateTime>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {

class Config : public Object {
public:
    Config();
    Config(const QString &json);
    ~Config() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    QString getKey() const;
    void setKey(const QString &key);
    bool is_key_Set() const;
    bool is_key_Valid() const;

    QString getEnvVar() const;
    void setEnvVar(const QString &env_var);
    bool is_env_var_Set() const;
    bool is_env_var_Valid() const;

    QString getConfigKey() const;
    void setConfigKey(const QString &config_key);
    bool is_config_key_Set() const;
    bool is_config_key_Valid() const;

    QString getSource() const;
    void setSource(const QString &source);
    bool is_source_Set() const;
    bool is_source_Valid() const;

    QDateTime getAccessed() const;
    void setAccessed(const QDateTime &accessed);
    bool is_accessed_Set() const;
    bool is_accessed_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_key;
    bool m_key_isSet;
    bool m_key_isValid;

    QString m_env_var;
    bool m_env_var_isSet;
    bool m_env_var_isValid;

    QString m_config_key;
    bool m_config_key_isSet;
    bool m_config_key_isValid;

    QString m_source;
    bool m_source_isSet;
    bool m_source_isValid;

    QDateTime m_accessed;
    bool m_accessed_isSet;
    bool m_accessed_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::Config)

#endif // Config_H
