/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ContentType.h
 *
 * Serializer for ContentType models.
 */

#ifndef ContentType_H
#define ContentType_H

#include <QJsonObject>
#include <QList>
#include <QMap>

#include <QString>

#include "Enum.h"
#include "HttpFileElement.h"
#include "Object.h"

namespace InvenTree {

class ContentType : public Object {
public:
    ContentType();
    ContentType(const QString &json);
    ~ContentType() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    QMap<QString, QString> asFormVariables() const override;
    QMap<QString, QString> asFormVariables(const QString &namePrefix) const override;
    QList<HttpFileElement> asFileElements() const override;
    QList<HttpFileElement> asFileElements(const QString &namePrefix) const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    QString getAppLabel() const;
    void setAppLabel(const QString &app_label);
    bool is_app_label_Set() const;
    bool is_app_label_Valid() const;

    QString getModel() const;
    void setModel(const QString &model);
    bool is_model_Set() const;
    bool is_model_Valid() const;

    QString getAppLabeledName() const;
    void setAppLabeledName(const QString &app_labeled_name);
    bool is_app_labeled_name_Set() const;
    bool is_app_labeled_name_Valid() const;

    bool isIsPlugin() const;
    void setIsPlugin(const bool &is_plugin);
    bool is_is_plugin_Set() const;
    bool is_is_plugin_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    QString m_app_label;
    bool m_app_label_isSet;
    bool m_app_label_isValid;

    QString m_model;
    bool m_model_isSet;
    bool m_model_isValid;

    QString m_app_labeled_name;
    bool m_app_labeled_name_isSet;
    bool m_app_labeled_name_isValid;

    bool m_is_plugin;
    bool m_is_plugin_isSet;
    bool m_is_plugin_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::ContentType)

#endif // ContentType_H
