/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "GetAuthToken.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

GetAuthToken::GetAuthToken(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

GetAuthToken::GetAuthToken() {
    this->initializeModel();
}

GetAuthToken::~GetAuthToken() {}

void GetAuthToken::initializeModel() {

    m_token_isSet = false;
    m_token_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_expiry_isSet = false;
    m_expiry_isValid = false;
}

void GetAuthToken::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void GetAuthToken::fromJsonObject(QJsonObject json) {

    m_token_isValid = ::InvenTree::fromJsonValue(m_token, json[QString("token")]);
    m_token_isSet = !json[QString("token")].isNull() && m_token_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_expiry_isValid = ::InvenTree::fromJsonValue(m_expiry, json[QString("expiry")]);
    m_expiry_isSet = !json[QString("expiry")].isNull() && m_expiry_isValid;
}

QString GetAuthToken::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject GetAuthToken::asJsonObject() const {
    QJsonObject obj;
    if (m_token_isSet) {
        obj.insert(QString("token"), ::InvenTree::toJsonValue(m_token));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_expiry_isSet) {
        obj.insert(QString("expiry"), ::InvenTree::toJsonValue(m_expiry));
    }
    return obj;
}

QMap<QString, QString> GetAuthToken::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> GetAuthToken::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_token_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("token"), namePrefix), m_token);
    }
    if (m_name_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("name"), namePrefix), m_name);
    }
    if (m_expiry_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("expiry"), namePrefix), m_expiry);
    }
    return vars;
}

QList<HttpFileElement> GetAuthToken::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> GetAuthToken::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_token_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("token"), namePrefix), m_token);
    }
    if (m_name_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("name"), namePrefix), m_name);
    }
    if (m_expiry_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("expiry"), namePrefix), m_expiry);
    }
    return files;
}

QString GetAuthToken::getToken() const {
    return m_token;
}
void GetAuthToken::setToken(const QString &token) {
    m_token = token;
    m_token_isSet = true;
}

bool GetAuthToken::is_token_Set() const{
    return m_token_isSet;
}

bool GetAuthToken::is_token_Valid() const{
    return m_token_isValid;
}

QString GetAuthToken::getName() const {
    return m_name;
}
void GetAuthToken::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool GetAuthToken::is_name_Set() const{
    return m_name_isSet;
}

bool GetAuthToken::is_name_Valid() const{
    return m_name_isValid;
}

QDate GetAuthToken::getExpiry() const {
    return m_expiry;
}
void GetAuthToken::setExpiry(const QDate &expiry) {
    m_expiry = expiry;
    m_expiry_isSet = true;
}

bool GetAuthToken::is_expiry_Set() const{
    return m_expiry_isSet;
}

bool GetAuthToken::is_expiry_Valid() const{
    return m_expiry_isValid;
}

bool GetAuthToken::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_token_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_expiry_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool GetAuthToken::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_token_isValid && m_name_isValid && m_expiry_isValid && true;
}

} // namespace InvenTree
