/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InfoApi.h
 *
 * InvenTree server information - some information might be blanked if called without elevated credentials.
 */

#ifndef InfoApi_H
#define InfoApi_H

#include <QJsonObject>
#include <QList>
#include <QMap>

#include "Customize.h"
#include "Settings.h"
#include <QJsonValue>
#include <QString>

#include "Enum.h"
#include "HttpFileElement.h"
#include "Object.h"

namespace InvenTree {
class Customize;
class Settings;

class InfoApi : public Object {
public:
    InfoApi();
    InfoApi(const QString &json);
    ~InfoApi() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    QMap<QString, QString> asFormVariables() const override;
    QMap<QString, QString> asFormVariables(const QString &namePrefix) const override;
    QList<HttpFileElement> asFileElements() const override;
    QList<HttpFileElement> asFileElements(const QString &namePrefix) const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    QString getServer() const;
    void setServer(const QString &server);
    bool is_server_Set() const;
    bool is_server_Valid() const;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getVersion() const;
    void setVersion(const QString &version);
    bool is_version_Set() const;
    bool is_version_Valid() const;

    QString getInstance() const;
    void setInstance(const QString &instance);
    bool is_instance_Set() const;
    bool is_instance_Valid() const;

    qint32 getApiVersion() const;
    void setApiVersion(const qint32 &api_version);
    bool is_api_version_Set() const;
    bool is_api_version_Valid() const;

    bool isWorkerRunning() const;
    void setWorkerRunning(const bool &worker_running);
    bool is_worker_running_Set() const;
    bool is_worker_running_Valid() const;

    qint32 getWorkerCount() const;
    void setWorkerCount(const qint32 &worker_count);
    bool is_worker_count_Set() const;
    bool is_worker_count_Valid() const;

    qint32 getWorkerPendingTasks() const;
    void setWorkerPendingTasks(const qint32 &worker_pending_tasks);
    bool is_worker_pending_tasks_Set() const;
    bool is_worker_pending_tasks_Valid() const;

    bool isPluginsEnabled() const;
    void setPluginsEnabled(const bool &plugins_enabled);
    bool is_plugins_enabled_Set() const;
    bool is_plugins_enabled_Valid() const;

    bool isPluginsInstallDisabled() const;
    void setPluginsInstallDisabled(const bool &plugins_install_disabled);
    bool is_plugins_install_disabled_Set() const;
    bool is_plugins_install_disabled_Valid() const;

    QJsonValue getActivePlugins() const;
    void setActivePlugins(const QJsonValue &active_plugins);
    bool is_active_plugins_Set() const;
    bool is_active_plugins_Valid() const;

    bool isEmailConfigured() const;
    void setEmailConfigured(const bool &email_configured);
    bool is_email_configured_Set() const;
    bool is_email_configured_Valid() const;

    bool isDebugMode() const;
    void setDebugMode(const bool &debug_mode);
    bool is_debug_mode_Set() const;
    bool is_debug_mode_Valid() const;

    bool isDockerMode() const;
    void setDockerMode(const bool &docker_mode);
    bool is_docker_mode_Set() const;
    bool is_docker_mode_Valid() const;

    QString getDefaultLocale() const;
    void setDefaultLocale(const QString &default_locale);
    bool is_default_locale_Set() const;
    bool is_default_locale_Valid() const;

    Customize getCustomize() const;
    void setCustomize(const Customize &customize);
    bool is_customize_Set() const;
    bool is_customize_Valid() const;

    bool isSystemHealth() const;
    void setSystemHealth(const bool &system_health);
    bool is_system_health_Set() const;
    bool is_system_health_Valid() const;

    QString getDatabase() const;
    void setDatabase(const QString &database);
    bool is_database_Set() const;
    bool is_database_Valid() const;

    QString getPlatform() const;
    void setPlatform(const QString &platform);
    bool is_platform_Set() const;
    bool is_platform_Valid() const;

    QString getInstaller() const;
    void setInstaller(const QString &installer);
    bool is_installer_Set() const;
    bool is_installer_Valid() const;

    QString getTarget() const;
    void setTarget(const QString &target);
    bool is_target_Set() const;
    bool is_target_Valid() const;

    QString getDjangoAdmin() const;
    void setDjangoAdmin(const QString &django_admin);
    bool is_django_admin_Set() const;
    bool is_django_admin_Valid() const;

    Settings getSettings() const;
    void setSettings(const Settings &settings);
    bool is_settings_Set() const;
    bool is_settings_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_server;
    bool m_server_isSet;
    bool m_server_isValid;

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_version;
    bool m_version_isSet;
    bool m_version_isValid;

    QString m_instance;
    bool m_instance_isSet;
    bool m_instance_isValid;

    qint32 m_api_version;
    bool m_api_version_isSet;
    bool m_api_version_isValid;

    bool m_worker_running;
    bool m_worker_running_isSet;
    bool m_worker_running_isValid;

    qint32 m_worker_count;
    bool m_worker_count_isSet;
    bool m_worker_count_isValid;

    qint32 m_worker_pending_tasks;
    bool m_worker_pending_tasks_isSet;
    bool m_worker_pending_tasks_isValid;

    bool m_plugins_enabled;
    bool m_plugins_enabled_isSet;
    bool m_plugins_enabled_isValid;

    bool m_plugins_install_disabled;
    bool m_plugins_install_disabled_isSet;
    bool m_plugins_install_disabled_isValid;

    QJsonValue m_active_plugins;
    bool m_active_plugins_isSet;
    bool m_active_plugins_isValid;

    bool m_email_configured;
    bool m_email_configured_isSet;
    bool m_email_configured_isValid;

    bool m_debug_mode;
    bool m_debug_mode_isSet;
    bool m_debug_mode_isValid;

    bool m_docker_mode;
    bool m_docker_mode_isSet;
    bool m_docker_mode_isValid;

    QString m_default_locale;
    bool m_default_locale_isSet;
    bool m_default_locale_isValid;

    Customize m_customize;
    bool m_customize_isSet;
    bool m_customize_isValid;

    bool m_system_health;
    bool m_system_health_isSet;
    bool m_system_health_isValid;

    QString m_database;
    bool m_database_isSet;
    bool m_database_isValid;

    QString m_platform;
    bool m_platform_isSet;
    bool m_platform_isValid;

    QString m_installer;
    bool m_installer_isSet;
    bool m_installer_isValid;

    QString m_target;
    bool m_target_isSet;
    bool m_target_isValid;

    QString m_django_admin;
    bool m_django_admin_isSet;
    bool m_django_admin_isValid;

    Settings m_settings;
    bool m_settings_isSet;
    bool m_settings_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::InfoApi)

#endif // InfoApi_H
