/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "MachineType.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

MachineType::MachineType(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

MachineType::MachineType() {
    this->initializeModel();
}

MachineType::~MachineType() {}

void MachineType::initializeModel() {

    m_slug_isSet = false;
    m_slug_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_provider_file_isSet = false;
    m_provider_file_isValid = false;

    m_provider_plugin_isSet = false;
    m_provider_plugin_isValid = false;

    m_is_builtin_isSet = false;
    m_is_builtin_isValid = false;
}

void MachineType::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void MachineType::fromJsonObject(QJsonObject json) {

    m_slug_isValid = ::InvenTree::fromJsonValue(m_slug, json[QString("slug")]);
    m_slug_isSet = !json[QString("slug")].isNull() && m_slug_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_description_isValid = ::InvenTree::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_provider_file_isValid = ::InvenTree::fromJsonValue(m_provider_file, json[QString("provider_file")]);
    m_provider_file_isSet = !json[QString("provider_file")].isNull() && m_provider_file_isValid;

    m_provider_plugin_isValid = ::InvenTree::fromJsonValue(m_provider_plugin, json[QString("provider_plugin")]);
    m_provider_plugin_isSet = !json[QString("provider_plugin")].isNull() && m_provider_plugin_isValid;

    m_is_builtin_isValid = ::InvenTree::fromJsonValue(m_is_builtin, json[QString("is_builtin")]);
    m_is_builtin_isSet = !json[QString("is_builtin")].isNull() && m_is_builtin_isValid;
}

QString MachineType::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject MachineType::asJsonObject() const {
    QJsonObject obj;
    if (m_slug_isSet) {
        obj.insert(QString("slug"), ::InvenTree::toJsonValue(m_slug));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::InvenTree::toJsonValue(m_description));
    }
    if (m_provider_file_isSet) {
        obj.insert(QString("provider_file"), ::InvenTree::toJsonValue(m_provider_file));
    }
    if (m_provider_plugin.size() > 0) {
        obj.insert(QString("provider_plugin"), ::InvenTree::toJsonValue(m_provider_plugin));
    }
    if (m_is_builtin_isSet) {
        obj.insert(QString("is_builtin"), ::InvenTree::toJsonValue(m_is_builtin));
    }
    return obj;
}

QString MachineType::getSlug() const {
    return m_slug;
}
void MachineType::setSlug(const QString &slug) {
    m_slug = slug;
    m_slug_isSet = true;
}

bool MachineType::is_slug_Set() const{
    return m_slug_isSet;
}

bool MachineType::is_slug_Valid() const{
    return m_slug_isValid;
}

QString MachineType::getName() const {
    return m_name;
}
void MachineType::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool MachineType::is_name_Set() const{
    return m_name_isSet;
}

bool MachineType::is_name_Valid() const{
    return m_name_isValid;
}

QString MachineType::getDescription() const {
    return m_description;
}
void MachineType::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool MachineType::is_description_Set() const{
    return m_description_isSet;
}

bool MachineType::is_description_Valid() const{
    return m_description_isValid;
}

QString MachineType::getProviderFile() const {
    return m_provider_file;
}
void MachineType::setProviderFile(const QString &provider_file) {
    m_provider_file = provider_file;
    m_provider_file_isSet = true;
}

bool MachineType::is_provider_file_Set() const{
    return m_provider_file_isSet;
}

bool MachineType::is_provider_file_Valid() const{
    return m_provider_file_isValid;
}

QMap<QString, QJsonValue> MachineType::getProviderPlugin() const {
    return m_provider_plugin;
}
void MachineType::setProviderPlugin(const QMap<QString, QJsonValue> &provider_plugin) {
    m_provider_plugin = provider_plugin;
    m_provider_plugin_isSet = true;
}

bool MachineType::is_provider_plugin_Set() const{
    return m_provider_plugin_isSet;
}

bool MachineType::is_provider_plugin_Valid() const{
    return m_provider_plugin_isValid;
}

bool MachineType::isIsBuiltin() const {
    return m_is_builtin;
}
void MachineType::setIsBuiltin(const bool &is_builtin) {
    m_is_builtin = is_builtin;
    m_is_builtin_isSet = true;
}

bool MachineType::is_is_builtin_Set() const{
    return m_is_builtin_isSet;
}

bool MachineType::is_is_builtin_Valid() const{
    return m_is_builtin_isValid;
}

bool MachineType::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_slug_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_provider_file_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_provider_plugin.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_is_builtin_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool MachineType::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_slug_isValid && m_name_isValid && m_description_isValid && m_provider_file_isValid && m_provider_plugin_isValid && m_is_builtin_isValid && true;
}

} // namespace InvenTree
