/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "MachineConfig.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

MachineConfig::MachineConfig(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

MachineConfig::MachineConfig() {
    this->initializeModel();
}

MachineConfig::~MachineConfig() {}

void MachineConfig::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_machine_type_isSet = false;
    m_machine_type_isValid = false;

    m_driver_isSet = false;
    m_driver_isValid = false;

    m_initialized_isSet = false;
    m_initialized_isValid = false;

    m_active_isSet = false;
    m_active_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;

    m_status_model_isSet = false;
    m_status_model_isValid = false;

    m_status_text_isSet = false;
    m_status_text_isValid = false;

    m_machine_errors_isSet = false;
    m_machine_errors_isValid = false;

    m_is_driver_available_isSet = false;
    m_is_driver_available_isValid = false;

    m_restart_required_isSet = false;
    m_restart_required_isValid = false;

    m_properties_isSet = false;
    m_properties_isValid = false;
}

void MachineConfig::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void MachineConfig::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_machine_type_isValid = ::InvenTree::fromJsonValue(m_machine_type, json[QString("machine_type")]);
    m_machine_type_isSet = !json[QString("machine_type")].isNull() && m_machine_type_isValid;

    m_driver_isValid = ::InvenTree::fromJsonValue(m_driver, json[QString("driver")]);
    m_driver_isSet = !json[QString("driver")].isNull() && m_driver_isValid;

    m_initialized_isValid = ::InvenTree::fromJsonValue(m_initialized, json[QString("initialized")]);
    m_initialized_isSet = !json[QString("initialized")].isNull() && m_initialized_isValid;

    m_active_isValid = ::InvenTree::fromJsonValue(m_active, json[QString("active")]);
    m_active_isSet = !json[QString("active")].isNull() && m_active_isValid;

    m_status_isValid = ::InvenTree::fromJsonValue(m_status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;

    m_status_model_isValid = ::InvenTree::fromJsonValue(m_status_model, json[QString("status_model")]);
    m_status_model_isSet = !json[QString("status_model")].isNull() && m_status_model_isValid;

    m_status_text_isValid = ::InvenTree::fromJsonValue(m_status_text, json[QString("status_text")]);
    m_status_text_isSet = !json[QString("status_text")].isNull() && m_status_text_isValid;

    m_machine_errors_isValid = ::InvenTree::fromJsonValue(m_machine_errors, json[QString("machine_errors")]);
    m_machine_errors_isSet = !json[QString("machine_errors")].isNull() && m_machine_errors_isValid;

    m_is_driver_available_isValid = ::InvenTree::fromJsonValue(m_is_driver_available, json[QString("is_driver_available")]);
    m_is_driver_available_isSet = !json[QString("is_driver_available")].isNull() && m_is_driver_available_isValid;

    m_restart_required_isValid = ::InvenTree::fromJsonValue(m_restart_required, json[QString("restart_required")]);
    m_restart_required_isSet = !json[QString("restart_required")].isNull() && m_restart_required_isValid;

    m_properties_isValid = ::InvenTree::fromJsonValue(m_properties, json[QString("properties")]);
    m_properties_isSet = !json[QString("properties")].isNull() && m_properties_isValid;
}

QString MachineConfig::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject MachineConfig::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_machine_type_isSet) {
        obj.insert(QString("machine_type"), ::InvenTree::toJsonValue(m_machine_type));
    }
    if (m_driver_isSet) {
        obj.insert(QString("driver"), ::InvenTree::toJsonValue(m_driver));
    }
    if (m_initialized_isSet) {
        obj.insert(QString("initialized"), ::InvenTree::toJsonValue(m_initialized));
    }
    if (m_active_isSet) {
        obj.insert(QString("active"), ::InvenTree::toJsonValue(m_active));
    }
    if (m_status_isSet) {
        obj.insert(QString("status"), ::InvenTree::toJsonValue(m_status));
    }
    if (m_status_model_isSet) {
        obj.insert(QString("status_model"), ::InvenTree::toJsonValue(m_status_model));
    }
    if (m_status_text_isSet) {
        obj.insert(QString("status_text"), ::InvenTree::toJsonValue(m_status_text));
    }
    if (m_machine_errors.size() > 0) {
        obj.insert(QString("machine_errors"), ::InvenTree::toJsonValue(m_machine_errors));
    }
    if (m_is_driver_available_isSet) {
        obj.insert(QString("is_driver_available"), ::InvenTree::toJsonValue(m_is_driver_available));
    }
    if (m_restart_required_isSet) {
        obj.insert(QString("restart_required"), ::InvenTree::toJsonValue(m_restart_required));
    }
    if (m_properties.size() > 0) {
        obj.insert(QString("properties"), ::InvenTree::toJsonValue(m_properties));
    }
    return obj;
}

QString MachineConfig::getPk() const {
    return m_pk;
}
void MachineConfig::setPk(const QString &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool MachineConfig::is_pk_Set() const{
    return m_pk_isSet;
}

bool MachineConfig::is_pk_Valid() const{
    return m_pk_isValid;
}

QString MachineConfig::getName() const {
    return m_name;
}
void MachineConfig::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool MachineConfig::is_name_Set() const{
    return m_name_isSet;
}

bool MachineConfig::is_name_Valid() const{
    return m_name_isValid;
}

QString MachineConfig::getMachineType() const {
    return m_machine_type;
}
void MachineConfig::setMachineType(const QString &machine_type) {
    m_machine_type = machine_type;
    m_machine_type_isSet = true;
}

bool MachineConfig::is_machine_type_Set() const{
    return m_machine_type_isSet;
}

bool MachineConfig::is_machine_type_Valid() const{
    return m_machine_type_isValid;
}

QString MachineConfig::getDriver() const {
    return m_driver;
}
void MachineConfig::setDriver(const QString &driver) {
    m_driver = driver;
    m_driver_isSet = true;
}

bool MachineConfig::is_driver_Set() const{
    return m_driver_isSet;
}

bool MachineConfig::is_driver_Valid() const{
    return m_driver_isValid;
}

bool MachineConfig::isInitialized() const {
    return m_initialized;
}
void MachineConfig::setInitialized(const bool &initialized) {
    m_initialized = initialized;
    m_initialized_isSet = true;
}

bool MachineConfig::is_initialized_Set() const{
    return m_initialized_isSet;
}

bool MachineConfig::is_initialized_Valid() const{
    return m_initialized_isValid;
}

bool MachineConfig::isActive() const {
    return m_active;
}
void MachineConfig::setActive(const bool &active) {
    m_active = active;
    m_active_isSet = true;
}

bool MachineConfig::is_active_Set() const{
    return m_active_isSet;
}

bool MachineConfig::is_active_Valid() const{
    return m_active_isValid;
}

qint32 MachineConfig::getStatus() const {
    return m_status;
}
void MachineConfig::setStatus(const qint32 &status) {
    m_status = status;
    m_status_isSet = true;
}

bool MachineConfig::is_status_Set() const{
    return m_status_isSet;
}

bool MachineConfig::is_status_Valid() const{
    return m_status_isValid;
}

QString MachineConfig::getStatusModel() const {
    return m_status_model;
}
void MachineConfig::setStatusModel(const QString &status_model) {
    m_status_model = status_model;
    m_status_model_isSet = true;
}

bool MachineConfig::is_status_model_Set() const{
    return m_status_model_isSet;
}

bool MachineConfig::is_status_model_Valid() const{
    return m_status_model_isValid;
}

QString MachineConfig::getStatusText() const {
    return m_status_text;
}
void MachineConfig::setStatusText(const QString &status_text) {
    m_status_text = status_text;
    m_status_text_isSet = true;
}

bool MachineConfig::is_status_text_Set() const{
    return m_status_text_isSet;
}

bool MachineConfig::is_status_text_Valid() const{
    return m_status_text_isValid;
}

QList<QString> MachineConfig::getMachineErrors() const {
    return m_machine_errors;
}
void MachineConfig::setMachineErrors(const QList<QString> &machine_errors) {
    m_machine_errors = machine_errors;
    m_machine_errors_isSet = true;
}

bool MachineConfig::is_machine_errors_Set() const{
    return m_machine_errors_isSet;
}

bool MachineConfig::is_machine_errors_Valid() const{
    return m_machine_errors_isValid;
}

bool MachineConfig::isIsDriverAvailable() const {
    return m_is_driver_available;
}
void MachineConfig::setIsDriverAvailable(const bool &is_driver_available) {
    m_is_driver_available = is_driver_available;
    m_is_driver_available_isSet = true;
}

bool MachineConfig::is_is_driver_available_Set() const{
    return m_is_driver_available_isSet;
}

bool MachineConfig::is_is_driver_available_Valid() const{
    return m_is_driver_available_isValid;
}

bool MachineConfig::isRestartRequired() const {
    return m_restart_required;
}
void MachineConfig::setRestartRequired(const bool &restart_required) {
    m_restart_required = restart_required;
    m_restart_required_isSet = true;
}

bool MachineConfig::is_restart_required_Set() const{
    return m_restart_required_isSet;
}

bool MachineConfig::is_restart_required_Valid() const{
    return m_restart_required_isValid;
}

QList<MachineProperty> MachineConfig::getProperties() const {
    return m_properties;
}
void MachineConfig::setProperties(const QList<MachineProperty> &properties) {
    m_properties = properties;
    m_properties_isSet = true;
}

bool MachineConfig::is_properties_Set() const{
    return m_properties_isSet;
}

bool MachineConfig::is_properties_Valid() const{
    return m_properties_isValid;
}

bool MachineConfig::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_machine_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_driver_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_initialized_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_active_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_model_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_text_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_machine_errors.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_is_driver_available_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_restart_required_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_properties.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool MachineConfig::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pk_isValid && m_name_isValid && m_machine_type_isValid && m_driver_isValid && m_initialized_isValid && m_status_isValid && m_status_text_isValid && m_machine_errors_isValid && m_is_driver_available_isValid && m_restart_required_isValid && m_properties_isValid && true;
}

} // namespace InvenTree
