/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "ModelType4f8Enum.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

ModelType4f8Enum::ModelType4f8Enum(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

ModelType4f8Enum::ModelType4f8Enum() {
    this->initializeModel();
}

ModelType4f8Enum::~ModelType4f8Enum() {}

void ModelType4f8Enum::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eModelType4f8Enum::INVALID_VALUE_OPENAPI_GENERATED;
}

void ModelType4f8Enum::fromJson(const QString &jsonString) {
    
    if ( jsonString.compare("build.build", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::BUILD_BUILD;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("company.company", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::COMPANY_COMPANY;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("company.manufacturerpart", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::COMPANY_MANUFACTURERPART;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("company.supplierpart", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::COMPANY_SUPPLIERPART;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("order.purchaseorder", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::ORDER_PURCHASEORDER;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("order.returnorder", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::ORDER_RETURNORDER;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("order.salesorder", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::ORDER_SALESORDER;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("part.part", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::PART_PART;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("stock.stocklocation", Qt::CaseInsensitive) == 0) {
        m_value = eModelType4f8Enum::STOCK_STOCKLOCATION;
        m_value_isSet = m_value_isValid = true;
    }
}

void ModelType4f8Enum::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString ModelType4f8Enum::asJson() const {
    
    QString val;
    switch (m_value){
        case eModelType4f8Enum::BUILD_BUILD:
            val = "build.build";
            break;
        case eModelType4f8Enum::COMPANY_COMPANY:
            val = "company.company";
            break;
        case eModelType4f8Enum::COMPANY_MANUFACTURERPART:
            val = "company.manufacturerpart";
            break;
        case eModelType4f8Enum::COMPANY_SUPPLIERPART:
            val = "company.supplierpart";
            break;
        case eModelType4f8Enum::ORDER_PURCHASEORDER:
            val = "order.purchaseorder";
            break;
        case eModelType4f8Enum::ORDER_RETURNORDER:
            val = "order.returnorder";
            break;
        case eModelType4f8Enum::ORDER_SALESORDER:
            val = "order.salesorder";
            break;
        case eModelType4f8Enum::PART_PART:
            val = "part.part";
            break;
        case eModelType4f8Enum::STOCK_STOCKLOCATION:
            val = "stock.stocklocation";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue ModelType4f8Enum::asJsonValue() const {
    
    return QJsonValue(asJson());
}


ModelType4f8Enum::eModelType4f8Enum ModelType4f8Enum::getValue() const {
    return m_value;
}

void ModelType4f8Enum::setValue(const ModelType4f8Enum::eModelType4f8Enum& value){
    m_value = value;
    m_value_isSet = true;
}
bool ModelType4f8Enum::isSet() const {
    
    return m_value_isSet;
}

bool ModelType4f8Enum::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace InvenTree
