/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 158
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _NewsApi_H
#define _NewsApi_H

#include "Helpers.h"
#include "HttpRequest.h"
#include "ServerConfiguration.h"
#include "Oauth.h"

#include "NewsFeedEntry.h"
#include "PaginatedNewsFeedEntryList.h"
#include "PatchedNewsFeedEntry.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace InvenTree {

class NewsApi : public QObject {
    Q_OBJECT

public:
    NewsApi(const int timeOut = 0);
    ~NewsApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables = QMap<QString, ServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);


    void news_Destroy();

    /**
    * @param[in]  id qint32 [required]
    */
    void news_Destroy2(const qint32 &id);

    /**
    * @param[in]  limit qint32 [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  read bool [optional]
    */
    void news_List(const ::InvenTree::OptionalParam<qint32> &limit = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &read = ::InvenTree::OptionalParam<bool>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_news_feed_entry PatchedNewsFeedEntry [optional]
    */
    void news_PartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedNewsFeedEntry> &patched_news_feed_entry = ::InvenTree::OptionalParam<PatchedNewsFeedEntry>());

    /**
    * @param[in]  id qint32 [required]
    */
    void news_Retrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  news_feed_entry NewsFeedEntry [required]
    */
    void news_Update(const qint32 &id, const NewsFeedEntry &news_feed_entry);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<ServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    HttpRequestInput _latestInput;
    HttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void news_DestroyCallback(HttpRequestWorker *worker);
    void news_Destroy2Callback(HttpRequestWorker *worker);
    void news_ListCallback(HttpRequestWorker *worker);
    void news_PartialUpdateCallback(HttpRequestWorker *worker);
    void news_RetrieveCallback(HttpRequestWorker *worker);
    void news_UpdateCallback(HttpRequestWorker *worker);

signals:

    void news_DestroySignal();
    void news_Destroy2Signal();
    void news_ListSignal(PaginatedNewsFeedEntryList summary);
    void news_PartialUpdateSignal(NewsFeedEntry summary);
    void news_RetrieveSignal(NewsFeedEntry summary);
    void news_UpdateSignal(NewsFeedEntry summary);

    void news_DestroySignalFull(HttpRequestWorker *worker);
    void news_Destroy2SignalFull(HttpRequestWorker *worker);
    void news_ListSignalFull(HttpRequestWorker *worker, PaginatedNewsFeedEntryList summary);
    void news_PartialUpdateSignalFull(HttpRequestWorker *worker, NewsFeedEntry summary);
    void news_RetrieveSignalFull(HttpRequestWorker *worker, NewsFeedEntry summary);
    void news_UpdateSignalFull(HttpRequestWorker *worker, NewsFeedEntry summary);

    Q_DECL_DEPRECATED_X("Use news_DestroySignalError() instead")
    void news_DestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void news_DestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_Destroy2SignalError() instead")
    void news_Destroy2SignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void news_Destroy2SignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_ListSignalError() instead")
    void news_ListSignalE(PaginatedNewsFeedEntryList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void news_ListSignalError(PaginatedNewsFeedEntryList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_PartialUpdateSignalError() instead")
    void news_PartialUpdateSignalE(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, QString error_str);
    void news_PartialUpdateSignalError(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_RetrieveSignalError() instead")
    void news_RetrieveSignalE(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, QString error_str);
    void news_RetrieveSignalError(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_UpdateSignalError() instead")
    void news_UpdateSignalE(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, QString error_str);
    void news_UpdateSignalError(NewsFeedEntry summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use news_DestroySignalErrorFull() instead")
    void news_DestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_DestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_Destroy2SignalErrorFull() instead")
    void news_Destroy2SignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_Destroy2SignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_ListSignalErrorFull() instead")
    void news_ListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_ListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_PartialUpdateSignalErrorFull() instead")
    void news_PartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_PartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_RetrieveSignalErrorFull() instead")
    void news_RetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_RetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use news_UpdateSignalErrorFull() instead")
    void news_UpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void news_UpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public slots:
    void tokenAvailable();
};

} // namespace InvenTree
#endif
