/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 160
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "Owner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

Owner::Owner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

Owner::Owner() {
    this->initializeModel();
}

Owner::~Owner() {}

void Owner::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_owner_id_isSet = false;
    m_owner_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_label_isSet = false;
    m_label_isValid = false;
}

void Owner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void Owner::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_owner_id_isValid = ::InvenTree::fromJsonValue(m_owner_id, json[QString("owner_id")]);
    m_owner_id_isSet = !json[QString("owner_id")].isNull() && m_owner_id_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_label_isValid = ::InvenTree::fromJsonValue(m_label, json[QString("label")]);
    m_label_isSet = !json[QString("label")].isNull() && m_label_isValid;
}

QString Owner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject Owner::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_owner_id_isSet) {
        obj.insert(QString("owner_id"), ::InvenTree::toJsonValue(m_owner_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_label_isSet) {
        obj.insert(QString("label"), ::InvenTree::toJsonValue(m_label));
    }
    return obj;
}

qint32 Owner::getPk() const {
    return m_pk;
}
void Owner::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool Owner::is_pk_Set() const{
    return m_pk_isSet;
}

bool Owner::is_pk_Valid() const{
    return m_pk_isValid;
}

qint64 Owner::getOwnerId() const {
    return m_owner_id;
}
void Owner::setOwnerId(const qint64 &owner_id) {
    m_owner_id = owner_id;
    m_owner_id_isSet = true;
}

bool Owner::is_owner_id_Set() const{
    return m_owner_id_isSet;
}

bool Owner::is_owner_id_Valid() const{
    return m_owner_id_isValid;
}

QString Owner::getName() const {
    return m_name;
}
void Owner::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool Owner::is_name_Set() const{
    return m_name_isSet;
}

bool Owner::is_name_Valid() const{
    return m_name_isValid;
}

QString Owner::getLabel() const {
    return m_label;
}
void Owner::setLabel(const QString &label) {
    m_label = label;
    m_label_isSet = true;
}

bool Owner::is_label_Set() const{
    return m_label_isSet;
}

bool Owner::is_label_Valid() const{
    return m_label_isValid;
}

bool Owner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_owner_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_label_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool Owner::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pk_isValid && m_name_isValid && m_label_isValid && true;
}

} // namespace InvenTree
