/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PaginatedAddressList.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PaginatedAddressList::PaginatedAddressList(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PaginatedAddressList::PaginatedAddressList() {
    this->initializeModel();
}

PaginatedAddressList::~PaginatedAddressList() {}

void PaginatedAddressList::initializeModel() {

    m_count_isSet = false;
    m_count_isValid = false;

    m_next_isSet = false;
    m_next_isValid = false;

    m_previous_isSet = false;
    m_previous_isValid = false;

    m_results_isSet = false;
    m_results_isValid = false;
}

void PaginatedAddressList::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PaginatedAddressList::fromJsonObject(QJsonObject json) {

    m_count_isValid = ::InvenTree::fromJsonValue(m_count, json[QString("count")]);
    m_count_isSet = !json[QString("count")].isNull() && m_count_isValid;

    m_next_isValid = ::InvenTree::fromJsonValue(m_next, json[QString("next")]);
    m_next_isSet = !json[QString("next")].isNull() && m_next_isValid;

    m_previous_isValid = ::InvenTree::fromJsonValue(m_previous, json[QString("previous")]);
    m_previous_isSet = !json[QString("previous")].isNull() && m_previous_isValid;

    m_results_isValid = ::InvenTree::fromJsonValue(m_results, json[QString("results")]);
    m_results_isSet = !json[QString("results")].isNull() && m_results_isValid;
}

QString PaginatedAddressList::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PaginatedAddressList::asJsonObject() const {
    QJsonObject obj;
    if (m_count_isSet) {
        obj.insert(QString("count"), ::InvenTree::toJsonValue(m_count));
    }
    if (m_next_isSet) {
        obj.insert(QString("next"), ::InvenTree::toJsonValue(m_next));
    }
    if (m_previous_isSet) {
        obj.insert(QString("previous"), ::InvenTree::toJsonValue(m_previous));
    }
    if (m_results.size() > 0) {
        obj.insert(QString("results"), ::InvenTree::toJsonValue(m_results));
    }
    return obj;
}

qint32 PaginatedAddressList::getCount() const {
    return m_count;
}
void PaginatedAddressList::setCount(const qint32 &count) {
    m_count = count;
    m_count_isSet = true;
}

bool PaginatedAddressList::is_count_Set() const{
    return m_count_isSet;
}

bool PaginatedAddressList::is_count_Valid() const{
    return m_count_isValid;
}

QString PaginatedAddressList::getNext() const {
    return m_next;
}
void PaginatedAddressList::setNext(const QString &next) {
    m_next = next;
    m_next_isSet = true;
}

bool PaginatedAddressList::is_next_Set() const{
    return m_next_isSet;
}

bool PaginatedAddressList::is_next_Valid() const{
    return m_next_isValid;
}

QString PaginatedAddressList::getPrevious() const {
    return m_previous;
}
void PaginatedAddressList::setPrevious(const QString &previous) {
    m_previous = previous;
    m_previous_isSet = true;
}

bool PaginatedAddressList::is_previous_Set() const{
    return m_previous_isSet;
}

bool PaginatedAddressList::is_previous_Valid() const{
    return m_previous_isValid;
}

QList<Address> PaginatedAddressList::getResults() const {
    return m_results;
}
void PaginatedAddressList::setResults(const QList<Address> &results) {
    m_results = results;
    m_results_isSet = true;
}

bool PaginatedAddressList::is_results_Set() const{
    return m_results_isSet;
}

bool PaginatedAddressList::is_results_Valid() const{
    return m_results_isValid;
}

bool PaginatedAddressList::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_count_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_next_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_previous_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_results.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PaginatedAddressList::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
