/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 225
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PartParameterTemplate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PartParameterTemplate::PartParameterTemplate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PartParameterTemplate::PartParameterTemplate() {
    this->initializeModel();
}

PartParameterTemplate::~PartParameterTemplate() {}

void PartParameterTemplate::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_units_isSet = false;
    m_units_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_parts_isSet = false;
    m_parts_isValid = false;

    m_checkbox_isSet = false;
    m_checkbox_isValid = false;

    m_choices_isSet = false;
    m_choices_isValid = false;
}

void PartParameterTemplate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PartParameterTemplate::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_units_isValid = ::InvenTree::fromJsonValue(m_units, json[QString("units")]);
    m_units_isSet = !json[QString("units")].isNull() && m_units_isValid;

    m_description_isValid = ::InvenTree::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_parts_isValid = ::InvenTree::fromJsonValue(m_parts, json[QString("parts")]);
    m_parts_isSet = !json[QString("parts")].isNull() && m_parts_isValid;

    m_checkbox_isValid = ::InvenTree::fromJsonValue(m_checkbox, json[QString("checkbox")]);
    m_checkbox_isSet = !json[QString("checkbox")].isNull() && m_checkbox_isValid;

    m_choices_isValid = ::InvenTree::fromJsonValue(m_choices, json[QString("choices")]);
    m_choices_isSet = !json[QString("choices")].isNull() && m_choices_isValid;
}

QString PartParameterTemplate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PartParameterTemplate::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_units_isSet) {
        obj.insert(QString("units"), ::InvenTree::toJsonValue(m_units));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::InvenTree::toJsonValue(m_description));
    }
    if (m_parts_isSet) {
        obj.insert(QString("parts"), ::InvenTree::toJsonValue(m_parts));
    }
    if (m_checkbox_isSet) {
        obj.insert(QString("checkbox"), ::InvenTree::toJsonValue(m_checkbox));
    }
    if (m_choices_isSet) {
        obj.insert(QString("choices"), ::InvenTree::toJsonValue(m_choices));
    }
    return obj;
}

qint32 PartParameterTemplate::getPk() const {
    return m_pk;
}
void PartParameterTemplate::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PartParameterTemplate::is_pk_Set() const{
    return m_pk_isSet;
}

bool PartParameterTemplate::is_pk_Valid() const{
    return m_pk_isValid;
}

QString PartParameterTemplate::getName() const {
    return m_name;
}
void PartParameterTemplate::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool PartParameterTemplate::is_name_Set() const{
    return m_name_isSet;
}

bool PartParameterTemplate::is_name_Valid() const{
    return m_name_isValid;
}

QString PartParameterTemplate::getUnits() const {
    return m_units;
}
void PartParameterTemplate::setUnits(const QString &units) {
    m_units = units;
    m_units_isSet = true;
}

bool PartParameterTemplate::is_units_Set() const{
    return m_units_isSet;
}

bool PartParameterTemplate::is_units_Valid() const{
    return m_units_isValid;
}

QString PartParameterTemplate::getDescription() const {
    return m_description;
}
void PartParameterTemplate::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool PartParameterTemplate::is_description_Set() const{
    return m_description_isSet;
}

bool PartParameterTemplate::is_description_Valid() const{
    return m_description_isValid;
}

qint32 PartParameterTemplate::getParts() const {
    return m_parts;
}
void PartParameterTemplate::setParts(const qint32 &parts) {
    m_parts = parts;
    m_parts_isSet = true;
}

bool PartParameterTemplate::is_parts_Set() const{
    return m_parts_isSet;
}

bool PartParameterTemplate::is_parts_Valid() const{
    return m_parts_isValid;
}

bool PartParameterTemplate::isCheckbox() const {
    return m_checkbox;
}
void PartParameterTemplate::setCheckbox(const bool &checkbox) {
    m_checkbox = checkbox;
    m_checkbox_isSet = true;
}

bool PartParameterTemplate::is_checkbox_Set() const{
    return m_checkbox_isSet;
}

bool PartParameterTemplate::is_checkbox_Valid() const{
    return m_checkbox_isValid;
}

QString PartParameterTemplate::getChoices() const {
    return m_choices;
}
void PartParameterTemplate::setChoices(const QString &choices) {
    m_choices = choices;
    m_choices_isSet = true;
}

bool PartParameterTemplate::is_choices_Set() const{
    return m_choices_isSet;
}

bool PartParameterTemplate::is_choices_Valid() const{
    return m_choices_isValid;
}

bool PartParameterTemplate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_units_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_parts_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_checkbox_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_choices_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PartParameterTemplate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pk_isValid && m_name_isValid && m_parts_isValid && true;
}

} // namespace InvenTree
