/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PartCopyBOM.h
 *
 * Serializer for copying a BOM from another part.
 */

#ifndef PartCopyBOM_H
#define PartCopyBOM_H

#include <QJsonObject>
#include <QList>
#include <QMap>


#include "Enum.h"
#include "HttpFileElement.h"
#include "Object.h"

namespace InvenTree {

class PartCopyBOM : public Object {
public:
    PartCopyBOM();
    PartCopyBOM(const QString &json);
    ~PartCopyBOM() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    QMap<QString, QString> asFormVariables() const override;
    QMap<QString, QString> asFormVariables(const QString &namePrefix) const override;
    QList<HttpFileElement> asFileElements() const override;
    QList<HttpFileElement> asFileElements(const QString &namePrefix) const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    qint32 getPart() const;
    void setPart(const qint32 &part);
    bool is_part_Set() const;
    bool is_part_Valid() const;

    bool isRemoveExisting() const;
    void setRemoveExisting(const bool &remove_existing);
    bool is_remove_existing_Set() const;
    bool is_remove_existing_Valid() const;

    bool isIncludeInherited() const;
    void setIncludeInherited(const bool &include_inherited);
    bool is_include_inherited_Set() const;
    bool is_include_inherited_Valid() const;

    bool isSkipInvalid() const;
    void setSkipInvalid(const bool &skip_invalid);
    bool is_skip_invalid_Set() const;
    bool is_skip_invalid_Valid() const;

    bool isCopySubstitutes() const;
    void setCopySubstitutes(const bool &copy_substitutes);
    bool is_copy_substitutes_Set() const;
    bool is_copy_substitutes_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_part;
    bool m_part_isSet;
    bool m_part_isValid;

    bool m_remove_existing;
    bool m_remove_existing_isSet;
    bool m_remove_existing_isValid;

    bool m_include_inherited;
    bool m_include_inherited_isSet;
    bool m_include_inherited_isValid;

    bool m_skip_invalid;
    bool m_skip_invalid_isSet;
    bool m_skip_invalid_isValid;

    bool m_copy_substitutes;
    bool m_copy_substitutes_isSet;
    bool m_copy_substitutes_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::PartCopyBOM)

#endif // PartCopyBOM_H
