/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedBomItem.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedBomItem::PatchedBomItem(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedBomItem::PatchedBomItem() {
    this->initializeModel();
}

PatchedBomItem::~PatchedBomItem() {}

void PatchedBomItem::initializeModel() {

    m_allow_variants_isSet = false;
    m_allow_variants_isValid = false;

    m_inherited_isSet = false;
    m_inherited_isValid = false;

    m_note_isSet = false;
    m_note_isValid = false;

    m_optional_isSet = false;
    m_optional_isValid = false;

    m_consumable_isSet = false;
    m_consumable_isValid = false;

    m_overage_isSet = false;
    m_overage_isValid = false;

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_part_isSet = false;
    m_part_isValid = false;

    m_pricing_min_isSet = false;
    m_pricing_min_isValid = false;

    m_pricing_max_isSet = false;
    m_pricing_max_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;

    m_reference_isSet = false;
    m_reference_isValid = false;

    m_sub_part_isSet = false;
    m_sub_part_isValid = false;

    m_substitutes_isSet = false;
    m_substitutes_isValid = false;

    m_validated_isSet = false;
    m_validated_isValid = false;

    m_available_stock_isSet = false;
    m_available_stock_isValid = false;

    m_available_substitute_stock_isSet = false;
    m_available_substitute_stock_isValid = false;

    m_available_variant_stock_isSet = false;
    m_available_variant_stock_isValid = false;

    m_external_stock_isSet = false;
    m_external_stock_isValid = false;

    m_on_order_isSet = false;
    m_on_order_isValid = false;

    m_building_isSet = false;
    m_building_isValid = false;
}

void PatchedBomItem::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedBomItem::fromJsonObject(QJsonObject json) {

    m_allow_variants_isValid = ::InvenTree::fromJsonValue(m_allow_variants, json[QString("allow_variants")]);
    m_allow_variants_isSet = !json[QString("allow_variants")].isNull() && m_allow_variants_isValid;

    m_inherited_isValid = ::InvenTree::fromJsonValue(m_inherited, json[QString("inherited")]);
    m_inherited_isSet = !json[QString("inherited")].isNull() && m_inherited_isValid;

    m_note_isValid = ::InvenTree::fromJsonValue(m_note, json[QString("note")]);
    m_note_isSet = !json[QString("note")].isNull() && m_note_isValid;

    m_optional_isValid = ::InvenTree::fromJsonValue(m_optional, json[QString("optional")]);
    m_optional_isSet = !json[QString("optional")].isNull() && m_optional_isValid;

    m_consumable_isValid = ::InvenTree::fromJsonValue(m_consumable, json[QString("consumable")]);
    m_consumable_isSet = !json[QString("consumable")].isNull() && m_consumable_isValid;

    m_overage_isValid = ::InvenTree::fromJsonValue(m_overage, json[QString("overage")]);
    m_overage_isSet = !json[QString("overage")].isNull() && m_overage_isValid;

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_part_isValid = ::InvenTree::fromJsonValue(m_part, json[QString("part")]);
    m_part_isSet = !json[QString("part")].isNull() && m_part_isValid;

    m_pricing_min_isValid = ::InvenTree::fromJsonValue(m_pricing_min, json[QString("pricing_min")]);
    m_pricing_min_isSet = !json[QString("pricing_min")].isNull() && m_pricing_min_isValid;

    m_pricing_max_isValid = ::InvenTree::fromJsonValue(m_pricing_max, json[QString("pricing_max")]);
    m_pricing_max_isSet = !json[QString("pricing_max")].isNull() && m_pricing_max_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;

    m_reference_isValid = ::InvenTree::fromJsonValue(m_reference, json[QString("reference")]);
    m_reference_isSet = !json[QString("reference")].isNull() && m_reference_isValid;

    m_sub_part_isValid = ::InvenTree::fromJsonValue(m_sub_part, json[QString("sub_part")]);
    m_sub_part_isSet = !json[QString("sub_part")].isNull() && m_sub_part_isValid;

    m_substitutes_isValid = ::InvenTree::fromJsonValue(m_substitutes, json[QString("substitutes")]);
    m_substitutes_isSet = !json[QString("substitutes")].isNull() && m_substitutes_isValid;

    m_validated_isValid = ::InvenTree::fromJsonValue(m_validated, json[QString("validated")]);
    m_validated_isSet = !json[QString("validated")].isNull() && m_validated_isValid;

    m_available_stock_isValid = ::InvenTree::fromJsonValue(m_available_stock, json[QString("available_stock")]);
    m_available_stock_isSet = !json[QString("available_stock")].isNull() && m_available_stock_isValid;

    m_available_substitute_stock_isValid = ::InvenTree::fromJsonValue(m_available_substitute_stock, json[QString("available_substitute_stock")]);
    m_available_substitute_stock_isSet = !json[QString("available_substitute_stock")].isNull() && m_available_substitute_stock_isValid;

    m_available_variant_stock_isValid = ::InvenTree::fromJsonValue(m_available_variant_stock, json[QString("available_variant_stock")]);
    m_available_variant_stock_isSet = !json[QString("available_variant_stock")].isNull() && m_available_variant_stock_isValid;

    m_external_stock_isValid = ::InvenTree::fromJsonValue(m_external_stock, json[QString("external_stock")]);
    m_external_stock_isSet = !json[QString("external_stock")].isNull() && m_external_stock_isValid;

    m_on_order_isValid = ::InvenTree::fromJsonValue(m_on_order, json[QString("on_order")]);
    m_on_order_isSet = !json[QString("on_order")].isNull() && m_on_order_isValid;

    m_building_isValid = ::InvenTree::fromJsonValue(m_building, json[QString("building")]);
    m_building_isSet = !json[QString("building")].isNull() && m_building_isValid;
}

QString PatchedBomItem::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedBomItem::asJsonObject() const {
    QJsonObject obj;
    if (m_allow_variants_isSet) {
        obj.insert(QString("allow_variants"), ::InvenTree::toJsonValue(m_allow_variants));
    }
    if (m_inherited_isSet) {
        obj.insert(QString("inherited"), ::InvenTree::toJsonValue(m_inherited));
    }
    if (m_note_isSet) {
        obj.insert(QString("note"), ::InvenTree::toJsonValue(m_note));
    }
    if (m_optional_isSet) {
        obj.insert(QString("optional"), ::InvenTree::toJsonValue(m_optional));
    }
    if (m_consumable_isSet) {
        obj.insert(QString("consumable"), ::InvenTree::toJsonValue(m_consumable));
    }
    if (m_overage_isSet) {
        obj.insert(QString("overage"), ::InvenTree::toJsonValue(m_overage));
    }
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_part_isSet) {
        obj.insert(QString("part"), ::InvenTree::toJsonValue(m_part));
    }
    if (m_pricing_min_isSet) {
        obj.insert(QString("pricing_min"), ::InvenTree::toJsonValue(m_pricing_min));
    }
    if (m_pricing_max_isSet) {
        obj.insert(QString("pricing_max"), ::InvenTree::toJsonValue(m_pricing_max));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    if (m_reference_isSet) {
        obj.insert(QString("reference"), ::InvenTree::toJsonValue(m_reference));
    }
    if (m_sub_part_isSet) {
        obj.insert(QString("sub_part"), ::InvenTree::toJsonValue(m_sub_part));
    }
    if (m_substitutes.size() > 0) {
        obj.insert(QString("substitutes"), ::InvenTree::toJsonValue(m_substitutes));
    }
    if (m_validated_isSet) {
        obj.insert(QString("validated"), ::InvenTree::toJsonValue(m_validated));
    }
    if (m_available_stock_isSet) {
        obj.insert(QString("available_stock"), ::InvenTree::toJsonValue(m_available_stock));
    }
    if (m_available_substitute_stock_isSet) {
        obj.insert(QString("available_substitute_stock"), ::InvenTree::toJsonValue(m_available_substitute_stock));
    }
    if (m_available_variant_stock_isSet) {
        obj.insert(QString("available_variant_stock"), ::InvenTree::toJsonValue(m_available_variant_stock));
    }
    if (m_external_stock_isSet) {
        obj.insert(QString("external_stock"), ::InvenTree::toJsonValue(m_external_stock));
    }
    if (m_on_order_isSet) {
        obj.insert(QString("on_order"), ::InvenTree::toJsonValue(m_on_order));
    }
    if (m_building_isSet) {
        obj.insert(QString("building"), ::InvenTree::toJsonValue(m_building));
    }
    return obj;
}

bool PatchedBomItem::isAllowVariants() const {
    return m_allow_variants;
}
void PatchedBomItem::setAllowVariants(const bool &allow_variants) {
    m_allow_variants = allow_variants;
    m_allow_variants_isSet = true;
}

bool PatchedBomItem::is_allow_variants_Set() const{
    return m_allow_variants_isSet;
}

bool PatchedBomItem::is_allow_variants_Valid() const{
    return m_allow_variants_isValid;
}

bool PatchedBomItem::isInherited() const {
    return m_inherited;
}
void PatchedBomItem::setInherited(const bool &inherited) {
    m_inherited = inherited;
    m_inherited_isSet = true;
}

bool PatchedBomItem::is_inherited_Set() const{
    return m_inherited_isSet;
}

bool PatchedBomItem::is_inherited_Valid() const{
    return m_inherited_isValid;
}

QString PatchedBomItem::getNote() const {
    return m_note;
}
void PatchedBomItem::setNote(const QString &note) {
    m_note = note;
    m_note_isSet = true;
}

bool PatchedBomItem::is_note_Set() const{
    return m_note_isSet;
}

bool PatchedBomItem::is_note_Valid() const{
    return m_note_isValid;
}

bool PatchedBomItem::isOptional() const {
    return m_optional;
}
void PatchedBomItem::setOptional(const bool &optional) {
    m_optional = optional;
    m_optional_isSet = true;
}

bool PatchedBomItem::is_optional_Set() const{
    return m_optional_isSet;
}

bool PatchedBomItem::is_optional_Valid() const{
    return m_optional_isValid;
}

bool PatchedBomItem::isConsumable() const {
    return m_consumable;
}
void PatchedBomItem::setConsumable(const bool &consumable) {
    m_consumable = consumable;
    m_consumable_isSet = true;
}

bool PatchedBomItem::is_consumable_Set() const{
    return m_consumable_isSet;
}

bool PatchedBomItem::is_consumable_Valid() const{
    return m_consumable_isValid;
}

QString PatchedBomItem::getOverage() const {
    return m_overage;
}
void PatchedBomItem::setOverage(const QString &overage) {
    m_overage = overage;
    m_overage_isSet = true;
}

bool PatchedBomItem::is_overage_Set() const{
    return m_overage_isSet;
}

bool PatchedBomItem::is_overage_Valid() const{
    return m_overage_isValid;
}

qint32 PatchedBomItem::getPk() const {
    return m_pk;
}
void PatchedBomItem::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedBomItem::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedBomItem::is_pk_Valid() const{
    return m_pk_isValid;
}

qint32 PatchedBomItem::getPart() const {
    return m_part;
}
void PatchedBomItem::setPart(const qint32 &part) {
    m_part = part;
    m_part_isSet = true;
}

bool PatchedBomItem::is_part_Set() const{
    return m_part_isSet;
}

bool PatchedBomItem::is_part_Valid() const{
    return m_part_isValid;
}

QString PatchedBomItem::getPricingMin() const {
    return m_pricing_min;
}
void PatchedBomItem::setPricingMin(const QString &pricing_min) {
    m_pricing_min = pricing_min;
    m_pricing_min_isSet = true;
}

bool PatchedBomItem::is_pricing_min_Set() const{
    return m_pricing_min_isSet;
}

bool PatchedBomItem::is_pricing_min_Valid() const{
    return m_pricing_min_isValid;
}

QString PatchedBomItem::getPricingMax() const {
    return m_pricing_max;
}
void PatchedBomItem::setPricingMax(const QString &pricing_max) {
    m_pricing_max = pricing_max;
    m_pricing_max_isSet = true;
}

bool PatchedBomItem::is_pricing_max_Set() const{
    return m_pricing_max_isSet;
}

bool PatchedBomItem::is_pricing_max_Valid() const{
    return m_pricing_max_isValid;
}

double PatchedBomItem::getQuantity() const {
    return m_quantity;
}
void PatchedBomItem::setQuantity(const double &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool PatchedBomItem::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool PatchedBomItem::is_quantity_Valid() const{
    return m_quantity_isValid;
}

QString PatchedBomItem::getReference() const {
    return m_reference;
}
void PatchedBomItem::setReference(const QString &reference) {
    m_reference = reference;
    m_reference_isSet = true;
}

bool PatchedBomItem::is_reference_Set() const{
    return m_reference_isSet;
}

bool PatchedBomItem::is_reference_Valid() const{
    return m_reference_isValid;
}

qint32 PatchedBomItem::getSubPart() const {
    return m_sub_part;
}
void PatchedBomItem::setSubPart(const qint32 &sub_part) {
    m_sub_part = sub_part;
    m_sub_part_isSet = true;
}

bool PatchedBomItem::is_sub_part_Set() const{
    return m_sub_part_isSet;
}

bool PatchedBomItem::is_sub_part_Valid() const{
    return m_sub_part_isValid;
}

QList<BomItemSubstitute> PatchedBomItem::getSubstitutes() const {
    return m_substitutes;
}
void PatchedBomItem::setSubstitutes(const QList<BomItemSubstitute> &substitutes) {
    m_substitutes = substitutes;
    m_substitutes_isSet = true;
}

bool PatchedBomItem::is_substitutes_Set() const{
    return m_substitutes_isSet;
}

bool PatchedBomItem::is_substitutes_Valid() const{
    return m_substitutes_isValid;
}

bool PatchedBomItem::isValidated() const {
    return m_validated;
}
void PatchedBomItem::setValidated(const bool &validated) {
    m_validated = validated;
    m_validated_isSet = true;
}

bool PatchedBomItem::is_validated_Set() const{
    return m_validated_isSet;
}

bool PatchedBomItem::is_validated_Valid() const{
    return m_validated_isValid;
}

double PatchedBomItem::getAvailableStock() const {
    return m_available_stock;
}
void PatchedBomItem::setAvailableStock(const double &available_stock) {
    m_available_stock = available_stock;
    m_available_stock_isSet = true;
}

bool PatchedBomItem::is_available_stock_Set() const{
    return m_available_stock_isSet;
}

bool PatchedBomItem::is_available_stock_Valid() const{
    return m_available_stock_isValid;
}

double PatchedBomItem::getAvailableSubstituteStock() const {
    return m_available_substitute_stock;
}
void PatchedBomItem::setAvailableSubstituteStock(const double &available_substitute_stock) {
    m_available_substitute_stock = available_substitute_stock;
    m_available_substitute_stock_isSet = true;
}

bool PatchedBomItem::is_available_substitute_stock_Set() const{
    return m_available_substitute_stock_isSet;
}

bool PatchedBomItem::is_available_substitute_stock_Valid() const{
    return m_available_substitute_stock_isValid;
}

double PatchedBomItem::getAvailableVariantStock() const {
    return m_available_variant_stock;
}
void PatchedBomItem::setAvailableVariantStock(const double &available_variant_stock) {
    m_available_variant_stock = available_variant_stock;
    m_available_variant_stock_isSet = true;
}

bool PatchedBomItem::is_available_variant_stock_Set() const{
    return m_available_variant_stock_isSet;
}

bool PatchedBomItem::is_available_variant_stock_Valid() const{
    return m_available_variant_stock_isValid;
}

double PatchedBomItem::getExternalStock() const {
    return m_external_stock;
}
void PatchedBomItem::setExternalStock(const double &external_stock) {
    m_external_stock = external_stock;
    m_external_stock_isSet = true;
}

bool PatchedBomItem::is_external_stock_Set() const{
    return m_external_stock_isSet;
}

bool PatchedBomItem::is_external_stock_Valid() const{
    return m_external_stock_isValid;
}

double PatchedBomItem::getOnOrder() const {
    return m_on_order;
}
void PatchedBomItem::setOnOrder(const double &on_order) {
    m_on_order = on_order;
    m_on_order_isSet = true;
}

bool PatchedBomItem::is_on_order_Set() const{
    return m_on_order_isSet;
}

bool PatchedBomItem::is_on_order_Valid() const{
    return m_on_order_isValid;
}

double PatchedBomItem::getBuilding() const {
    return m_building;
}
void PatchedBomItem::setBuilding(const double &building) {
    m_building = building;
    m_building_isSet = true;
}

bool PatchedBomItem::is_building_Set() const{
    return m_building_isSet;
}

bool PatchedBomItem::is_building_Valid() const{
    return m_building_isValid;
}

bool PatchedBomItem::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_allow_variants_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_inherited_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_note_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_optional_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_consumable_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_overage_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_part_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_pricing_min_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_pricing_max_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_reference_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_sub_part_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_substitutes.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_validated_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_available_stock_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_available_substitute_stock_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_available_variant_stock_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_external_stock_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_on_order_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_building_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedBomItem::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
