/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedStockItemTestResult.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedStockItemTestResult::PatchedStockItemTestResult(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedStockItemTestResult::PatchedStockItemTestResult() {
    this->initializeModel();
}

PatchedStockItemTestResult::~PatchedStockItemTestResult() {}

void PatchedStockItemTestResult::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_stock_item_isSet = false;
    m_stock_item_isValid = false;

    m_result_isSet = false;
    m_result_isValid = false;

    m_value_isSet = false;
    m_value_isValid = false;

    m_attachment_isSet = false;
    m_attachment_isValid = false;

    m_notes_isSet = false;
    m_notes_isValid = false;

    m_test_station_isSet = false;
    m_test_station_isValid = false;

    m_started_datetime_isSet = false;
    m_started_datetime_isValid = false;

    m_finished_datetime_isSet = false;
    m_finished_datetime_isValid = false;

    m_user_isSet = false;
    m_user_isValid = false;

    m_user_detail_isSet = false;
    m_user_detail_isValid = false;

    m_date_isSet = false;
    m_date_isValid = false;

    m_r_template_isSet = false;
    m_r_template_isValid = false;

    m_template_detail_isSet = false;
    m_template_detail_isValid = false;
}

void PatchedStockItemTestResult::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedStockItemTestResult::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_stock_item_isValid = ::InvenTree::fromJsonValue(m_stock_item, json[QString("stock_item")]);
    m_stock_item_isSet = !json[QString("stock_item")].isNull() && m_stock_item_isValid;

    m_result_isValid = ::InvenTree::fromJsonValue(m_result, json[QString("result")]);
    m_result_isSet = !json[QString("result")].isNull() && m_result_isValid;

    m_value_isValid = ::InvenTree::fromJsonValue(m_value, json[QString("value")]);
    m_value_isSet = !json[QString("value")].isNull() && m_value_isValid;

    m_attachment_isValid = ::InvenTree::fromJsonValue(m_attachment, json[QString("attachment")]);
    m_attachment_isSet = !json[QString("attachment")].isNull() && m_attachment_isValid;

    m_notes_isValid = ::InvenTree::fromJsonValue(m_notes, json[QString("notes")]);
    m_notes_isSet = !json[QString("notes")].isNull() && m_notes_isValid;

    m_test_station_isValid = ::InvenTree::fromJsonValue(m_test_station, json[QString("test_station")]);
    m_test_station_isSet = !json[QString("test_station")].isNull() && m_test_station_isValid;

    m_started_datetime_isValid = ::InvenTree::fromJsonValue(m_started_datetime, json[QString("started_datetime")]);
    m_started_datetime_isSet = !json[QString("started_datetime")].isNull() && m_started_datetime_isValid;

    m_finished_datetime_isValid = ::InvenTree::fromJsonValue(m_finished_datetime, json[QString("finished_datetime")]);
    m_finished_datetime_isSet = !json[QString("finished_datetime")].isNull() && m_finished_datetime_isValid;

    m_user_isValid = ::InvenTree::fromJsonValue(m_user, json[QString("user")]);
    m_user_isSet = !json[QString("user")].isNull() && m_user_isValid;

    m_user_detail_isValid = ::InvenTree::fromJsonValue(m_user_detail, json[QString("user_detail")]);
    m_user_detail_isSet = !json[QString("user_detail")].isNull() && m_user_detail_isValid;

    m_date_isValid = ::InvenTree::fromJsonValue(m_date, json[QString("date")]);
    m_date_isSet = !json[QString("date")].isNull() && m_date_isValid;

    m_r_template_isValid = ::InvenTree::fromJsonValue(m_r_template, json[QString("template")]);
    m_r_template_isSet = !json[QString("template")].isNull() && m_r_template_isValid;

    m_template_detail_isValid = ::InvenTree::fromJsonValue(m_template_detail, json[QString("template_detail")]);
    m_template_detail_isSet = !json[QString("template_detail")].isNull() && m_template_detail_isValid;
}

QString PatchedStockItemTestResult::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedStockItemTestResult::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_stock_item_isSet) {
        obj.insert(QString("stock_item"), ::InvenTree::toJsonValue(m_stock_item));
    }
    if (m_result_isSet) {
        obj.insert(QString("result"), ::InvenTree::toJsonValue(m_result));
    }
    if (m_value_isSet) {
        obj.insert(QString("value"), ::InvenTree::toJsonValue(m_value));
    }
    if (m_attachment_isSet) {
        obj.insert(QString("attachment"), ::InvenTree::toJsonValue(m_attachment));
    }
    if (m_notes_isSet) {
        obj.insert(QString("notes"), ::InvenTree::toJsonValue(m_notes));
    }
    if (m_test_station_isSet) {
        obj.insert(QString("test_station"), ::InvenTree::toJsonValue(m_test_station));
    }
    if (m_started_datetime_isSet) {
        obj.insert(QString("started_datetime"), ::InvenTree::toJsonValue(m_started_datetime));
    }
    if (m_finished_datetime_isSet) {
        obj.insert(QString("finished_datetime"), ::InvenTree::toJsonValue(m_finished_datetime));
    }
    if (m_user_isSet) {
        obj.insert(QString("user"), ::InvenTree::toJsonValue(m_user));
    }
    if (m_user_detail.isSet()) {
        obj.insert(QString("user_detail"), ::InvenTree::toJsonValue(m_user_detail));
    }
    if (m_date_isSet) {
        obj.insert(QString("date"), ::InvenTree::toJsonValue(m_date));
    }
    if (m_r_template_isSet) {
        obj.insert(QString("template"), ::InvenTree::toJsonValue(m_r_template));
    }
    if (m_template_detail.isSet()) {
        obj.insert(QString("template_detail"), ::InvenTree::toJsonValue(m_template_detail));
    }
    return obj;
}

QMap<QString, QString> PatchedStockItemTestResult::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> PatchedStockItemTestResult::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_pk_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("pk"), namePrefix), m_pk);
    }
    if (m_stock_item_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("stock_item"), namePrefix), m_stock_item);
    }
    if (m_result_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("result"), namePrefix), m_result);
    }
    if (m_value_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("value"), namePrefix), m_value);
    }
    if (m_attachment_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("attachment"), namePrefix), m_attachment);
    }
    if (m_notes_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("notes"), namePrefix), m_notes);
    }
    if (m_test_station_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("test_station"), namePrefix), m_test_station);
    }
    if (m_started_datetime_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("started_datetime"), namePrefix), m_started_datetime);
    }
    if (m_finished_datetime_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("finished_datetime"), namePrefix), m_finished_datetime);
    }
    if (m_user_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("user"), namePrefix), m_user);
    }
    if (m_user_detail.isSet()) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("user_detail"), namePrefix), m_user_detail);
    }
    if (m_date_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("date"), namePrefix), m_date);
    }
    if (m_r_template_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("template"), namePrefix), m_r_template);
    }
    if (m_template_detail.isSet()) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("template_detail"), namePrefix), m_template_detail);
    }
    return vars;
}

QList<HttpFileElement> PatchedStockItemTestResult::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> PatchedStockItemTestResult::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_pk_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("pk"), namePrefix), m_pk);
    }
    if (m_stock_item_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("stock_item"), namePrefix), m_stock_item);
    }
    if (m_result_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("result"), namePrefix), m_result);
    }
    if (m_value_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("value"), namePrefix), m_value);
    }
    if (m_attachment_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("attachment"), namePrefix), m_attachment);
    }
    if (m_notes_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("notes"), namePrefix), m_notes);
    }
    if (m_test_station_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("test_station"), namePrefix), m_test_station);
    }
    if (m_started_datetime_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("started_datetime"), namePrefix), m_started_datetime);
    }
    if (m_finished_datetime_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("finished_datetime"), namePrefix), m_finished_datetime);
    }
    if (m_user_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("user"), namePrefix), m_user);
    }
    if (m_user_detail.isSet()) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("user_detail"), namePrefix), m_user_detail);
    }
    if (m_date_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("date"), namePrefix), m_date);
    }
    if (m_r_template_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("template"), namePrefix), m_r_template);
    }
    if (m_template_detail.isSet()) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("template_detail"), namePrefix), m_template_detail);
    }
    return files;
}

qint32 PatchedStockItemTestResult::getPk() const {
    return m_pk;
}
void PatchedStockItemTestResult::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedStockItemTestResult::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedStockItemTestResult::is_pk_Valid() const{
    return m_pk_isValid;
}

qint32 PatchedStockItemTestResult::getStockItem() const {
    return m_stock_item;
}
void PatchedStockItemTestResult::setStockItem(const qint32 &stock_item) {
    m_stock_item = stock_item;
    m_stock_item_isSet = true;
}

bool PatchedStockItemTestResult::is_stock_item_Set() const{
    return m_stock_item_isSet;
}

bool PatchedStockItemTestResult::is_stock_item_Valid() const{
    return m_stock_item_isValid;
}

bool PatchedStockItemTestResult::isResult() const {
    return m_result;
}
void PatchedStockItemTestResult::setResult(const bool &result) {
    m_result = result;
    m_result_isSet = true;
}

bool PatchedStockItemTestResult::is_result_Set() const{
    return m_result_isSet;
}

bool PatchedStockItemTestResult::is_result_Valid() const{
    return m_result_isValid;
}

QString PatchedStockItemTestResult::getValue() const {
    return m_value;
}
void PatchedStockItemTestResult::setValue(const QString &value) {
    m_value = value;
    m_value_isSet = true;
}

bool PatchedStockItemTestResult::is_value_Set() const{
    return m_value_isSet;
}

bool PatchedStockItemTestResult::is_value_Valid() const{
    return m_value_isValid;
}

QString PatchedStockItemTestResult::getAttachment() const {
    return m_attachment;
}
void PatchedStockItemTestResult::setAttachment(const QString &attachment) {
    m_attachment = attachment;
    m_attachment_isSet = true;
}

bool PatchedStockItemTestResult::is_attachment_Set() const{
    return m_attachment_isSet;
}

bool PatchedStockItemTestResult::is_attachment_Valid() const{
    return m_attachment_isValid;
}

QString PatchedStockItemTestResult::getNotes() const {
    return m_notes;
}
void PatchedStockItemTestResult::setNotes(const QString &notes) {
    m_notes = notes;
    m_notes_isSet = true;
}

bool PatchedStockItemTestResult::is_notes_Set() const{
    return m_notes_isSet;
}

bool PatchedStockItemTestResult::is_notes_Valid() const{
    return m_notes_isValid;
}

QString PatchedStockItemTestResult::getTestStation() const {
    return m_test_station;
}
void PatchedStockItemTestResult::setTestStation(const QString &test_station) {
    m_test_station = test_station;
    m_test_station_isSet = true;
}

bool PatchedStockItemTestResult::is_test_station_Set() const{
    return m_test_station_isSet;
}

bool PatchedStockItemTestResult::is_test_station_Valid() const{
    return m_test_station_isValid;
}

QDateTime PatchedStockItemTestResult::getStartedDatetime() const {
    return m_started_datetime;
}
void PatchedStockItemTestResult::setStartedDatetime(const QDateTime &started_datetime) {
    m_started_datetime = started_datetime;
    m_started_datetime_isSet = true;
}

bool PatchedStockItemTestResult::is_started_datetime_Set() const{
    return m_started_datetime_isSet;
}

bool PatchedStockItemTestResult::is_started_datetime_Valid() const{
    return m_started_datetime_isValid;
}

QDateTime PatchedStockItemTestResult::getFinishedDatetime() const {
    return m_finished_datetime;
}
void PatchedStockItemTestResult::setFinishedDatetime(const QDateTime &finished_datetime) {
    m_finished_datetime = finished_datetime;
    m_finished_datetime_isSet = true;
}

bool PatchedStockItemTestResult::is_finished_datetime_Set() const{
    return m_finished_datetime_isSet;
}

bool PatchedStockItemTestResult::is_finished_datetime_Valid() const{
    return m_finished_datetime_isValid;
}

qint32 PatchedStockItemTestResult::getUser() const {
    return m_user;
}
void PatchedStockItemTestResult::setUser(const qint32 &user) {
    m_user = user;
    m_user_isSet = true;
}

bool PatchedStockItemTestResult::is_user_Set() const{
    return m_user_isSet;
}

bool PatchedStockItemTestResult::is_user_Valid() const{
    return m_user_isValid;
}

User PatchedStockItemTestResult::getUserDetail() const {
    return m_user_detail;
}
void PatchedStockItemTestResult::setUserDetail(const User &user_detail) {
    m_user_detail = user_detail;
    m_user_detail_isSet = true;
}

bool PatchedStockItemTestResult::is_user_detail_Set() const{
    return m_user_detail_isSet;
}

bool PatchedStockItemTestResult::is_user_detail_Valid() const{
    return m_user_detail_isValid;
}

QDateTime PatchedStockItemTestResult::getDate() const {
    return m_date;
}
void PatchedStockItemTestResult::setDate(const QDateTime &date) {
    m_date = date;
    m_date_isSet = true;
}

bool PatchedStockItemTestResult::is_date_Set() const{
    return m_date_isSet;
}

bool PatchedStockItemTestResult::is_date_Valid() const{
    return m_date_isValid;
}

qint32 PatchedStockItemTestResult::getRTemplate() const {
    return m_r_template;
}
void PatchedStockItemTestResult::setRTemplate(const qint32 &r_template) {
    m_r_template = r_template;
    m_r_template_isSet = true;
}

bool PatchedStockItemTestResult::is_r_template_Set() const{
    return m_r_template_isSet;
}

bool PatchedStockItemTestResult::is_r_template_Valid() const{
    return m_r_template_isValid;
}

PartTestTemplate PatchedStockItemTestResult::getTemplateDetail() const {
    return m_template_detail;
}
void PatchedStockItemTestResult::setTemplateDetail(const PartTestTemplate &template_detail) {
    m_template_detail = template_detail;
    m_template_detail_isSet = true;
}

bool PatchedStockItemTestResult::is_template_detail_Set() const{
    return m_template_detail_isSet;
}

bool PatchedStockItemTestResult::is_template_detail_Valid() const{
    return m_template_detail_isValid;
}

bool PatchedStockItemTestResult::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_stock_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_result_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_value_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_attachment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_notes_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_test_station_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_started_datetime_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_finished_datetime_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_r_template_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_template_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedStockItemTestResult::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
