/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedContact.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedContact::PatchedContact(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedContact::PatchedContact() {
    this->initializeModel();
}

PatchedContact::~PatchedContact() {}

void PatchedContact::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_company_isSet = false;
    m_company_isValid = false;

    m_company_name_isSet = false;
    m_company_name_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_phone_isSet = false;
    m_phone_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;

    m_role_isSet = false;
    m_role_isValid = false;
}

void PatchedContact::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedContact::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_company_isValid = ::InvenTree::fromJsonValue(m_company, json[QString("company")]);
    m_company_isSet = !json[QString("company")].isNull() && m_company_isValid;

    m_company_name_isValid = ::InvenTree::fromJsonValue(m_company_name, json[QString("company_name")]);
    m_company_name_isSet = !json[QString("company_name")].isNull() && m_company_name_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_phone_isValid = ::InvenTree::fromJsonValue(m_phone, json[QString("phone")]);
    m_phone_isSet = !json[QString("phone")].isNull() && m_phone_isValid;

    m_email_isValid = ::InvenTree::fromJsonValue(m_email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;

    m_role_isValid = ::InvenTree::fromJsonValue(m_role, json[QString("role")]);
    m_role_isSet = !json[QString("role")].isNull() && m_role_isValid;
}

QString PatchedContact::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedContact::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_company_isSet) {
        obj.insert(QString("company"), ::InvenTree::toJsonValue(m_company));
    }
    if (m_company_name_isSet) {
        obj.insert(QString("company_name"), ::InvenTree::toJsonValue(m_company_name));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_phone_isSet) {
        obj.insert(QString("phone"), ::InvenTree::toJsonValue(m_phone));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::InvenTree::toJsonValue(m_email));
    }
    if (m_role_isSet) {
        obj.insert(QString("role"), ::InvenTree::toJsonValue(m_role));
    }
    return obj;
}

qint32 PatchedContact::getPk() const {
    return m_pk;
}
void PatchedContact::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedContact::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedContact::is_pk_Valid() const{
    return m_pk_isValid;
}

qint32 PatchedContact::getCompany() const {
    return m_company;
}
void PatchedContact::setCompany(const qint32 &company) {
    m_company = company;
    m_company_isSet = true;
}

bool PatchedContact::is_company_Set() const{
    return m_company_isSet;
}

bool PatchedContact::is_company_Valid() const{
    return m_company_isValid;
}

QString PatchedContact::getCompanyName() const {
    return m_company_name;
}
void PatchedContact::setCompanyName(const QString &company_name) {
    m_company_name = company_name;
    m_company_name_isSet = true;
}

bool PatchedContact::is_company_name_Set() const{
    return m_company_name_isSet;
}

bool PatchedContact::is_company_name_Valid() const{
    return m_company_name_isValid;
}

QString PatchedContact::getName() const {
    return m_name;
}
void PatchedContact::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool PatchedContact::is_name_Set() const{
    return m_name_isSet;
}

bool PatchedContact::is_name_Valid() const{
    return m_name_isValid;
}

QString PatchedContact::getPhone() const {
    return m_phone;
}
void PatchedContact::setPhone(const QString &phone) {
    m_phone = phone;
    m_phone_isSet = true;
}

bool PatchedContact::is_phone_Set() const{
    return m_phone_isSet;
}

bool PatchedContact::is_phone_Valid() const{
    return m_phone_isValid;
}

QString PatchedContact::getEmail() const {
    return m_email;
}
void PatchedContact::setEmail(const QString &email) {
    m_email = email;
    m_email_isSet = true;
}

bool PatchedContact::is_email_Set() const{
    return m_email_isSet;
}

bool PatchedContact::is_email_Valid() const{
    return m_email_isValid;
}

QString PatchedContact::getRole() const {
    return m_role;
}
void PatchedContact::setRole(const QString &role) {
    m_role = role;
    m_role_isSet = true;
}

bool PatchedContact::is_role_Set() const{
    return m_role_isSet;
}

bool PatchedContact::is_role_Valid() const{
    return m_role_isValid;
}

bool PatchedContact::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_company_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_company_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_phone_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_role_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedContact::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
