/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 225
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedDataImportSession.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedDataImportSession::PatchedDataImportSession(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedDataImportSession::PatchedDataImportSession() {
    this->initializeModel();
}

PatchedDataImportSession::~PatchedDataImportSession() {}

void PatchedDataImportSession::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_timestamp_isSet = false;
    m_timestamp_isValid = false;

    m_data_file_isSet = false;
    m_data_file_isValid = false;

    m_model_type_isSet = false;
    m_model_type_isValid = false;

    m_available_fields_isSet = false;
    m_available_fields_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;

    m_user_isSet = false;
    m_user_isValid = false;

    m_user_detail_isSet = false;
    m_user_detail_isValid = false;

    m_columns_isSet = false;
    m_columns_isValid = false;

    m_column_mappings_isSet = false;
    m_column_mappings_isValid = false;

    m_field_defaults_isSet = false;
    m_field_defaults_isValid = false;

    m_field_overrides_isSet = false;
    m_field_overrides_isValid = false;

    m_field_filters_isSet = false;
    m_field_filters_isValid = false;

    m_row_count_isSet = false;
    m_row_count_isValid = false;

    m_completed_row_count_isSet = false;
    m_completed_row_count_isValid = false;
}

void PatchedDataImportSession::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedDataImportSession::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_timestamp_isValid = ::InvenTree::fromJsonValue(m_timestamp, json[QString("timestamp")]);
    m_timestamp_isSet = !json[QString("timestamp")].isNull() && m_timestamp_isValid;

    m_data_file_isValid = ::InvenTree::fromJsonValue(m_data_file, json[QString("data_file")]);
    m_data_file_isSet = !json[QString("data_file")].isNull() && m_data_file_isValid;

    m_model_type_isValid = ::InvenTree::fromJsonValue(m_model_type, json[QString("model_type")]);
    m_model_type_isSet = !json[QString("model_type")].isNull() && m_model_type_isValid;

    m_available_fields_isValid = ::InvenTree::fromJsonValue(m_available_fields, json[QString("available_fields")]);
    m_available_fields_isSet = !json[QString("available_fields")].isNull() && m_available_fields_isValid;

    m_status_isValid = ::InvenTree::fromJsonValue(m_status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;

    m_user_isValid = ::InvenTree::fromJsonValue(m_user, json[QString("user")]);
    m_user_isSet = !json[QString("user")].isNull() && m_user_isValid;

    m_user_detail_isValid = ::InvenTree::fromJsonValue(m_user_detail, json[QString("user_detail")]);
    m_user_detail_isSet = !json[QString("user_detail")].isNull() && m_user_detail_isValid;

    m_columns_isValid = ::InvenTree::fromJsonValue(m_columns, json[QString("columns")]);
    m_columns_isSet = !json[QString("columns")].isNull() && m_columns_isValid;

    m_column_mappings_isValid = ::InvenTree::fromJsonValue(m_column_mappings, json[QString("column_mappings")]);
    m_column_mappings_isSet = !json[QString("column_mappings")].isNull() && m_column_mappings_isValid;

    m_field_defaults_isValid = ::InvenTree::fromJsonValue(m_field_defaults, json[QString("field_defaults")]);
    m_field_defaults_isSet = !json[QString("field_defaults")].isNull() && m_field_defaults_isValid;

    m_field_overrides_isValid = ::InvenTree::fromJsonValue(m_field_overrides, json[QString("field_overrides")]);
    m_field_overrides_isSet = !json[QString("field_overrides")].isNull() && m_field_overrides_isValid;

    m_field_filters_isValid = ::InvenTree::fromJsonValue(m_field_filters, json[QString("field_filters")]);
    m_field_filters_isSet = !json[QString("field_filters")].isNull() && m_field_filters_isValid;

    m_row_count_isValid = ::InvenTree::fromJsonValue(m_row_count, json[QString("row_count")]);
    m_row_count_isSet = !json[QString("row_count")].isNull() && m_row_count_isValid;

    m_completed_row_count_isValid = ::InvenTree::fromJsonValue(m_completed_row_count, json[QString("completed_row_count")]);
    m_completed_row_count_isSet = !json[QString("completed_row_count")].isNull() && m_completed_row_count_isValid;
}

QString PatchedDataImportSession::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedDataImportSession::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_timestamp_isSet) {
        obj.insert(QString("timestamp"), ::InvenTree::toJsonValue(m_timestamp));
    }
    if (m_data_file_isSet) {
        obj.insert(QString("data_file"), ::InvenTree::toJsonValue(m_data_file));
    }
    if (m_model_type.isSet()) {
        obj.insert(QString("model_type"), ::InvenTree::toJsonValue(m_model_type));
    }
    if (m_available_fields_isSet) {
        obj.insert(QString("available_fields"), ::InvenTree::toJsonValue(m_available_fields));
    }
    if (m_status.isSet()) {
        obj.insert(QString("status"), ::InvenTree::toJsonValue(m_status));
    }
    if (m_user_isSet) {
        obj.insert(QString("user"), ::InvenTree::toJsonValue(m_user));
    }
    if (m_user_detail.isSet()) {
        obj.insert(QString("user_detail"), ::InvenTree::toJsonValue(m_user_detail));
    }
    if (m_columns_isSet) {
        obj.insert(QString("columns"), ::InvenTree::toJsonValue(m_columns));
    }
    if (m_column_mappings.size() > 0) {
        obj.insert(QString("column_mappings"), ::InvenTree::toJsonValue(m_column_mappings));
    }
    if (m_field_defaults_isSet) {
        obj.insert(QString("field_defaults"), ::InvenTree::toJsonValue(m_field_defaults));
    }
    if (m_field_overrides_isSet) {
        obj.insert(QString("field_overrides"), ::InvenTree::toJsonValue(m_field_overrides));
    }
    if (m_field_filters_isSet) {
        obj.insert(QString("field_filters"), ::InvenTree::toJsonValue(m_field_filters));
    }
    if (m_row_count_isSet) {
        obj.insert(QString("row_count"), ::InvenTree::toJsonValue(m_row_count));
    }
    if (m_completed_row_count_isSet) {
        obj.insert(QString("completed_row_count"), ::InvenTree::toJsonValue(m_completed_row_count));
    }
    return obj;
}

qint32 PatchedDataImportSession::getPk() const {
    return m_pk;
}
void PatchedDataImportSession::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedDataImportSession::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedDataImportSession::is_pk_Valid() const{
    return m_pk_isValid;
}

QDateTime PatchedDataImportSession::getTimestamp() const {
    return m_timestamp;
}
void PatchedDataImportSession::setTimestamp(const QDateTime &timestamp) {
    m_timestamp = timestamp;
    m_timestamp_isSet = true;
}

bool PatchedDataImportSession::is_timestamp_Set() const{
    return m_timestamp_isSet;
}

bool PatchedDataImportSession::is_timestamp_Valid() const{
    return m_timestamp_isValid;
}

QString PatchedDataImportSession::getDataFile() const {
    return m_data_file;
}
void PatchedDataImportSession::setDataFile(const QString &data_file) {
    m_data_file = data_file;
    m_data_file_isSet = true;
}

bool PatchedDataImportSession::is_data_file_Set() const{
    return m_data_file_isSet;
}

bool PatchedDataImportSession::is_data_file_Valid() const{
    return m_data_file_isValid;
}

DataImportSessionModelTypeEnum PatchedDataImportSession::getModelType() const {
    return m_model_type;
}
void PatchedDataImportSession::setModelType(const DataImportSessionModelTypeEnum &model_type) {
    m_model_type = model_type;
    m_model_type_isSet = true;
}

bool PatchedDataImportSession::is_model_type_Set() const{
    return m_model_type_isSet;
}

bool PatchedDataImportSession::is_model_type_Valid() const{
    return m_model_type_isValid;
}

QJsonValue PatchedDataImportSession::getAvailableFields() const {
    return m_available_fields;
}
void PatchedDataImportSession::setAvailableFields(const QJsonValue &available_fields) {
    m_available_fields = available_fields;
    m_available_fields_isSet = true;
}

bool PatchedDataImportSession::is_available_fields_Set() const{
    return m_available_fields_isSet;
}

bool PatchedDataImportSession::is_available_fields_Valid() const{
    return m_available_fields_isValid;
}

DataImportSessionStatusEnum PatchedDataImportSession::getStatus() const {
    return m_status;
}
void PatchedDataImportSession::setStatus(const DataImportSessionStatusEnum &status) {
    m_status = status;
    m_status_isSet = true;
}

bool PatchedDataImportSession::is_status_Set() const{
    return m_status_isSet;
}

bool PatchedDataImportSession::is_status_Valid() const{
    return m_status_isValid;
}

qint32 PatchedDataImportSession::getUser() const {
    return m_user;
}
void PatchedDataImportSession::setUser(const qint32 &user) {
    m_user = user;
    m_user_isSet = true;
}

bool PatchedDataImportSession::is_user_Set() const{
    return m_user_isSet;
}

bool PatchedDataImportSession::is_user_Valid() const{
    return m_user_isValid;
}

User PatchedDataImportSession::getUserDetail() const {
    return m_user_detail;
}
void PatchedDataImportSession::setUserDetail(const User &user_detail) {
    m_user_detail = user_detail;
    m_user_detail_isSet = true;
}

bool PatchedDataImportSession::is_user_detail_Set() const{
    return m_user_detail_isSet;
}

bool PatchedDataImportSession::is_user_detail_Valid() const{
    return m_user_detail_isValid;
}

QJsonValue PatchedDataImportSession::getColumns() const {
    return m_columns;
}
void PatchedDataImportSession::setColumns(const QJsonValue &columns) {
    m_columns = columns;
    m_columns_isSet = true;
}

bool PatchedDataImportSession::is_columns_Set() const{
    return m_columns_isSet;
}

bool PatchedDataImportSession::is_columns_Valid() const{
    return m_columns_isValid;
}

QList<DataImportColumnMap> PatchedDataImportSession::getColumnMappings() const {
    return m_column_mappings;
}
void PatchedDataImportSession::setColumnMappings(const QList<DataImportColumnMap> &column_mappings) {
    m_column_mappings = column_mappings;
    m_column_mappings_isSet = true;
}

bool PatchedDataImportSession::is_column_mappings_Set() const{
    return m_column_mappings_isSet;
}

bool PatchedDataImportSession::is_column_mappings_Valid() const{
    return m_column_mappings_isValid;
}

QJsonValue PatchedDataImportSession::getFieldDefaults() const {
    return m_field_defaults;
}
void PatchedDataImportSession::setFieldDefaults(const QJsonValue &field_defaults) {
    m_field_defaults = field_defaults;
    m_field_defaults_isSet = true;
}

bool PatchedDataImportSession::is_field_defaults_Set() const{
    return m_field_defaults_isSet;
}

bool PatchedDataImportSession::is_field_defaults_Valid() const{
    return m_field_defaults_isValid;
}

QJsonValue PatchedDataImportSession::getFieldOverrides() const {
    return m_field_overrides;
}
void PatchedDataImportSession::setFieldOverrides(const QJsonValue &field_overrides) {
    m_field_overrides = field_overrides;
    m_field_overrides_isSet = true;
}

bool PatchedDataImportSession::is_field_overrides_Set() const{
    return m_field_overrides_isSet;
}

bool PatchedDataImportSession::is_field_overrides_Valid() const{
    return m_field_overrides_isValid;
}

QJsonValue PatchedDataImportSession::getFieldFilters() const {
    return m_field_filters;
}
void PatchedDataImportSession::setFieldFilters(const QJsonValue &field_filters) {
    m_field_filters = field_filters;
    m_field_filters_isSet = true;
}

bool PatchedDataImportSession::is_field_filters_Set() const{
    return m_field_filters_isSet;
}

bool PatchedDataImportSession::is_field_filters_Valid() const{
    return m_field_filters_isValid;
}

qint32 PatchedDataImportSession::getRowCount() const {
    return m_row_count;
}
void PatchedDataImportSession::setRowCount(const qint32 &row_count) {
    m_row_count = row_count;
    m_row_count_isSet = true;
}

bool PatchedDataImportSession::is_row_count_Set() const{
    return m_row_count_isSet;
}

bool PatchedDataImportSession::is_row_count_Valid() const{
    return m_row_count_isValid;
}

qint32 PatchedDataImportSession::getCompletedRowCount() const {
    return m_completed_row_count;
}
void PatchedDataImportSession::setCompletedRowCount(const qint32 &completed_row_count) {
    m_completed_row_count = completed_row_count;
    m_completed_row_count_isSet = true;
}

bool PatchedDataImportSession::is_completed_row_count_Set() const{
    return m_completed_row_count_isSet;
}

bool PatchedDataImportSession::is_completed_row_count_Valid() const{
    return m_completed_row_count_isValid;
}

bool PatchedDataImportSession::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_timestamp_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_data_file_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_model_type.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_available_fields_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_columns_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_column_mappings.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_field_defaults_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_field_overrides_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_field_filters_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_row_count_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_completed_row_count_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedDataImportSession::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
