/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedRuleSet.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedRuleSet::PatchedRuleSet(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedRuleSet::PatchedRuleSet() {
    this->initializeModel();
}

PatchedRuleSet::~PatchedRuleSet() {}

void PatchedRuleSet::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_label_isSet = false;
    m_label_isValid = false;

    m_group_isSet = false;
    m_group_isValid = false;

    m_can_view_isSet = false;
    m_can_view_isValid = false;

    m_can_add_isSet = false;
    m_can_add_isValid = false;

    m_can_change_isSet = false;
    m_can_change_isValid = false;

    m_can_delete_isSet = false;
    m_can_delete_isValid = false;
}

void PatchedRuleSet::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedRuleSet::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_label_isValid = ::InvenTree::fromJsonValue(m_label, json[QString("label")]);
    m_label_isSet = !json[QString("label")].isNull() && m_label_isValid;

    m_group_isValid = ::InvenTree::fromJsonValue(m_group, json[QString("group")]);
    m_group_isSet = !json[QString("group")].isNull() && m_group_isValid;

    m_can_view_isValid = ::InvenTree::fromJsonValue(m_can_view, json[QString("can_view")]);
    m_can_view_isSet = !json[QString("can_view")].isNull() && m_can_view_isValid;

    m_can_add_isValid = ::InvenTree::fromJsonValue(m_can_add, json[QString("can_add")]);
    m_can_add_isSet = !json[QString("can_add")].isNull() && m_can_add_isValid;

    m_can_change_isValid = ::InvenTree::fromJsonValue(m_can_change, json[QString("can_change")]);
    m_can_change_isSet = !json[QString("can_change")].isNull() && m_can_change_isValid;

    m_can_delete_isValid = ::InvenTree::fromJsonValue(m_can_delete, json[QString("can_delete")]);
    m_can_delete_isSet = !json[QString("can_delete")].isNull() && m_can_delete_isValid;
}

QString PatchedRuleSet::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedRuleSet::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_name.isSet()) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_label_isSet) {
        obj.insert(QString("label"), ::InvenTree::toJsonValue(m_label));
    }
    if (m_group_isSet) {
        obj.insert(QString("group"), ::InvenTree::toJsonValue(m_group));
    }
    if (m_can_view_isSet) {
        obj.insert(QString("can_view"), ::InvenTree::toJsonValue(m_can_view));
    }
    if (m_can_add_isSet) {
        obj.insert(QString("can_add"), ::InvenTree::toJsonValue(m_can_add));
    }
    if (m_can_change_isSet) {
        obj.insert(QString("can_change"), ::InvenTree::toJsonValue(m_can_change));
    }
    if (m_can_delete_isSet) {
        obj.insert(QString("can_delete"), ::InvenTree::toJsonValue(m_can_delete));
    }
    return obj;
}

qint32 PatchedRuleSet::getPk() const {
    return m_pk;
}
void PatchedRuleSet::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedRuleSet::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedRuleSet::is_pk_Valid() const{
    return m_pk_isValid;
}

NameEnum PatchedRuleSet::getName() const {
    return m_name;
}
void PatchedRuleSet::setName(const NameEnum &name) {
    m_name = name;
    m_name_isSet = true;
}

bool PatchedRuleSet::is_name_Set() const{
    return m_name_isSet;
}

bool PatchedRuleSet::is_name_Valid() const{
    return m_name_isValid;
}

QString PatchedRuleSet::getLabel() const {
    return m_label;
}
void PatchedRuleSet::setLabel(const QString &label) {
    m_label = label;
    m_label_isSet = true;
}

bool PatchedRuleSet::is_label_Set() const{
    return m_label_isSet;
}

bool PatchedRuleSet::is_label_Valid() const{
    return m_label_isValid;
}

qint32 PatchedRuleSet::getGroup() const {
    return m_group;
}
void PatchedRuleSet::setGroup(const qint32 &group) {
    m_group = group;
    m_group_isSet = true;
}

bool PatchedRuleSet::is_group_Set() const{
    return m_group_isSet;
}

bool PatchedRuleSet::is_group_Valid() const{
    return m_group_isValid;
}

bool PatchedRuleSet::isCanView() const {
    return m_can_view;
}
void PatchedRuleSet::setCanView(const bool &can_view) {
    m_can_view = can_view;
    m_can_view_isSet = true;
}

bool PatchedRuleSet::is_can_view_Set() const{
    return m_can_view_isSet;
}

bool PatchedRuleSet::is_can_view_Valid() const{
    return m_can_view_isValid;
}

bool PatchedRuleSet::isCanAdd() const {
    return m_can_add;
}
void PatchedRuleSet::setCanAdd(const bool &can_add) {
    m_can_add = can_add;
    m_can_add_isSet = true;
}

bool PatchedRuleSet::is_can_add_Set() const{
    return m_can_add_isSet;
}

bool PatchedRuleSet::is_can_add_Valid() const{
    return m_can_add_isValid;
}

bool PatchedRuleSet::isCanChange() const {
    return m_can_change;
}
void PatchedRuleSet::setCanChange(const bool &can_change) {
    m_can_change = can_change;
    m_can_change_isSet = true;
}

bool PatchedRuleSet::is_can_change_Set() const{
    return m_can_change_isSet;
}

bool PatchedRuleSet::is_can_change_Valid() const{
    return m_can_change_isValid;
}

bool PatchedRuleSet::isCanDelete() const {
    return m_can_delete;
}
void PatchedRuleSet::setCanDelete(const bool &can_delete) {
    m_can_delete = can_delete;
    m_can_delete_isSet = true;
}

bool PatchedRuleSet::is_can_delete_Set() const{
    return m_can_delete_isSet;
}

bool PatchedRuleSet::is_can_delete_Valid() const{
    return m_can_delete_isValid;
}

bool PatchedRuleSet::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_label_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_group_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_can_view_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_can_add_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_can_change_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_can_delete_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedRuleSet::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
