/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 158
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedSalesOrderAttachment.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedSalesOrderAttachment::PatchedSalesOrderAttachment(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedSalesOrderAttachment::PatchedSalesOrderAttachment() {
    this->initializeModel();
}

PatchedSalesOrderAttachment::~PatchedSalesOrderAttachment() {}

void PatchedSalesOrderAttachment::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_attachment_isSet = false;
    m_attachment_isValid = false;

    m_filename_isSet = false;
    m_filename_isValid = false;

    m_link_isSet = false;
    m_link_isValid = false;

    m_comment_isSet = false;
    m_comment_isValid = false;

    m_upload_date_isSet = false;
    m_upload_date_isValid = false;

    m_user_isSet = false;
    m_user_isValid = false;

    m_user_detail_isSet = false;
    m_user_detail_isValid = false;

    m_order_isSet = false;
    m_order_isValid = false;
}

void PatchedSalesOrderAttachment::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedSalesOrderAttachment::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_attachment_isValid = ::InvenTree::fromJsonValue(m_attachment, json[QString("attachment")]);
    m_attachment_isSet = !json[QString("attachment")].isNull() && m_attachment_isValid;

    m_filename_isValid = ::InvenTree::fromJsonValue(m_filename, json[QString("filename")]);
    m_filename_isSet = !json[QString("filename")].isNull() && m_filename_isValid;

    m_link_isValid = ::InvenTree::fromJsonValue(m_link, json[QString("link")]);
    m_link_isSet = !json[QString("link")].isNull() && m_link_isValid;

    m_comment_isValid = ::InvenTree::fromJsonValue(m_comment, json[QString("comment")]);
    m_comment_isSet = !json[QString("comment")].isNull() && m_comment_isValid;

    m_upload_date_isValid = ::InvenTree::fromJsonValue(m_upload_date, json[QString("upload_date")]);
    m_upload_date_isSet = !json[QString("upload_date")].isNull() && m_upload_date_isValid;

    m_user_isValid = ::InvenTree::fromJsonValue(m_user, json[QString("user")]);
    m_user_isSet = !json[QString("user")].isNull() && m_user_isValid;

    m_user_detail_isValid = ::InvenTree::fromJsonValue(m_user_detail, json[QString("user_detail")]);
    m_user_detail_isSet = !json[QString("user_detail")].isNull() && m_user_detail_isValid;

    m_order_isValid = ::InvenTree::fromJsonValue(m_order, json[QString("order")]);
    m_order_isSet = !json[QString("order")].isNull() && m_order_isValid;
}

QString PatchedSalesOrderAttachment::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedSalesOrderAttachment::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_attachment_isSet) {
        obj.insert(QString("attachment"), ::InvenTree::toJsonValue(m_attachment));
    }
    if (m_filename_isSet) {
        obj.insert(QString("filename"), ::InvenTree::toJsonValue(m_filename));
    }
    if (m_link_isSet) {
        obj.insert(QString("link"), ::InvenTree::toJsonValue(m_link));
    }
    if (m_comment_isSet) {
        obj.insert(QString("comment"), ::InvenTree::toJsonValue(m_comment));
    }
    if (m_upload_date_isSet) {
        obj.insert(QString("upload_date"), ::InvenTree::toJsonValue(m_upload_date));
    }
    if (m_user_isSet) {
        obj.insert(QString("user"), ::InvenTree::toJsonValue(m_user));
    }
    if (m_user_detail.isSet()) {
        obj.insert(QString("user_detail"), ::InvenTree::toJsonValue(m_user_detail));
    }
    if (m_order_isSet) {
        obj.insert(QString("order"), ::InvenTree::toJsonValue(m_order));
    }
    return obj;
}

qint32 PatchedSalesOrderAttachment::getPk() const {
    return m_pk;
}
void PatchedSalesOrderAttachment::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedSalesOrderAttachment::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedSalesOrderAttachment::is_pk_Valid() const{
    return m_pk_isValid;
}

QString PatchedSalesOrderAttachment::getAttachment() const {
    return m_attachment;
}
void PatchedSalesOrderAttachment::setAttachment(const QString &attachment) {
    m_attachment = attachment;
    m_attachment_isSet = true;
}

bool PatchedSalesOrderAttachment::is_attachment_Set() const{
    return m_attachment_isSet;
}

bool PatchedSalesOrderAttachment::is_attachment_Valid() const{
    return m_attachment_isValid;
}

QString PatchedSalesOrderAttachment::getFilename() const {
    return m_filename;
}
void PatchedSalesOrderAttachment::setFilename(const QString &filename) {
    m_filename = filename;
    m_filename_isSet = true;
}

bool PatchedSalesOrderAttachment::is_filename_Set() const{
    return m_filename_isSet;
}

bool PatchedSalesOrderAttachment::is_filename_Valid() const{
    return m_filename_isValid;
}

QString PatchedSalesOrderAttachment::getLink() const {
    return m_link;
}
void PatchedSalesOrderAttachment::setLink(const QString &link) {
    m_link = link;
    m_link_isSet = true;
}

bool PatchedSalesOrderAttachment::is_link_Set() const{
    return m_link_isSet;
}

bool PatchedSalesOrderAttachment::is_link_Valid() const{
    return m_link_isValid;
}

QString PatchedSalesOrderAttachment::getComment() const {
    return m_comment;
}
void PatchedSalesOrderAttachment::setComment(const QString &comment) {
    m_comment = comment;
    m_comment_isSet = true;
}

bool PatchedSalesOrderAttachment::is_comment_Set() const{
    return m_comment_isSet;
}

bool PatchedSalesOrderAttachment::is_comment_Valid() const{
    return m_comment_isValid;
}

QDate PatchedSalesOrderAttachment::getUploadDate() const {
    return m_upload_date;
}
void PatchedSalesOrderAttachment::setUploadDate(const QDate &upload_date) {
    m_upload_date = upload_date;
    m_upload_date_isSet = true;
}

bool PatchedSalesOrderAttachment::is_upload_date_Set() const{
    return m_upload_date_isSet;
}

bool PatchedSalesOrderAttachment::is_upload_date_Valid() const{
    return m_upload_date_isValid;
}

qint32 PatchedSalesOrderAttachment::getUser() const {
    return m_user;
}
void PatchedSalesOrderAttachment::setUser(const qint32 &user) {
    m_user = user;
    m_user_isSet = true;
}

bool PatchedSalesOrderAttachment::is_user_Set() const{
    return m_user_isSet;
}

bool PatchedSalesOrderAttachment::is_user_Valid() const{
    return m_user_isValid;
}

User PatchedSalesOrderAttachment::getUserDetail() const {
    return m_user_detail;
}
void PatchedSalesOrderAttachment::setUserDetail(const User &user_detail) {
    m_user_detail = user_detail;
    m_user_detail_isSet = true;
}

bool PatchedSalesOrderAttachment::is_user_detail_Set() const{
    return m_user_detail_isSet;
}

bool PatchedSalesOrderAttachment::is_user_detail_Valid() const{
    return m_user_detail_isValid;
}

qint32 PatchedSalesOrderAttachment::getOrder() const {
    return m_order;
}
void PatchedSalesOrderAttachment::setOrder(const qint32 &order) {
    m_order = order;
    m_order_isSet = true;
}

bool PatchedSalesOrderAttachment::is_order_Set() const{
    return m_order_isSet;
}

bool PatchedSalesOrderAttachment::is_order_Valid() const{
    return m_order_isValid;
}

bool PatchedSalesOrderAttachment::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_attachment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_filename_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_link_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_comment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_upload_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_order_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedSalesOrderAttachment::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
