/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 158
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedStockLocationReport.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedStockLocationReport::PatchedStockLocationReport(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedStockLocationReport::PatchedStockLocationReport() {
    this->initializeModel();
}

PatchedStockLocationReport::~PatchedStockLocationReport() {}

void PatchedStockLocationReport::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_r_template_isSet = false;
    m_r_template_isValid = false;

    m_filters_isSet = false;
    m_filters_isValid = false;

    m_enabled_isSet = false;
    m_enabled_isValid = false;
}

void PatchedStockLocationReport::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedStockLocationReport::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_description_isValid = ::InvenTree::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_r_template_isValid = ::InvenTree::fromJsonValue(m_r_template, json[QString("template")]);
    m_r_template_isSet = !json[QString("template")].isNull() && m_r_template_isValid;

    m_filters_isValid = ::InvenTree::fromJsonValue(m_filters, json[QString("filters")]);
    m_filters_isSet = !json[QString("filters")].isNull() && m_filters_isValid;

    m_enabled_isValid = ::InvenTree::fromJsonValue(m_enabled, json[QString("enabled")]);
    m_enabled_isSet = !json[QString("enabled")].isNull() && m_enabled_isValid;
}

QString PatchedStockLocationReport::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedStockLocationReport::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::InvenTree::toJsonValue(m_description));
    }
    if (m_r_template_isSet) {
        obj.insert(QString("template"), ::InvenTree::toJsonValue(m_r_template));
    }
    if (m_filters_isSet) {
        obj.insert(QString("filters"), ::InvenTree::toJsonValue(m_filters));
    }
    if (m_enabled_isSet) {
        obj.insert(QString("enabled"), ::InvenTree::toJsonValue(m_enabled));
    }
    return obj;
}

qint32 PatchedStockLocationReport::getPk() const {
    return m_pk;
}
void PatchedStockLocationReport::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedStockLocationReport::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedStockLocationReport::is_pk_Valid() const{
    return m_pk_isValid;
}

QString PatchedStockLocationReport::getName() const {
    return m_name;
}
void PatchedStockLocationReport::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool PatchedStockLocationReport::is_name_Set() const{
    return m_name_isSet;
}

bool PatchedStockLocationReport::is_name_Valid() const{
    return m_name_isValid;
}

QString PatchedStockLocationReport::getDescription() const {
    return m_description;
}
void PatchedStockLocationReport::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool PatchedStockLocationReport::is_description_Set() const{
    return m_description_isSet;
}

bool PatchedStockLocationReport::is_description_Valid() const{
    return m_description_isValid;
}

QString PatchedStockLocationReport::getRTemplate() const {
    return m_r_template;
}
void PatchedStockLocationReport::setRTemplate(const QString &r_template) {
    m_r_template = r_template;
    m_r_template_isSet = true;
}

bool PatchedStockLocationReport::is_r_template_Set() const{
    return m_r_template_isSet;
}

bool PatchedStockLocationReport::is_r_template_Valid() const{
    return m_r_template_isValid;
}

QString PatchedStockLocationReport::getFilters() const {
    return m_filters;
}
void PatchedStockLocationReport::setFilters(const QString &filters) {
    m_filters = filters;
    m_filters_isSet = true;
}

bool PatchedStockLocationReport::is_filters_Set() const{
    return m_filters_isSet;
}

bool PatchedStockLocationReport::is_filters_Valid() const{
    return m_filters_isValid;
}

bool PatchedStockLocationReport::isEnabled() const {
    return m_enabled;
}
void PatchedStockLocationReport::setEnabled(const bool &enabled) {
    m_enabled = enabled;
    m_enabled_isSet = true;
}

bool PatchedStockLocationReport::is_enabled_Set() const{
    return m_enabled_isSet;
}

bool PatchedStockLocationReport::is_enabled_Valid() const{
    return m_enabled_isValid;
}

bool PatchedStockLocationReport::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_r_template_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_filters_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_enabled_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedStockLocationReport::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
