/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedSelectionEntry.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedSelectionEntry::PatchedSelectionEntry(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedSelectionEntry::PatchedSelectionEntry() {
    this->initializeModel();
}

PatchedSelectionEntry::~PatchedSelectionEntry() {}

void PatchedSelectionEntry::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_value_isSet = false;
    m_value_isValid = false;

    m_label_isSet = false;
    m_label_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_active_isSet = false;
    m_active_isValid = false;

    m_list_isSet = false;
    m_list_isValid = false;
}

void PatchedSelectionEntry::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedSelectionEntry::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::InvenTree::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_value_isValid = ::InvenTree::fromJsonValue(m_value, json[QString("value")]);
    m_value_isSet = !json[QString("value")].isNull() && m_value_isValid;

    m_label_isValid = ::InvenTree::fromJsonValue(m_label, json[QString("label")]);
    m_label_isSet = !json[QString("label")].isNull() && m_label_isValid;

    m_description_isValid = ::InvenTree::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_active_isValid = ::InvenTree::fromJsonValue(m_active, json[QString("active")]);
    m_active_isSet = !json[QString("active")].isNull() && m_active_isValid;

    m_list_isValid = ::InvenTree::fromJsonValue(m_list, json[QString("list")]);
    m_list_isSet = !json[QString("list")].isNull() && m_list_isValid;
}

QString PatchedSelectionEntry::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedSelectionEntry::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::InvenTree::toJsonValue(m_id));
    }
    if (m_value_isSet) {
        obj.insert(QString("value"), ::InvenTree::toJsonValue(m_value));
    }
    if (m_label_isSet) {
        obj.insert(QString("label"), ::InvenTree::toJsonValue(m_label));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::InvenTree::toJsonValue(m_description));
    }
    if (m_active_isSet) {
        obj.insert(QString("active"), ::InvenTree::toJsonValue(m_active));
    }
    if (m_list_isSet) {
        obj.insert(QString("list"), ::InvenTree::toJsonValue(m_list));
    }
    return obj;
}

qint32 PatchedSelectionEntry::getId() const {
    return m_id;
}
void PatchedSelectionEntry::setId(const qint32 &id) {
    m_id = id;
    m_id_isSet = true;
}

bool PatchedSelectionEntry::is_id_Set() const{
    return m_id_isSet;
}

bool PatchedSelectionEntry::is_id_Valid() const{
    return m_id_isValid;
}

QString PatchedSelectionEntry::getValue() const {
    return m_value;
}
void PatchedSelectionEntry::setValue(const QString &value) {
    m_value = value;
    m_value_isSet = true;
}

bool PatchedSelectionEntry::is_value_Set() const{
    return m_value_isSet;
}

bool PatchedSelectionEntry::is_value_Valid() const{
    return m_value_isValid;
}

QString PatchedSelectionEntry::getLabel() const {
    return m_label;
}
void PatchedSelectionEntry::setLabel(const QString &label) {
    m_label = label;
    m_label_isSet = true;
}

bool PatchedSelectionEntry::is_label_Set() const{
    return m_label_isSet;
}

bool PatchedSelectionEntry::is_label_Valid() const{
    return m_label_isValid;
}

QString PatchedSelectionEntry::getDescription() const {
    return m_description;
}
void PatchedSelectionEntry::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool PatchedSelectionEntry::is_description_Set() const{
    return m_description_isSet;
}

bool PatchedSelectionEntry::is_description_Valid() const{
    return m_description_isValid;
}

bool PatchedSelectionEntry::isActive() const {
    return m_active;
}
void PatchedSelectionEntry::setActive(const bool &active) {
    m_active = active;
    m_active_isSet = true;
}

bool PatchedSelectionEntry::is_active_Set() const{
    return m_active_isSet;
}

bool PatchedSelectionEntry::is_active_Valid() const{
    return m_active_isValid;
}

qint32 PatchedSelectionEntry::getList() const {
    return m_list;
}
void PatchedSelectionEntry::setList(const qint32 &list) {
    m_list = list;
    m_list_isSet = true;
}

bool PatchedSelectionEntry::is_list_Set() const{
    return m_list_isSet;
}

bool PatchedSelectionEntry::is_list_Valid() const{
    return m_list_isValid;
}

bool PatchedSelectionEntry::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_value_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_label_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_active_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_list_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedSelectionEntry::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
