/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 225
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedSalesOrderAllocation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedSalesOrderAllocation::PatchedSalesOrderAllocation(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedSalesOrderAllocation::PatchedSalesOrderAllocation() {
    this->initializeModel();
}

PatchedSalesOrderAllocation::~PatchedSalesOrderAllocation() {}

void PatchedSalesOrderAllocation::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_line_isSet = false;
    m_line_isValid = false;

    m_serial_isSet = false;
    m_serial_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;

    m_location_isSet = false;
    m_location_isValid = false;

    m_item_isSet = false;
    m_item_isValid = false;

    m_item_detail_isSet = false;
    m_item_detail_isValid = false;

    m_order_isSet = false;
    m_order_isValid = false;

    m_part_isSet = false;
    m_part_isValid = false;

    m_part_detail_isSet = false;
    m_part_detail_isValid = false;

    m_shipment_isSet = false;
    m_shipment_isValid = false;

    m_shipment_date_isSet = false;
    m_shipment_date_isValid = false;
}

void PatchedSalesOrderAllocation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedSalesOrderAllocation::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_line_isValid = ::InvenTree::fromJsonValue(m_line, json[QString("line")]);
    m_line_isSet = !json[QString("line")].isNull() && m_line_isValid;

    m_serial_isValid = ::InvenTree::fromJsonValue(m_serial, json[QString("serial")]);
    m_serial_isSet = !json[QString("serial")].isNull() && m_serial_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;

    m_location_isValid = ::InvenTree::fromJsonValue(m_location, json[QString("location")]);
    m_location_isSet = !json[QString("location")].isNull() && m_location_isValid;

    m_item_isValid = ::InvenTree::fromJsonValue(m_item, json[QString("item")]);
    m_item_isSet = !json[QString("item")].isNull() && m_item_isValid;

    m_item_detail_isValid = ::InvenTree::fromJsonValue(m_item_detail, json[QString("item_detail")]);
    m_item_detail_isSet = !json[QString("item_detail")].isNull() && m_item_detail_isValid;

    m_order_isValid = ::InvenTree::fromJsonValue(m_order, json[QString("order")]);
    m_order_isSet = !json[QString("order")].isNull() && m_order_isValid;

    m_part_isValid = ::InvenTree::fromJsonValue(m_part, json[QString("part")]);
    m_part_isSet = !json[QString("part")].isNull() && m_part_isValid;

    m_part_detail_isValid = ::InvenTree::fromJsonValue(m_part_detail, json[QString("part_detail")]);
    m_part_detail_isSet = !json[QString("part_detail")].isNull() && m_part_detail_isValid;

    m_shipment_isValid = ::InvenTree::fromJsonValue(m_shipment, json[QString("shipment")]);
    m_shipment_isSet = !json[QString("shipment")].isNull() && m_shipment_isValid;

    m_shipment_date_isValid = ::InvenTree::fromJsonValue(m_shipment_date, json[QString("shipment_date")]);
    m_shipment_date_isSet = !json[QString("shipment_date")].isNull() && m_shipment_date_isValid;
}

QString PatchedSalesOrderAllocation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedSalesOrderAllocation::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_line_isSet) {
        obj.insert(QString("line"), ::InvenTree::toJsonValue(m_line));
    }
    if (m_serial_isSet) {
        obj.insert(QString("serial"), ::InvenTree::toJsonValue(m_serial));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    if (m_location_isSet) {
        obj.insert(QString("location"), ::InvenTree::toJsonValue(m_location));
    }
    if (m_item_isSet) {
        obj.insert(QString("item"), ::InvenTree::toJsonValue(m_item));
    }
    if (m_item_detail.isSet()) {
        obj.insert(QString("item_detail"), ::InvenTree::toJsonValue(m_item_detail));
    }
    if (m_order_isSet) {
        obj.insert(QString("order"), ::InvenTree::toJsonValue(m_order));
    }
    if (m_part_isSet) {
        obj.insert(QString("part"), ::InvenTree::toJsonValue(m_part));
    }
    if (m_part_detail.isSet()) {
        obj.insert(QString("part_detail"), ::InvenTree::toJsonValue(m_part_detail));
    }
    if (m_shipment_isSet) {
        obj.insert(QString("shipment"), ::InvenTree::toJsonValue(m_shipment));
    }
    if (m_shipment_date_isSet) {
        obj.insert(QString("shipment_date"), ::InvenTree::toJsonValue(m_shipment_date));
    }
    return obj;
}

qint32 PatchedSalesOrderAllocation::getPk() const {
    return m_pk;
}
void PatchedSalesOrderAllocation::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedSalesOrderAllocation::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedSalesOrderAllocation::is_pk_Valid() const{
    return m_pk_isValid;
}

qint32 PatchedSalesOrderAllocation::getLine() const {
    return m_line;
}
void PatchedSalesOrderAllocation::setLine(const qint32 &line) {
    m_line = line;
    m_line_isSet = true;
}

bool PatchedSalesOrderAllocation::is_line_Set() const{
    return m_line_isSet;
}

bool PatchedSalesOrderAllocation::is_line_Valid() const{
    return m_line_isValid;
}

QString PatchedSalesOrderAllocation::getSerial() const {
    return m_serial;
}
void PatchedSalesOrderAllocation::setSerial(const QString &serial) {
    m_serial = serial;
    m_serial_isSet = true;
}

bool PatchedSalesOrderAllocation::is_serial_Set() const{
    return m_serial_isSet;
}

bool PatchedSalesOrderAllocation::is_serial_Valid() const{
    return m_serial_isValid;
}

double PatchedSalesOrderAllocation::getQuantity() const {
    return m_quantity;
}
void PatchedSalesOrderAllocation::setQuantity(const double &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool PatchedSalesOrderAllocation::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool PatchedSalesOrderAllocation::is_quantity_Valid() const{
    return m_quantity_isValid;
}

qint32 PatchedSalesOrderAllocation::getLocation() const {
    return m_location;
}
void PatchedSalesOrderAllocation::setLocation(const qint32 &location) {
    m_location = location;
    m_location_isSet = true;
}

bool PatchedSalesOrderAllocation::is_location_Set() const{
    return m_location_isSet;
}

bool PatchedSalesOrderAllocation::is_location_Valid() const{
    return m_location_isValid;
}

qint32 PatchedSalesOrderAllocation::getItem() const {
    return m_item;
}
void PatchedSalesOrderAllocation::setItem(const qint32 &item) {
    m_item = item;
    m_item_isSet = true;
}

bool PatchedSalesOrderAllocation::is_item_Set() const{
    return m_item_isSet;
}

bool PatchedSalesOrderAllocation::is_item_Valid() const{
    return m_item_isValid;
}

StockItem PatchedSalesOrderAllocation::getItemDetail() const {
    return m_item_detail;
}
void PatchedSalesOrderAllocation::setItemDetail(const StockItem &item_detail) {
    m_item_detail = item_detail;
    m_item_detail_isSet = true;
}

bool PatchedSalesOrderAllocation::is_item_detail_Set() const{
    return m_item_detail_isSet;
}

bool PatchedSalesOrderAllocation::is_item_detail_Valid() const{
    return m_item_detail_isValid;
}

qint32 PatchedSalesOrderAllocation::getOrder() const {
    return m_order;
}
void PatchedSalesOrderAllocation::setOrder(const qint32 &order) {
    m_order = order;
    m_order_isSet = true;
}

bool PatchedSalesOrderAllocation::is_order_Set() const{
    return m_order_isSet;
}

bool PatchedSalesOrderAllocation::is_order_Valid() const{
    return m_order_isValid;
}

qint32 PatchedSalesOrderAllocation::getPart() const {
    return m_part;
}
void PatchedSalesOrderAllocation::setPart(const qint32 &part) {
    m_part = part;
    m_part_isSet = true;
}

bool PatchedSalesOrderAllocation::is_part_Set() const{
    return m_part_isSet;
}

bool PatchedSalesOrderAllocation::is_part_Valid() const{
    return m_part_isValid;
}

PartBrief PatchedSalesOrderAllocation::getPartDetail() const {
    return m_part_detail;
}
void PatchedSalesOrderAllocation::setPartDetail(const PartBrief &part_detail) {
    m_part_detail = part_detail;
    m_part_detail_isSet = true;
}

bool PatchedSalesOrderAllocation::is_part_detail_Set() const{
    return m_part_detail_isSet;
}

bool PatchedSalesOrderAllocation::is_part_detail_Valid() const{
    return m_part_detail_isValid;
}

qint32 PatchedSalesOrderAllocation::getShipment() const {
    return m_shipment;
}
void PatchedSalesOrderAllocation::setShipment(const qint32 &shipment) {
    m_shipment = shipment;
    m_shipment_isSet = true;
}

bool PatchedSalesOrderAllocation::is_shipment_Set() const{
    return m_shipment_isSet;
}

bool PatchedSalesOrderAllocation::is_shipment_Valid() const{
    return m_shipment_isValid;
}

QDate PatchedSalesOrderAllocation::getShipmentDate() const {
    return m_shipment_date;
}
void PatchedSalesOrderAllocation::setShipmentDate(const QDate &shipment_date) {
    m_shipment_date = shipment_date;
    m_shipment_date_isSet = true;
}

bool PatchedSalesOrderAllocation::is_shipment_date_Set() const{
    return m_shipment_date_isSet;
}

bool PatchedSalesOrderAllocation::is_shipment_date_Valid() const{
    return m_shipment_date_isValid;
}

bool PatchedSalesOrderAllocation::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_line_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_serial_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_location_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_item_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_order_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_part_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_part_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_shipment_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_shipment_date_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedSalesOrderAllocation::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
