/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 225
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PatchedPartParameter.h
 *
 * JSON serializers for the PartParameter model.
 */

#ifndef PatchedPartParameter_H
#define PatchedPartParameter_H

#include <QJsonObject>

#include "PartParameterTemplate.h"
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {
class PartParameterTemplate;

class PatchedPartParameter : public Object {
public:
    PatchedPartParameter();
    PatchedPartParameter(QString json);
    ~PatchedPartParameter() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    qint32 getPart() const;
    void setPart(const qint32 &part);
    bool is_part_Set() const;
    bool is_part_Valid() const;

    qint32 getRTemplate() const;
    void setRTemplate(const qint32 &r_template);
    bool is_r_template_Set() const;
    bool is_r_template_Valid() const;

    PartParameterTemplate getTemplateDetail() const;
    void setTemplateDetail(const PartParameterTemplate &template_detail);
    bool is_template_detail_Set() const;
    bool is_template_detail_Valid() const;

    QString getData() const;
    void setData(const QString &data);
    bool is_data_Set() const;
    bool is_data_Valid() const;

    double getDataNumeric() const;
    void setDataNumeric(const double &data_numeric);
    bool is_data_numeric_Set() const;
    bool is_data_numeric_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    qint32 m_part;
    bool m_part_isSet;
    bool m_part_isValid;

    qint32 m_r_template;
    bool m_r_template_isSet;
    bool m_r_template_isValid;

    PartParameterTemplate m_template_detail;
    bool m_template_detail_isSet;
    bool m_template_detail_isValid;

    QString m_data;
    bool m_data_isSet;
    bool m_data_isValid;

    double m_data_numeric;
    bool m_data_numeric_isSet;
    bool m_data_numeric_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::PatchedPartParameter)

#endif // PatchedPartParameter_H
