/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PatchedReturnOrderLineItem.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PatchedReturnOrderLineItem::PatchedReturnOrderLineItem(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PatchedReturnOrderLineItem::PatchedReturnOrderLineItem() {
    this->initializeModel();
}

PatchedReturnOrderLineItem::~PatchedReturnOrderLineItem() {}

void PatchedReturnOrderLineItem::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_link_isSet = false;
    m_link_isValid = false;

    m_notes_isSet = false;
    m_notes_isValid = false;

    m_order_isSet = false;
    m_order_isValid = false;

    m_project_code_isSet = false;
    m_project_code_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;

    m_reference_isSet = false;
    m_reference_isValid = false;

    m_target_date_isSet = false;
    m_target_date_isValid = false;

    m_order_detail_isSet = false;
    m_order_detail_isValid = false;

    m_project_code_label_isSet = false;
    m_project_code_label_isValid = false;

    m_project_code_detail_isSet = false;
    m_project_code_detail_isValid = false;

    m_item_isSet = false;
    m_item_isValid = false;

    m_received_date_isSet = false;
    m_received_date_isValid = false;

    m_outcome_isSet = false;
    m_outcome_isValid = false;

    m_price_isSet = false;
    m_price_isValid = false;

    m_price_currency_isSet = false;
    m_price_currency_isValid = false;

    m_item_detail_isSet = false;
    m_item_detail_isValid = false;

    m_part_detail_isSet = false;
    m_part_detail_isValid = false;
}

void PatchedReturnOrderLineItem::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PatchedReturnOrderLineItem::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_link_isValid = ::InvenTree::fromJsonValue(m_link, json[QString("link")]);
    m_link_isSet = !json[QString("link")].isNull() && m_link_isValid;

    m_notes_isValid = ::InvenTree::fromJsonValue(m_notes, json[QString("notes")]);
    m_notes_isSet = !json[QString("notes")].isNull() && m_notes_isValid;

    m_order_isValid = ::InvenTree::fromJsonValue(m_order, json[QString("order")]);
    m_order_isSet = !json[QString("order")].isNull() && m_order_isValid;

    m_project_code_isValid = ::InvenTree::fromJsonValue(m_project_code, json[QString("project_code")]);
    m_project_code_isSet = !json[QString("project_code")].isNull() && m_project_code_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;

    m_reference_isValid = ::InvenTree::fromJsonValue(m_reference, json[QString("reference")]);
    m_reference_isSet = !json[QString("reference")].isNull() && m_reference_isValid;

    m_target_date_isValid = ::InvenTree::fromJsonValue(m_target_date, json[QString("target_date")]);
    m_target_date_isSet = !json[QString("target_date")].isNull() && m_target_date_isValid;

    m_order_detail_isValid = ::InvenTree::fromJsonValue(m_order_detail, json[QString("order_detail")]);
    m_order_detail_isSet = !json[QString("order_detail")].isNull() && m_order_detail_isValid;

    m_project_code_label_isValid = ::InvenTree::fromJsonValue(m_project_code_label, json[QString("project_code_label")]);
    m_project_code_label_isSet = !json[QString("project_code_label")].isNull() && m_project_code_label_isValid;

    m_project_code_detail_isValid = ::InvenTree::fromJsonValue(m_project_code_detail, json[QString("project_code_detail")]);
    m_project_code_detail_isSet = !json[QString("project_code_detail")].isNull() && m_project_code_detail_isValid;

    m_item_isValid = ::InvenTree::fromJsonValue(m_item, json[QString("item")]);
    m_item_isSet = !json[QString("item")].isNull() && m_item_isValid;

    m_received_date_isValid = ::InvenTree::fromJsonValue(m_received_date, json[QString("received_date")]);
    m_received_date_isSet = !json[QString("received_date")].isNull() && m_received_date_isValid;

    m_outcome_isValid = ::InvenTree::fromJsonValue(m_outcome, json[QString("outcome")]);
    m_outcome_isSet = !json[QString("outcome")].isNull() && m_outcome_isValid;

    m_price_isValid = ::InvenTree::fromJsonValue(m_price, json[QString("price")]);
    m_price_isSet = !json[QString("price")].isNull() && m_price_isValid;

    m_price_currency_isValid = ::InvenTree::fromJsonValue(m_price_currency, json[QString("price_currency")]);
    m_price_currency_isSet = !json[QString("price_currency")].isNull() && m_price_currency_isValid;

    m_item_detail_isValid = ::InvenTree::fromJsonValue(m_item_detail, json[QString("item_detail")]);
    m_item_detail_isSet = !json[QString("item_detail")].isNull() && m_item_detail_isValid;

    m_part_detail_isValid = ::InvenTree::fromJsonValue(m_part_detail, json[QString("part_detail")]);
    m_part_detail_isSet = !json[QString("part_detail")].isNull() && m_part_detail_isValid;
}

QString PatchedReturnOrderLineItem::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PatchedReturnOrderLineItem::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_link_isSet) {
        obj.insert(QString("link"), ::InvenTree::toJsonValue(m_link));
    }
    if (m_notes_isSet) {
        obj.insert(QString("notes"), ::InvenTree::toJsonValue(m_notes));
    }
    if (m_order_isSet) {
        obj.insert(QString("order"), ::InvenTree::toJsonValue(m_order));
    }
    if (m_project_code_isSet) {
        obj.insert(QString("project_code"), ::InvenTree::toJsonValue(m_project_code));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    if (m_reference_isSet) {
        obj.insert(QString("reference"), ::InvenTree::toJsonValue(m_reference));
    }
    if (m_target_date_isSet) {
        obj.insert(QString("target_date"), ::InvenTree::toJsonValue(m_target_date));
    }
    if (m_order_detail.isSet()) {
        obj.insert(QString("order_detail"), ::InvenTree::toJsonValue(m_order_detail));
    }
    if (m_project_code_label_isSet) {
        obj.insert(QString("project_code_label"), ::InvenTree::toJsonValue(m_project_code_label));
    }
    if (m_project_code_detail.isSet()) {
        obj.insert(QString("project_code_detail"), ::InvenTree::toJsonValue(m_project_code_detail));
    }
    if (m_item_isSet) {
        obj.insert(QString("item"), ::InvenTree::toJsonValue(m_item));
    }
    if (m_received_date_isSet) {
        obj.insert(QString("received_date"), ::InvenTree::toJsonValue(m_received_date));
    }
    if (m_outcome.isSet()) {
        obj.insert(QString("outcome"), ::InvenTree::toJsonValue(m_outcome));
    }
    if (m_price_isSet) {
        obj.insert(QString("price"), ::InvenTree::toJsonValue(m_price));
    }
    if (m_price_currency_isSet) {
        obj.insert(QString("price_currency"), ::InvenTree::toJsonValue(m_price_currency));
    }
    if (m_item_detail.isSet()) {
        obj.insert(QString("item_detail"), ::InvenTree::toJsonValue(m_item_detail));
    }
    if (m_part_detail.isSet()) {
        obj.insert(QString("part_detail"), ::InvenTree::toJsonValue(m_part_detail));
    }
    return obj;
}

qint32 PatchedReturnOrderLineItem::getPk() const {
    return m_pk;
}
void PatchedReturnOrderLineItem::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PatchedReturnOrderLineItem::is_pk_Set() const{
    return m_pk_isSet;
}

bool PatchedReturnOrderLineItem::is_pk_Valid() const{
    return m_pk_isValid;
}

QString PatchedReturnOrderLineItem::getLink() const {
    return m_link;
}
void PatchedReturnOrderLineItem::setLink(const QString &link) {
    m_link = link;
    m_link_isSet = true;
}

bool PatchedReturnOrderLineItem::is_link_Set() const{
    return m_link_isSet;
}

bool PatchedReturnOrderLineItem::is_link_Valid() const{
    return m_link_isValid;
}

QString PatchedReturnOrderLineItem::getNotes() const {
    return m_notes;
}
void PatchedReturnOrderLineItem::setNotes(const QString &notes) {
    m_notes = notes;
    m_notes_isSet = true;
}

bool PatchedReturnOrderLineItem::is_notes_Set() const{
    return m_notes_isSet;
}

bool PatchedReturnOrderLineItem::is_notes_Valid() const{
    return m_notes_isValid;
}

qint32 PatchedReturnOrderLineItem::getOrder() const {
    return m_order;
}
void PatchedReturnOrderLineItem::setOrder(const qint32 &order) {
    m_order = order;
    m_order_isSet = true;
}

bool PatchedReturnOrderLineItem::is_order_Set() const{
    return m_order_isSet;
}

bool PatchedReturnOrderLineItem::is_order_Valid() const{
    return m_order_isValid;
}

qint32 PatchedReturnOrderLineItem::getProjectCode() const {
    return m_project_code;
}
void PatchedReturnOrderLineItem::setProjectCode(const qint32 &project_code) {
    m_project_code = project_code;
    m_project_code_isSet = true;
}

bool PatchedReturnOrderLineItem::is_project_code_Set() const{
    return m_project_code_isSet;
}

bool PatchedReturnOrderLineItem::is_project_code_Valid() const{
    return m_project_code_isValid;
}

double PatchedReturnOrderLineItem::getQuantity() const {
    return m_quantity;
}
void PatchedReturnOrderLineItem::setQuantity(const double &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool PatchedReturnOrderLineItem::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool PatchedReturnOrderLineItem::is_quantity_Valid() const{
    return m_quantity_isValid;
}

QString PatchedReturnOrderLineItem::getReference() const {
    return m_reference;
}
void PatchedReturnOrderLineItem::setReference(const QString &reference) {
    m_reference = reference;
    m_reference_isSet = true;
}

bool PatchedReturnOrderLineItem::is_reference_Set() const{
    return m_reference_isSet;
}

bool PatchedReturnOrderLineItem::is_reference_Valid() const{
    return m_reference_isValid;
}

QDate PatchedReturnOrderLineItem::getTargetDate() const {
    return m_target_date;
}
void PatchedReturnOrderLineItem::setTargetDate(const QDate &target_date) {
    m_target_date = target_date;
    m_target_date_isSet = true;
}

bool PatchedReturnOrderLineItem::is_target_date_Set() const{
    return m_target_date_isSet;
}

bool PatchedReturnOrderLineItem::is_target_date_Valid() const{
    return m_target_date_isValid;
}

ReturnOrder PatchedReturnOrderLineItem::getOrderDetail() const {
    return m_order_detail;
}
void PatchedReturnOrderLineItem::setOrderDetail(const ReturnOrder &order_detail) {
    m_order_detail = order_detail;
    m_order_detail_isSet = true;
}

bool PatchedReturnOrderLineItem::is_order_detail_Set() const{
    return m_order_detail_isSet;
}

bool PatchedReturnOrderLineItem::is_order_detail_Valid() const{
    return m_order_detail_isValid;
}

QString PatchedReturnOrderLineItem::getProjectCodeLabel() const {
    return m_project_code_label;
}
void PatchedReturnOrderLineItem::setProjectCodeLabel(const QString &project_code_label) {
    m_project_code_label = project_code_label;
    m_project_code_label_isSet = true;
}

bool PatchedReturnOrderLineItem::is_project_code_label_Set() const{
    return m_project_code_label_isSet;
}

bool PatchedReturnOrderLineItem::is_project_code_label_Valid() const{
    return m_project_code_label_isValid;
}

ProjectCode PatchedReturnOrderLineItem::getProjectCodeDetail() const {
    return m_project_code_detail;
}
void PatchedReturnOrderLineItem::setProjectCodeDetail(const ProjectCode &project_code_detail) {
    m_project_code_detail = project_code_detail;
    m_project_code_detail_isSet = true;
}

bool PatchedReturnOrderLineItem::is_project_code_detail_Set() const{
    return m_project_code_detail_isSet;
}

bool PatchedReturnOrderLineItem::is_project_code_detail_Valid() const{
    return m_project_code_detail_isValid;
}

qint32 PatchedReturnOrderLineItem::getItem() const {
    return m_item;
}
void PatchedReturnOrderLineItem::setItem(const qint32 &item) {
    m_item = item;
    m_item_isSet = true;
}

bool PatchedReturnOrderLineItem::is_item_Set() const{
    return m_item_isSet;
}

bool PatchedReturnOrderLineItem::is_item_Valid() const{
    return m_item_isValid;
}

QDate PatchedReturnOrderLineItem::getReceivedDate() const {
    return m_received_date;
}
void PatchedReturnOrderLineItem::setReceivedDate(const QDate &received_date) {
    m_received_date = received_date;
    m_received_date_isSet = true;
}

bool PatchedReturnOrderLineItem::is_received_date_Set() const{
    return m_received_date_isSet;
}

bool PatchedReturnOrderLineItem::is_received_date_Valid() const{
    return m_received_date_isValid;
}

OutcomeEnum PatchedReturnOrderLineItem::getOutcome() const {
    return m_outcome;
}
void PatchedReturnOrderLineItem::setOutcome(const OutcomeEnum &outcome) {
    m_outcome = outcome;
    m_outcome_isSet = true;
}

bool PatchedReturnOrderLineItem::is_outcome_Set() const{
    return m_outcome_isSet;
}

bool PatchedReturnOrderLineItem::is_outcome_Valid() const{
    return m_outcome_isValid;
}

QString PatchedReturnOrderLineItem::getPrice() const {
    return m_price;
}
void PatchedReturnOrderLineItem::setPrice(const QString &price) {
    m_price = price;
    m_price_isSet = true;
}

bool PatchedReturnOrderLineItem::is_price_Set() const{
    return m_price_isSet;
}

bool PatchedReturnOrderLineItem::is_price_Valid() const{
    return m_price_isValid;
}

QString PatchedReturnOrderLineItem::getPriceCurrency() const {
    return m_price_currency;
}
void PatchedReturnOrderLineItem::setPriceCurrency(const QString &price_currency) {
    m_price_currency = price_currency;
    m_price_currency_isSet = true;
}

bool PatchedReturnOrderLineItem::is_price_currency_Set() const{
    return m_price_currency_isSet;
}

bool PatchedReturnOrderLineItem::is_price_currency_Valid() const{
    return m_price_currency_isValid;
}

StockItem PatchedReturnOrderLineItem::getItemDetail() const {
    return m_item_detail;
}
void PatchedReturnOrderLineItem::setItemDetail(const StockItem &item_detail) {
    m_item_detail = item_detail;
    m_item_detail_isSet = true;
}

bool PatchedReturnOrderLineItem::is_item_detail_Set() const{
    return m_item_detail_isSet;
}

bool PatchedReturnOrderLineItem::is_item_detail_Valid() const{
    return m_item_detail_isValid;
}

PartBrief PatchedReturnOrderLineItem::getPartDetail() const {
    return m_part_detail;
}
void PatchedReturnOrderLineItem::setPartDetail(const PartBrief &part_detail) {
    m_part_detail = part_detail;
    m_part_detail_isSet = true;
}

bool PatchedReturnOrderLineItem::is_part_detail_Set() const{
    return m_part_detail_isSet;
}

bool PatchedReturnOrderLineItem::is_part_detail_Valid() const{
    return m_part_detail_isValid;
}

bool PatchedReturnOrderLineItem::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_link_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_notes_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_order_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_project_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_reference_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_target_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_order_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_project_code_label_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_project_code_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_received_date_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_outcome.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_price_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_price_currency_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_item_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_part_detail.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PatchedReturnOrderLineItem::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
