/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PendingTask.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PendingTask::PendingTask(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PendingTask::PendingTask() {
    this->initializeModel();
}

PendingTask::~PendingTask() {}

void PendingTask::initializeModel() {

    m_pk_isSet = false;
    m_pk_isValid = false;

    m_key_isSet = false;
    m_key_isValid = false;

    m_lock_isSet = false;
    m_lock_isValid = false;

    m_task_id_isSet = false;
    m_task_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_func_isSet = false;
    m_func_isValid = false;

    m_args_isSet = false;
    m_args_isValid = false;

    m_kwargs_isSet = false;
    m_kwargs_isValid = false;
}

void PendingTask::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PendingTask::fromJsonObject(QJsonObject json) {

    m_pk_isValid = ::InvenTree::fromJsonValue(m_pk, json[QString("pk")]);
    m_pk_isSet = !json[QString("pk")].isNull() && m_pk_isValid;

    m_key_isValid = ::InvenTree::fromJsonValue(m_key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_lock_isValid = ::InvenTree::fromJsonValue(m_lock, json[QString("lock")]);
    m_lock_isSet = !json[QString("lock")].isNull() && m_lock_isValid;

    m_task_id_isValid = ::InvenTree::fromJsonValue(m_task_id, json[QString("task_id")]);
    m_task_id_isSet = !json[QString("task_id")].isNull() && m_task_id_isValid;

    m_name_isValid = ::InvenTree::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_func_isValid = ::InvenTree::fromJsonValue(m_func, json[QString("func")]);
    m_func_isSet = !json[QString("func")].isNull() && m_func_isValid;

    m_args_isValid = ::InvenTree::fromJsonValue(m_args, json[QString("args")]);
    m_args_isSet = !json[QString("args")].isNull() && m_args_isValid;

    m_kwargs_isValid = ::InvenTree::fromJsonValue(m_kwargs, json[QString("kwargs")]);
    m_kwargs_isSet = !json[QString("kwargs")].isNull() && m_kwargs_isValid;
}

QString PendingTask::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PendingTask::asJsonObject() const {
    QJsonObject obj;
    if (m_pk_isSet) {
        obj.insert(QString("pk"), ::InvenTree::toJsonValue(m_pk));
    }
    if (m_key_isSet) {
        obj.insert(QString("key"), ::InvenTree::toJsonValue(m_key));
    }
    if (m_lock_isSet) {
        obj.insert(QString("lock"), ::InvenTree::toJsonValue(m_lock));
    }
    if (m_task_id_isSet) {
        obj.insert(QString("task_id"), ::InvenTree::toJsonValue(m_task_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::InvenTree::toJsonValue(m_name));
    }
    if (m_func_isSet) {
        obj.insert(QString("func"), ::InvenTree::toJsonValue(m_func));
    }
    if (m_args_isSet) {
        obj.insert(QString("args"), ::InvenTree::toJsonValue(m_args));
    }
    if (m_kwargs_isSet) {
        obj.insert(QString("kwargs"), ::InvenTree::toJsonValue(m_kwargs));
    }
    return obj;
}

QMap<QString, QString> PendingTask::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> PendingTask::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_pk_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("pk"), namePrefix), m_pk);
    }
    if (m_key_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("key"), namePrefix), m_key);
    }
    if (m_lock_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("lock"), namePrefix), m_lock);
    }
    if (m_task_id_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("task_id"), namePrefix), m_task_id);
    }
    if (m_name_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("name"), namePrefix), m_name);
    }
    if (m_func_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("func"), namePrefix), m_func);
    }
    if (m_args_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("args"), namePrefix), m_args);
    }
    if (m_kwargs_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("kwargs"), namePrefix), m_kwargs);
    }
    return vars;
}

QList<HttpFileElement> PendingTask::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> PendingTask::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_pk_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("pk"), namePrefix), m_pk);
    }
    if (m_key_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("key"), namePrefix), m_key);
    }
    if (m_lock_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("lock"), namePrefix), m_lock);
    }
    if (m_task_id_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("task_id"), namePrefix), m_task_id);
    }
    if (m_name_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("name"), namePrefix), m_name);
    }
    if (m_func_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("func"), namePrefix), m_func);
    }
    if (m_args_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("args"), namePrefix), m_args);
    }
    if (m_kwargs_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("kwargs"), namePrefix), m_kwargs);
    }
    return files;
}

qint32 PendingTask::getPk() const {
    return m_pk;
}
void PendingTask::setPk(const qint32 &pk) {
    m_pk = pk;
    m_pk_isSet = true;
}

bool PendingTask::is_pk_Set() const{
    return m_pk_isSet;
}

bool PendingTask::is_pk_Valid() const{
    return m_pk_isValid;
}

QString PendingTask::getKey() const {
    return m_key;
}
void PendingTask::setKey(const QString &key) {
    m_key = key;
    m_key_isSet = true;
}

bool PendingTask::is_key_Set() const{
    return m_key_isSet;
}

bool PendingTask::is_key_Valid() const{
    return m_key_isValid;
}

QDateTime PendingTask::getLock() const {
    return m_lock;
}
void PendingTask::setLock(const QDateTime &lock) {
    m_lock = lock;
    m_lock_isSet = true;
}

bool PendingTask::is_lock_Set() const{
    return m_lock_isSet;
}

bool PendingTask::is_lock_Valid() const{
    return m_lock_isValid;
}

QString PendingTask::getTaskId() const {
    return m_task_id;
}
void PendingTask::setTaskId(const QString &task_id) {
    m_task_id = task_id;
    m_task_id_isSet = true;
}

bool PendingTask::is_task_id_Set() const{
    return m_task_id_isSet;
}

bool PendingTask::is_task_id_Valid() const{
    return m_task_id_isValid;
}

QString PendingTask::getName() const {
    return m_name;
}
void PendingTask::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool PendingTask::is_name_Set() const{
    return m_name_isSet;
}

bool PendingTask::is_name_Valid() const{
    return m_name_isValid;
}

QString PendingTask::getFunc() const {
    return m_func;
}
void PendingTask::setFunc(const QString &func) {
    m_func = func;
    m_func_isSet = true;
}

bool PendingTask::is_func_Set() const{
    return m_func_isSet;
}

bool PendingTask::is_func_Valid() const{
    return m_func_isValid;
}

QString PendingTask::getArgs() const {
    return m_args;
}
void PendingTask::setArgs(const QString &args) {
    m_args = args;
    m_args_isSet = true;
}

bool PendingTask::is_args_Set() const{
    return m_args_isSet;
}

bool PendingTask::is_args_Valid() const{
    return m_args_isValid;
}

QString PendingTask::getKwargs() const {
    return m_kwargs;
}
void PendingTask::setKwargs(const QString &kwargs) {
    m_kwargs = kwargs;
    m_kwargs_isSet = true;
}

bool PendingTask::is_kwargs_Set() const{
    return m_kwargs_isSet;
}

bool PendingTask::is_kwargs_Valid() const{
    return m_kwargs_isValid;
}

bool PendingTask::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_pk_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_lock_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_task_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_func_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_args_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_kwargs_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PendingTask::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_pk_isValid && m_key_isValid && m_lock_isValid && m_task_id_isValid && m_name_isValid && m_func_isValid && m_args_isValid && m_kwargs_isValid && true;
}

} // namespace InvenTree
