/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PluginUninstall.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PluginUninstall::PluginUninstall(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PluginUninstall::PluginUninstall() {
    this->initializeModel();
}

PluginUninstall::~PluginUninstall() {}

void PluginUninstall::initializeModel() {

    m_delete_config_isSet = false;
    m_delete_config_isValid = false;
}

void PluginUninstall::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PluginUninstall::fromJsonObject(QJsonObject json) {

    m_delete_config_isValid = ::InvenTree::fromJsonValue(m_delete_config, json[QString("delete_config")]);
    m_delete_config_isSet = !json[QString("delete_config")].isNull() && m_delete_config_isValid;
}

QString PluginUninstall::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PluginUninstall::asJsonObject() const {
    QJsonObject obj;
    if (m_delete_config_isSet) {
        obj.insert(QString("delete_config"), ::InvenTree::toJsonValue(m_delete_config));
    }
    return obj;
}

QMap<QString, QString> PluginUninstall::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> PluginUninstall::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_delete_config_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("delete_config"), namePrefix), m_delete_config);
    }
    return vars;
}

QList<HttpFileElement> PluginUninstall::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> PluginUninstall::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_delete_config_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("delete_config"), namePrefix), m_delete_config);
    }
    return files;
}

bool PluginUninstall::isDeleteConfig() const {
    return m_delete_config;
}
void PluginUninstall::setDeleteConfig(const bool &delete_config) {
    m_delete_config = delete_config;
    m_delete_config_isSet = true;
}

bool PluginUninstall::is_delete_config_Set() const{
    return m_delete_config_isSet;
}

bool PluginUninstall::is_delete_config_Valid() const{
    return m_delete_config_isValid;
}

bool PluginUninstall::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_delete_config_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PluginUninstall::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
