/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PluginActivate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PluginActivate::PluginActivate(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PluginActivate::PluginActivate() {
    this->initializeModel();
}

PluginActivate::~PluginActivate() {}

void PluginActivate::initializeModel() {

    m_active_isSet = false;
    m_active_isValid = false;
}

void PluginActivate::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PluginActivate::fromJsonObject(QJsonObject json) {

    m_active_isValid = ::InvenTree::fromJsonValue(m_active, json[QString("active")]);
    m_active_isSet = !json[QString("active")].isNull() && m_active_isValid;
}

QString PluginActivate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PluginActivate::asJsonObject() const {
    QJsonObject obj;
    if (m_active_isSet) {
        obj.insert(QString("active"), ::InvenTree::toJsonValue(m_active));
    }
    return obj;
}

QMap<QString, QString> PluginActivate::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> PluginActivate::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_active_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("active"), namePrefix), m_active);
    }
    return vars;
}

QList<HttpFileElement> PluginActivate::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> PluginActivate::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_active_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("active"), namePrefix), m_active);
    }
    return files;
}

bool PluginActivate::isActive() const {
    return m_active;
}
void PluginActivate::setActive(const bool &active) {
    m_active = active;
    m_active_isSet = true;
}

bool PluginActivate::is_active_Set() const{
    return m_active_isSet;
}

bool PluginActivate::is_active_Valid() const{
    return m_active_isValid;
}

bool PluginActivate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_active_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PluginActivate::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace InvenTree
