/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _PluginsApi_H
#define _PluginsApi_H

#include "Helpers.h"
#include "HttpRequest.h"
#include "ServerConfiguration.h"
#include "Oauth.h"

#include "PaginatedPluginConfigList.h"
#include "PaginatedPluginSettingList.h"
#include "PatchedPluginActivate.h"
#include "PatchedPluginSetting.h"
#include "PatchedPluginUninstall.h"
#include "PatchedPluginUserSetting.h"
#include "PluginActivate.h"
#include "PluginAdminDetail.h"
#include "PluginConfig.h"
#include "PluginConfigInstall.h"
#include "PluginRegistryStatus.h"
#include "PluginReload.h"
#include "PluginSetting.h"
#include "PluginUIFeature.h"
#include "PluginUninstall.h"
#include "PluginUserSetting.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace InvenTree {

class PluginsApi : public QObject {
    Q_OBJECT

public:
    PluginsApi(const int timeOut = 0);
    ~PluginsApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setServerIndex(int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables = QMap<QString, ServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  plugin QString [required]
    * @param[in]  patched_plugin_activate PatchedPluginActivate [optional]
    */
    virtual void pluginsActivatePartialUpdate(const QString &plugin, const ::InvenTree::OptionalParam<PatchedPluginActivate> &patched_plugin_activate = ::InvenTree::OptionalParam<PatchedPluginActivate>());

    /**
    * @param[in]  plugin QString [required]
    * @param[in]  plugin_activate PluginActivate [optional]
    */
    virtual void pluginsActivateUpdate(const QString &plugin, const ::InvenTree::OptionalParam<PluginActivate> &plugin_activate = ::InvenTree::OptionalParam<PluginActivate>());

    /**
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsAdminRetrieve(const QString &plugin);

    /**
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsDestroy(const QString &plugin);

    /**
    * @param[in]  plugin_config_install PluginConfigInstall [required]
    */
    virtual void pluginsInstallCreate(const PluginConfigInstall &plugin_config_install);

    /**
    * @param[in]  limit qint32 [required]
    * @param[in]  active bool [optional]
    * @param[in]  builtin bool [optional]
    * @param[in]  installed bool [optional]
    * @param[in]  mandatory bool [optional]
    * @param[in]  mixin QString [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  ordering QString [optional]
    * @param[in]  sample bool [optional]
    * @param[in]  search QString [optional]
    */
    virtual void pluginsList(const qint32 &limit, const ::InvenTree::OptionalParam<bool> &active = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &builtin = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &installed = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<bool> &mandatory = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &mixin = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &ordering = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &sample = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>());

    /**
    * @param[in]  plugin_reload PluginReload [optional]
    */
    virtual void pluginsReloadCreate(const ::InvenTree::OptionalParam<PluginReload> &plugin_reload = ::InvenTree::OptionalParam<PluginReload>());

    /**
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsRetrieve(const QString &plugin);

    /**
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsSettingsList(const QString &plugin);

    /**
    * @param[in]  limit qint32 [required]
    * @param[in]  offset qint32 [optional]
    * @param[in]  plugin__active bool [optional]
    * @param[in]  plugin__key QString [optional]
    */
    virtual void pluginsSettingsListAll(const qint32 &limit, const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<bool> &plugin__active = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &plugin__key = ::InvenTree::OptionalParam<QString>());

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    * @param[in]  patched_plugin_setting PatchedPluginSetting [optional]
    */
    virtual void pluginsSettingsPartialUpdate(const QString &key, const QString &plugin, const ::InvenTree::OptionalParam<PatchedPluginSetting> &patched_plugin_setting = ::InvenTree::OptionalParam<PatchedPluginSetting>());

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsSettingsRetrieve(const QString &key, const QString &plugin);

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    * @param[in]  plugin_setting PluginSetting [required]
    */
    virtual void pluginsSettingsUpdate(const QString &key, const QString &plugin, const PluginSetting &plugin_setting);


    virtual void pluginsStatusRetrieve();

    /**
    * @param[in]  feature QString [required]
    */
    virtual void pluginsUiFeaturesList(const QString &feature);

    /**
    * @param[in]  plugin QString [required]
    * @param[in]  patched_plugin_uninstall PatchedPluginUninstall [optional]
    */
    virtual void pluginsUninstallPartialUpdate(const QString &plugin, const ::InvenTree::OptionalParam<PatchedPluginUninstall> &patched_plugin_uninstall = ::InvenTree::OptionalParam<PatchedPluginUninstall>());

    /**
    * @param[in]  plugin QString [required]
    * @param[in]  plugin_uninstall PluginUninstall [optional]
    */
    virtual void pluginsUninstallUpdate(const QString &plugin, const ::InvenTree::OptionalParam<PluginUninstall> &plugin_uninstall = ::InvenTree::OptionalParam<PluginUninstall>());

    /**
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsUserSettingsList(const QString &plugin);

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    * @param[in]  patched_plugin_user_setting PatchedPluginUserSetting [optional]
    */
    virtual void pluginsUserSettingsPartialUpdate(const QString &key, const QString &plugin, const ::InvenTree::OptionalParam<PatchedPluginUserSetting> &patched_plugin_user_setting = ::InvenTree::OptionalParam<PatchedPluginUserSetting>());

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    */
    virtual void pluginsUserSettingsRetrieve(const QString &key, const QString &plugin);

    /**
    * @param[in]  key QString [required]
    * @param[in]  plugin QString [required]
    * @param[in]  plugin_user_setting PluginUserSetting [required]
    */
    virtual void pluginsUserSettingsUpdate(const QString &key, const QString &plugin, const PluginUserSetting &plugin_user_setting);


private:
    enum class OauthMethod : int {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ImplicitFlow = 1,
        AuthorizationFlow = 2,
        ClientCredentialsFlow = 3,
        ResourceOwnerPasswordFlow = 4
    };
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<ServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    HttpRequestInput _latestInput;
    HttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    OauthMethod _OauthMethod = OauthMethod::INVALID_VALUE_OPENAPI_GENERATED;

    void pluginsActivatePartialUpdateCallback(HttpRequestWorker *worker);
    void pluginsActivateUpdateCallback(HttpRequestWorker *worker);
    void pluginsAdminRetrieveCallback(HttpRequestWorker *worker);
    void pluginsDestroyCallback(HttpRequestWorker *worker);
    void pluginsInstallCreateCallback(HttpRequestWorker *worker);
    void pluginsListCallback(HttpRequestWorker *worker);
    void pluginsReloadCreateCallback(HttpRequestWorker *worker);
    void pluginsRetrieveCallback(HttpRequestWorker *worker);
    void pluginsSettingsListCallback(HttpRequestWorker *worker);
    void pluginsSettingsListAllCallback(HttpRequestWorker *worker);
    void pluginsSettingsPartialUpdateCallback(HttpRequestWorker *worker);
    void pluginsSettingsRetrieveCallback(HttpRequestWorker *worker);
    void pluginsSettingsUpdateCallback(HttpRequestWorker *worker);
    void pluginsStatusRetrieveCallback(HttpRequestWorker *worker);
    void pluginsUiFeaturesListCallback(HttpRequestWorker *worker);
    void pluginsUninstallPartialUpdateCallback(HttpRequestWorker *worker);
    void pluginsUninstallUpdateCallback(HttpRequestWorker *worker);
    void pluginsUserSettingsListCallback(HttpRequestWorker *worker);
    void pluginsUserSettingsPartialUpdateCallback(HttpRequestWorker *worker);
    void pluginsUserSettingsRetrieveCallback(HttpRequestWorker *worker);
    void pluginsUserSettingsUpdateCallback(HttpRequestWorker *worker);

Q_SIGNALS:

    void pluginsActivatePartialUpdateSignal(PluginActivate summary);
    void pluginsActivateUpdateSignal(PluginActivate summary);
    void pluginsAdminRetrieveSignal(PluginAdminDetail summary);
    void pluginsDestroySignal();
    void pluginsInstallCreateSignal(PluginConfigInstall summary);
    void pluginsListSignal(PaginatedPluginConfigList summary);
    void pluginsReloadCreateSignal(PluginReload summary);
    void pluginsRetrieveSignal(PluginConfig summary);
    void pluginsSettingsListSignal(QList<PluginSetting> summary);
    void pluginsSettingsListAllSignal(PaginatedPluginSettingList summary);
    void pluginsSettingsPartialUpdateSignal(PluginSetting summary);
    void pluginsSettingsRetrieveSignal(PluginSetting summary);
    void pluginsSettingsUpdateSignal(PluginSetting summary);
    void pluginsStatusRetrieveSignal(PluginRegistryStatus summary);
    void pluginsUiFeaturesListSignal(QList<PluginUIFeature> summary);
    void pluginsUninstallPartialUpdateSignal(PluginUninstall summary);
    void pluginsUninstallUpdateSignal(PluginUninstall summary);
    void pluginsUserSettingsListSignal(QList<PluginUserSetting> summary);
    void pluginsUserSettingsPartialUpdateSignal(PluginUserSetting summary);
    void pluginsUserSettingsRetrieveSignal(PluginUserSetting summary);
    void pluginsUserSettingsUpdateSignal(PluginUserSetting summary);


    void pluginsActivatePartialUpdateSignalFull(HttpRequestWorker *worker, PluginActivate summary);
    void pluginsActivateUpdateSignalFull(HttpRequestWorker *worker, PluginActivate summary);
    void pluginsAdminRetrieveSignalFull(HttpRequestWorker *worker, PluginAdminDetail summary);
    void pluginsDestroySignalFull(HttpRequestWorker *worker);
    void pluginsInstallCreateSignalFull(HttpRequestWorker *worker, PluginConfigInstall summary);
    void pluginsListSignalFull(HttpRequestWorker *worker, PaginatedPluginConfigList summary);
    void pluginsReloadCreateSignalFull(HttpRequestWorker *worker, PluginReload summary);
    void pluginsRetrieveSignalFull(HttpRequestWorker *worker, PluginConfig summary);
    void pluginsSettingsListSignalFull(HttpRequestWorker *worker, QList<PluginSetting> summary);
    void pluginsSettingsListAllSignalFull(HttpRequestWorker *worker, PaginatedPluginSettingList summary);
    void pluginsSettingsPartialUpdateSignalFull(HttpRequestWorker *worker, PluginSetting summary);
    void pluginsSettingsRetrieveSignalFull(HttpRequestWorker *worker, PluginSetting summary);
    void pluginsSettingsUpdateSignalFull(HttpRequestWorker *worker, PluginSetting summary);
    void pluginsStatusRetrieveSignalFull(HttpRequestWorker *worker, PluginRegistryStatus summary);
    void pluginsUiFeaturesListSignalFull(HttpRequestWorker *worker, QList<PluginUIFeature> summary);
    void pluginsUninstallPartialUpdateSignalFull(HttpRequestWorker *worker, PluginUninstall summary);
    void pluginsUninstallUpdateSignalFull(HttpRequestWorker *worker, PluginUninstall summary);
    void pluginsUserSettingsListSignalFull(HttpRequestWorker *worker, QList<PluginUserSetting> summary);
    void pluginsUserSettingsPartialUpdateSignalFull(HttpRequestWorker *worker, PluginUserSetting summary);
    void pluginsUserSettingsRetrieveSignalFull(HttpRequestWorker *worker, PluginUserSetting summary);
    void pluginsUserSettingsUpdateSignalFull(HttpRequestWorker *worker, PluginUserSetting summary);

    Q_DECL_DEPRECATED_X("Use pluginsActivatePartialUpdateSignalError() instead")
    void pluginsActivatePartialUpdateSignalE(PluginActivate summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsActivatePartialUpdateSignalError(PluginActivate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsActivateUpdateSignalError() instead")
    void pluginsActivateUpdateSignalE(PluginActivate summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsActivateUpdateSignalError(PluginActivate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsAdminRetrieveSignalError() instead")
    void pluginsAdminRetrieveSignalE(PluginAdminDetail summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsAdminRetrieveSignalError(PluginAdminDetail summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsDestroySignalError() instead")
    void pluginsDestroySignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsInstallCreateSignalError() instead")
    void pluginsInstallCreateSignalE(PluginConfigInstall summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsInstallCreateSignalError(PluginConfigInstall summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsListSignalError() instead")
    void pluginsListSignalE(PaginatedPluginConfigList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsListSignalError(PaginatedPluginConfigList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsReloadCreateSignalError() instead")
    void pluginsReloadCreateSignalE(PluginReload summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsReloadCreateSignalError(PluginReload summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsRetrieveSignalError() instead")
    void pluginsRetrieveSignalE(PluginConfig summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsRetrieveSignalError(PluginConfig summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsListSignalError() instead")
    void pluginsSettingsListSignalE(QList<PluginSetting> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsListSignalError(QList<PluginSetting> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsListAllSignalError() instead")
    void pluginsSettingsListAllSignalE(PaginatedPluginSettingList summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsListAllSignalError(PaginatedPluginSettingList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsPartialUpdateSignalError() instead")
    void pluginsSettingsPartialUpdateSignalE(PluginSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsPartialUpdateSignalError(PluginSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsRetrieveSignalError() instead")
    void pluginsSettingsRetrieveSignalE(PluginSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsRetrieveSignalError(PluginSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsUpdateSignalError() instead")
    void pluginsSettingsUpdateSignalE(PluginSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsUpdateSignalError(PluginSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsStatusRetrieveSignalError() instead")
    void pluginsStatusRetrieveSignalE(PluginRegistryStatus summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsStatusRetrieveSignalError(PluginRegistryStatus summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUiFeaturesListSignalError() instead")
    void pluginsUiFeaturesListSignalE(QList<PluginUIFeature> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUiFeaturesListSignalError(QList<PluginUIFeature> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUninstallPartialUpdateSignalError() instead")
    void pluginsUninstallPartialUpdateSignalE(PluginUninstall summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUninstallPartialUpdateSignalError(PluginUninstall summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUninstallUpdateSignalError() instead")
    void pluginsUninstallUpdateSignalE(PluginUninstall summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUninstallUpdateSignalError(PluginUninstall summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsListSignalError() instead")
    void pluginsUserSettingsListSignalE(QList<PluginUserSetting> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsListSignalError(QList<PluginUserSetting> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsPartialUpdateSignalError() instead")
    void pluginsUserSettingsPartialUpdateSignalE(PluginUserSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsPartialUpdateSignalError(PluginUserSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsRetrieveSignalError() instead")
    void pluginsUserSettingsRetrieveSignalE(PluginUserSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsRetrieveSignalError(PluginUserSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsUpdateSignalError() instead")
    void pluginsUserSettingsUpdateSignalE(PluginUserSetting summary, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsUpdateSignalError(PluginUserSetting summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use pluginsActivatePartialUpdateSignalErrorFull() instead")
    void pluginsActivatePartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsActivatePartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsActivateUpdateSignalErrorFull() instead")
    void pluginsActivateUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsActivateUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsAdminRetrieveSignalErrorFull() instead")
    void pluginsAdminRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsAdminRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsDestroySignalErrorFull() instead")
    void pluginsDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsInstallCreateSignalErrorFull() instead")
    void pluginsInstallCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsInstallCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsListSignalErrorFull() instead")
    void pluginsListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsReloadCreateSignalErrorFull() instead")
    void pluginsReloadCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsReloadCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsRetrieveSignalErrorFull() instead")
    void pluginsRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsListSignalErrorFull() instead")
    void pluginsSettingsListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsListAllSignalErrorFull() instead")
    void pluginsSettingsListAllSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsListAllSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsPartialUpdateSignalErrorFull() instead")
    void pluginsSettingsPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsRetrieveSignalErrorFull() instead")
    void pluginsSettingsRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsSettingsUpdateSignalErrorFull() instead")
    void pluginsSettingsUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsSettingsUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsStatusRetrieveSignalErrorFull() instead")
    void pluginsStatusRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsStatusRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUiFeaturesListSignalErrorFull() instead")
    void pluginsUiFeaturesListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUiFeaturesListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUninstallPartialUpdateSignalErrorFull() instead")
    void pluginsUninstallPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUninstallPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUninstallUpdateSignalErrorFull() instead")
    void pluginsUninstallUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUninstallUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsListSignalErrorFull() instead")
    void pluginsUserSettingsListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsPartialUpdateSignalErrorFull() instead")
    void pluginsUserSettingsPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsRetrieveSignalErrorFull() instead")
    void pluginsUserSettingsRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use pluginsUserSettingsUpdateSignalErrorFull() instead")
    void pluginsUserSettingsUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void pluginsUserSettingsUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace InvenTree
#endif
