/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PriorityEnum.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PriorityEnum::PriorityEnum(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

PriorityEnum::PriorityEnum() {
    this->initializeModel();
}

PriorityEnum::~PriorityEnum() {}

void PriorityEnum::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = ePriorityEnum::INVALID_VALUE_OPENAPI_GENERATED;
}

void PriorityEnum::fromJson(QString jsonString) {
    
    if ( jsonString.compare(QString::number(0), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_0;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(1), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_1;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(2), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_2;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(3), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_3;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(4), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_4;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(5), Qt::CaseInsensitive) == 0) {
        m_value = ePriorityEnum::_5;
        m_value_isSet = m_value_isValid = true;
    }
}

void PriorityEnum::fromJsonValue(QJsonValue json) {
m_value = static_cast<ePriorityEnum>(json.toInt());
}

QString PriorityEnum::asJson() const {
    
    QString val;
    switch (m_value){
        case ePriorityEnum::_0:
            val = QString::number(0);
            break;
        case ePriorityEnum::_1:
            val = QString::number(1);
            break;
        case ePriorityEnum::_2:
            val = QString::number(2);
            break;
        case ePriorityEnum::_3:
            val = QString::number(3);
            break;
        case ePriorityEnum::_4:
            val = QString::number(4);
            break;
        case ePriorityEnum::_5:
            val = QString::number(5);
            break;
        default:
            break;
    }
    return val;
}

QJsonValue PriorityEnum::asJsonValue() const {
    
    return QJsonValue(static_cast<int>(m_value));
}


PriorityEnum::ePriorityEnum PriorityEnum::getValue() const {
    return m_value;
}

void PriorityEnum::setValue(const PriorityEnum::ePriorityEnum& value){
    m_value = value;
    m_value_isSet = true;
}
bool PriorityEnum::isSet() const {
    
    return m_value_isSet;
}

bool PriorityEnum::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace InvenTree
