/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "PurchaseOrderReceive.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

PurchaseOrderReceive::PurchaseOrderReceive(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

PurchaseOrderReceive::PurchaseOrderReceive() {
    this->initializeModel();
}

PurchaseOrderReceive::~PurchaseOrderReceive() {}

void PurchaseOrderReceive::initializeModel() {

    m_items_isSet = false;
    m_items_isValid = false;

    m_location_isSet = false;
    m_location_isValid = false;
}

void PurchaseOrderReceive::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void PurchaseOrderReceive::fromJsonObject(QJsonObject json) {

    m_items_isValid = ::InvenTree::fromJsonValue(m_items, json[QString("items")]);
    m_items_isSet = !json[QString("items")].isNull() && m_items_isValid;

    m_location_isValid = ::InvenTree::fromJsonValue(m_location, json[QString("location")]);
    m_location_isSet = !json[QString("location")].isNull() && m_location_isValid;
}

QString PurchaseOrderReceive::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject PurchaseOrderReceive::asJsonObject() const {
    QJsonObject obj;
    if (m_items.size() > 0) {
        obj.insert(QString("items"), ::InvenTree::toJsonValue(m_items));
    }
    if (m_location_isSet) {
        obj.insert(QString("location"), ::InvenTree::toJsonValue(m_location));
    }
    return obj;
}

QMap<QString, QString> PurchaseOrderReceive::asFormVariables() const {
    return asFormVariables(QString());
}

QMap<QString, QString> PurchaseOrderReceive::asFormVariables(const QString &namePrefix) const {
    (void)namePrefix;
    QMap<QString, QString> vars;

    if (m_items.size() > 0) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("items"), namePrefix), m_items);
    }
    if (m_location_isSet) {
        ::InvenTree::insertFormVariable(vars, ::InvenTree::toFormFieldName(QString("location"), namePrefix), m_location);
    }
    return vars;
}

QList<HttpFileElement> PurchaseOrderReceive::asFileElements() const {
    return asFileElements(QString());
}

QList<HttpFileElement> PurchaseOrderReceive::asFileElements(const QString &namePrefix) const {
    (void)namePrefix;
    QList<HttpFileElement> files;

    if (m_items.size() > 0) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("items"), namePrefix), m_items);
    }
    if (m_location_isSet) {
        ::InvenTree::appendFileElements(files, ::InvenTree::toFormFieldName(QString("location"), namePrefix), m_location);
    }
    return files;
}

QList<PurchaseOrderLineItemReceive> PurchaseOrderReceive::getItems() const {
    return m_items;
}
void PurchaseOrderReceive::setItems(const QList<PurchaseOrderLineItemReceive> &items) {
    m_items = items;
    m_items_isSet = true;
}

bool PurchaseOrderReceive::is_items_Set() const{
    return m_items_isSet;
}

bool PurchaseOrderReceive::is_items_Valid() const{
    return m_items_isValid;
}

qint32 PurchaseOrderReceive::getLocation() const {
    return m_location;
}
void PurchaseOrderReceive::setLocation(const qint32 &location) {
    m_location = location;
    m_location_isSet = true;
}

bool PurchaseOrderReceive::is_location_Set() const{
    return m_location_isSet;
}

bool PurchaseOrderReceive::is_location_Valid() const{
    return m_location_isValid;
}

bool PurchaseOrderReceive::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_items.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_location_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool PurchaseOrderReceive::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_items_isValid && true;
}

} // namespace InvenTree
