/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _ReportApi_H
#define _ReportApi_H

#include "Helpers.h"
#include "HttpRequest.h"
#include "ServerConfiguration.h"
#include "Oauth.h"

#include "PaginatedReportAssetList.h"
#include "PaginatedReportSnippetList.h"
#include "PaginatedReportTemplateList.h"
#include "PatchedReportAsset.h"
#include "PatchedReportSnippet.h"
#include "PatchedReportTemplate.h"
#include "ReportAsset.h"
#include "ReportPrint.h"
#include "ReportSnippet.h"
#include "ReportTemplate.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace InvenTree {

class ReportApi : public QObject {
    Q_OBJECT

public:
    ReportApi(const int timeOut = 0);
    ~ReportApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setServerIndex(int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables = QMap<QString, ServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, ServerVariable> &variables =  QMap<QString, ServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  report_asset ReportAsset [required]
    */
    virtual void reportAssetCreate(const ReportAsset &report_asset);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportAssetDestroy(const qint32 &id);

    /**
    * @param[in]  limit qint32 [required]
    * @param[in]  offset qint32 [optional]
    */
    virtual void reportAssetList(const qint32 &limit, const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_report_asset PatchedReportAsset [optional]
    */
    virtual void reportAssetPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedReportAsset> &patched_report_asset = ::InvenTree::OptionalParam<PatchedReportAsset>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportAssetRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  report_asset ReportAsset [required]
    */
    virtual void reportAssetUpdate(const qint32 &id, const ReportAsset &report_asset);

    /**
    * @param[in]  report_print ReportPrint [required]
    */
    virtual void reportPrintCreate(const ReportPrint &report_print);

    /**
    * @param[in]  report_snippet ReportSnippet [required]
    */
    virtual void reportSnippetCreate(const ReportSnippet &report_snippet);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportSnippetDestroy(const qint32 &id);

    /**
    * @param[in]  limit qint32 [required]
    * @param[in]  offset qint32 [optional]
    */
    virtual void reportSnippetList(const qint32 &limit, const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_report_snippet PatchedReportSnippet [optional]
    */
    virtual void reportSnippetPartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedReportSnippet> &patched_report_snippet = ::InvenTree::OptionalParam<PatchedReportSnippet>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportSnippetRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  report_snippet ReportSnippet [required]
    */
    virtual void reportSnippetUpdate(const qint32 &id, const ReportSnippet &report_snippet);

    /**
    * @param[in]  report_template ReportTemplate [required]
    */
    virtual void reportTemplateCreate(const ReportTemplate &report_template);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportTemplateDestroy(const qint32 &id);

    /**
    * @param[in]  limit qint32 [required]
    * @param[in]  enabled bool [optional]
    * @param[in]  items QString [optional]
    * @param[in]  landscape bool [optional]
    * @param[in]  model_type QString [optional]
    * @param[in]  offset qint32 [optional]
    * @param[in]  search QString [optional]
    */
    virtual void reportTemplateList(const qint32 &limit, const ::InvenTree::OptionalParam<bool> &enabled = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &items = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<bool> &landscape = ::InvenTree::OptionalParam<bool>(), const ::InvenTree::OptionalParam<QString> &model_type = ::InvenTree::OptionalParam<QString>(), const ::InvenTree::OptionalParam<qint32> &offset = ::InvenTree::OptionalParam<qint32>(), const ::InvenTree::OptionalParam<QString> &search = ::InvenTree::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  patched_report_template PatchedReportTemplate [optional]
    */
    virtual void reportTemplatePartialUpdate(const qint32 &id, const ::InvenTree::OptionalParam<PatchedReportTemplate> &patched_report_template = ::InvenTree::OptionalParam<PatchedReportTemplate>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void reportTemplateRetrieve(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  report_template ReportTemplate [required]
    */
    virtual void reportTemplateUpdate(const qint32 &id, const ReportTemplate &report_template);


private:
    enum class OauthMethod : int {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ImplicitFlow = 1,
        AuthorizationFlow = 2,
        ClientCredentialsFlow = 3,
        ResourceOwnerPasswordFlow = 4
    };
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<ServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    HttpRequestInput _latestInput;
    HttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    OauthMethod _OauthMethod = OauthMethod::INVALID_VALUE_OPENAPI_GENERATED;

    void reportAssetCreateCallback(HttpRequestWorker *worker);
    void reportAssetDestroyCallback(HttpRequestWorker *worker);
    void reportAssetListCallback(HttpRequestWorker *worker);
    void reportAssetPartialUpdateCallback(HttpRequestWorker *worker);
    void reportAssetRetrieveCallback(HttpRequestWorker *worker);
    void reportAssetUpdateCallback(HttpRequestWorker *worker);
    void reportPrintCreateCallback(HttpRequestWorker *worker);
    void reportSnippetCreateCallback(HttpRequestWorker *worker);
    void reportSnippetDestroyCallback(HttpRequestWorker *worker);
    void reportSnippetListCallback(HttpRequestWorker *worker);
    void reportSnippetPartialUpdateCallback(HttpRequestWorker *worker);
    void reportSnippetRetrieveCallback(HttpRequestWorker *worker);
    void reportSnippetUpdateCallback(HttpRequestWorker *worker);
    void reportTemplateCreateCallback(HttpRequestWorker *worker);
    void reportTemplateDestroyCallback(HttpRequestWorker *worker);
    void reportTemplateListCallback(HttpRequestWorker *worker);
    void reportTemplatePartialUpdateCallback(HttpRequestWorker *worker);
    void reportTemplateRetrieveCallback(HttpRequestWorker *worker);
    void reportTemplateUpdateCallback(HttpRequestWorker *worker);

Q_SIGNALS:

    void reportAssetCreateSignal(ReportAsset summary);
    void reportAssetDestroySignal();
    void reportAssetListSignal(PaginatedReportAssetList summary);
    void reportAssetPartialUpdateSignal(ReportAsset summary);
    void reportAssetRetrieveSignal(ReportAsset summary);
    void reportAssetUpdateSignal(ReportAsset summary);
    void reportPrintCreateSignal(ReportPrint summary);
    void reportSnippetCreateSignal(ReportSnippet summary);
    void reportSnippetDestroySignal();
    void reportSnippetListSignal(PaginatedReportSnippetList summary);
    void reportSnippetPartialUpdateSignal(ReportSnippet summary);
    void reportSnippetRetrieveSignal(ReportSnippet summary);
    void reportSnippetUpdateSignal(ReportSnippet summary);
    void reportTemplateCreateSignal(ReportTemplate summary);
    void reportTemplateDestroySignal();
    void reportTemplateListSignal(PaginatedReportTemplateList summary);
    void reportTemplatePartialUpdateSignal(ReportTemplate summary);
    void reportTemplateRetrieveSignal(ReportTemplate summary);
    void reportTemplateUpdateSignal(ReportTemplate summary);


    void reportAssetCreateSignalFull(HttpRequestWorker *worker, ReportAsset summary);
    void reportAssetDestroySignalFull(HttpRequestWorker *worker);
    void reportAssetListSignalFull(HttpRequestWorker *worker, PaginatedReportAssetList summary);
    void reportAssetPartialUpdateSignalFull(HttpRequestWorker *worker, ReportAsset summary);
    void reportAssetRetrieveSignalFull(HttpRequestWorker *worker, ReportAsset summary);
    void reportAssetUpdateSignalFull(HttpRequestWorker *worker, ReportAsset summary);
    void reportPrintCreateSignalFull(HttpRequestWorker *worker, ReportPrint summary);
    void reportSnippetCreateSignalFull(HttpRequestWorker *worker, ReportSnippet summary);
    void reportSnippetDestroySignalFull(HttpRequestWorker *worker);
    void reportSnippetListSignalFull(HttpRequestWorker *worker, PaginatedReportSnippetList summary);
    void reportSnippetPartialUpdateSignalFull(HttpRequestWorker *worker, ReportSnippet summary);
    void reportSnippetRetrieveSignalFull(HttpRequestWorker *worker, ReportSnippet summary);
    void reportSnippetUpdateSignalFull(HttpRequestWorker *worker, ReportSnippet summary);
    void reportTemplateCreateSignalFull(HttpRequestWorker *worker, ReportTemplate summary);
    void reportTemplateDestroySignalFull(HttpRequestWorker *worker);
    void reportTemplateListSignalFull(HttpRequestWorker *worker, PaginatedReportTemplateList summary);
    void reportTemplatePartialUpdateSignalFull(HttpRequestWorker *worker, ReportTemplate summary);
    void reportTemplateRetrieveSignalFull(HttpRequestWorker *worker, ReportTemplate summary);
    void reportTemplateUpdateSignalFull(HttpRequestWorker *worker, ReportTemplate summary);

    Q_DECL_DEPRECATED_X("Use reportAssetCreateSignalError() instead")
    void reportAssetCreateSignalE(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetCreateSignalError(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetDestroySignalError() instead")
    void reportAssetDestroySignalE(QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetListSignalError() instead")
    void reportAssetListSignalE(PaginatedReportAssetList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetListSignalError(PaginatedReportAssetList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetPartialUpdateSignalError() instead")
    void reportAssetPartialUpdateSignalE(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetPartialUpdateSignalError(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetRetrieveSignalError() instead")
    void reportAssetRetrieveSignalE(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetRetrieveSignalError(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetUpdateSignalError() instead")
    void reportAssetUpdateSignalE(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetUpdateSignalError(ReportAsset summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportPrintCreateSignalError() instead")
    void reportPrintCreateSignalE(ReportPrint summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportPrintCreateSignalError(ReportPrint summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetCreateSignalError() instead")
    void reportSnippetCreateSignalE(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetCreateSignalError(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetDestroySignalError() instead")
    void reportSnippetDestroySignalE(QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetListSignalError() instead")
    void reportSnippetListSignalE(PaginatedReportSnippetList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetListSignalError(PaginatedReportSnippetList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetPartialUpdateSignalError() instead")
    void reportSnippetPartialUpdateSignalE(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetPartialUpdateSignalError(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetRetrieveSignalError() instead")
    void reportSnippetRetrieveSignalE(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetRetrieveSignalError(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetUpdateSignalError() instead")
    void reportSnippetUpdateSignalE(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetUpdateSignalError(ReportSnippet summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateCreateSignalError() instead")
    void reportTemplateCreateSignalE(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateCreateSignalError(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateDestroySignalError() instead")
    void reportTemplateDestroySignalE(QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateDestroySignalError(QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateListSignalError() instead")
    void reportTemplateListSignalE(PaginatedReportTemplateList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateListSignalError(PaginatedReportTemplateList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplatePartialUpdateSignalError() instead")
    void reportTemplatePartialUpdateSignalE(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplatePartialUpdateSignalError(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateRetrieveSignalError() instead")
    void reportTemplateRetrieveSignalE(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateRetrieveSignalError(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateUpdateSignalError() instead")
    void reportTemplateUpdateSignalE(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateUpdateSignalError(ReportTemplate summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use reportAssetCreateSignalErrorFull() instead")
    void reportAssetCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetDestroySignalErrorFull() instead")
    void reportAssetDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetListSignalErrorFull() instead")
    void reportAssetListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetPartialUpdateSignalErrorFull() instead")
    void reportAssetPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetRetrieveSignalErrorFull() instead")
    void reportAssetRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportAssetUpdateSignalErrorFull() instead")
    void reportAssetUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportAssetUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportPrintCreateSignalErrorFull() instead")
    void reportPrintCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportPrintCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetCreateSignalErrorFull() instead")
    void reportSnippetCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetDestroySignalErrorFull() instead")
    void reportSnippetDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetListSignalErrorFull() instead")
    void reportSnippetListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetPartialUpdateSignalErrorFull() instead")
    void reportSnippetPartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetPartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetRetrieveSignalErrorFull() instead")
    void reportSnippetRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportSnippetUpdateSignalErrorFull() instead")
    void reportSnippetUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportSnippetUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateCreateSignalErrorFull() instead")
    void reportTemplateCreateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateCreateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateDestroySignalErrorFull() instead")
    void reportTemplateDestroySignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateDestroySignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateListSignalErrorFull() instead")
    void reportTemplateListSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateListSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplatePartialUpdateSignalErrorFull() instead")
    void reportTemplatePartialUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplatePartialUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateRetrieveSignalErrorFull() instead")
    void reportTemplateRetrieveSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateRetrieveSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use reportTemplateUpdateSignalErrorFull() instead")
    void reportTemplateUpdateSignalEFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void reportTemplateUpdateSignalErrorFull(HttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace InvenTree
#endif
