/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 225
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestAuthDetail.h
 *
 * 
 */

#ifndef RestAuthDetail_H
#define RestAuthDetail_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {

class RestAuthDetail : public Object {
public:
    RestAuthDetail();
    RestAuthDetail(QString json);
    ~RestAuthDetail() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getDetail() const;
    void setDetail(const QString &detail);
    bool is_detail_Set() const;
    bool is_detail_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_detail;
    bool m_detail_isSet;
    bool m_detail_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::RestAuthDetail)

#endif // RestAuthDetail_H
