/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "SalesOrderShipmentAllocationItem.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

SalesOrderShipmentAllocationItem::SalesOrderShipmentAllocationItem(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

SalesOrderShipmentAllocationItem::SalesOrderShipmentAllocationItem() {
    this->initializeModel();
}

SalesOrderShipmentAllocationItem::~SalesOrderShipmentAllocationItem() {}

void SalesOrderShipmentAllocationItem::initializeModel() {

    m_line_item_isSet = false;
    m_line_item_isValid = false;

    m_stock_item_isSet = false;
    m_stock_item_isValid = false;

    m_quantity_isSet = false;
    m_quantity_isValid = false;
}

void SalesOrderShipmentAllocationItem::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void SalesOrderShipmentAllocationItem::fromJsonObject(QJsonObject json) {

    m_line_item_isValid = ::InvenTree::fromJsonValue(m_line_item, json[QString("line_item")]);
    m_line_item_isSet = !json[QString("line_item")].isNull() && m_line_item_isValid;

    m_stock_item_isValid = ::InvenTree::fromJsonValue(m_stock_item, json[QString("stock_item")]);
    m_stock_item_isSet = !json[QString("stock_item")].isNull() && m_stock_item_isValid;

    m_quantity_isValid = ::InvenTree::fromJsonValue(m_quantity, json[QString("quantity")]);
    m_quantity_isSet = !json[QString("quantity")].isNull() && m_quantity_isValid;
}

QString SalesOrderShipmentAllocationItem::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject SalesOrderShipmentAllocationItem::asJsonObject() const {
    QJsonObject obj;
    if (m_line_item_isSet) {
        obj.insert(QString("line_item"), ::InvenTree::toJsonValue(m_line_item));
    }
    if (m_stock_item_isSet) {
        obj.insert(QString("stock_item"), ::InvenTree::toJsonValue(m_stock_item));
    }
    if (m_quantity_isSet) {
        obj.insert(QString("quantity"), ::InvenTree::toJsonValue(m_quantity));
    }
    return obj;
}

qint32 SalesOrderShipmentAllocationItem::getLineItem() const {
    return m_line_item;
}
void SalesOrderShipmentAllocationItem::setLineItem(const qint32 &line_item) {
    m_line_item = line_item;
    m_line_item_isSet = true;
}

bool SalesOrderShipmentAllocationItem::is_line_item_Set() const{
    return m_line_item_isSet;
}

bool SalesOrderShipmentAllocationItem::is_line_item_Valid() const{
    return m_line_item_isValid;
}

qint32 SalesOrderShipmentAllocationItem::getStockItem() const {
    return m_stock_item;
}
void SalesOrderShipmentAllocationItem::setStockItem(const qint32 &stock_item) {
    m_stock_item = stock_item;
    m_stock_item_isSet = true;
}

bool SalesOrderShipmentAllocationItem::is_stock_item_Set() const{
    return m_stock_item_isSet;
}

bool SalesOrderShipmentAllocationItem::is_stock_item_Valid() const{
    return m_stock_item_isValid;
}

QString SalesOrderShipmentAllocationItem::getQuantity() const {
    return m_quantity;
}
void SalesOrderShipmentAllocationItem::setQuantity(const QString &quantity) {
    m_quantity = quantity;
    m_quantity_isSet = true;
}

bool SalesOrderShipmentAllocationItem::is_quantity_Set() const{
    return m_quantity_isSet;
}

bool SalesOrderShipmentAllocationItem::is_quantity_Valid() const{
    return m_quantity_isValid;
}

bool SalesOrderShipmentAllocationItem::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_line_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_stock_item_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_quantity_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool SalesOrderShipmentAllocationItem::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_line_item_isValid && m_stock_item_isValid && m_quantity_isValid && true;
}

} // namespace InvenTree
