/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 166
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "ScheduleTypeEnum.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

ScheduleTypeEnum::ScheduleTypeEnum(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

ScheduleTypeEnum::ScheduleTypeEnum() {
    this->initializeModel();
}

ScheduleTypeEnum::~ScheduleTypeEnum() {}

void ScheduleTypeEnum::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eScheduleTypeEnum::INVALID_VALUE_OPENAPI_GENERATED;
}

void ScheduleTypeEnum::fromJson(QString jsonString) {
    
    if ( jsonString.compare("O", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::O;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("I", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::I;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("H", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::H;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("D", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::D;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("W", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::W;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("BW", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::BW;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("M", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::M;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("BM", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::BM;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Q", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::Q;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("Y", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::Y;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("C", Qt::CaseInsensitive) == 0) {
        m_value = eScheduleTypeEnum::C;
        m_value_isSet = m_value_isValid = true;
    }
}

void ScheduleTypeEnum::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString ScheduleTypeEnum::asJson() const {
    
    QString val;
    switch (m_value){
        case eScheduleTypeEnum::O:
            val = "O";
            break;
        case eScheduleTypeEnum::I:
            val = "I";
            break;
        case eScheduleTypeEnum::H:
            val = "H";
            break;
        case eScheduleTypeEnum::D:
            val = "D";
            break;
        case eScheduleTypeEnum::W:
            val = "W";
            break;
        case eScheduleTypeEnum::BW:
            val = "BW";
            break;
        case eScheduleTypeEnum::M:
            val = "M";
            break;
        case eScheduleTypeEnum::BM:
            val = "BM";
            break;
        case eScheduleTypeEnum::Q:
            val = "Q";
            break;
        case eScheduleTypeEnum::Y:
            val = "Y";
            break;
        case eScheduleTypeEnum::C:
            val = "C";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue ScheduleTypeEnum::asJsonValue() const {
    
    return QJsonValue(asJson());
}


ScheduleTypeEnum::eScheduleTypeEnum ScheduleTypeEnum::getValue() const {
    return m_value;
}

void ScheduleTypeEnum::setValue(const ScheduleTypeEnum::eScheduleTypeEnum& value){
    m_value = value;
    m_value_isSet = true;
}
bool ScheduleTypeEnum::isSet() const {
    
    return m_value_isSet;
}

bool ScheduleTypeEnum::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace InvenTree
