/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchResult.h
 *
 * Serializer for a search result.
 */

#ifndef SearchResult_H
#define SearchResult_H

#include <QJsonObject>

#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {

class SearchResult : public Object {
public:
    SearchResult();
    SearchResult(QString json);
    ~SearchResult() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getSku() const;
    void setSku(const QString &sku);
    bool is_sku_Set() const;
    bool is_sku_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    bool isExact() const;
    void setExact(const bool &exact);
    bool is_exact_Set() const;
    bool is_exact_Valid() const;

    QString getDescription() const;
    void setDescription(const QString &description);
    bool is_description_Set() const;
    bool is_description_Valid() const;

    QString getPrice() const;
    void setPrice(const QString &price);
    bool is_price_Set() const;
    bool is_price_Valid() const;

    QString getLink() const;
    void setLink(const QString &link);
    bool is_link_Set() const;
    bool is_link_Valid() const;

    QString getImageUrl() const;
    void setImageUrl(const QString &image_url);
    bool is_image_url_Set() const;
    bool is_image_url_Valid() const;

    qint32 getExistingPartId() const;
    void setExistingPartId(const qint32 &existing_part_id);
    bool is_existing_part_id_Set() const;
    bool is_existing_part_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_sku;
    bool m_sku_isSet;
    bool m_sku_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    bool m_exact;
    bool m_exact_isSet;
    bool m_exact_isValid;

    QString m_description;
    bool m_description_isSet;
    bool m_description_isValid;

    QString m_price;
    bool m_price_isSet;
    bool m_price_isValid;

    QString m_link;
    bool m_link_isSet;
    bool m_link_isValid;

    QString m_image_url;
    bool m_image_url_isSet;
    bool m_image_url_isValid;

    qint32 m_existing_part_id;
    bool m_existing_part_id_isSet;
    bool m_existing_part_id_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::SearchResult)

#endif // SearchResult_H
