/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 185
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StockAdjustmentItem.h
 *
 * Serializer for a single StockItem within a stock adjument request.  Required Fields:     - item: StockItem object     - quantity: Numerical quantity  Optional Fields (may be used by external tools)     - status: Change StockItem status code     - packaging: Change StockItem packaging     - batch: Change StockItem batch code  The optional fields can be used to adjust values for individual stock items
 */

#ifndef StockAdjustmentItem_H
#define StockAdjustmentItem_H

#include <QJsonObject>

#include "StockAdjustmentItem_status.h"
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {

class StockAdjustmentItem : public Object {
public:
    StockAdjustmentItem();
    StockAdjustmentItem(QString json);
    ~StockAdjustmentItem() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    QString getQuantity() const;
    void setQuantity(const QString &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    QString getBatch() const;
    void setBatch(const QString &batch);
    bool is_batch_Set() const;
    bool is_batch_Valid() const;

    StockAdjustmentItem_status getStatus() const;
    void setStatus(const StockAdjustmentItem_status &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getPackaging() const;
    void setPackaging(const QString &packaging);
    bool is_packaging_Set() const;
    bool is_packaging_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    QString m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;

    QString m_batch;
    bool m_batch_isSet;
    bool m_batch_isValid;

    StockAdjustmentItem_status m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString m_packaging;
    bool m_packaging_isSet;
    bool m_packaging_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::StockAdjustmentItem)

#endif // StockAdjustmentItem_H
