/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 166
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StockItemTestResult.h
 *
 * Serializer for the StockItemTestResult model.
 */

#ifndef StockItemTestResult_H
#define StockItemTestResult_H

#include <QJsonObject>

#include <QDateTime>
#include <QString>

#include "Enum.h"
#include "Object.h"

namespace InvenTree {

class StockItemTestResult : public Object {
public:
    StockItemTestResult();
    StockItemTestResult(QString json);
    ~StockItemTestResult() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPk() const;
    void setPk(const qint32 &pk);
    bool is_pk_Set() const;
    bool is_pk_Valid() const;

    qint32 getStockItem() const;
    void setStockItem(const qint32 &stock_item);
    bool is_stock_item_Set() const;
    bool is_stock_item_Valid() const;

    QString getKey() const;
    void setKey(const QString &key);
    bool is_key_Set() const;
    bool is_key_Valid() const;

    QString getTest() const;
    void setTest(const QString &test);
    bool is_test_Set() const;
    bool is_test_Valid() const;

    bool isResult() const;
    void setResult(const bool &result);
    bool is_result_Set() const;
    bool is_result_Valid() const;

    QString getValue() const;
    void setValue(const QString &value);
    bool is_value_Set() const;
    bool is_value_Valid() const;

    QString getAttachment() const;
    void setAttachment(const QString &attachment);
    bool is_attachment_Set() const;
    bool is_attachment_Valid() const;

    QString getNotes() const;
    void setNotes(const QString &notes);
    bool is_notes_Set() const;
    bool is_notes_Valid() const;

    qint32 getUser() const;
    void setUser(const qint32 &user);
    bool is_user_Set() const;
    bool is_user_Valid() const;

    QDateTime getDate() const;
    void setDate(const QDateTime &date);
    bool is_date_Set() const;
    bool is_date_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_pk;
    bool m_pk_isSet;
    bool m_pk_isValid;

    qint32 m_stock_item;
    bool m_stock_item_isSet;
    bool m_stock_item_isValid;

    QString m_key;
    bool m_key_isSet;
    bool m_key_isValid;

    QString m_test;
    bool m_test_isSet;
    bool m_test_isValid;

    bool m_result;
    bool m_result_isSet;
    bool m_result_isValid;

    QString m_value;
    bool m_value_isSet;
    bool m_value_isValid;

    QString m_attachment;
    bool m_attachment_isSet;
    bool m_attachment_isValid;

    QString m_notes;
    bool m_notes_isSet;
    bool m_notes_isValid;

    qint32 m_user;
    bool m_user_isSet;
    bool m_user_isValid;

    QDateTime m_date;
    bool m_date_isSet;
    bool m_date_isValid;
};

} // namespace InvenTree

Q_DECLARE_METATYPE(InvenTree::StockItemTestResult)

#endif // StockItemTestResult_H
