/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "StockItemSerialNumbers.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

StockItemSerialNumbers::StockItemSerialNumbers(const QString &json) {
    this->initializeModel();
    this->fromJson(json);
}

StockItemSerialNumbers::StockItemSerialNumbers() {
    this->initializeModel();
}

StockItemSerialNumbers::~StockItemSerialNumbers() {}

void StockItemSerialNumbers::initializeModel() {

    m_next_isSet = false;
    m_next_isValid = false;

    m_previous_isSet = false;
    m_previous_isValid = false;
}

void StockItemSerialNumbers::fromJson(const QString &jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void StockItemSerialNumbers::fromJsonObject(QJsonObject json) {

    m_next_isValid = ::InvenTree::fromJsonValue(m_next, json[QString("next")]);
    m_next_isSet = !json[QString("next")].isNull() && m_next_isValid;

    m_previous_isValid = ::InvenTree::fromJsonValue(m_previous, json[QString("previous")]);
    m_previous_isSet = !json[QString("previous")].isNull() && m_previous_isValid;
}

QString StockItemSerialNumbers::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject StockItemSerialNumbers::asJsonObject() const {
    QJsonObject obj;
    if (m_next.isSet()) {
        obj.insert(QString("next"), ::InvenTree::toJsonValue(m_next));
    }
    if (m_previous.isSet()) {
        obj.insert(QString("previous"), ::InvenTree::toJsonValue(m_previous));
    }
    return obj;
}

StockItem StockItemSerialNumbers::getNext() const {
    return m_next;
}
void StockItemSerialNumbers::setNext(const StockItem &next) {
    m_next = next;
    m_next_isSet = true;
}

bool StockItemSerialNumbers::is_next_Set() const{
    return m_next_isSet;
}

bool StockItemSerialNumbers::is_next_Valid() const{
    return m_next_isValid;
}

StockItem StockItemSerialNumbers::getPrevious() const {
    return m_previous;
}
void StockItemSerialNumbers::setPrevious(const StockItem &previous) {
    m_previous = previous;
    m_previous_isSet = true;
}

bool StockItemSerialNumbers::is_previous_Set() const{
    return m_previous_isSet;
}

bool StockItemSerialNumbers::is_previous_Valid() const{
    return m_previous_isValid;
}

bool StockItemSerialNumbers::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_next.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_previous.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool StockItemSerialNumbers::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_next_isValid && m_previous_isValid && true;
}

} // namespace InvenTree
