/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "StockItemStatusEnum.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

StockItemStatusEnum::StockItemStatusEnum(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

StockItemStatusEnum::StockItemStatusEnum() {
    this->initializeModel();
}

StockItemStatusEnum::~StockItemStatusEnum() {}

void StockItemStatusEnum::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eStockItemStatusEnum::INVALID_VALUE_OPENAPI_GENERATED;
}

void StockItemStatusEnum::fromJson(QString jsonString) {
    
    if ( jsonString.compare(QString::number(10), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_10;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(50), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_50;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(55), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_55;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(60), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_60;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(65), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_65;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(70), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_70;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(75), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_75;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare(QString::number(85), Qt::CaseInsensitive) == 0) {
        m_value = eStockItemStatusEnum::_85;
        m_value_isSet = m_value_isValid = true;
    }
}

void StockItemStatusEnum::fromJsonValue(QJsonValue json) {
m_value = static_cast<eStockItemStatusEnum>(json.toInt());
}

QString StockItemStatusEnum::asJson() const {
    
    QString val;
    switch (m_value){
        case eStockItemStatusEnum::_10:
            val = QString::number(10);
            break;
        case eStockItemStatusEnum::_50:
            val = QString::number(50);
            break;
        case eStockItemStatusEnum::_55:
            val = QString::number(55);
            break;
        case eStockItemStatusEnum::_60:
            val = QString::number(60);
            break;
        case eStockItemStatusEnum::_65:
            val = QString::number(65);
            break;
        case eStockItemStatusEnum::_70:
            val = QString::number(70);
            break;
        case eStockItemStatusEnum::_75:
            val = QString::number(75);
            break;
        case eStockItemStatusEnum::_85:
            val = QString::number(85);
            break;
        default:
            break;
    }
    return val;
}

QJsonValue StockItemStatusEnum::asJsonValue() const {
    
    return QJsonValue(static_cast<int>(m_value));
}


StockItemStatusEnum::eStockItemStatusEnum StockItemStatusEnum::getValue() const {
    return m_value;
}

void StockItemStatusEnum::setValue(const StockItemStatusEnum::eStockItemStatusEnum& value){
    m_value = value;
    m_value_isSet = true;
}
bool StockItemStatusEnum::isSet() const {
    
    return m_value_isSet;
}

bool StockItemStatusEnum::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace InvenTree
