/**
 * InvenTree API
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 442
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "UserSetPassword.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "Helpers.h"

namespace InvenTree {

UserSetPassword::UserSetPassword(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

UserSetPassword::UserSetPassword() {
    this->initializeModel();
}

UserSetPassword::~UserSetPassword() {}

void UserSetPassword::initializeModel() {

    m_password_isSet = false;
    m_password_isValid = false;

    m_override_warning_isSet = false;
    m_override_warning_isValid = false;
}

void UserSetPassword::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void UserSetPassword::fromJsonObject(QJsonObject json) {

    m_password_isValid = ::InvenTree::fromJsonValue(m_password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;

    m_override_warning_isValid = ::InvenTree::fromJsonValue(m_override_warning, json[QString("override_warning")]);
    m_override_warning_isSet = !json[QString("override_warning")].isNull() && m_override_warning_isValid;
}

QString UserSetPassword::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject UserSetPassword::asJsonObject() const {
    QJsonObject obj;
    if (m_password_isSet) {
        obj.insert(QString("password"), ::InvenTree::toJsonValue(m_password));
    }
    if (m_override_warning_isSet) {
        obj.insert(QString("override_warning"), ::InvenTree::toJsonValue(m_override_warning));
    }
    return obj;
}

QString UserSetPassword::getPassword() const {
    return m_password;
}
void UserSetPassword::setPassword(const QString &password) {
    m_password = password;
    m_password_isSet = true;
}

bool UserSetPassword::is_password_Set() const{
    return m_password_isSet;
}

bool UserSetPassword::is_password_Valid() const{
    return m_password_isValid;
}

bool UserSetPassword::isOverrideWarning() const {
    return m_override_warning;
}
void UserSetPassword::setOverrideWarning(const bool &override_warning) {
    m_override_warning = override_warning;
    m_override_warning_isSet = true;
}

bool UserSetPassword::is_override_warning_Set() const{
    return m_override_warning_isSet;
}

bool UserSetPassword::is_override_warning_Valid() const{
    return m_override_warning_isValid;
}

bool UserSetPassword::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_override_warning_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool UserSetPassword::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_password_isValid && true;
}

} // namespace InvenTree
